### PR TITLE
Suppress relationship string in template vars for public contact

### LINKED ISSUE #7468: Contact search always shows 'you are a fan of'
### Expected behavior
The search result should show the correct relationship status. Non-contacts (strangers) shouldn't be listed as 'you are a fan of'.

### Actual behavior
When I search for people they show the relationship status correctly when they are already in my contacts. But non-contacts (strangers) are shown as 'you are a fan of'. That's wrong.

### Steps to reproduce the problem
Type something like `@stranger` into the search box in the top panel. Hit 'Enter'. Look at the relationship status.

Bildschirmfoto von 2019-08-04 11-02-44

### Friendica version you encountered the problem
2019.09-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #7468

### CODE REVIEW

File: src/Module/Contact.php [hunk 1]
```diff
@@ -984,24 +984,26 @@ public static function getContactTemplateVars(array $rr)
 		$dir_icon = '';
 		$alt_text = '';
 
-		switch ($rr['rel']) {
-			case Model\Contact::FRIEND:
-				$dir_icon = 'images/lrarrow.gif';
-				$alt_text = L10n::t('Mutual Friendship');
-				break;
+		if ($rr['uid']) {
```
Comment (annando) [inline src/Module/Contact.php]: Why no "empty(...)" here?

Comment (MrPetovan) [reply src/Module/Contact.php]: You're right, I expect the `uid` field to be existing like the `rel` field is expected to exist but it may not be the case.
