### PR TITLE
Issue 8565: Sanitize  input data

### LINKED ISSUE #8565: DB error: 1366 - incorrect integer value
### Expected behavior
Don't try to store empty strings in integer fields.

### Actual behavior
```2020-04-29T20:19:53Z worker [ERROR]: DB Error {"code":1366,"error":"Incorrect integer value: '' for column `friendica`.`gserver`.`relay-subscribe` at row
 1","callstack":"Database::update, DBA::update, GServer::discoverRelay, GServer::detect, GServer::check, GContact::sanitize, PortableContact::load, Fetch
PoCo::execute","params":"UPDATE `gserver` SET `relay-subscribe` = '', `relay-scope` = '' WHERE (`id` = 2081)"} - {"file":"Database.php","line":736,"funct
ion":"e","uid":"a613ef","process_id":5283}``` 

### Friendica version you encountered the problem
2020.06-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
MariaDB 10.3

### PR DESCRIPTION
**Pull request by annando**
Fixes #8565

### CODE REVIEW

File: src/Model/GServer.php [hunk 1]
```diff
@@ -339,7 +339,7 @@ public static function detect(string $url, string $network = '')
 	 * @param string $server_url address of the server
 	 * @throws \Friendica\Network\HTTPException\InternalServerErrorException
 	 */
-	private static function discoverRelay(string $server_url)
+	public static function discoverRelay(string $server_url)
```
Comment (MrPetovan) [inline src/Model/GServer.php:342]: Is this change intended or was is just for testing?

Comment (annando) [reply src/Model/GServer.php:342]: Good eye.
