### PR TITLE
C2S: Posting is now possible

### LINKED ISSUE #12776: [ActivityPub C2S] Implement posting via ActivityPub C2S
This is one of ActivityPub C2S implementation problems, reported by me at @annando request (see my first report at https://github.com/andstatus/andstatus/issues/573#issuecomment-1417286215 )

Currently posting to outbox fails: it is not implemented yet, as I understand. I got HTML page as a response instead (time in UTC below)
```
02-05 09:38:24.604 D/HttpReadResult: getJsonObject; ; statusCode:OK (200); url:'https://pirati.ca/outbox/andstatus'; response:'<!DOCTYPE html…'
```

### PR DESCRIPTION
**Pull request by annando**
Fixes #12776

### CODE REVIEW

File: src/Protocol/ActivityPub/Receiver.php [hunk 1]
```diff
@@ -1849,9 +1847,9 @@ private static function processAttachmentUrls(array $urls): array
 	 * @return array|bool Object data or FALSE if $object does not contain @id element
 	 * @throws \Exception
 	 */
-	private static function processObject(array $object)
+	private static function processObject(array $object, bool $c2s)
```
Comment (nupplaphil) [inline src/Protocol/ActivityPub/Receiver.php]: PHPdoc for `$c2s`

File: src/Protocol/ActivityPub/Receiver.php [hunk 2]
```diff
@@ -2025,4 +2027,137 @@ private static function hasArrived(string $id): bool
 	{
 		return DBA::exists('arrived-activity', ['object-id' => $id]);
 	}
+
+	public static function processC2SActivity(array $activity, int $uid, array $application)
```
Comment (nupplaphil) [inline src/Protocol/ActivityPub/Receiver.php]: PHPDoc

File: src/Protocol/ActivityPub/Receiver.php [hunk 3]
```diff
@@ -2025,4 +2027,137 @@ private static function hasArrived(string $id): bool
...
+		$object_id   = JsonLD::fetchElement($ldactivity, 'as:object', '@id') ?? '';
+		$object_type = self::fetchObjectType($ldactivity, $object_id, $uid);
+		if (!$object_type && !$object_id) {
+			Logger::notice('Empty object type or id', ['activity' => $ldactivity, 'uid' => $uid]);
+			return;
+		}
+
+		Logger::debug('Processing activity', ['type' => $type, 'object_type' => $object_type, 'object_id' => $object_id, 'activity' => $ldactivity]);
+		self::routeC2SActivities($type, $object_type, $object_id, $uid, $application, $ldactivity);
+		throw new \Friendica\Network\HTTPException\AcceptedException();
```
Comment (nupplaphil) [inline src/Protocol/ActivityPub/Receiver.php]: Is this really the only way?

I really dislike this "throw out" mechanism during the runtime. Normally it should return something "normal", so the caller can chose what to do with it.

I don't know, what @MrPetovan thinks about it, but for me:
Throwing = unwanted exits
return = wanted exists

And I know we don't follow this paradigm everywhere, like for redirects (which already caused some regressions too :) )

File: src/Protocol/ActivityPub/Receiver.php [hunk 4]
```diff
@@ -2025,4 +2027,137 @@ private static function hasArrived(string $id): bool
...
+		}
+		$post = ['title' => $item['title'], 'body' => $item['body']];
+		Logger::debug('Got data', ['id' => $id, 'uid' => $uid, 'item' => $post]);
+		Item::update($post, ['id' => $id]);
+		Item::updateDisplayCache($original_post['uri-id']);
+
+		System::jsonExit(Transmitter::createActivityFromItem($id));
+	}
+
+	private static function followAccount($uid, $object_id, $ldactivity)
```
Comment (nupplaphil) [inline src/Protocol/ActivityPub/Receiver.php]: empty hull? :)

File: src/Protocol/ActivityPub/Receiver.php [hunk 5]
```diff
@@ -2025,4 +2027,137 @@ private static function hasArrived(string $id): bool
...
+	{
+		$object_data = self::processObject($ldactivity['as:object'], true);
+		$item = Processor::processC2SContent($object_data, $application, $uid);
+		Logger::debug('Got data', ['item' => $item, 'object' => $object_data]);
+
+		$id = Item::insert($item, true);
+		if (!empty($id)) {
+			$item = Post::selectFirst(['uri-id'], ['id' => $id]);
+			if (!empty($item['uri-id'])) {
+				System::jsonExit(Transmitter::createActivityFromItem($id));
```
Comment (nupplaphil) [inline src/Protocol/ActivityPub/Receiver.php]: As said at the throw. I think the only place, where we should exit a HTTP Request should be inside a `BaseModule` based class. The "inner" classes should return a value which can guide the caller what to do.

Another thing is that with returning something instead of calling exit or throwing exceptions, we can specifically test these classes :)

File: src/Protocol/ActivityPub/Receiver.php [hunk 6]
```diff
@@ -2025,4 +2027,137 @@ private static function hasArrived(string $id): bool
...
+		if (empty($item['title']) && empty($item['body'])) {
+			Logger::debug('Empty body and title', ['id' => $id, 'uid' => $uid, 'object_id' => $object_id, 'activity' => $ldactivity]);
+			return;
+		}
+		$post = ['title' => $item['title'], 'body' => $item['body']];
+		Logger::debug('Got data', ['id' => $id, 'uid' => $uid, 'item' => $post]);
+		Item::update($post, ['id' => $id]);
+		Item::updateDisplayCache($original_post['uri-id']);
+
+		System::jsonExit(Transmitter::createActivityFromItem($id));
```
Comment (nupplaphil) [inline src/Protocol/ActivityPub/Receiver.php]: Like above

**Review by nupplaphil — CHANGES_REQUESTED** [review]

File: src/Protocol/ActivityPub/Receiver.php (hunk 4 above)
Comment (annando) [reply src/Protocol/ActivityPub/Receiver.php]: I have to figure out the expected return value since I don't know any documentation about it.

File: src/Protocol/ActivityPub/Receiver.php (hunk 3 above)
Comment (MrPetovan) [reply src/Protocol/ActivityPub/Receiver.php]: I agree, it's been confusing for us having "positive" exceptions.

File: src/Protocol/ActivityPub/Receiver.php (hunk 5 above)
Comment (MrPetovan) [reply src/Protocol/ActivityPub/Receiver.php]: I agree with that, the `exit` methods should only be called in Module classes.

File: src/Protocol/ActivityPub/Receiver.php (hunk 1 above)
Comment (annando) [reply src/Protocol/ActivityPub/Receiver.php]: Added

File: src/Protocol/ActivityPub/Receiver.php [hunk 7]
```diff
@@ -1843,6 +1843,7 @@ private static function processAttachmentUrls(array $urls): array
 	 * Fetches data from the object part of an activity
 	 *
 	 * @param array $object
+	 * @param bool  $c2s    "true" = The object is a "client to server" object
```
Comment (MrPetovan) [inline src/Protocol/ActivityPub/Receiver.php]: Please link somewhere to the documentation describing these objects. If there doesn't exist a public documentation page, please be as descriptive as possible. I'm guessing you developed this feature hands-on with actual messages sent by an app, so I'd rather not lose this knowledge you acquired for the people who will have to understand this code next.

I'm still not sure what C2S is about.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Protocol/ActivityPub/Receiver.php (hunk 7 above)
Comment (annando) [reply src/Protocol/ActivityPub/Receiver.php]: AFAIK there is no deep dive documentation. Just like AP S2S, the basic rules for AP C2S are set and the rest has to be done via the implementation.

The switch does two things:
1. C2S messages don't have an id. This will be added in the later process. So any check for the id mustn't be done here
2. The switch also defines, if we are the receiver or the sender of the message. Depending on this, we have to assign users or contacts to the actors in `to`, `cc`, `bcc` or `bto`.

Comment (MrPetovan) [reply src/Protocol/ActivityPub/Receiver.php]: Ah wait, I think I get it. C2S is a generic ActivityPub API, overlapping in features with the Mastodon API which has become the de facto standard even though it was meant for Mastodon only.

And it uses the same endpoints as S2S? Is there a way we can do the C2S/S2S differentiation in the modules instead of the ActivityPub library?

Comment (annando) [reply src/Protocol/ActivityPub/Receiver.php]: Yeah, it uses the same endpoints as S2S. There will also always be some overlapping in the message processing. But we should be able to move some functionality in a new C2S class. But it still would be more in the `Protocol` than the `API` namespace, I think.

Comment (MrPetovan) [reply src/Protocol/ActivityPub/Receiver.php]: The namespace isn't important for me, I just would prefer C2S to be separate from the generic ActivityPub processing.

Comment (annando) [reply src/Protocol/ActivityPub/Receiver.php]: So `Protocol/ActivityPub/ClientToServer.php` would be fine for you?

Comment (MrPetovan) [reply src/Protocol/ActivityPub/Receiver.php]: Absolutely, as long as it's separate.

File: src/Protocol/ActivityPub/ClientToServer.php [hunk 8]
```diff
@@ -0,0 +1,310 @@
...
+	 *
+	 * @param integer $uid
+	 * @param array $application
+	 * @param array $ldactivity
+	 * @return array
+	 */
+	private static function createContent(int $uid, array $application, array $ldactivity): array
+	{
+		$object_data = self::processObject($ldactivity['as:object']);
+		$item = ClientToServer::processContent($object_data, $application, $uid);
```
Comment (MrPetovan) [inline src/Protocol/ActivityPub/ClientToServer.php]:
```suggestion
		$object_data = self::processObject($ldactivity['as:object']);
		$item        = ClientToServer::processContent($object_data, $application, $uid);
```

File: src/Protocol/ActivityPub/ClientToServer.php [hunk 9]
```diff
@@ -0,0 +1,310 @@
...
+	 * @param integer $uid
+	 * @param string $object_id
+	 * @param array $application
+	 * @param array $ldactivity
+	 * @return array
+	 */
+	private static function updateContent(int $uid, string $object_id, array $application, array $ldactivity):array
+	{
+		$id = Item::fetchByLink($object_id, $uid);
+		$original_post = Post::selectFirst(['uri-id'], ['uid' => $uid, 'origin' => true, 'id' => $id]);
```
Comment (MrPetovan) [inline src/Protocol/ActivityPub/ClientToServer.php]:
```suggestion
		$id            = Item::fetchByLink($object_id, $uid);
		$original_post = Post::selectFirst(['uri-id'], ['uid' => $uid, 'origin' => true, 'id' => $id]);
```

File: src/Protocol/ActivityPub/ClientToServer.php [hunk 10]
```diff
@@ -0,0 +1,310 @@
...
+		if (empty($original_post)) {
+			Logger::debug('Item not found or does not belong to the user', ['id' => $id, 'uid' => $uid, 'object_id' => $object_id, 'activity' => $ldactivity]);
+			return [];
+		}
+
+		$object_data = self::processObject($ldactivity['as:object']);
+		$item = ClientToServer::processContent($object_data, $application, $uid);
```
Comment (MrPetovan) [inline src/Protocol/ActivityPub/ClientToServer.php]:
```suggestion
		$object_data = self::processObject($ldactivity['as:object']);
		$item        = ClientToServer::processContent($object_data, $application, $uid);
```

File: src/Protocol/ActivityPub/ClientToServer.php [hunk 11]
```diff
@@ -0,0 +1,310 @@
...
+	{
+		$owner = User::getOwnerDataById($uid);
+
+		$item = [];
+
+		$item['network']    = Protocol::DFRN;
+		$item['uid']        = $uid;
+		$item['verb']       = Activity::POST;
+		$item['contact-id'] = $owner['id'];
+		$item['author-id']  = $item['owner-id'] = Contact::getPublicIdByUserId($uid);
```
Comment (MrPetovan) [inline src/Protocol/ActivityPub/ClientToServer.php]:
```suggestion
		$item['author-id']  = $item['owner-id']  = Contact::getPublicIdByUserId($uid);
```

File: src/Protocol/ActivityPub/ClientToServer.php [hunk 12]
```diff
@@ -0,0 +1,310 @@
...
+			$item['allow_gid'] = '';
+			$item['deny_cid']  = '';
+			$item['deny_gid']  = '';
+			$item['private']   = Item::UNLISTED;
+		} elseif (!empty($object_data['target'][Receiver::TARGET_FOLLOWER])) {
+			$item['allow_cid'] = '';
+			$item['allow_gid'] = '<' . Group::FOLLOWERS . '>';
+			$item['deny_cid']  = '';
+			$item['deny_gid']  = '';
+			$item['private'] = Item::PRIVATE;
```
Comment (MrPetovan) [inline src/Protocol/ActivityPub/ClientToServer.php]:
```suggestion
			$item['deny_gid']  = '';
			$item['private']   = Item::PRIVATE;
```

File: src/Protocol/ActivityPub/ClientToServer.php [hunk 13]
```diff
@@ -0,0 +1,310 @@
...
+		} else {
+			// @todo Set permissions via the $object_data['target'] array
+			$item['allow_cid'] = '<' . $owner['id'] . '>';
+			$item['allow_gid'] = '';
+			$item['deny_cid']  = '';
+			$item['deny_gid']  = '';
+			$item['private'] = Item::PRIVATE;
```
Comment (MrPetovan) [inline src/Protocol/ActivityPub/ClientToServer.php]:
```suggestion
			$item['deny_gid']  = '';
			$item['private']   = Item::PRIVATE;
```

File: src/Protocol/ActivityPub/ClientToServer.php [hunk 14]
```diff
@@ -0,0 +1,310 @@
...
+		}
+
+		if (!empty($object_data['summary'])) {
+			$item['body'] = '[abstract=' . Protocol::ACTIVITYPUB . ']' . $object_data['summary'] . "[/abstract]\n" . $item['body'];
+		}
+
+		if ($object_data['reply-to-id']) {
+			$item['thr-parent'] = $object_data['reply-to-id'];
+			$item['gravity'] = Item::GRAVITY_COMMENT;
```
Comment (MrPetovan) [inline src/Protocol/ActivityPub/ClientToServer.php]:
```suggestion
			$item['thr-parent'] = $object_data['reply-to-id'];
			$item['gravity']    = Item::GRAVITY_COMMENT;
```

**Review by MrPetovan — CHANGES_REQUESTED** [review]
From the PHP CS Fixer output

File: src/Protocol/ActivityPub/Receiver.php (hunk 7 above)
Comment (annando) [reply src/Protocol/ActivityPub/Receiver.php]: Later I will move the C2S inbox stuff to there as well. But this will be done in some future PR, I think.

Edit: It is done.

File: src/Module/ActivityPub/Inbox.php [hunk 15]
```diff
@@ -61,9 +61,9 @@ protected function rawContent(array $request = [])
 			if ($owner['uid'] != $uid) {
 				throw new \Friendica\Network\HTTPException\ForbiddenException();
 			}
-			$outbox = ActivityPub\Transmitter::getInbox($uid, $page, $request['max_id'] ?? null);
+			$outbox = ActivityPub\ClientToServer::getInbox($uid, $page, $request['max_id'] ?? null);
```
Comment (MrPetovan) [inline src/Module/ActivityPub/Inbox.php]: Please rename this variable to `$inbox`.

File: src/Protocol/ActivityPub/Processor.php [hunk 16]
```diff
@@ -35,6 +35,7 @@
 use Friendica\Model\Contact;
 use Friendica\Model\Conversation;
 use Friendica\Model\Event;
+use Friendica\Model\Group;
```
Comment (MrPetovan) [inline src/Protocol/ActivityPub/Processor.php]: Still needed?

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Protocol/ActivityPub/Processor.php (hunk 16 above)
Comment (annando) [reply src/Protocol/ActivityPub/Processor.php]: Nope

File: src/Module/ActivityPub/Inbox.php (hunk 15 above)
Comment (annando) [reply src/Module/ActivityPub/Inbox.php]: Done

**Review by MrPetovan — APPROVED** [review]
