### PR TITLE
Never mention yourself

### LINKED ISSUE #9480: Never auto-mention yourself
- [X] I have searched open and closed issues for duplicates

### Bug Description
When I reply to an own (post or)* comment Friendica adds on odd auto-mention of myself. That's weird and uncommon.
That's especially bad when using implicit mentions where you're unable to delete the weird self-mention before submitting the comment.

*) I think it doesn't happen with replies to top level posts. But I'm not sure.

### Steps to Reproduce

1.  Look for a comment of yourself
2.  Reply to that comment
3.  When using implicit mentions you need to look at your comment from another network. When using explicit mentions you will see it right away locally on Friendica.
4. You have mentioned yourself. See?

Actual Result:
Automatic self-mentions are weird, wrong and useless.

Expected Result:
Never ever auto-mention yourself. I can't come up with a situation where they are useful or meaningful. We should prevent/suppress these self-mentions - no matter if the mentions are explicit or implicit.

### Screenshots
(don't want to shoot my screen. it's a good screen)

### Platform Info

Friendica Version:
2020.12-dev

Friendica Source: 
git
PHP version:
7.4
SQL version:
10.3 MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #9480 

Additionally, it fixes a minor mention formatting issue outlined here: https://discourse.joinmastodon.org/t/whats-the-interoperable-mention-format/3069

### CODE REVIEW

File: src/Protocol/ActivityPub/Transmitter.php [hunk 1]
```diff
@@ -1258,7 +1258,7 @@ private static function mentionCallback($match)
 			return $match[0];
 		}
 
-		return '@[url=' . $data['url'] . ']' . $data['nick'] . '[/url]';
+		return '[url=' . $data['url'] . ']@' . $data['nick'] . '[/url]';
```
Comment (annando) [inline src/Protocol/ActivityPub/Transmitter.php:1261]: In Pleroma and Mastodon the `@` is outside the link, it is just some CSS tricks that it looks like it is part of the link.

Comment (MrPetovan) [reply src/Protocol/ActivityPub/Transmitter.php:1261]: Nope, see Mastodon HTML code for a mention:
```html
<a href="https://mastodon.xyz/@lightone" class="u-url mention status-link" title="lightone@mastodon.xyz" target="_blank" rel="noopener noreferrer">
    @<span>lightone</span>
</a>
```

Comment (annando) [reply src/Protocol/ActivityPub/Transmitter.php:1261]: There are also differences between Pleroma and Mastodon. But we can see if there are side effects or not.
