### PR TITLE
Revert node.config.php into Config table

### LINKED ISSUE #12715: Resetting the admin settings (node.config.php)
- [ x] I have searched open and closed issues for duplicates

### Bug Description

After today's git pull https://github.com/friendica/friendica/commit/ced77ccbce8e6310b47500769fe5736c59e88f72 the following areas in the adminstartions area were deleted or reset to initial values of the first installation

General information
	- page name 
	- Additional information
	
Registration 
	- Registration text
	
Upload file
	- Quality of JPEG image 

Performace
	- Clean up database
	- Lifetime of contributions from other nodes 
	- Lifetime of not requested contributions 
	- Lifetime of contributions (reset)
	- Optimize tables regularly 
	
Message relay
	- Direct relay transmission 
	
Administration - protocols
	- Keep log
	- Log file
	- Log level
	
deleted the complete settings of the imprint addon 

these are all settings which are stored in the node.config.php as far as I know

### Platform Info

Friendica Version:

Friendica Source:  2023.03-dev - 1512

PHP version: 8.1.2-1ubuntu2.9

SQL version: MariaDB 10.6.11

### PR DESCRIPTION
**Pull request by nupplaphil**
Well ... I revert the node.config.php ...
Fixes #12715 

This isn't working as expected! Moreover I think it makes things more worse :-/

<strike>It's not ready yet and I'm on holidays the next days, so please expect that I will finish it in about a week.</strike>

ToDos:
- [x] Fix tests (or the code, I'm not totally sure yet)
- [x] Upgrade my instance and check the logs

I already talked with @annando that I do like to switch back to the database **but** I will save the enabled addons as a file and extract the hooks as planned. This will avoid the problems I had with the Addon rewrite. Hopeully/Maybe a more clean solution .. But that's part of another PR :)

### CODE REVIEW

**Comment by MrPetovan** [comment]
Thank you, this must not have been an easy decision.

File: src/Core/Config/Util/SerializeUtil.php [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+/**
+ * Serialize utils
+ *
+ * Retrieved from https://github.com/WordPress/wordpress-develop/blob/6.1/src/wp-includes/functions.php
+ */
+class SerializeUtil
+{
+	public static function maybeSerialize($value): string
+	{
+		if (is_array($value) || is_object($value)) {
```
Comment (annando) [inline src/Core/Config/Util/SerializeUtil.php]: I think to keep the variable type in any case - we should call the serialize in every case when it wasn't a string.

**Comment by nupplaphil** [comment]
ha! got it and optimized tests and the CurResult as well :)

**Comment by nupplaphil** [comment]
I think I'm ready, the friendica.philipp.info node was successfully updated.. I had to check if the update routine must create the `Config` table manually first, because otherwise the Update fails. But this is just necessary in case somebody uses the current develop branch and dropped the `Config` table (like I did :D )..

File: mods/local.config.ci.php [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+/* If automatic system installation fails:
+ *
+ * Copy this file to local.config.php
+ *
+ * Why local.config.php? Because it contains sensitive information which could
+ * give somebody complete control of your database. Apache's default
+ * configuration will interpret any .php file as a script and won't show the values
+ *
+ * Then set the following for your MySQL installation
+ */
```
Comment (MrPetovan) [inline mods/local.config.ci.php]: Do we need this for the Continuous Integration config file?

File: src/Core/Logger/Type/StreamLogger.php [hunk 3]
```diff
@@ -92,7 +92,7 @@ public function __construct(string $channel, IManageConfigValues $config, IHaveC
 		$this->fileSystem = $fileSystem;
 
 		$stream = $this->logfile ?? $config->get('system', 'logfile');
-		if ((file_exists($stream) && !is_writable($stream)) || is_writable(basename($stream))) {
+		if ((@file_exists($stream) && !@is_writable($stream)) || @is_writable(basename($stream))) {
```
Comment (MrPetovan) [inline src/Core/Logger/Type/StreamLogger.php]: Why do we throw an Exception when the base name is writable?

File: src/DI.php [hunk 4]
```diff
@@ -37,9 +37,24 @@ abstract class DI
 	/** @var Dice */
 	private static $dice;
 
-	public static function init(Dice $dice)
+	public static function init(Dice $dice, bool $disableDepByHand = false)
```
Comment (MrPetovan) [inline src/DI.php:49]: Please add some documentation for this new parameter.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Core/Logger/Type/StreamLogger.php (hunk 3 above)
Comment (nupplaphil) [reply src/Core/Logger/Type/StreamLogger.php]: because the `vfs://` prefix of the file isn't supported by some of the PHP native functions, like `file_exists` and, AFAIK, `is_writable` as well. It doesn't break the tests, but throws `E_WARNING`s all over the output.

File: mods/local.config.ci.php (hunk 2 above)
Comment (nupplaphil) [reply mods/local.config.ci.php]: yep .. Shall I delete it again and we live with the CI failure? I wasn't sure but tbh tend to let it fail ;)

File: src/Core/Logger/Type/StreamLogger.php (hunk 3 above)
Comment (MrPetovan) [reply src/Core/Logger/Type/StreamLogger.php]: I’m not asking about the error suppression operator, I’m asking about the whole condition. An exception is thrown if the filename exists and is *not* writable or if the base folder *is* writable?

File: mods/local.config.ci.php (hunk 2 above)
Comment (MrPetovan) [reply mods/local.config.ci.php]: No, I meant the human-readable comments I highlighted?

Comment (nupplaphil) [reply mods/local.config.ci.php]: thx for the hint!

File: src/Core/Logger/Type/StreamLogger.php (hunk 3 above)
Comment (nupplaphil) [reply src/Core/Logger/Type/StreamLogger.php]: got it .. wrong boolean logic *g*

**Review by MrPetovan — APPROVED** [review]

**Comment by AlfredSK** [comment]
I have one node where I deleted the config and addon tables and one node where I haven't deleted the tables.
Does it matter if I deleted the tables or not? Should I drop the tables before pulling this update?

**Comment by MrPetovan** [comment]
I believe @nupplaphil accounted for both cases, creating back the table if it had been deleted.

**Comment by nupplaphil** [comment]
It should work for both. I tested it locally with a config table and on my friendica.philipp.info node without config table :-)

**Comment by AlfredSK** [comment]
Thank you!

**Comment by sekretaerbaer** [comment]
thx
