### PR TITLE
Issue 12701: Fix Markdown problems with Quotes

### LINKED ISSUE #12701: Quotes in ALT-text of images messes up D* federation
### Bug Description

For posts created through the Mastodon API when the ALT-text for an image has actual quotes in it, then the federation to Diaspora gets very messed up. The problem doesn't seem to manifest on Mastodon.

### Steps to Reproduce
1. Create a post with an image attachment that has quotes (not smart quotes) in it as a media attachment through the API
2. Check the result on a Diaspora server to show that it is getting garbled BBcode text rather than an embedded image

Actual Result:

Garbled BBCode text 

Expected Result:

An image.

### Screenshots

This post from my friendica server: https://friendica.myportal.social/display/e65e1095-1363-ca14-3a61-8b4346494405
image

As seen from the diasp.org server (improper): https://diasp.org/posts/e65e1095-1363-ca14-3a61-8b4346494405
image

As seen on the techhub.social Mastodon server (proper): https://techhub.social/@hankg@friendica.myportal.social/109719575090310057
image

### Platform Info

Friendica Version: Image created with 2022.12, post created with 2023.01

Friendica Source: https://github.com/friendica/friendica/ stable branch

PHP version: 7.4.33

SQL version: MariaDB 15.1

### PR DESCRIPTION
**Pull request by annando**
Fixes #12701
The Diaspora Markdown parser has got a problem with quotes in the "title" field. So we don't transmit them in case they contain a quote sign. This is no accessibility problem, since we always transmit the "alt" description and it is parsed by Diaspora.

### CODE REVIEW

**Comment by nupplaphil** [comment]
I'm sorry... I.. must.. say.. it...

Tests? :X .. :X :-)

**Comment by annando** [comment]
Do we have got tests for `BBCode::toMarkdown`?

**Comment by nupplaphil** [comment]
https://github.com/friendica/friendica/blob/2023.03-rc/tests/src/Content/Text/BBCodeTest.php#L336

File: src/Content/Text/BBCode.php [hunk 1]
```diff
@@ -1567,8 +1567,13 @@ function ($matches) use ($simple_html, $uriid) {
 					"/\[[iz]mg\=(.*?)\](.*?)\[\/[iz]mg\]/ism",
 					function ($matches) use ($simple_html, $uriid) {
 						$matches[1] = self::proxyUrl($matches[1], $simple_html, $uriid);
-						$matches[2] = htmlspecialchars($matches[2], ENT_COMPAT);
-						return '<img src="' . $matches[1] . '" alt="' . $matches[2] . '" title="' . $matches[2] . '">';
+						$alt = htmlspecialchars($matches[2], ENT_COMPAT);
+						// Fix for Markdown problems wirh Diaspora, see issue #12701
```
Comment (MrPetovan) [inline src/Content/Text/BBCode.php]:
```suggestion
						// Fix for Markdown problems with Diaspora, see issue #12701
```

**Review by MrPetovan — DISMISSED** [review]

**Review by MrPetovan — CHANGES_REQUESTED** [review]
Typo

File: src/Content/Text/BBCode.php (hunk 1 above)
Comment (annando) [reply src/Content/Text/BBCode.php]: Fixed

File: tests/src/Content/Text/BBCodeTest.php [hunk 2]
```diff
@@ -331,7 +339,7 @@ public function dataBBCodesToMarkdown()
 	 *
 	 * @throws InternalServerErrorException
 	 */
-	public function testToMarkdown(string $expected, string $text, $for_diaspora = false)
+	public function testToMarkdown(string $expected, string $text, $for_diaspora = true)
```
Comment (MrPetovan) [inline tests/src/Content/Text/BBCodeTest.php:342]: This argument’s default value should match the tested method’s. To provide a different value for a test case, you need to mention it in the data array.

File: tests/src/Content/Text/BBCodeTest.php [hunk 3]
```diff
@@ -317,6 +317,14 @@ public function dataBBCodesToMarkdown()
 				'expected' => '&amp;`&`',
 				'text' => '&[code]&[/code]',
 			],
+			'bug-12701-quotes' => [
+				'expected' => '[![abc"fgh](https://domain.tld/photo/86912721086415cdc8e0a03226831581-1.png)](https://domain.tld/photos/user/image/86912721086415cdc8e0a03226831581)',
+				'text' => '[url=https://domain.tld/photos/user/image/86912721086415cdc8e0a03226831581][img=https://domain.tld/photo/86912721086415cdc8e0a03226831581-1.png]abc"fgh[/img][/url]'
+			],
```
Comment (MrPetovan) [inline tests/src/Content/Text/BBCodeTest.php:323]: ***
				'for_diaspora' => true,
			],
***

File: tests/src/Content/Text/BBCodeTest.php [hunk 4]
```diff
@@ -317,6 +317,14 @@ public function dataBBCodesToMarkdown()
...
+			'bug-12701-no-quotes' => [
+				'expected' => '[![abcfgh](https://domain.tld/photo/86912721086415cdc8e0a03226831581-1.png "abcfgh")](https://domain.tld/photos/user/image/86912721086415cdc8e0a03226831581)',
+				'text' => '[url=https://domain.tld/photos/user/image/86912721086415cdc8e0a03226831581][img=https://domain.tld/photo/86912721086415cdc8e0a03226831581-1.png]abcfgh[/img][/url]'
+			],
```
Comment (MrPetovan) [inline tests/src/Content/Text/BBCodeTest.php:327]: ***
				'for_diaspora' => true,
			],
***

File: tests/src/Content/Text/BBCodeTest.php (hunk 2 above)
Comment (annando) [reply tests/src/Content/Text/BBCodeTest.php:342]: That's exactly what I did: https://github.com/friendica/friendica/blob/2023.03-rc/src/Content/Text/BBCode.php#L2036

Comment (MrPetovan) [reply tests/src/Content/Text/BBCodeTest.php:342]: Cool, I found the opposite when I updated the BBCode tests so I thought it was the same dynamic here. I’m on mobile all week so I can’t easily check.
