### PR TITLE
Move profile module to src/

### LINKED ISSUE #6553: Unexpected ActivityPub profile page response for deleted accounts
I'm receiving activites to my ActivityPub inbox from several Friendica instances, and I can not verify it using HTTP signatures.
### Expected behavior
* Got activity signed with keyId of http://friendicainstance.tld/profile/username#main-key
* Request with `Accept: application/activity+json` header to http://friendicainstance.tld/profile/username should return:
1. HTTP 200 and ActivityPub Person object and his key
2. HTTP 404 for unknown user
3. HTTP 410 for known (gone) user
### Actual behavior
I see HTTP 200 and empty JSON array (`[]`) from some usernames and can not understand how to handle it.

### Friendica version you encountered the problem
Version 2019.01 as reported from one of these services

### PR DESCRIPTION
**Pull request by MrPetovan**
Incorporate changes from #6561
Fixes #6553
Part of #4090

### CODE REVIEW

File: src/Module/Profile.php [hunk 1]
```diff
@@ -0,0 +1,353 @@
...
+
+		$o .= conversation($a, $items, $pager, 'profile', $update, false, 'created', $a->profile['profile_uid']);
+
+		if (!$update) {
+			$o .= $pager->renderMinimal(count($items));
+		}
+
+		return $o;
+	}
+}
```
Comment (nupplaphil) [inline src/Module/Profile.php]: Code standard - missing last linebreak ;-) ;-)

**Comment by nupplaphil** [comment]
I don't know if it's possible, but for me when changing from `mod/profile.php` to `src/Module/Profile`, we should have a look about the hard-dependencies -> in this class, we do have about 20 static class-usages. Maybe it's possible to separate the frontend/input-logic (f.e. Http::SystemExit() , parameter-checks) from backend-logic (using Models, f.e.).

f.e. we can create a `Profile` Object, which holds `$which` and `$profile`, including all the business logic around this concret object (f.e. interacting with the model-classes, reading from configs, ...). And the module is using it (f.e. validating the parameters, outputing into `$a->page[]`, checks `$a->isMobile()`, ...). The `Profile` Object can be used as `$profile = new Profile($argument)` and holds `$which` and `$profile` as a state.

I think this will reduce the static-depdencies to near half per class and will help increasing maintanibility and (of course ;-) testing (we can f.e. mock the `Profile` class and with it all inherit dependencies).

File: src/Module/Profile.php [hunk 2]
```diff
@@ -0,0 +1,353 @@
...
+			// If the page user is the owner of the page we should query for unseen
+			// items. Otherwise use a timestamp of the last succesful update request.
+			if ($is_owner || !$last_updated) {
+				$sql_extra4 = " AND `item`.`unseen`";
+			} else {
+				$gmupdate = gmdate(DateTimeFormat::MYSQL, $last_updated);
+				$sql_extra4 = " AND `item`.`received` > '" . $gmupdate . "'";
+			}
+
+			$items_stmt = DBA::p(
```
Comment (nupplaphil) [inline src/Module/Profile.php]: maybe we can add it into `Item::getParentUri($profile_id)` ?

**Comment by MrPetovan** [comment]
The ideal, of course, is that Modules should be proper objects with injected dependencies. The static module classes are a transitional step between the global module functions in `mod/` and the glorious future with dependency injection.

**Comment by nupplaphil** [comment]
I'm not for 100% ideal, it was just a thought about a first step into this direction.
In fact it would "just" be a split into two classes instead of one and reducing the `use` statemens to a half each :-) . Maybe as a good base for the "glorious future" ;-). And I think it would be a "cheap" way for improving the testability of this part of code.

**Comment by MrPetovan** [comment]
This can be a good next transitional step, but I'd rather move all modules from `mod/` first before we start this next phase out of static classes.

**Comment by nupplaphil** [comment]
Alright :-)

File: src/Module/Profile.php (hunk 2 above)
Comment (MrPetovan) [reply src/Module/Profile.php]: I'll confess I didn't look too hard into what it was doing, I just converted a deprecated `q()` call to avoid having to require `include/dba.php` anymore.

Comment (annando) [reply src/Module/Profile.php]: @nupplaphil This is one of these calls that can't easily be replaced, due to the added SQL commands in the ```$sql_extra``` and ```$sql_extra4``` variables.

Comment (MrPetovan) [reply src/Module/Profile.php]: I think he meant moving the query as is in a new `Model\Item` method.
