### PR TITLE
Issue 9246: Don't perform fulltext searches on URL

### LINKED ISSUE #9246: DB error 1064: syntax error when manually fetching a post from Mastodon
### Expected behavior
When I try to fetch a post from Mastodon via search field it should be imported.

### Actual behavior
When I try to fetch that post via search field `https://mastodon.social/@evolbug/104891984441147017` I get a 'no results' error.

I'm wondering about the "unexpected '@'". I tried other posts from mastodon.social and they were imported as expected.

```
2020-09-20T08:03:25Z index [ERROR]: DB Error {"code":1064,"error":"syntax error, unexpected '@', expecting $end","callstack":"DBA::select, ItemContent::getURIIdListBySearch, Index::content, call_user_func, Page::initContent, Page::run, App::runFrontend","params":"SELECT `uri-id` FROM `item` WHERE (`uri-id` IN (SELECT `uri-id` FROM `item-content` WHERE MATCH (`title`, `content-warning`, `body`) AGAINST ('https:\/\/mastodon.social\/@evolbug\/104891984441147017' IN BOOLEAN MODE)) AND (NOT `private` OR (`private` AND `uid` = 1))) GROUP BY `uri-id` ORDER BY `uri-id` DESC LIMIT 0, 30"} - {"file":"Database.php","line":668,"function":"p","uid":"239f33","process_id":3496247}
2020-09-20T08:03:25Z index [ERROR]: DB Error {"code":1064,"error":"syntax error, unexpected '@', expecting $end","callstack":"DBA::count, ItemContent::countBySearch, Index::content, call_user_func, Page::initContent, Page::run, App::runFrontend","params":"SELECT COUNT(*) AS `count` FROM `item` WHERE (`uri-id` IN (SELECT `uri-id` FROM `item-content` WHERE MATCH (`title`, `content-warning`, `body`) AGAINST ('https:\/\/mastodon.social\/@evolbug\/104891984441147017' IN BOOLEAN MODE)) AND (NOT `private` OR (`private` AND `uid` = 1)))"} - {"file":"Database.php","line":668,"function":"p","uid":"239f33","process_id":3496247}
```

**Related?**
`PHP Notice:  Trying to access array offset on value of type bool in .../src/Database/Database.php on line 1592`

The same thing happens on stable. But w/o the DB error. Import fails.

I tried to disable the full text search and repeated the import attempt. Failed again.

### Originally reported here
https://libranet.de/display/0b6b25a8-105f-6708-0f13-a27545755399

### Steps to reproduce the problem
Manually import `https://mastodon.social/@evolbug/104891984441147017` via search field.
Look at the error info bubble.
Look at the application log for errors.
Look at the PHP log for errors/notices.

### Friendica version you encountered the problem
2020.09-rc
But also fails on stable.

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

### PR DESCRIPTION
**Pull request by annando**
Fixes https://github.com/friendica/friendica/issues/9246

### CODE REVIEW

File: src/Module/Search/Index.php [hunk 1]
```diff
@@ -132,6 +132,14 @@ public static function content(array $parameters = [])
 			}
 		}
 
+		// Don't perform a fulltext or tag search on search results that look like an URL
+		// Tags don't look like an URL and the fulltext search does only work with natural words
+		if (parse_url($search, PHP_URL_SCHEME) && parse_url($search, PHP_URL_HOST)) {
+			Logger::info('Skipping tag and fulltext search since the search looks like an URL.', ['q' => $search]);
```
Comment (AlfredSK) [inline src/Module/Search/Index.php]:
```suggestion
			Logger::info('Skipping tag and fulltext search since the search looks like a URL.', ['q' => $search]);
```

**Review by MrPetovan — APPROVED** [review]
