### PR TITLE
Gender, Maritial status and sexual preference fix

### LINKED ISSUE #5596: Gender, Maritial status and sexual preference are saved in generic language
### Expected behavior
When saving your gender, maritial status or sexual preference in 1 locale and you change the locale to another one, the data is translated as well

### Actual behavior
When saving your gender, maritial status or sexual preference in 1 locale and you change the locale to another one, the data is blank

### Steps to reproduce the problem
* Save one (or more) of the datas
* Change the locale (eg. german)
* Check the data just set

### Friendica version you encountered the problem
2018.08-dev

### Friendica source (git, zip)
GIT

### PHP version
PHP-7.2

### SQL version
MariaDB-10.2

Assigned to @JeroenED as a contribution for the 2018.11-release so he has something to relax while painting and moving into his apartment.

### PR DESCRIPTION
**Pull request by JeroenED**
Fixes #5596
Please do not merge yet.

Already pushing this PR to get your feedback on (mainly) code style and other things that you would to fix this issue.

### CODE REVIEW

File: src/Content/ContactSelector.php [hunk 1]
```diff
@@ -119,15 +119,29 @@ public static function networkToName($s, $profile = "")
 	public static function gender($current = "", $suffix = "")
 	{
 		$o = '';
-		$select = ['', L10n::t('Male'), L10n::t('Female'), L10n::t('Currently Male'), L10n::t('Currently Female'), L10n::t('Mostly Male'), L10n::t('Mostly Female'), L10n::t('Transgender'), L10n::t('Intersex'), L10n::t('Transsexual'), L10n::t('Hermaphrodite'), L10n::t('Neuter'), L10n::t('Non-specific'), L10n::t('Other'), L10n::t('Undecided')];
+		$select[''] = '';
```
Comment (MrPetovan) [inline src/Content/ContactSelector.php]: I'm more familiar with the following array declaration syntax:
```php
$select = [
  ''     => '',
  'Male' => L10n::t('Male'),
...
];
```
Additionally. I like the arrows to be aligned based on the longest or second longest key in the declared array.

Comment (JeroenED) [reply src/Content/ContactSelector.php]: would you do anything to the double `'Male' => L10n::t('Male'),`
To me copying is a catch for future related bugs.

Comment (MrPetovan) [reply src/Content/ContactSelector.php]: What double are you talking about?

Comment (JeroenED) [reply src/Content/ContactSelector.php]: the key that is copied into `L10n::t();` as parameter.

Comment (MrPetovan) [reply src/Content/ContactSelector.php]: The list isn't moving that often and is small enough to be quickly checked manually. If you want to be that cautious, you can write something like this:
```php
$select = [];
$choices = [
  '',
  'Male',
  ...
];
foreach($choices as $choice) {
  $select[$choice] = L10n::t($choice);
}
```

Comment (redmatrix) [reply src/Content/ContactSelector.php]: The issue with that is that the translation string extraction won't contain the actual strings which need to be translated, only a variable.

Comment (JeroenED) [reply src/Content/ContactSelector.php]: For now only the profile-view on friendica has actually been translated. I will tackle the federation protocols soon making them to translate it before sending if necessary.

Comment (MrPetovan) [reply src/Content/ContactSelector.php]: @redmatrix Do you mean that at the next pass of gettext, the existing translations would be wiped out because they wouldn't be found? In this case, we would have to keep the syntax in https://github.com/friendica/friendica/pull/5751#discussion_r216170614

Comment (redmatrix) [reply src/Content/ContactSelector.php]: All I can say for sure is that it is difficult to translate a variable. That's why for the most part translations are performed on "constant" strings. If you're satisfied that t($something) will be translated correctly for any possible value of $something you can ignore this warning. The code has changed dramatically since I last worked on it, but  the  ability to translate variables  is sort of a binary decision. Either you provide a mechanism to translate every possible value of the variable, or you need to enumerate each of them for the translation service.

Comment (MrPetovan) [reply src/Content/ContactSelector.php]: Got it, thanks for the elaboration.

**Comment by JeroenED** [comment]
https://social.jeroened.be/display/cd9f100a-155b-d389-92b8-815344260863

**Comment by fabrixxm** [comment]
link is dead:
https://forum.friendi.ca/display/cd9f100a-155b-d389-92b8-815344260863

File: src/Database/PostUpdate.php [hunk 2]
```diff
@@ -375,4 +376,49 @@ private static function update1281()
 
 		return false;
 	}
+
+	// Post-update script of PR 5596
+	function fixGenderStrings() {
```
Comment (MrPetovan) [inline src/Database/PostUpdate.php]: The post-update function naming scheme is `updateXXXX` where XXXX is the new database version number that should trigger the post update function. It doesn't matter if there aren't any actual database change, you can just bump the database version number in `config/dbstructure.config.php`.

Comment (MrPetovan) [inline src/Database/PostUpdate.php]: Code standards: Please add a new line before function opening brace.

File: src/Database/PostUpdate.php [hunk 3]
```diff
@@ -375,4 +376,49 @@ private static function update1281()
...
+		$allGenders = DBA::select('contact', ['id', 'gender']);
+		$allLangs = L10n::getAvailableLanguages();
+		$success = 0;
+		$fail = 0;
+		foreach($allGenders as $key=>$gender) {
```
Comment (MrPetovan) [inline src/Database/PostUpdate.php]: Code standards: Please add a space after `foreach` and wrap operators (like `=>`) with spaces.

File: src/Database/PostUpdate.php [hunk 4]
```diff
@@ -375,4 +376,49 @@ private static function update1281()
...
+				}
+				if (file_exists("addon/morechoice/lang/$lang/strings.php")) {
+					include "addon/morechoice/lang/$lang/strings.php";
+				}
+
+				$localizedStrings = $a->strings;
+				unset($a);
+
+				$key = array_search($gender['gender'], $localizedStrings);
+				if($key !== false) {
```
Comment (MrPetovan) [inline src/Database/PostUpdate.php]: Code standards: Please add a space after `if`.

File: src/Database/PostUpdate.php [hunk 5]
```diff
@@ -375,4 +376,49 @@ private static function update1281()
...
+				// defaulting to empty string
+				$key = '';
+			}
+			DBA::update('contact', ['gender' => $key], ['id' => $gender['id']]);
+			logger::log('Updated contact ' . $gender['id'] . ' to gender ' . $key . ' (was: ' . $gender['gender'] . ')');
+
+			if ($key == '') {
+				$fail++;
+			}
+			else {
```
Comment (MrPetovan) [inline src/Database/PostUpdate.php]: Code Standards: Please keep the `else` on the same line as the closing brace (still separated by a space).

File: src/Database/PostUpdate.php (hunk 2 above)
Comment (annando) [reply src/Database/PostUpdate.php]: We do have two different ways of processing updates after the update. There is the update.php and the postupdate.php. The latter one is only meant for stuff that will last some more time and that can be processed while the system is running.

This one more calls for a place in the update.php.

File: update.php [hunk 6]
```diff
@@ -256,3 +256,49 @@ function update_1288() {
 
 	return Update::SUCCESS;
 }
+
+	
+// Post-update script of PR 5751
+function update_1293() {
```
Comment (MrPetovan) [inline update.php]: Code standards: Please add a new line before function opening brace.

File: update.php [hunk 7]
```diff
@@ -256,3 +256,49 @@ function update_1288() {
...
+	$allGenders = DBA::select('contact', ['id', 'gender']);
+	$allLangs = L10n::getAvailableLanguages();
+	$success = 0;
+	$fail = 0;
+	foreach ($allGenders as $key=>$gender) {
```
Comment (MrPetovan) [inline update.php]: Code standards: Please wrap operators with spaces.

File: update.php (hunk 6 above)
Comment (JeroenED) [reply update.php]: It's weird to see this comment while all other functions in this file have the same style.

Comment (JeroenED) [reply update.php]: https://github.com/friendica/friendica/blob/develop/update.php

Comment (MrPetovan) [reply update.php]: Please rest assured I'm not singling you out. This file has been created before I started badgering people with code standards, and not all files have been retroactively fixed in that regard. However, any added code is scrutinized equally, regardless of the rest of the file (except for quote style that must match the most popular style in the function/file)

**Comment by MrPetovan** [comment]
Have you tried the post update function on an existing install already?

File: update.php (hunk 6 above)
Comment (fabrixxm) [reply update.php]: And at some point, without realizing, you start to write correct code :-)

Comment (JeroenED) [reply update.php]: A little delay, I didn't mean it like this. I also think having good code standards is neccesary. Otherwise you'll get a mik-mak of several styles and no one wants to contribute because nobody understands anymore.

Moreover, when this PR is I'll create another PR where I'll update update.php towards code standards :)

**Comment by JeroenED** [comment]
> Have you tried the post update function on an existing install already?

No, not yet. First I want to make sure my code standards are correct and then I'll proceed testing it on the vagrant machine and then on my personal node. I do believe that it won't take much edits while testign.

Please see https://github.com/friendica/friendica/pull/5751#issuecomment-448226222 for more info.

File: update.php (hunk 6 above)
Comment (MrPetovan) [reply update.php]: That's the spirit!

**Comment by JeroenED** [comment]
Ready to merge!!

Putting this comment was such a relief :)

**Comment by JeroenED** [comment]
Don't forget to merge this one as well :)

https://github.com/friendica/friendica-addons/pull/733

**Comment by MrPetovan** [comment]
Thank you for your work!
