### PR TITLE
Replace NOT EXIST(SELECT) with LEFT JOIN WHERE IS NULL in ExpirePosts

### LINKED ISSUE #14828: expired content cleanup hangs the instance
- [X] I have searched open and closed issues for duplicates

### Bug Description

There's a query that runs for a very long time (> 30 minutes) and causes all other sessions in MariaDB to go into `Waiting for table metadata lock` status.
I see around 5 of these queries running, other sessions fill up to `max_connections` (set to 1000) and then the site becomes unavailable.

This is the query:
```
SELECT `id` FROM `item-uri` WHERE (`id` < 27659980 AND NOT EXISTS(SELECT `uri-id` FROM `post-user` WHERE `uri-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `parent-uri-id` FROM `post-user` WHERE `parent-uri-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `thr-parent-id` FROM `post-user` WHERE `thr-parent-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `external-id` FROM `post-user` WHERE `external-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `replies-id` FROM `post-user` WHERE `replies-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `context-id` FROM `post-thread` WHERE `context-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `conversation-id` FROM `post-thread` WHERE `conversation-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `uri-id` FROM `mail` WHERE `uri-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `uri-id` FROM `event` WHERE `uri-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `uri-id` FROM `user-contact` WHERE `uri-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `uri-id` FROM `contact` WHERE `uri-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `uri-id` FROM `apcontact` WHERE `uri-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `uri-id` FROM `diaspora-contact` WHERE `uri-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `uri-id` FROM `inbox-status` WHERE `uri-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `uri-id` FROM `post-delivery` WHERE `uri-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `uri-id` FROM `post-delivery` WHERE `inbox-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `parent-uri-id` FROM `mail` WHERE `parent-uri-id` = `item-uri`.`id`) AND NOT EXISTS(SELECT `thr-parent-id` FROM `mail` WHERE `thr-parent-id` = `item-uri`.`id`)) LIMIT 1000
```

I am told this is part of the content cleanup.

### Steps to Reproduce

1.  just wait
2.  these queries will start
3.  other sessions will start waiting
4. new sessions wait as well, until max_connections is reached
5. site becomes unavailable
6. After killing the long-running queries, the other sessions complete succesfully.

Actual Result:

Site becomes unavailable

Expected Result:

Site stays available. (Queries / way of cleanup should be tuned)

### Screenshots
N/A

### Platform Info

Friendica Version:

Friendica Source: 

PHP version:

SQL version: 11.6.2

Image

### PR DESCRIPTION
**Pull request by MrPetovan**
Fix #14828 

- Improves the query execution plan

Thanks to @ruudschilders for their suggestion.

### CODE REVIEW

**Comment by MrPetovan** [comment]
I was able to verify on my dev node that both the existing query and the new one are returning the same data, albeit much faster for the new one.

**Comment by MrPetovan** [comment]
The tests are failing because the Friendica Addon Gitea repository isn't returning any data.

File: src/Worker/ExpirePosts.php [hunk 1]
```diff
@@ -199,31 +199,56 @@ private static function deleteUnusedItemUri()
...
-			AND NOT EXISTS(SELECT `uri-id` FROM `diaspora-contact` WHERE `uri-id` = `item-uri`.`id`)
-			AND NOT EXISTS(SELECT `uri-id` FROM `inbox-status` WHERE `uri-id` = `item-uri`.`id`)
-			AND NOT EXISTS(SELECT `uri-id` FROM `post-delivery` WHERE `uri-id` = `item-uri`.`id`)
-			AND NOT EXISTS(SELECT `uri-id` FROM `post-delivery` WHERE `inbox-id` = `item-uri`.`id`)
-			AND NOT EXISTS(SELECT `parent-uri-id` FROM `mail` WHERE `parent-uri-id` = `item-uri`.`id`)
-			AND NOT EXISTS(SELECT `thr-parent-id` FROM `mail` WHERE `thr-parent-id` = `item-uri`.`id`)", $item['uri-id']
+
+		$sql = [
+			'SELECT i.id
+FROM `item-uri` i
```
Comment (annando) [inline src/Worker/ExpirePosts.php]: Can you align then indentation?
