### PR TITLE
Respect Forwarded-For headers

### LINKED ISSUE #11317: Respect Forwarded-For headers in log file
I've set up my friendica instance behind a nginx reverse proxy.

Looking into the friendica log searching for failed logins, I see that the original IP is not available. This is the log line I found:
`2022-03-11T11:45:33Z index [WARNING]: authenticate: failed login attempt {"action":"login","username":"errewr","ip":"10.0.2.100"} - {"file":"Authentication.php","line":261,"function":"withPassword","uid":"bf0e28","process_id":123}
`
10.0.2.100 is the proxy address of the podman stack. I believe, docker is doing something similar and even just with a plain setup behind a reverse proxy it would be the proxy's ip address.

I request to add the original callers ip into the log line. This is neccessary to identify it for using fail2ban or Crowdsec.

As an example: Nextcloud uses the trusted-proxy array in it's configuration to determine if the original ip or the one in Forwarded-For header is to be logged as remote address (if ip is in trusted proxy use Forwarded-For header, otherwise senders ip).

### PR DESCRIPTION
**Pull request by nupplaphil**
We do now respect reverse proxies when retrieving IPs for different situations:

- Logging
- Cookies & Sessions

closes #11317

### CODE REVIEW

File: src/App/Request.php [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+		return false;
+	}
+
+	/**
+	 * Determines the remote address, if the connection came from a trusted proxy
+	 * and `forwarded_for_headers` has been configured then the IP address
+	 * specified in this header will be returned instead.
+	 *
+	 * @param IManageConfigValues $config
+	 * @param array               $server
```
Comment (MrPetovan) [inline src/App/Request.php]:
```suggestion
	 * @param array               $server The $_SERVER array
```

File: src/App/Request.php [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+ * Container for the whole request
+ *
+ * @see https://www.php-fig.org/psr/psr-7/#321-psrhttpmessageserverrequestinterface
+ *
+ * @todo future container class for whole requests, currently it's not :-)
+ */
+class Request
+{
+	/** @var string the default possible headers, which could contain the client IP */
+	const ORDERED_FORWARD_FOR_HEADER = 'HTTP_X_FORWARDED_FOR';
```
Comment (MrPetovan) [inline src/App/Request.php]:
```suggestion
	/** @var string the default header that could contain the actual client IP in a proxy request */
	const DEFAULT_FORWARD_FOR_HEADER = 'HTTP_X_FORWARDED_FOR';
```

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/App/Request.php (hunk 2 above)
Comment (nupplaphil) [reply src/App/Request.php]: This could be a list as well, I added some (hopefully) better documentation about it :)

File: src/App/Request.php [hunk 3]
```diff
@@ -32,8 +32,13 @@
  */
 class Request
 {
-	/** @var string the default possible headers, which could contain the client IP */
-	const ORDERED_FORWARD_FOR_HEADER = 'HTTP_X_FORWARDED_FOR';
+	/**
+	 * A comma separated list of default headers that could contain the client IP in a proxy request
+	 * Beware: This list is ordered
```
Comment (MrPetovan) [inline src/App/Request.php]: This comment belongs in the description of the `proxy.forwarded_for_headers` config value. It's unwarranted here since we control the value.

File: src/App/Request.php (hunk 2 above)
Comment (MrPetovan) [reply src/App/Request.php]: But it's a constant and it isn't a list, so what's the point? I agree the description is warranted for the config value, but you already did it.

File: static/defaults.config.php [hunk 4]
```diff
@@ -632,6 +632,16 @@
 		// Timeout in seconds for fetching the XRD links and other requests with an expected shorter timeout
 		'xrd_timeout' => 20,
 	],
+	'proxy' => [
+		// forwarded_for_headers (String)
+		// A comma separated list of all allowed header values to retrieve the real client IP
```
Comment (MrPetovan) [inline static/defaults.config.php:637]: Please add that the headers are evaluated in order.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

**Review by MrPetovan — APPROVED** [review]
