### PR TITLE
Issue 5733: Changing relationship values does work now again with DFRN

### LINKED ISSUE #5733: DFRN: Changing relationsships doesn't work as expected
Following an follower should change the relationship into a bidirectional relationship - unfollowing should turn this into a "follower" state.

This doesn't work at the moment.

### PR DESCRIPTION
**Pull request by annando**
Fixes #5733

### CODE REVIEW

File: src/Protocol/Diaspora.php [hunk 1]
```diff
@@ -388,7 +389,11 @@ public static function decodeRaw(array $importer, $raw)
 
 			if (!is_object($j_outer_key_bundle)) {
 				logger('Outer Salmon did not verify. Discarding.');
-				System::httpExit(400);
+				if ($no_exit) {
+					return false;
+				} else {
+					System::httpExit(400);
```
Comment (MrPetovan) [inline src/Protocol/Diaspora.php]: This should be done in the calling module instead of here. You got the right idea adding a `return false;`, but I think you didn't bring it far enough. There should be no flag in the function parameter, and `System::httpExit()` should be called in the calling modules.

Comment (annando) [reply src/Protocol/Diaspora.php]: So close before a release I hadn't intended to change too much.

Comment (MrPetovan) [reply src/Protocol/Diaspora.php]: I created a tracking issue for the next release.
