### PR TITLE
Issue 10983: Use the user's settings for the help language

### LINKED ISSUE #10983: language not applied for help page
### Bug Description
Help section is ignoring language setting

### Steps to Reproduce
Set language to english.

Actual Result:
Help page shows in german

Expected Result:
Help page should follow language setting.

### Screenshots
help in german
language settings

### Platform Info
This is Friendica, version 2021.12-dev that is running at the web location https://pirati.ca. The database version is 1443/1443, the post update version is 1427/1427.

### PR DESCRIPTION
**Pull request by annando**
Fixes #10983

### CODE REVIEW

File: src/Module/Help.php [hunk 1]
```diff
@@ -39,10 +39,10 @@ public static function content(array $parameters = [])
 		$text = '';
 		$filename = '';
 
-		$a = DI::app();
 		$config = DI::config();
-		$lang = $config->get('system', 'language');
-
+		$lang = DI::session()->get('language');
+		$lang = $lang ?? $config->get('system', 'language');
```
Comment (MrPetovan) [inline src/Module/Help.php]:
```suggestion
		$lang = DI::session()->get('language') ?? $config->get('system', 'language');
```
Or
```suggestion
		$lang = DI::session()->get('language', $config->get('system', 'language'));
```

**Review by MrPetovan — CHANGES_REQUESTED** [review]

**Review by MrPetovan — APPROVED** [review]
