### PR TITLE
Issue 5733: Removing contacts does work now on the same machine as well

### LINKED ISSUE #5733: DFRN: Changing relationsships doesn't work as expected
Following an follower should change the relationship into a bidirectional relationship - unfollowing should turn this into a "follower" state.

This doesn't work at the moment.

### PR DESCRIPTION
**Pull request by annando**
This fixes #5733 - finally.

### CODE REVIEW

File: mod/contacts.php [hunk 1]
```diff
@@ -47,6 +47,11 @@ function contacts_init(App $a)
 		if (!DBA::isResult($contact)) {
 			$contact = DBA::selectFirst('contact', [], ['id' => $contact_id, 'uid' => 0]);
 		}
+
+		// Don't display contacts that are about to be deleted
+		if (($contact['network'] == Protocol::PHANTOM)) {
```
Comment (MrPetovan) [inline mod/contacts.php]: Double-parentheses.
