### PR TITLE
Issue 8958: Ensure to have no foreign key violation

### LINKED ISSUE #8958: DB errors: 1451 - Cannot delete or update a parent row: a foreign key constraint fails
The two DB errors seem to be related because they always occur together and the `cid` is the same.

I'm not sure if this is a concerning issue or somehow expected. So I report it so it can be investigated.

### Actual behavior
```
2020-08-01T08:45:09Z worker [ERROR]: DB Error {"code":1062,"error":"Duplicate entry '26557239-2-0-56352' for key 'PRIMARY'","callstack":"DBA::update, MergeContact::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"UPDATE `post-tag` SET `cid` = 56352 WHERE (`cid` = 1187513)"} - {"file":"Database.php","line":769,"function":"e","uid":"f1a955","process_id":580899}

2020-08-01T08:45:09Z worker [ERROR]: DB Error {"code":1451,"error":"Cannot delete or update a parent row: a foreign key constraint fails (`friendica`.`post-tag`, CONSTRAINT `post-tag-cid-contact-id` FOREIGN KEY (`cid`) REFERENCES `contact` (`id`))","callstack":"DBA::delete, MergeContact::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"DELETE FROM `contact` WHERE `id` IN (1187513);"} - {"file":"Database.php","line":769,"function":"e","uid":"f1a955","process_id":580899}
```

### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

### PR DESCRIPTION
**Pull request by annando**
Fixes https://github.com/friendica/friendica/issues/8958

### CODE REVIEW

File: src/Worker/MergeContact.php [hunk 1]
```diff
@@ -52,6 +52,7 @@ public static function execute(int $new_cid, int $old_cid, int $uid)
 		// These fields only contain public contact entries (uid = 0)
 		if ($uid == 0) {
 			DBA::update('post-tag', ['cid' => $new_cid], ['cid' => $old_cid]);
+			DBA::delete('post-tag', ['cid' => $old_cid]);
```
Comment (MrPetovan) [inline src/Worker/MergeContact.php:55]: Isn't this supposed to delete exactly 0 rows after the previous query?

Comment (annando) [reply src/Worker/MergeContact.php:55]: No. Sometimes the `new_cid` and `old_cid` are both used in the same post. Since we use an unique key here, for these rows the `cid` won't be updated. So at the end we get rid of them.

**Review by MrPetovan — APPROVED** [review]
