### PR TITLE
Send AP Tombstone activity on deleted profiles

### LINKED ISSUE #6943: ActivityPub: Send out Delete activities for users and serve a proper response when the deleted user object is requested
### Expected behavior
When the user is deleted the server would send out Delete activities.

When the user is requested with `Accept: application/activity+json` header the server would serve [either a Tombstone object with a 410 Gone status code, or a 404 Not Found with an empty response body](https://www.w3.org/TR/activitypub/#delete-activity-outbox)
### Actual behavior
When the user is deleted the server does not appear to send out Delete activities

When the user is requested with `Accept: application/activity+json` header it returns  an empty array with 200 OK status code, which is not a valid AS2 object, so it confuses other fedi software
### Steps to reproduce the problem
1. Delete a user account
### Friendica version you encountered the problem

Tried on https://tryfriendica.de and https://nerdica.net

### Friendica source (git, zip)
N/A
### PHP version
N/A
### SQL version
N/A

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #6943
Follow-up to #6562 

Additionally, this PR normalizes the response for unavailable local profiles to 404 status code.

We don't store the deletion date and time for users, so all the three activity date fields I'm not sure are optional have been populated with the current time.

### CODE REVIEW

File: src/Module/Profile.php [hunk 1]
```diff
@@ -54,15 +54,28 @@ public static function rawContent()
...
+			}
+
+			if (!empty($data)) {
 				System::jsonExit($data, 'application/activity+json');
 			} elseif (DBA::exists('userd', ['username' => self::$which])) {
 				// Known deleted user
-				System::httpExit(410);
+				$data = [
+					'@context' => ActivityPub::CONTEXT,
+					'id' => System::baseUrl() . '/profile/' . self::$which,
```
Comment (nupplaphil) [inline src/Module/Profile.php]:
```suggestion
					'id' => $app->getBaseUrl() . '/profile/' . self::$which,
```

Comment (MrPetovan) [reply src/Module/Profile.php]: I appreciate your feedback, but I almost committed WSOD-inducing code. If you make a suggestion through GitHub, may I ask you to check for actual feasability? In this case `$app` doesn't exist in this function, but the suggestion display doesn't allow for an easy check.

File: src/Module/Profile.php [hunk 2]
```diff
@@ -54,15 +54,28 @@ public static function rawContent()
...
 			} elseif (DBA::exists('userd', ['username' => self::$which])) {
 				// Known deleted user
-				System::httpExit(410);
+				$data = [
+					'@context' => ActivityPub::CONTEXT,
+					'id' => self::getApp()->getBaseUrl() . '/profile/' . self::$which,
+					'type' => 'Tombstone',
+					'published' => DateTimeFormat::utcNow(DateTimeFormat::ATOM),
+					'updated' => DateTimeFormat::utcNow(DateTimeFormat::ATOM),
+					'deleted' => DateTimeFormat::utcNow(DateTimeFormat::ATOM),
```
Comment (annando) [inline src/Module/Profile.php]: I would suggest to add the deletion date to the "userd" table and to use it here. Additionally I would like to check if this is totally AP conform.

Comment (MrPetovan) [reply src/Module/Profile.php]: I copied the structure outlined here: https://www.w3.org/TR/activitypub/#delete-activity-outbox

Adding the deletion date to the userd table is good but I won't add it to this PR myself.

File: src/Module/Profile.php (hunk 1 above)
Comment (nupplaphil) [reply src/Module/Profile.php]: I'm sorry, next time I'll just add a "real" suggestion in case I'm sure with it. I saw it as a suggestion to change it "like/at least" that way.

File: src/Module/Profile.php (hunk 2 above)
Comment (annando) [reply src/Module/Profile.php]: Nonetheless I think that this has to part of the "Transmitter" class of the ActivityPub protocol.

File: src/Module/Profile.php (hunk 1 above)
Comment (MrPetovan) [reply src/Module/Profile.php]: I get it, and I've been on your end of this problem, where my suggestion in a code block (without even the convenient `Commit suggestion` button) has been used as is even though it was bogus (see https://github.com/friendica/friendica/commit/3de1fc3097cc7a1e38bf1a0c3cae5ae4ec8067eb).

Suggesting code is a tricky business, I'm tripping over myself regularly so the above ask is valid for myself as well.

File: src/Module/Profile.php (hunk 2 above)
Comment (MrPetovan) [reply src/Module/Profile.php]: Fair enough, I can move this code away from the Module.

File: src/Module/Profile.php [hunk 3]
```diff
@@ -54,15 +54,28 @@ public static function rawContent()
 	{
 		if (ActivityPub::isRequest()) {
 			$user = DBA::selectFirst('user', ['uid'], ['nickname' => self::$which]);
```
[the remark this answers is not in the document]
Comment (MrPetovan) [reply src/Module/Profile.php]: This check is already done by ActivityPub\Transmitter::getProfile. And I'm used to check the successful condition first (there is user data), then process the fail conditions (410 or 404).

[the remark this answers is not in the document]
Comment (annando) [reply src/Module/Profile.php]: Ah, I hadn't got a look at that function.

**Comment by annando** [comment]
BTW: I just checked with Mastodon: On deleted profiles they just return an empty page with a 410 header.

**Comment by MrPetovan** [comment]
"Friendica, now with better ActivityPub support than Mastodon!"

**Comment by annando** [comment]
@MrPetovan what are your plans with this PR? Do you intent to move the tombstone stuff into the AP class?

**Comment by MrPetovan** [comment]
Oh yeah, I forgot about it.

**Comment by MrPetovan** [comment]
All done.

File: src/Module/Profile.php [hunk 4]
```diff
@@ -63,14 +63,7 @@ public static function rawContent()
...
 				// Known deleted user
-				$data = [
-					'@context' => ActivityPub::CONTEXT,
-					'id' => self::getApp()->getBaseUrl() . '/profile/' . self::$which,
-					'type' => 'Tombstone',
-					'published' => DateTimeFormat::utcNow(DateTimeFormat::ATOM),
-					'updated' => DateTimeFormat::utcNow(DateTimeFormat::ATOM),
-					'deleted' => DateTimeFormat::utcNow(DateTimeFormat::ATOM),
-				];
+				$data = ActivityPub\Transmitter::getDeletedUser(self::$which);
```
Comment (annando) [inline src/Module/Profile.php]: Wouldn't ```getTombstoneForUsername``` a better name? "Tombstone" because the type is "tombstone" and this "ForUsername" because we possibly could have similar stuff for user ids or for item ids or other objects.

Comment (MrPetovan) [reply src/Module/Profile.php]: Possibly, I took after the name `getProfile` but it can be changed. `createNote` actually can return a `type: "Tombstone"` as well but it isn't explicit in the function name.

Comment (annando) [reply src/Module/Profile.php]: Ah okay.
