### PR TITLE
Guess language from plaintext

### LINKED ISSUE #4867: Guess language from the plaintext version of posts' body
Currently, short posts with an URL trigger the language filter even with a content limit set and the guessed language is often wrong because it includes the URL.

I want to extract the plaintext from items' body, run the language guesser on the plaintext only, and match the character limit of the `langfilter` addon against the plaintext body as well.

This would add another column to the `item` table with the plaintext content to avoid repetitive content parsing.

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #4867

This PR introduces a backward-incompatible change as `BBCode::toPlaintext` is completely replaced. It used to be an item-specific function that is now `Item::getPlaintextPost()`.

Don't forget https://github.com/friendica/friendica-addons/pull/591 after merging this.

### CODE REVIEW

**Comment by annando** [comment]
Why had you moved it in the item class? I thought that in this class only database specific stuff containing items is okay?

**Comment by MrPetovan** [comment]
I can move it to the `Object\Post` class instead, but it uses `item` table field names, so my first instinct was to move it to Item. Besides the `Object\Post` class isn't a static class.

But I agree with your premise. I just didn't know where else to put this big blob about an item fields but without database calls.

**Comment by annando** [comment]
We have the ```include/conversation.php``` and ```include/items.php``` to convert to classes well. I think that both files are playing in the same area.

**Comment by MrPetovan** [comment]
I can do that indeed.

**Comment by MrPetovan** [comment]
I created a new `Model\ItemContent` class to handle the item content in a separate class as you suggested here: https://github.com/friendica/friendica/issues/4867#issuecomment-383079418

File: src/Model/ItemContent.php [hunk 1]
```diff
@@ -0,0 +1,177 @@
...
+				$limit = $limit - 23;
+			}
+
+			if (iconv_strlen($msg, 'UTF-8') > $limit) {
+				if (($post['type'] == 'text') && isset($post['url'])) {
+					$post['url'] = $item['plink'];
+				} elseif (!isset($post['url'])) {
+					$limit = $limit - 23;
+					$post['url'] = $item['plink'];
+					// Which purpose has this line? It is now uncommented, but left as a reminder
```
Comment (annando) [inline src/Model/ItemContent.php]: This line is important for posting reshared items to networks that don't support these reshares. By adding the original post people can follow this link to see that we aren't faking it.

**Comment by MrPetovan** [comment]
> And during the review I just realised that we have src/Content/Text/Plaintext.php - isn't it confusing having some plaintext function outside that class?

No, this function specifically operates on an `$item` array, while Text\* classes are operating on strings only to separate concerns.

File: src/Model/ItemContent.php (hunk 1 above)
Comment (MrPetovan) [reply src/Model/ItemContent.php]: I didn't write the original comment, I don't know who did because they didn't sign and now the code has moved file twice.

Should we even keep the commented code below?

Comment (annando) [reply src/Model/ItemContent.php]: Luckily this hadn't been removed. This code should be uncommented.

**Comment by annando** [comment]
I guess I will never understand to which namespace a class belongs ...

File: src/Model/ItemContent.php (hunk 1 above)
Comment (MrPetovan) [reply src/Model/ItemContent.php]: So uncomment the code, remove the comment?

Comment (annando) [reply src/Model/ItemContent.php]: I think so.

Comment (MrPetovan) [reply src/Model/ItemContent.php]: Done.

**Comment by MrPetovan** [comment]
Can we move on with this PR (and the one in addons?)

**Comment by annando** [comment]
I had been busy all day and visited friends, so I hadn't got time until now.
