### PR TITLE
Mark string translatable in View logs

### LINKED ISSUE #10767: Strings are not marked as translatable in View Logs
### Bug Description

The file [view/theme/frio/templates/admin/logs/view.tpl](https://github.com/friendica/friendica/blob/develop/view/theme/frio/templates/admin/logs/view.tpl) has all the strings hard coded, there is no translation support. These strings are displayed always in English in the browser.

### Steps to Reproduce

Open the source file mentioned above and check the strings. Nothing is marked as translatable.

Actual Result:

The page is rendered always in English. It doesn't honor the system language.

Expected Result:

The page should be rendered in the language of the system.

### Platform Info

Friendica Version: 2021.09

### PR DESCRIPTION
**Pull request by fabrixxm**
and update messages.po

should fix #10767 

level and context filters values are not translated , because they are as they appear in log messages (which are not translated, also...)

### CODE REVIEW

File: src/Module/Admin/Logs/View.php [hunk 1]
```diff
@@ -81,13 +80,35 @@ public static function content(array $parameters = [])
 			}
 		}
 		return Renderer::replaceMacros($t, [
-			'$title'         => DI::l10n()->t('Administration'),
-			'$page'          => DI::l10n()->t('View Logs'),
+			'$title' => DI::l10n()->t('Administration'),
+			'$page'  => DI::l10n()->t('View Logs'),
+			'$l10n'  => [
```
Comment (MrPetovan) [inline src/Module/Admin/Logs/View.php:85]: Hmmm, interesting.

**Review by MrPetovan — APPROVED** [review]

File: src/Module/Admin/Logs/View.php [hunk 2]
```diff
@@ -81,13 +80,35 @@ public static function content(array $parameters = [])
...
+				'UID'                   => DI::l10n()->t('UID'),
+				'Process_ID'            => DI::l10n()->t('Process ID'),
+				'Close'                 => DI::l10n()->t('Close'),
+			],
 			'$data'          => $data,
 			'$q'             => $search,
 			'$filters'       => $filters,
 			'$filtersvalues' => $filters_valid_values,
 			'$error'         => $error,
+			'$baseurl'       => DI::baseUrl()->get(true),
```
Comment (tobiasd) [inline src/Module/Admin/Logs/View.php]: What is the baseurl needed for?

Comment (fabrixxm) [reply src/Module/Admin/Logs/View.php]: mmh.. nothing I think.. I copy-pasted some code from Settings.php and forgot to remove that.. let me see..

Comment (MrPetovan) [reply src/Module/Admin/Logs/View.php]: It can be needed to use absolute URLs in templates, and as such it is added by default in all templates, so this instance is superfluous on multiple counts.

**Review by MrPetovan — APPROVED** [review]

File: src/Module/Admin/Logs/View.php (hunk 1 above)
Comment (urbalazs) [reply src/Module/Admin/Logs/View.php:85]: This results more readable source code. I would like to see this solution for other template files.

Comment (MrPetovan) [reply src/Module/Admin/Logs/View.php:85]: Thank you for your input, this is something you would be able to help with yourself. Template files are mentioned in the PHP source code where the variables are passed, it just is a matter of isolating the translation strings in the variable array and updating the references in the template files (watch our for theme-specific copies of the same template name).
