### PR TITLE
 Catch missing Certainty bundle exception when checking for exposed password

### LINKED ISSUE #7709: Password reset doenst work
Request password reset and received email but the link doesnt work.

Got a HTTP ERROR 500 

Logfile:

```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ParagonIE\\Certainty\\Exception\\BundleException: No valid bundles were found in the data directory. in /var/www/clients/client0/web1/web/vendor/paragonie/certainty/src/Fetch.php:128
Stack trace:
#0 /var/www/clients/client0/web1/web/vendor/divineomega/password_exposed/src/PasswordExposedChecker.php(72): ParagonIE\\Certainty\\Fetch->getLatestBundle()
#1 /var/www/clients/client0/web1/web/vendor/divineomega/password_exposed/src/PasswordExposedChecker.php(45): DivineOmega\\PasswordExposed\\PasswordExposedChecker->getBundleFromCertainty()
#2 /var/www/clients/client0/web1/web/src/Model/User.php(414): DivineOmega\\PasswordExposed\\PasswordExposedChecker->__construct(Object(GuzzleHttp\\Client), Object(DivineOmega\\DOFileCachePSR6\\CacheItemPool))
#3 /var/www/clients/client0/web1/web/src/Model/User.php(462): Friendica\\Model\\User::isPasswordExposed
...
```

Any help is much appreciated :)

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #7709 

Missing Certainty bundles won't crash password exposition check anymore. Exceptions are now logged.

### CODE REVIEW

File: src/Core/Logger.php [hunk 1]
```diff
@@ -64,7 +64,6 @@ class Logger extends BaseObject
 		self::TRACE => 'Trace',
 		self::DEBUG => 'Debug',
 		self::DATA => 'Data',
-		self::ALL => 'All',
```
Comment (nupplaphil) [inline src/Core/Logger.php]: How is this entry a duplicate?

File: src/Model/User.php [hunk 2]
```diff
@@ -420,9 +421,20 @@ public static function isPasswordExposed($password)
 			'cacheDirectory' => get_temppath() . '/password-exposed-cache/',
 		]);
 
-		$PasswordExposedCHecker = new PasswordExposed\PasswordExposedChecker(null, $cache);
+		try {
+			$passwordExposedChecker = new PasswordExposed\PasswordExposedChecker(null, $cache);
+
+			return $passwordExposedChecker->passwordExposed($password) === PasswordExposed\PasswordStatus::EXPOSED;
+		} catch (\Exception $e) {
```
Comment (nupplaphil) [inline src/Model/User.php]: Using `Throwable` since it seems like we're catching technical exceptions too?

File: src/Core/Logger.php (hunk 1 above)
Comment (MrPetovan) [reply src/Core/Logger.php]: Look at the definition of the constants, both `self::DATA` and `self::ALL` equal `debug`, which makes them unsuitable to be keys in the same array.

File: src/Model/User.php (hunk 2 above)
Comment (MrPetovan) [reply src/Model/User.php]: I'm not sure about that, since the result is a silent success of password exposed. I'd rather only catch userland exceptions at this point. I feel like catching `\Throwable` should be lower in the call chain.
