### PR TITLE
Convert Atom last updated date to MySQL format

### LINKED ISSUE #4390: Cant update new posts from diaspora because something tries to store incorrect datetime Format
Hey there,

I get no new Posts from diaspora because it gets a wrong datetime.

Friendica contact posts are stored correctly.

Is this a failure in my mysql, php or should I change something in code?

```
2018-02-03T23:02:22Z@wrk5a763f770551f0.64773636 [NORMAL]:dba.php:546:e  DB Error 1292: Incorrect datetime value: '2017-05-14T16:56:06Z' for column 'last-item' at row 1                                                           │
dba::update, OnePoll::execute, call_user_func_array, Worker::processQueue                                                                                                                                                         │
UPDATE `contact` SET `last-item` = '2017-05-14T16:56:06Z', `last-update` = '2018-02-03 23:02:22', `success_update` = '2018-02-03 23:02:22' WHERE `id` = '20'                                                                      │
2018-02-03T23:02:22Z@log5a763f7696e341.90752934 [NORMAL]:Worker.php:386:execFunction    Process 9096 - Prio 40 - ID 9806: OnePoll - done in 7.319 seconds. Process PID: wrk5a763f770551f0.64773636                                │
2018-02-03T23:02:22Z@wrk5a763f76c9ff43.47452872 [NORMAL]:dba.php:546:e  DB Error 1292: Incorrect datetime value: '2018-02-02T20:53:07Z' for column 'last-item' at row 1                                                           │
dba::update, OnePoll::execute, call_user_func_array, Worker::processQueue
```

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #4390

Two issues here:
- We were inserting Atom-formatted dates into MySQL datetime fields
- `DBM::date()` was localizing date in the DB although we normally store UTC datetimes.

### CODE REVIEW

File: src/Database/DBM.php [hunk 1]
```diff
@@ -114,19 +114,13 @@ public static function esc_array(&$arr, $add_quotation = false)
...
 	{
-		$timestamp = strtotime($date);
-
-		// Don't allow lower date strings as '0001-01-01 00:00:00'
-		if ($timestamp < -62135596800) {
-			$timestamp = -62135596800;
-		}
-
-		return date(DateTimeFormat::MYSQL, (int)$timestamp);
+		return DateTimeFormat::utc($date);
```
Comment (annando) [inline src/Database/DBM.php]: The special thing about the old function is to check for the minimal date that is allowed. I think that this has to be added somewhere.

Comment (MrPetovan) [reply src/Database/DBM.php]: I believe it is already right here: https://github.com/friendica/friendica/blob/develop/src/Util/DateTimeFormat.php#L111

Comment (annando) [reply src/Database/DBM.php]: This looks really, really ugly to me, since you can use keywords for this function that might interfere. Have you checked if this works?

**Comment by annando** [comment]
Something in general: I compared the output of the functions:
```
echo DateTimeFormat::utc('now')."\n";
echo DBM::date('now')."\n";
```
It looked identically. ```DBM::date``` already returned the data in the MySQL format. So the source of the problem described above seems to be something different.

But in fact the old function does some localisation which doesn't seem to be right.

I guess we have to dig deeper for the problem that had been described in issue #4390 - and this "hackish" solution is so hackish that I would like to have some more obvious way. And finally I discovered that the ```utc``` function doesn't accept leaving out the date parameter. The ```date``` function then defaults to "now" which should be a good solution for the ```utc``` function as well.

File: src/Database/DBM.php (hunk 1 above)
Comment (MrPetovan) [reply src/Database/DBM.php]: We using are using keywords explicitly, so there are no reasons to believe we would intentionally go before 0001.

**Comment by MrPetovan** [comment]
The problem was the output format of the PortableContact::lastUpdated function which wasn’t always passed to `DBM::date()`. Even if it was, it would have been wrong because localized.

If you want UTC now, just use `DateTimeFormat::utcNow()`. Explicit arguments are better for readability. You can’t guess what `datetime_convert()` does by itself without looking at the function declaration, but you don’t have to guess what `DateTimeFormat::utcNow()` does.

**Comment by MrPetovan** [comment]
What is hackish about this solution? The Atom feed will always return a ISO formatted datetime string, and we only use MySQL formatted datetime strings, whether for comparison or database storage.

**Comment by annando** [comment]
With "hackish" I'm only referring to the "+32days" solution in the convert function. (And the comment there, that describes the solution as "hackish" by itself.

**Comment by MrPetovan** [comment]
The non-hackish way would be to throw an Exception if the date is out of range, not silently modify the input because it is more convenient.

**Comment by annando** [comment]
I don't like exceptions :-)
