### PR TITLE
Move missing POST part of Profile\Photos\Index from mod/photos

### LINKED ISSUE #12245: Image upload broken - Exception method not allowed
- [x] I have searched open and closed issues for duplicates

### Bug Description

Image/photo upload is broken in develop branch.

### Steps to Reproduce

1.  go to your photos page
2.  select 'browse' to find a photo on your device
3.  click 'submit'

Doesn't work with or w/o 'js_upload' add-on.

Actual Result:

```
Exception thrown in .../src/Module/HTTPException/MethodNotAllowed.php:32
Stack trace:
#0 .../src/BaseModule.php(244): Friendica\Module\HTTPException\MethodNotAllowed->content()
#1 .../src/App.php(739): Friendica\BaseModule->run()
#2 .../index.php(44): Friendica\App->runFrontend()
#3 {main}
```

Expected Result:

Well, I want to upload images.

### Platform Info

Friendica Version:
2022.12-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #4090
Fix #12245
Follow-up to #12228

### CODE REVIEW

**Comment by AlfredSK** [comment]
Thanks! Can you please have a look at the failing messages.po check?

**Comment by MrPetovan** [comment]
Yup!

File: src/Module/Profile/Photos/Index.php [hunk 1]
```diff
@@ -52,16 +61,268 @@ class Index extends \Friendica\Module\BaseProfile
...
+		if (!$user) {
+			throw new HTTPException\NotFoundException($this->t('User not found.'));
+		}
+
+		$page_owner_uid = intval($user['uid']);
+		$visitor   = $this->session->getRemoteContactID($page_owner_uid);
+
+		$can_post =
+			$this->session->getLocalUserId() && ($this->session->getLocalUserId() == $page_owner_uid)
+			|| $visitor && $user['page-flags'] == User::PAGE_FLAGS_COMMUNITY;
```
Comment (nupplaphil) [inline src/Module/Profile/Photos/Index.php]: Does it really work like intended?
It seems like without parantheses, it's enough to just be a `$visitor`

**Review by nupplaphil — CHANGES_REQUESTED** [review]

File: src/Module/Profile/Photos/Index.php (hunk 1 above)
Comment (MrPetovan) [reply src/Module/Profile/Photos/Index.php]: && has precedence over || so `visitor and community` is evaluated altogether.

Comment (annando) [reply src/Module/Profile/Photos/Index.php]: This community thingy looks like some really old preparation for some functionality that never had been fully implemented. Doesn't this coding mean that any subscriber of a forum does have got write access? This doesn't really feel quite right. I would prefer having this feature disabled by default.

File: src/Module/Profile/Photos/Index.php [hunk 2]
```diff
@@ -52,16 +61,268 @@ class Index extends \Friendica\Module\BaseProfile
...
+
+	protected function post(array $request = [])
+	{
+		$user = User::getByNickname($this->parameters['nickname'] ?? '');
+		if (!$user) {
+			throw new HTTPException\NotFoundException($this->t('User not found.'));
+		}
+
+		$page_owner_uid = intval($user['uid']);
+		$visitor   = $this->session->getRemoteContactID($page_owner_uid);
```
Comment (annando) [inline src/Module/Profile/Photos/Index.php]: In the original code `$visitor` is set to `0` for local users. I would prefer keeping it that way to avoid any side effects.

Comment (MrPetovan) [reply src/Module/Profile/Photos/Index.php]: I thought it was the case in `getRemoteContactID`. Why are we populating the contact Id of the local user?

File: src/Module/Profile/Photos/Index.php (hunk 1 above)
Comment (MrPetovan) [reply src/Module/Profile/Photos/Index.php]: Gladly and yes, that was the intent.

File: src/Module/Profile/Photos/Index.php (hunk 2 above)
Comment (annando) [reply src/Module/Profile/Photos/Index.php]: I haven't checked, but I wouldn't rely on it in any way 😬

File: src/Module/Profile/Photos/Index.php [hunk 3]
```diff
@@ -52,16 +61,265 @@ class Index extends \Friendica\Module\BaseProfile
...
+
+	protected function post(array $request = [])
+	{
+		$user = User::getByNickname($this->parameters['nickname'] ?? '');
+		if (!$user) {
+			throw new HTTPException\NotFoundException($this->t('User not found.'));
+		}
+
+		$page_owner_uid = intval($user['uid']);
+		$visitor        = $this->session->getLocalUserId() ? 0 : $this->session->getRemoteContactID($page_owner_uid);
```
Comment (annando) [inline src/Module/Profile/Photos/Index.php]: Using the `$visitor` doesn't make sense when `$can_post` will be `false` each time the `$visitor` is non-zero.

File: src/Module/Profile/Photos/Index.php (hunk 2 above)
Comment (MrPetovan) [reply src/Module/Profile/Photos/Index.php]: I reverted to the existing behavior.

File: src/Module/Profile/Photos/Index.php (hunk 3 above)
Comment (MrPetovan) [reply src/Module/Profile/Photos/Index.php]: `$visitor` is provided when creating the Photo records later.

Comment (annando) [reply src/Module/Profile/Photos/Index.php]: Since we only continue with a local user, the `$visitor` will now always be `0`. So we don't need to set it any more, don't we?

Comment (MrPetovan) [reply src/Module/Profile/Photos/Index.php]: Ah, right, I missed the condition. I'll remove the superfluous code.

Comment (annando) [reply src/Module/Profile/Photos/Index.php]: Soon I'm off for the day. I guess I can have a short glance at it tomorrow.

**Review by annando — APPROVED** [review]
I'm happy with this when @nupplaphil is as well. Had you tested it on your machine?

**Comment by MrPetovan** [comment]
Not this particular PR, I'll be able to perform a couple of uploads later today.

**Comment by MrPetovan** [comment]
This has now been tested on my production node with success.

**Comment by nupplaphil** [comment]
Meeeerge conflicts :-)

**Review by nupplaphil — APPROVED** [review]
