### PR TITLE
Transform email header string to header array

### LINKED ISSUE #9142: [phpmailer] Double Message-ID header in some notification mails - RFC violation
### Expected behavior
A mail must contain one Message-ID header. Two Message-ID headers are a RFC violation.
Setting the message ID is a task for the used mailer but not for the application, I think.

### Actual behavior
Some (!) - not all - notification messages have two Message-ID headers. I got bounce mails because of this RFC violation.

I think the problem is here:
https://github.com/friendica/friendica/blob/40a93223ee0fcc77d541f2ef9c3c02a2722a41fe/include/enotify.php#L523

Example:
```
Date: Fri, 4 Sep 2020 00:42:35 +0000
To: libranet@someremotedomain.com
From: "LIBRANET.de" <admin@libranet.de>
Reply-To: "LIBRANET.de" <admin@libranet.de>
Subject: [Friendica:Notify] Example User tagged you (exampleuser@libranet.de)
Message-ID: <Blx5qbY0czTL40q3ZNGWzGjgvszFW9ECBcRJWwGU@librabox2.libranet.de>
X-Mailer: PHPMailer 6.1.4 (https://github.com/PHPMailer/PHPMailer)
Precedence: list
X-Friendica-Host: libranet.de
X-Friendica-Platform: Friendica
X-Friendica-Version: 2020.09-dev
List-ID: <notification.libranet.de>
List-Archive: <https://libranet.de/notifications/system>
X-Friendica-Account: <exampleuser@libranet.de>
Message-ID: <83810059@libranet.de>
MIME-Version: 1.0
Content-Type: multipart/alternative;
....
```

### Steps to reproduce the problem
I do use the phpmailer add-on. That add-on creates a message ID with the local hostname as domain part. That's okay.

But enotify adds another message ID under some circumstances. Most other notification mails have a `References: <83200641@libranet.de>` and `In-Reply-To: <83200641@libranet.de>` instead. That works. But the two message IDs are bad.

### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

### PR DESCRIPTION
**Pull request by nupplaphil**
Fixes #9142 

Prerequisite for addon fix https://github.com/friendica/friendica-addons/pull/1020

### CODE REVIEW

File: src/Util/EMailer/MailBuilder.php [hunk 1]
```diff
@@ -159,15 +160,32 @@ public function withRecipient(string $address)
...
+	 * @param string $value The value to set
 	 *
 	 * @return static
 	 */
-	public function addHeaders(string $headers)
+	public function	setHeader(string $name, string $value)
 	{
-		$this->headers .= $headers;
+		$this->headers[$name] = [];
+		$this->headers[$name][] = $value;
```
Comment (MrPetovan) [inline src/Util/EMailer/MailBuilder.php]:
```suggestion
		$this->headers[$name] = [$value];
```

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Util/EMailer/MailBuilder.php (hunk 1 above)
Comment (nupplaphil) [reply src/Util/EMailer/MailBuilder.php:188]: Is it really the same? Adding a value to an values array?

**Review by MrPetovan — APPROVED** [review]
