### PR TITLE
Add relocate console command and fix the missing DB tables for the relocation

### LINKED ISSUE #11511: Domain Name Change
I have had to switch domains from www.xxx.tk to www.xxx.org since my .tk domain was lost. I have read that changing domains is supported but I cannot find any instructions on how to do it. I tried to set the ENV VAR FRIENDICA_URL=https://www.xxx.org but it has no effect on an existing docker installation.
Thanks for your help.

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #11511

### CODE REVIEW

**Review by tobiasd — APPROVED** [review]

**Comment by tobiasd** [comment]
Some checks are failing

File: src/Core/Relocate.php [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+		$this->database->replaceInTableFields('contact', ['addr'], $old_host, $new_host);
+
+		// update config
+		$this->config->set('system', 'url', $new_url);
+		$this->baseUrl->saveByURL($new_url);
+
+		// send relocate
+		$users = $this->database->selectToArray('user', ['uid'], ['account_removed' => false, 'account_expired' => false]);
+		foreach ($users as $user) {
+			Worker::add(PRIORITY_HIGH, 'Notifier', Delivery::RELOCATION, $user['uid']);
```
Comment (tobiasd) [inline src/Core/Relocate.php]: Is it possible to add a similar functionality for the Fediverse contacts? Some automatic follow request for the Mastodon, Pixelfed etc. contacts that do not understand the relocate for Friendica and Diaspora*?

Net necessarily now, but in general possible?

**Review by tobiasd — APPROVED** [review]

File: src/Core/Relocate.php (hunk 1 above)
Comment (annando) [reply src/Core/Relocate.php]: The relocation mechanism is completely different for Mastodon (and I'm not sure if any other system is supporting it). The Mastodon way only works when both systems are reachable.

Comment (tobiasd) [reply src/Core/Relocate.php]: Ok, so when @annando is happy with the code, he can merge the PR :)

File: src/Core/Relocate.php [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+
+		// Generate host names for relocation the addresses in the format user@address.tld
+		$new_host = str_replace('http://', '@', Strings::normaliseLink($new_url));
+		$old_host = str_replace('http://', '@', Strings::normaliseLink($old_url));
+
+		// update tables
+		// update profile links in the format "http://server.tld"
+		$this->database->replaceInTableFields('profile', ['photo', 'thumb'], $old_url, $new_url);
+		$this->database->replaceInTableFields('contact', ['photo', 'thumb', 'micro', 'url', 'nurl', 'alias', 'request', 'notify', 'poll', 'confirm', 'poco', 'avatar'], $old_url, $new_url);
+		$this->database->replaceInTableFields('post-content', ['body'], $old_url, $new_url);
```
Comment (annando) [inline src/Core/Relocate.php]: there are more tables that contain an URL, for example the `fcontact` and the `apcontact`. Also there is the  item-uri` table.

Also in the `tag` table there are now links as well.

Comment (MrPetovan) [reply src/Core/Relocate.php]: I just moved the existing feature in its separate class, if I need to update it to be current with the database structure, can you make sure of the list of additional tables/fields that need to be updated?

Comment (annando) [reply src/Core/Relocate.php]: I had a look at all tables that contain fields  with links:

- `gserver`
- `user`
- `item-uri`
- `contact`
- `tag`
- `apcontact`
- `conv`
- `delayed-post`
- `endpoint`
- `event`
- `fcontact`
- `fsuggest`
- `inbox-status`
- `mail`
- `notify`
- `post-content`
- `post-history`
- `post-link`
- `post-media`

Comment (MrPetovan) [reply src/Core/Relocate.php]: Thank you for the list, the important is that it may contain local link based on the relocated server domain.

Comment (annando) [reply src/Core/Relocate.php]: With some of them I'm not 100% sure (for example the `tag` table). But better safe than sorry, I think.

Comment (MrPetovan) [reply src/Core/Relocate.php]: I guess so, it's an expensive action anyway, adding a few more tables even if unwarranted won't change much to that.

Comment (MrPetovan) [reply src/Core/Relocate.php]: What are the URL fields in the `user` table? I wasn't able to find any.

**Comment by MrPetovan** [comment]
I've updated the list of tables that are changed during the process.

File: src/Core/Relocate.php (hunk 2 above)
Comment (annando) [reply src/Core/Relocate.php]: You are right, there doesn't seem to be any fields in that table that need to be changed. But the other should be okay.

File: src/Module/Admin/Site.php [hunk 3]
```diff
@@ -60,70 +61,19 @@ protected function post(array $request = [])
...
-			$new_url = rtrim($new_url, "/");
-
-			$parsed = @parse_url($new_url);
-			if (!is_array($parsed) || empty($parsed['host']) || empty($parsed['scheme'])) {
-				notice(DI::l10n()->t("Can not parse base url. Must have at least <scheme>://<domain>"));
-				DI::baseUrl()->redirect('admin/site');
+		if (!empty($_POST['relocate']) && !empty($_POST['relocate_url'])) {
+			try {
+				$relocate = new Relocate(DI::baseUrl(), DI::dba(), DI::config(), DI::logger());
+				$relocate->run($_POST['relocate_url']);
```
Comment (annando) [inline src/Module/Admin/Site.php]: We change that much data during the execution of this command, that I don't think that we can execute it via the web frontend. It will run into a timeout and then will leave the system in a quirky state. We should only allow the relocate command via the command line.

**Review by annando — CHANGES_REQUESTED** [review]
Because of the mass of data that is changed here, I think that we shouldn't execute it via the web, because most likely it will last longer than the timeouts that most system do have for the execution time of their frontend php process.

When this is moved to a console only command, we then could also provide some visual output via the execution.

**Comment by tobiasd** [comment]
You mean remove the relocate option from the admin panel? But then, please, leave a "clear" note in the admin panel that the option to relocate is available with the console command.

**Comment by annando** [comment]
Yeah, executed via the admin panel this will surely lead to a corrupted database. And yes, we should reference to the console command like we do with the relay settings.

File: src/Module/Admin/Site.php (hunk 3 above)
Comment (MrPetovan) [reply src/Module/Admin/Site.php]: Ok, fair enough.

Comment (annando) [reply src/Module/Admin/Site.php]: Sorry, that I hadn't thought about this earlier.

**Comment by MrPetovan** [comment]
Should we use a transaction for this process?

**Comment by annando** [comment]
Sounds like a good idea with the transaction.

**Comment by MrPetovan** [comment]
Done, added transaction, replaced admin site settings form by the mention of the console command,

Didn't test the command.

**Review by annando — APPROVED** [review]
