### PR TITLE
 Fix OEmbed iframe

### LINKED ISSUE #4173: Missing OEmbed URL failing with X-Frame-Options: Same-Origin policy
Post from Diaspora: https://friendica.mrpetovan.com/display/527f8ee0d3fd0135db5d0242ac150005

Original embedded URL: https://blogs.mprnews.org/newscut/2018/01/reporters-on-icebergs-while-dc-tells-minnesota-to-stuff-it-over-our-weather-expertise/
Expected OEmbed iframe URL: https://blogs.mprnews.org/newscut/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fblogs.mprnews.org%2Fnewscut%2F2018%2F01%2Freporters-on-icebergs-while-dc-tells-minnesota-to-stuff-it-over-our-weather-expertise%2F

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #4173

I finally got a chance to really dive deep into OEmbed, and I gotta say it's pretty cool as it allows to add HTML to display rich third-party content embeds.

Of course, this means that bad actors can add harmful scripts to their OEmbed snippets and harvest data on our local website. So far, we relied on a same domain iframe to mitigate the issue which would actually do very little while adding complexity.

Now we have a domain whitelist to allow specific domains to embed their HTML in Friendica posts (#4167) and we don't use the same domain iframe anymore. I left the function in the code in case someone wants to implement a different OEmbed domain settings.

I also tackled an issue that was bugging me for a while. We receive quote tweets from Twitter as shares, and if the quoted tweet mentions another tweet, it is treated as a link attachment and the display is mangled.

Instead, the quoted tweet is now treated as a rich attachment for display purposes and we let Twitter decide to display mentioned links (or not).

Caveat: Let's Encrypt for Apache2 on Debian Stretch sets X-Frame-Options=SAMEORIGIN for all requests, which effectively kills most iframe-based embeds, including WordPress. Unless people comment out the `Header always set X-Frame-Options SAMEORIGIN` line in their Let's Encrypt configuration file (`/etc/letsencrypt/options-ssl-apache.conf` on Debian), there's nothing to do to fix those embeds.

### CODE REVIEW

**Comment by MrPetovan** [comment]
I opened a ticket at https://github.com/certbot/certbot/issues/5376 but their current shared Apache configuration file doesn't feature the `X-Frame-Options` directive...

File: include/bbcode.php [hunk 1]
```diff
@@ -586,20 +586,26 @@ function bb_ShareAttributes($share, $simplehtml)
...
-			$text .= replace_macros($tpl, array(
-					'$profile' => $profile,
-					'$avatar' => $avatar,
-					'$author' => $author,
-					'$link' => $link,
-					'$posted' => $posted,
-					'$content' => trim($share[3])
-				)
-			);
+			// Transforms quoted tweets in rich attachments to avoid nested tweetsx
```
Comment (tobiasd) [inline include/bbcode.php]: Is tweetsx a typo or a new term (I am actually really confused with new terms being invented by everyone, so tweetsx might just be something I've never heard about before)

Comment (MrPetovan) [reply include/bbcode.php]: It is a typo! 😄

File: include/bbcode.php [hunk 2]
```diff
@@ -586,20 +586,26 @@ function bb_ShareAttributes($share, $simplehtml)
...
+			if (stripos(normalise_link($link), 'http://twitter.com/') === 0) {
```
Comment (annando) [inline include/bbcode.php]: What will happen when rich oembedding is deactivated?

File: src/Content/OEmbed.php [hunk 3]
```diff
@@ -299,6 +296,8 @@ public static function HTML2BBCode($text)
 	 * Since the iframe is automatically resized on load, there are no need for ugly
 	 * and impractical scrollbars.
 	 *
+	 * @todo This function is currently unused until someone™ adds support for a separate OEmbed domain
```
Comment (annando) [inline src/Content/OEmbed.php]: 😀

File: src/Content/OEmbed.php [hunk 4]
```diff
@@ -315,10 +314,7 @@ private static function iframe($src, $width, $height)
 		}
 		$width = '100%';
 
-		// Only proxy OEmbed URLs to avoid mixed-content errors
```
Comment (annando) [inline src/Content/OEmbed.php]: Mixed content problems cannot exist anymore?

Comment (MrPetovan) [reply src/Content/OEmbed.php]: No because we're just pasting the Oembed HTML snippet directly into the post rendered HTML.

File: include/bbcode.php (hunk 2 above)
Comment (MrPetovan) [reply include/bbcode.php]: That's a very good question, I'll test it.

File: include/bbcode.php (hunk 1 above)
Comment (annando) [reply include/bbcode.php]: Do you want to fix it?

Comment (MrPetovan) [reply include/bbcode.php]: Yes I will, I had friends over at home today which explains the lack of reaction.

**Comment by annando** [comment]
This PR generated a problem because "tryoembed" doesn't exist anymore:
```
PHP Warning:  preg_replace_callback(): Requires argument 2, 'tryoembed', to be a valid callback in /var/www/virtual/pirati.ca/htdocs/include/bbcode.php on line 1026
PHP Warning:  preg_replace_callback(): Requires argument 2, 'tryoembed', to be a valid callback in /var/www/virtual/pirati.ca/htdocs/include/bbcode.php on line 1225
PHP Warning:  preg_replace_callback(): Requires argument 2, 'tryoembed', to be a valid callback in /var/www/virtual/pirati.ca/htdocs/include/bbcode.php on line 1226
PHP Warning:  preg_replace_callback(): Requires argument 2, 'tryoembed', to be a valid callback in /var/www/virtual/pirati.ca/htdocs/include/bbcode.php on line 1245
PHP Warning:  preg_replace_callback(): Requires argument 2, 'tryoembed', to be a valid callback in /var/www/virtual/pirati.ca/htdocs/include/bbcode.php on line 1246
PHP Warning:  preg_replace_callback(): Requires argument 2, 'tryoembed', to be a valid callback in /var/www/virtual/pirati.ca/htdocs/include/bbcode.php on line 1247
PHP Warning:  preg_replace_callback(): Requires argument 2, 'tryoembed', to be a valid callback in /var/www/virtual/pirati.ca/htdocs/include/bbcode.php on line 1262
PHP Warning:  preg_replace_callback(): Requires argument 2, 'tryoembed', to be a valid callback in /var/www/virtual/pirati.ca/htdocs/include/bbcode.php on line 1263
PHP Warning:  preg_replace_callback(): Requires argument 2, 'tryoembed', to be a valid callback in /var/www/virtual/pirati.ca/htdocs/include/bbcode.php on line 991
```
