### PR TITLE
Issue 14524: Fix Open Search

### LINKED ISSUE #14524: OpenSearch provider not working: "Format not valid"
- [x] I have searched open and closed issues for duplicates

### Bug Description

When attempting to add Friendica as an OpenSearch provider to my browser, the process fails. The browser states that the format of the search is not valid.

### Steps to Reproduce

1.  Open your favorite Friendica instance.
2.  In your browser's search bar, click on the button to add Friendica as a search provider.

Actual Result:

The browser returns a pop-up error with a message similar to this:

> Format not valid
> Firefox could not install the searcher of: https://friendica.example.net/opensearch

Expected Result:

The browser should accept Friendica as a new search provider.

### Screenshots

imagen

### Platform Info

Friendica Version: 2024.08 through 2024.09-rc

Friendica Source: Both in Stable and Development

PHP version: 8.2

SQL version: 10.11.6-MariaDB-0+deb12u1

### PR DESCRIPTION
**Pull request by annando**
Fixes #14524

### CODE REVIEW

File: src/Module/OpenSearch.php [hunk 1]
```diff
@@ -9,33 +9,52 @@
...
  * Prints the opensearch description document
  * @see https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md#opensearch-description-document
  */
 class OpenSearch extends BaseModule
 {
+	/** @var IManageConfigValues */
+	private $config;
+
+	/** @var App\baseUrl */
+	protected $baseUrl;
```
Comment (MrPetovan) [inline src/Module/OpenSearch.php:31]: No need to repeat this class property already defined in `BaseModule`.
```suggestion
```

File: src/Module/OpenSearch.php [hunk 2]
```diff
@@ -9,33 +9,52 @@
...
+	/** @var string */
+	private $basePath;
+
+	public function __construct(BasePath $basePath, IManageConfigValues $config, L10n $l10n, App\baseUrl $baseUrl, App\Arguments $args, LoggerInterface $logger, Profiler $profiler, Response $response, array $server, array $parameters = [])
+	{
+		parent::__construct($l10n, $baseUrl, $args, $logger, $profiler, $response, $server, $parameters);
+
+		$this->config   = $config;
+		$this->basePath = $basePath->getPath();
+		$this->baseUrl  = $baseUrl;
```
Comment (MrPetovan) [inline src/Module/OpenSearch.php:42]: Duplicated assignment from the `BaseModule` constructor.
```suggestion
```
