### PR TITLE
Issue 12702: Let the user decide how to handle spoiler texts

### LINKED ISSUE #12702: CW/Spoiler Text isn't federating to Mastodon Correctly through Mastodon API
### Bug Description

When creating posts through the Mastodon API with CW/spoiler text it does not federate over to Mastodon in a way that renders correctly.

### Steps to Reproduce

1. Create a post through the Mastodon API that fillers in the spoiler field
2. Go to a Mastodon server to see how it renders.

For example this body:
```json
{
  "status": "main content",
  "visibility": "public",
  "spoiler_text": "A header"
}
```

sent into the POST endpoint: `/api/v1/statuses`

Actual Result:

With posts created in the 2022.12 and 2023.01 version the CW renders as a Title field which when clicked opens up to the post itself but without any additional text.

Expected Result:
It should render with a "SHOW MORE" button. 

### Screenshots
Below is a screenshot of a native Mastodon post below one federated over from the Friendica server:
image

This is the same native post with the additional text shown:
image

This is the post created with 2023.01 as rendered on the Friendica server:
image

This is the rendering of that post on Mastodon when I click on the header:
image

### Platform Info

Friendica Version: 2022.12 and 2023.01

Friendica Source: https://github.com/friendica/friendica/ stable branch

PHP version: 7.4.33

SQL version: MariaDB 15.1

### PR DESCRIPTION
**Pull request by annando**
Fixes #12702 by letting the user decide what to do with the spoiler text when a post is sent via the API.

### CODE REVIEW

File: src/Module/Settings/Connectors.php [hunk 1]
```diff
@@ -218,8 +220,8 @@ protected function content(array $request = []): string
...
 			'$simple_shortening'       => ['simple_shortening', $this->t('Enable simple text shortening'), $simple_shortening, $this->t('Normally the system shortens posts at the next line feed. If this option is enabled then the system will shorten the text at the maximum character limit.')],
 			'$attach_link_title'       => ['attach_link_title', $this->t('Attach the link title'), $attach_link_title, $this->t('When activated, the title of the attached link will be added as a title on posts to Diaspora. This is mostly helpful with "remote-self" contacts that share feed content.')],
+			'$api_spoiler_title'       => ['api_spoiler_title', $this->t('API: Use spoiler field as title'), $api_spoiler_title, $this->t('When activated, the "spoiler_text" field in the API will be used for the title on staring posts. When deactivated it will be used for spoiler text. For comments it will be used for spoiler text in any case.')],
```
Comment (MrPetovan) [inline src/Module/Settings/Connectors.php]:
```suggestion
			'$api_spoiler_title'       => ['api_spoiler_title', $this->t('API: Use spoiler field as title'), $api_spoiler_title, $this->t('When activated, the "spoiler_text" field in the API will be used for the title on standalone posts. When deactivated it will be used for spoiler text. For comments it will be always be used for spoiler text.')],
```

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Module/Settings/Connectors.php (hunk 1 above)
Comment (annando) [reply src/Module/Settings/Connectors.php]: We haven't used "standalone posts" for thread starting posts by now, I think. Possibly we should use some name that we already used?

Comment (MrPetovan) [reply src/Module/Settings/Connectors.php]: Internally we use "top-level" but we just started using it in translation strings (in the Post Not Found page of the display module).

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
I am surprised the messages.po check doesn't bark after you removed the duplicate "be".

**Comment by annando** [comment]
@MrPetovan look at https://github.com/friendica/friendica/pull/12720/commits/87e9dafc563a6fe91d9eb6880efa10c354b944e0 :-)

**Comment by HankG** [comment]
Would it be possible to make it so the default is to *not* share the old way. There is no indication to a user of Friendica that the way they are pushing stuff into the network via the API is not rendering with the hidden text behind the spoiler text but instead the link method. If not perhaps I could add an API endpoint to allow toggling through the API. We don't have a general settings endpoint yet but I know I'm going to need at least one for getting the maximum upload size for a given server. 

Anyway using the test server I have confirmed that the setting and new code is working. 
image

The same messages federated over to D* looks like everything is consistent with the settings there as well:
image
