### PR TITLE
Automatic BaseURL determination fix

### LINKED ISSUE #6941: Failure during config-file changing without a ',' at the end
```Parse error: syntax error, unexpected ''basepath'' (T_CONSTANT_ENCAPSED_STRING), expecting ']' in /path/to/friendica/config/local.config.php on line 96```

My config entry before this had no ```,```:

```
                'pidfile' => '/tmp/daemon.pid'
                'basepath' => '/path/to/friendica',
```

_Originally posted by @annando in https://github.com/friendica/friendica/pull/6935#issuecomment-476860496_

### PR DESCRIPTION
**Pull request by nupplaphil**
**A new beginning**

Fixes #6941 (by almost reverting that PR)
Part of #6720 
Reverting parts of #6920 
(still) Prerequesists of #6815 

This is a "new beginning" of this topic, because I felt like my first way isn't working well.

- Removing `ConfigFileSaver` because of complexity, bugs and no proper outlook/way.
- Introducing `Friendica\Util\BaseURL`, which checks, determines, holds and saves the following information
  - urlpath
  - ssl_policy
  - hostname
  - url
  - scheme
- Removing this parts of determination from the `App`
- Moving the `SSL_*` definition to the `BaseURL`

In fact, the BaseURL is now the main class for every URL-based checks.
It checks immediately after the configuration load, if we do have any of the values above. If not, it determines this parameter and saves it into the config table of the DB.

=> We don't do any config-file upgrade anymore, but instead we save the values in the DB.

As a test, I removed different parts of the values above and after the first load, the values are still reloaded into the config table again. I added some tests and tried it around.

This PR should work out of the box, and after it, I'll add the install-step again.

### CODE REVIEW

File: src/Util/BaseURL.php [hunk 1]
```diff
@@ -0,0 +1,363 @@
...
+	 *
+	 * @return bool true, if successful
+	 */
+	public function save($hostname = null, $sslPolicy = null, $urlPath = null)
+	{
+		$success = true;
+
+		if (!empty($hostname) && $hostname !== $this->hostname) {
+			$this->hostname  = $hostname;
+			if (!$this->config->set('config', 'hostname', $this->hostname)) {
```
Comment (MrPetovan) [inline src/Util/BaseURL.php]: Why not do `$success = $this->config->set('config', 'hostname', $this->hostname);` instead and save anf `if`?

This goes for all three following `config->set` calls.

Comment (nupplaphil) [reply src/Util/BaseURL.php]: Because `$success` should remain fals, even if the next setting was successful.

Comment (MrPetovan) [reply src/Util/BaseURL.php]: It smells like this is missing exceptions. What's the point of going forward with a non-descriptive `false` if any of the three config save aren't successful?

Comment (nupplaphil) [reply src/Util/BaseURL.php]: Hm.. The question is how can I make this step transactional. Because throwing an exception implies for me that the save wasn't successful at all.. Maybe inside a catch.. Or what do you think?

Comment (MrPetovan) [reply src/Util/BaseURL.php]: You can call `config->save` in the `catch` block with the previous values indeed. In the current form it isn't transactional either so I'm not sure it needs to be, but if you can fit it in, that would be great. Or use `config->save` with an array of changes?

Comment (nupplaphil) [reply src/Util/BaseURL.php]: Throwing an exception wouldn't be that easy and will lead to changing behavior in the `Config` class. Thus I don't want to change it for now.

I added a resetting logic in case one save wouldn't work.

**Comment by MrPetovan** [comment]
Will this PR automatically update an existing install? Even if it's missing the base URL from the config file?

**Comment by nupplaphil** [comment]
Yep. I tried it with my local instances (removed entries for url, urlpath & ssl_policy in config and DB).

The first call after the update will determine url, urlpath, ssl_policy automatically and saves it to the config table.

**Comment by nupplaphil** [comment]
mom .. I found a regression..

**Comment by nupplaphil** [comment]
Now it works again .. It was a regression of the old code (blacklist for saving).. I was wondering why everything worked except hostname .. Now it works as designed ;-)

**Comment by MrPetovan** [comment]
Here goes nothing!

**Comment by nupplaphil** [comment]
> 
> 
> Here goes nothing!

What? Shall I revert it?

**Comment by MrPetovan** [comment]
Don't worry, it just is an expression before starting something to moderate expectations.

I pulled on my node without an issue. But I think I had updated my base URL from an earlier failed try.

**Comment by nupplaphil** [comment]
> 
> 
> Don't worry, it just is an expression before starting something to moderate expectations.
> 
> I pulled on my node without an issue. But I think I had updated my base URL from an earlier failed try.

Ah OK. If there's a value in the DB, this will get used now. I could add a "is_directory" check during loading and in case it isn't a directory, it deteremines the basepath again.
