### PR TITLE
Fix Notifications cleared for threads

### LINKED ISSUE #8205: Notifications aren't cleared for a whole thread
### Expected behavior

Clicking on a post/reply notification clears the notifications for the whole thread.

### Actual behavior

Clicking on a post/reply notification clears the notification for the specific item in the thread (the most recent one) and then the next most recent notification in the same thread appears in the notification dropdown as if there was a new reply in the thread.

I believe this is a regression that was introduced by @nupplaphil 's work on notifications.

### PR DESCRIPTION
**Pull request by nupplaphil**
Fixes #8205
And fixes the failing travis test ;-)

### CODE REVIEW

File: include/api.php [hunk 1]
```diff
@@ -5973,6 +5973,8 @@ function api_friendica_notification_seen($type)
 		return api_format_data('result', $type, ['result' => "success"]);
 	} catch (NotFoundException $e) {
 		throw new BadRequestException('Invalid argument');
+	} catch (Exception $e) {
+		throw new InternalServerErrorException('Internal Server exception');
```
Comment (MrPetovan) [inline include/api.php]: If this happens, do we have the actual error (in `$e->getMessage()` logged anywhere?

Comment (nupplaphil) [reply include/api.php]: Now we have :) The origin exception will now get chained to the current exception and is now shown in the stack trace at `$e->getTraceAsString()`
