### PR TITLE
Issue 15607: Improved system actor handling

### LINKED ISSUE #15607: Missing uid 0 contact record causes ActivityPub follows to fall back to RSS
- [X] I have searched open and closed issues for duplicates

## Issue Description

On my Friendica node, following any Mastodon or ActivityPub account results
in the contact being created as an RSS feed connection rather than an
ActivityPub connection. The contact is stored with network type `feed` and
the URL is the `.rss` variant of the profile URL rather than the ActivityPub
actor URL.

## What I have investigated

WebFinger lookups from my server work correctly. Curl confirms that both
WebFinger and ActivityPub actor endpoints on remote instances respond
correctly when called from my server, including with Friendica's user agent
string. Inbound federation works fine, remote servers can post to my inbox
successfully.

The debug log shows the following error occurring during the follow process:
```log
Error fetching url: https://mastodon.social/users/MastodonEngineering
Exception: Could not find owner for uid 0 in HTTPSignature.php:546
```

The full sequence is that WebFinger succeeds and returns the correct
ActivityPub self link, but `ActivityPub::probeProfile` then calls
`HTTPSignature::fetchRaw` with uid 0, which fails because it cannot find an
owner for that uid. With `ap_profile` returning empty, the probe falls
through to `Probe::feed`, fetches the URL without an ActivityPub Accept
header, follows the redirect to the `.rss` URL, and stores the contact as
a feed.

## How to resolve this?

My question is whether this `Could not find owner for uid 0` error indicates
a misconfiguration on my node, for example a missing or broken system
account, and if so how to diagnose and fix it.

## Platform Info

| Field | Value |
|---|---|
| Friendica Version | 2026.01-1586 |
| Friendica Source | Git |
| PHP version | 8.4 |
| SQL version | |

### PR DESCRIPTION
**Pull request by annando**
This could fix #15607. At least it adds some logging to analyse possible problems.

### CODE REVIEW

File: src/Model/User.php [hunk 1]
```diff
@@ -253,27 +257,46 @@ private static function createSystemAccount()
...
+			if ($system_actor_name != $self['nick']) {
+				DI::logger()->notice('Set the actor name to the system contact name', ['name' => $self['nick'], 'systemactor' => $system_actor_name]);
+				DI::config()->set('system', 'actor_name', $self['nick']);
+			} else {
+				DI::logger()->debug('Use system contact name as system actor', ['name' => $self['nick']]);
+			}
+			return $self['nick'];
+		}
+
+		if (isset($system_actor_name)) {
```
Comment (Raroun) [inline src/Model/User.php:284]: why `isset` and not `!empty`?

`DI::config()->get()` returns null when not set.

isset("") → true (returns empty string, invalid actor name)
!empty("") → false (falls back to ['friendica', 'actor', ...])

Using isset here breaks the fallback mechanism if the config is set to an empty string.
Or is this intended?

Comment (annando) [reply src/Model/User.php:284]: You can have a lengthy discussion with @nupplaphil concerning the usage of `empty()`. 😬

Comment (Raroun) [reply src/Model/User.php:284]: Better not ;-)
Besides that - it's looking good to me.

**Review by Raroun — APPROVED** [review]
