### PR TITLE
[frio] Add support for asynchronous call to /filerm module for post categories and folders

### LINKED ISSUE #11861: empty page when removing category from post
- [X] I have searched open and closed issues for duplicates

### Bug Description

When I click the small (x) on a category of a post, to remove the category from that post, I end up on an (almost) empty page. It looks as if a redirect back to the post is missing. Or maybe it is supposed to work with javascript. I'm not sure. (the clicked link was: `https://libranet.de/filerm/214024006?cat=quote` )

1.  edit post
2.  add category or multiple categories
3.  save and go back to the 'status' page
5.  remove category by clicking the small (x) 

Actual Result:

An empty page after clicking, only with menu at the top. I have to use the browser back button.
I used firefox. Here a screenshot:

friendica-remove-category

Expected Result:

to be redirected back to the post, (or the page where I was). or stay on the page and see just a disappearing category 

### Platform Info

"Diese Friendica-Instanz verwendet die Version 2022.09-dev, sie ist unter der folgenden Adresse im Web zu finden https://libranet.de. Die Datenbankversion ist 1481/1481 und die Post-Update-Version 1452/1452."

Theme: Frio V.0.8.5

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #11861

- This prevents the page to change to an empty page when clicking on the remove link of categories and folders

### CODE REVIEW

**Comment by AlfredSK** [comment]
The messages.po check is failing.

**Comment by MrPetovan** [comment]
messages.po file updated

File: src/Module/Filer/RemoveTag.php [hunk 1]
```diff
@@ -21,30 +21,68 @@
...
 	{
 		if (!local_user()) {
 			throw new HTTPException\ForbiddenException();
 		}
 
-		$logger = DI::logger();
+		$this->removeTag($request, $type, $term);
+
+		if ($type == Post\Category::FILE) {
+			DI::baseUrl()->redirect('filed?file=' . rawurlencode($term));
```
Comment (nupplaphil) [inline src/Module/Filer/RemoveTag.php]:
```suggestion
			$this->baseUrl->redirect('filed?file=' . rawurlencode($term));
```

File: src/Module/Filer/RemoveTag.php [hunk 2]
```diff
@@ -21,30 +21,68 @@
 
 namespace Friendica\Module\Filer;
 
+use Friendica\App;
 use Friendica\BaseModule;
+use Friendica\Core\L10n;
+use Friendica\Core\System;
 use Friendica\Database\DBA;
 use Friendica\DI;
```
Comment (nupplaphil) [inline src/Module/Filer/RemoveTag.php]: Can we delete this reference now?

File: src/Module/Filer/RemoveTag.php [hunk 3]
```diff
@@ -21,30 +21,68 @@
...
+
+		if ($type == Post\Category::FILE) {
+			DI::baseUrl()->redirect('filed?file=' . rawurlencode($term));
+		}
+
+		return '';
+	}
 
+	/**
+	 * @param array       $request The $_REQUEST array
```
Comment (nupplaphil) [inline src/Module/Filer/RemoveTag.php:72]: Plz add a short description, what/why are tags removed

File: src/Module/Filer/RemoveTag.php [hunk 4]
```diff
@@ -21,30 +21,68 @@
...
+	 * @param string|null $type    Output parameter with the computed type
+	 * @param string|null $term    Output parameter with the computed term
+	 * @return int The relevant HTTP code
```
Comment (nupplaphil) [inline src/Module/Filer/RemoveTag.php:76]:
```suggestion

	 * @return int The relevant HTTP code
```

File: src/Module/Filer/RemoveTag.php [hunk 5]
```diff
@@ -21,30 +21,68 @@
...
+	 * @throws \Exception
```
Comment (nupplaphil) [inline src/Module/Filer/RemoveTag.php:78]:
```suggestion

	 * @throws \Exception
```

File: src/Module/Filer/RemoveTag.php [hunk 6]
```diff
@@ -53,28 +91,27 @@ protected function content(array $request = []): string
...
-			$item = Post::selectFirst(['uri-id'], ['id' => $item_id]);
-			if (!DBA::isResult($item)) {
-				return '';
-			}
-			if (!Post\Category::deleteFileByURIId($item['uri-id'], local_user(), $type, $term)) {
-				notice(DI::l10n()->t('Item was not removed'));
-			}
-		} else {
-			notice(DI::l10n()->t('Item was not deleted'));
+		if (!$item_id || !strlen($term)) {
```
Comment (nupplaphil) [inline src/Module/Filer/RemoveTag.php:100]:
```suggestion
		if (empty($item_id) || !strlen($term)) {
```
Seems more safe, but it's up to you :-)

File: src/Module/Filer/RemoveTag.php [hunk 7]
```diff
@@ -53,28 +91,27 @@ protected function content(array $request = []): string
...
+			$this->systemMessages->addNotice($this->l10n->t('Item was not deleted'));
+			return 401;
 		}
 
-		if ($type == Post\Category::FILE) {
-			DI::baseUrl()->redirect('filed?file=' . rawurlencode($term));
+		$item = Post::selectFirst(['uri-id'], ['id' => $item_id]);
+		if (!DBA::isResult($item)) {
```
Comment (nupplaphil) [inline src/Module/Filer/RemoveTag.php:106]: Adding `Database $dba` instead at the constructor?

File: src/Module/Filer/RemoveTag.php [hunk 8]
```diff
@@ -53,28 +91,27 @@ protected function content(array $request = []): string
...
+			return 404;
 		}
 
-		return '';
+		if (!Post\Category::deleteFileByURIId($item['uri-id'], local_user(), $type, $term)) {
+			$this->systemMessages->addNotice($this->l10n->t('Item was not removed'));
+			return 500;
+		}
+
+		return 200;
```
Comment (nupplaphil) [inline src/Module/Filer/RemoveTag.php:115]: Are there equivalent constants for HTTP codes we could use?

**Review by nupplaphil — CHANGES_REQUESTED** [review]

File: src/Module/Filer/RemoveTag.php (hunk 8 above)
Comment (MrPetovan) [reply src/Module/Filer/RemoveTag.php:115]: Not that I know of 🤔

File: src/Module/Filer/RemoveTag.php (hunk 7 above)
Comment (MrPetovan) [reply src/Module/Filer/RemoveTag.php:106]: The `isResult` call is unwarranted here. In general this method should be deprecated because of its polysemy.

File: src/Module/Filer/RemoveTag.php (hunk 3 above)
Comment (MrPetovan) [reply src/Module/Filer/RemoveTag.php:72]: Unfortunately I cannot reliably answer this question.

File: src/Module/Filer/RemoveTag.php (hunk 6 above)
Comment (MrPetovan) [reply src/Module/Filer/RemoveTag.php:100]: `$item_id` is a variable set in the same function to the result of a null-coalescing operation, so we don't need the extra `isset()` that `empty()` provides.

**Comment by MrPetovan** [comment]
PR updated to the best of my ability, rebased on the RC branch.
