### PR TITLE
Fix #12262 - shared friendica posts are filtered on status page

### LINKED ISSUE #12262: Shared Posts from the same instance are not shown at /Profile/{nickname} or /profile/{nickname}/status (Home)
### Bug Description

Shared Posts from the same instance are not shown at /Profile/{nickname} or /profile/{nickname}/status (Home)

### Steps to Reproduce

1.  Share a post that was created by an someone else from the same instance 
2.  switch to your Status Site (Home)

Actual Result: Shared Post is not listed (but followers see the post in their timeline)

Expected Result: Should be visible - same effect if you browse to the /profile/nickname/status site of an other account.

### Platform Info

Friendica Version: Dev and stable 

Friendica Source: This repo

PHP version: 8.1

SQL version: Unknown

### PR DESCRIPTION
**Pull request by matthiasmoritz**
Native shares from the same Instance (or maybe all Friendica instances) were filtered out from the users home. With this commit they now appear on the users Profile/Status

### CODE REVIEW

**Comment by matthiasmoritz** [comment]
Not tested if this fixes also #11915

File: src/Module/Profile/Status.php [hunk 1]
```diff
@@ -174,8 +174,8 @@ protected function content(array $request = []): string
 
 		$condition = DBA::mergeConditions($condition, ["((`gravity` = ? AND `wall`) OR
 			(`gravity` = ? AND `vid` = ? AND `origin`
-			AND `thr-parent-id` IN (SELECT `uri-id` FROM `post` WHERE `gravity` = ? AND `network` = ?)))",
-			Item::GRAVITY_PARENT, Item::GRAVITY_ACTIVITY, Verb::getID(Activity::ANNOUNCE), Item::GRAVITY_PARENT, Protocol::ACTIVITYPUB]);
+			AND `thr-parent-id` IN (SELECT `uri-id` FROM `post` WHERE `gravity` = ? )))",
+			Item::GRAVITY_PARENT, Item::GRAVITY_ACTIVITY, Verb::getID(Activity::ANNOUNCE), Item::GRAVITY_PARENT]);
```
Comment (annando) [inline src/Module/Profile/Status.php]: Instead of removing AP, please add `Protocol::DFRN` to the list of networks.

**Review by annando — CHANGES_REQUESTED** [review]

**Review by annando — APPROVED** [review]

**Review by MrPetovan — COMMENTED** [review]
Thank you for your work!
