### PR TITLE
Issue 9231: Speed up full text search

### LINKED ISSUE #9231: cannot search word without hashtag
### Expected behavior
It should be possible to search a word that was mentioned by other people without using a hashtag, like on Twitter.

### Actual behavior
It is not possible to search a word if the message is not using a hashtag for the word.

### Steps to reproduce the problem
Create a message with the word Friendica without hashtag on a public server like https://social.isurf.ca/ (direct link to message: https://social.isurf.ca/display/c443a55c-105f-64cb-a7ec-96a959460101).
Try to search the word Friendica (direct link to search results: https://social.isurf.ca/search?q=friendica).

### Friendica version you encountered the problem
2020.09-rc

### Friendica source (git, zip)
https://social.isurf.ca/

### PHP version
N/A

### SQL version
N/A

### PR DESCRIPTION
**Pull request by annando**
Fixes https://github.com/friendica/friendica/issues/9231

The search is now using a fulltext index, which should work on most systems. The search is in the binary mode, so that you can several patterns, see: https://dev.mysql.com/doc/refman/5.6/en/fulltext-boolean.html

### CODE REVIEW

File: database.sql [hunk 1]
```diff
@@ -786,6 +786,7 @@ CREATE TABLE IF NOT EXISTS `item-content` (
 	`verb` varchar(100) NOT NULL DEFAULT '' COMMENT 'ActivityStreams verb',
 	 PRIMARY KEY(`id`),
 	 UNIQUE INDEX `uri-plink-hash` (`uri-plink-hash`),
+	 FULLTEXT INDEX `body` (`body`),
```
Comment (MrPetovan) [inline database.sql]: I believe this index needs needs to cover `title`, `content-warning`, `location` and `app` as well as they all are displayed and may be expected to show up in a search.

File: src/Module/Search/Index.php [hunk 2]
```diff
@@ -151,30 +152,18 @@ public static function content(array $parameters = [])
...
-				$params = ['order' => ['id' => true], 'group_by' => ['uri-id']];
-				$items = Item::selectForUser(local_user(), [], ['uri-id' => $uriids], $params);
-				$r = Item::inArray($items);
-				$count = Tag::countByTag($search, local_user());
-			} else {
-				$count = 0;
-			}
 		} else {
 			Logger::info('Start fulltext search.', ['q' => $search]);
+			$uriids = ItemContent::getURIIdListBySearch($search, local_user(), $pager->getStart(), $pager->getItemsPerPage());
```
Comment (MrPetovan) [inline src/Module/Search/Index.php:158]: You need a total count for this case as well.

File: src/Module/Search/Index.php [hunk 3]
```diff
@@ -151,30 +152,18 @@ public static function content(array $parameters = [])
...
-				'order' => ['id' => true],
-				'limit' => [$pager->getStart(), $pager->getItemsPerPage()]
-			];
-			$items = Item::selectForUser(local_user(), [], $condition, $params);
+		if (!empty($uriids)) {
+			$params = ['order' => ['id' => true], 'group_by' => ['uri-id']];
+			$items = Item::selectForUser(local_user(), [], ['uri-id' => $uriids], $params);
 			$r = Item::inArray($items);
-			$count = DBA::count('item', $condition);
+			$count = Tag::countByTag($search, local_user());
```
Comment (MrPetovan) [inline src/Module/Search/Index.php]: This needs to be moved in the `if ($tag)` condition above.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

**Comment by MrPetovan** [comment]
Additionally, if this provides satisfactory performances, we should remove the full text disable setting.

File: database.sql (hunk 1 above)
Comment (annando) [reply database.sql]: I don't think that `location` and `app` should be used for the search. But `title` and `content-warning` sounds okay.

**Comment by annando** [comment]
Concerning the performance we should decide this in the next release.

File: src/Module/Search/Index.php (hunk 2 above)
Comment (annando) [reply src/Module/Search/Index.php:158]: Done

File: src/Module/Search/Index.php (hunk 3 above)
Comment (annando) [reply src/Module/Search/Index.php]: Done

File: database.sql (hunk 1 above)
Comment (MrPetovan) [reply database.sql]: Why not? They are user-controlled public fields. What if someone wants to retrieve all posts submitted through Tusky? What if someone wants to retrieve all posts reportedly submitted from Germany?

File: src/Module/Search/Index.php [hunk 4]
```diff
@@ -151,30 +152,19 @@ public static function content(array $parameters = [])
...
-				'limit' => [$pager->getStart(), $pager->getItemsPerPage()]
-			];
-			$items = Item::selectForUser(local_user(), [], $condition, $params);
+		if (!empty($uriids)) {
+			$params = ['order' => ['id' => true], 'group_by' => ['uri-id']];
+			$items = Item::selectForUser(local_user(), [], ['uri-id' => $uriids], $params);
 			$r = Item::inArray($items);
-			$count = DBA::count('item', $condition);
+		} else {
+			$count = 0;
```
Comment (MrPetovan) [inline src/Module/Search/Index.php]: This is now superfluous, we need a total count even if the current page doesn't show anything to show the Back button at least.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Module/Search/Index.php (hunk 4 above)
Comment (annando) [reply src/Module/Search/Index.php]: Done

File: database.sql (hunk 1 above)
Comment (annando) [reply database.sql]: It will also lead to (i guess massive) false positives. When you - for example - are searching for content about "android" - but you also get all posts that had been posted via some app that announces itself as "... for android" - or you search for something that happened in hamburg - but you get all posts that had been posted from hamburg as well.

Comment (MrPetovan) [reply database.sql]: Fair enough. This file still needs to be updated with the expanded index.

Comment (annando) [reply database.sql]: Done

**Review by MrPetovan — APPROVED** [review]
