### PR TITLE
Item post functionality is removed from photos

### LINKED ISSUE #12536: The checkbox at the photo upload ..
### Bug Description

I have unchecked the checkbox at the photo upload "don't create a post for this upload" and then I have uploaded a photo.

It seemed as if no post was created. Friendica doesn't show one. 
But then I saw in my diaspora account : There was a post. 

So either it would be nice to remove that checkbox, or, make it work, so that friendica shows me that post, too.

### Screenshots

here the checkbox, that I mean:

checkbox

and the post, that I found on diaspora:

checkbox-the-post

### Platform Info

Friendica Version:

Diese Friendica-Instanz verwendet die Version 2023.03-dev, sie ist unter der folgenden Adresse im Web zu finden https://amical.info. Die Datenbankversion ist 1504/1504 und die Post-Update-Version 1484/1484.

Theme: Frio

PHP version: PHP 8.1.13

SQL version: mysql  Ver 15.1 Distrib 10.6.11-MariaDB, for Linux (x86_64) using readline 5.1

### LINKED ISSUE #15301: No way to delete photo comments
- [X] I have searched open and closed issues for duplicates

### Bug Description

I wanted to add an alt-Text to a photo, but accidentally wrote a comment to that picture.
Now I can't find a possibility, to delete that comment. See the screenshot.
The avatar picture seems to be broken, too.

### Screenshots

Image

### Platform Info

Friendica Version:  2025.07-rc 
Db-version: 1584/1584 
Post-Update-Version: 1550/1550.

Friendica Source: GitHub

PHP version: 8.4.7

SQL version: mariadb from 11.1.2-MariaDB, client 15.2 for Linux (x86_64) using readline 5.1

### LINKED ISSUE #15516: Remove "Do not show a status post for this upload" functionality from photo upload
As talked about on #15513

The feature does not appear to work, and if people want to create a post from an image they can create a post and add the image instead, thereby also having the ability to add text, more images, preview it etc.

### PR DESCRIPTION
**Pull request by annando**
Fixes #15516
Fixes #12536
Fixes #15301

### CODE REVIEW

**Comment by marcusxss** [comment]
Thanks for removing that checkbox and doing a cleanup! :D

So it also removes reacts (likes/dislikes), comments and tags on photos?
This leaves the image with caption/alt text + album + rotation as the things one can do on one's own photos?
You can still see the photos someone else has(?), but not interact with them directly.

That's different from e.g. Facebook where you can like/comment on someone's photos - but maybe that's okay. Or would it be missed? I guess right now it's not working that well anyway, so maybe not, at least by existing users.
On the other hand I think maybe this functionality is similar to Mastodon and Twitter, if I remember correctly.

I wonder if that makes the ability to see someone else's photos under /profile slightly unnecessary/unexpected? Instead maybe the existing "Media" page makes more sense, as that's something Mastodon has. Not saying Photos on other's profiles should just be removed like that (!), just wondering.

**Comment by annando** [comment]
I suspect that most users didn't knew about this functionality at all. It was from a time where we only interacted with other people using DFRN. People from other systems never had been able to comment, like or dislike on these pictures at all.

File: mod/photos.php [hunk 1]
```diff
@@ -76,20 +67,14 @@ function photos_init()
...
-
 		if ($ret['success']) {
 			$photo_albums_widget = Renderer::replaceMacros(Renderer::getMarkupTemplate('photo_albums.tpl'), [
 				'$nick'     => $owner['nickname'],
 				'$title'    => DI::l10n()->t('Photo Albums'),
 				'$recent'   => DI::l10n()->t('Recent Photos'),
 				'$albums'   => $ret['albums'],
 				'$upload'   => [DI::l10n()->t('Upload photo'), 'photos/' . $owner['nickname'] . '/upload'],
-				'$can_post' => $can_post
+				'$can_post' => (DI::userSession()->getLocalUserId() && $owner['uid'] == DI::userSession()->getLocalUserId())
```
Comment (nupplaphil) [inline mod/photos.php]:
```suggestion
				'$can_post' => (DI::userSession()->getLocalUserId() && $owner['uid'] === DI::userSession()->getLocalUserId())
```

**Review by nupplaphil — CHANGES_REQUESTED** [review]
just a tiny thing :)

**Comment by annando** [comment]
@nupplaphil done
