### PR TITLE
Remove contact drop feature

### LINKED ISSUE #10729: Trouble when trying to drop contact
### Bug Description

Error messages, faulty UI and action never proceeding when trying to drop contact.

### Steps to Reproduce

1.  Open contacts list
2.  Tick checkbox in bottom right of contact in the list
3.  Click `Drop Contact` icon

Actual Result:

Error message shows multiple times: "The form security token was not correct. This probably happened because the form has been opened for too long (>3 hours) before submitting it."

Friendica UI shows second friendica overlay over existing UI.

Expected Result:

Contact should be dropped.

### Screenshots
error
double UI

### Platform Info

Friendica Version:

This is Friendica, version 2021.09-rc that is running at the web location https://pirati.ca. The database version is 1435/1435, the post update version is 1427/1427.

### PR DESCRIPTION
**Pull request by MrPetovan**
Redux of #10751 (for conversation)
Closes #10729 
Depends on #10796

Additionally, this PR adds contact relationship termination to block action to be more consistent with other social media platforms.

### CODE REVIEW

File: src/Module/Contact.php [hunk 1]
```diff
@@ -206,15 +201,26 @@ private static function updateContactFromProbe(int $contact_id)
...
+	private static function toggleBlockContact(array $cdata, int $owner_id)
 	{
-		$blocked = !Model\Contact\User::isBlocked($contact_id, local_user());
-		Model\Contact\User::setBlocked($contact_id, local_user(), $blocked);
+		$newBlockedState = !Model\Contact\User::isBlocked($cdata['public'], local_user());
+		if ($newBlockedState && $cdata['user']) {
+			$contact = Model\Contact::getContactForUser($cdata['user'], $owner_id);
+			$owner = Model\User::getOwnerDataById($owner_id);
+			if (DBA::isResult($contact) && DBA::isResult($owner)) {
+				Model\Contact::terminateFriendship($owner, $contact, true);
```
Comment (annando) [inline src/Module/Contact.php]: Terminating the connection when blocking someone is a problem since the connection isn't restored when the connection is unblocked.

**Review by annando — CHANGES_REQUESTED** [review]
Before accepting this PR we have to ensure that:
- Unfollowing of feed and mail contacts does delete the contact (It doesn't at the moment)
- We can revoke a remote subscription. Revoking it inside the blocking has got issues (see my comment there)

File: src/Module/Contact.php (hunk 1 above)
Comment (MrPetovan) [reply src/Module/Contact.php]: This is the standard behavior on both Facebook and Twitter, I don't see a need to restore the connection on unblocking. The Friendica user will be able to follow them again on their own, which is the important part we have control over.

Comment (annando) [reply src/Module/Contact.php]: What happens when you accidentally block someone? You won't realize that you unfollowed that contact. You will revert the block and think that everything went well. And even some message won't help because people don't read messages.

**Comment by MrPetovan** [comment]
> - Unfollowing of feed and mail contacts does delete the contact (It doesn't at the moment)

I can make this happen, but as for:

> - We can revoke a remote subscription. Revoking it inside the blocking has got issues (see my comment there)

I don't think it is a blocker. It isn't an expected feature as far as I know. We can expose the technical feature for users but it doesn't exist on any platform I know and it's never been requested either, so expectations are low.

Same for your blocking idea, nobody expects broken relationships through a block to be restored as is once the block is lifted. For me, this means we should go forward with this PR that removes a confusing feature to match users' expectations coming from several other platforms.

**Comment by annando** [comment]
When I block someone and then unblock that person then my expectation is that things are back to normal.

And considering this subscription revocation: It is no big deal adding it in this same PR. And a reason why other networks normally don't have this feature is that most networks don't have the feature to allow or reject following requests.

File: src/Module/Contact.php (hunk 1 above)
Comment (MrPetovan) [reply src/Module/Contact.php]: I'm guessing that "blocking" has a very cold, technical meaning for you that it usually doesn't carry for most other people. Blocking is the nuclear option, it's the be-all and end-all of online relationship breakup, and as such it is expected to leave no trace of any former relationship. On Twitter for example, it is known as the only way to revoke a follow or to be forcibly removed from a contact list created by someone else.

When it is done by mistake, it is a big deal and people will realize that they aren't following that contact, if only because we will say as much on the contact page.

**Comment by MrPetovan** [comment]
> When I block someone and then unblock that person then my expectation is that things are back to normal.

This is a very technical approach to social media networks that cannot be expected from most users and as such I don't believe we should apply it to all Friendica users.

**Comment by annando** [comment]
Well, I think that the assumption that unblocking reverts the blocking is very nontechnical.

File: src/Module/Contact.php (hunk 1 above)
Comment (annando) [reply src/Module/Contact.php]: I don't think that people will always know if the other side followed you as well. And even then when you wanted to revert the blocking you had not only to follow that person again but had to write the other person to follow you again because you accidentally blocked that person.

I think that the user should decide on their own whether to block, unfollow, or revert the subscription of a contact.

I guess we should ask the users about this.

**Comment by MrPetovan** [comment]
Then we should run an informal poll to help figure this out.

**Comment by MrPetovan** [comment]
Here's the public poll: https://friendica.mrpetovan.com/display/735a2029-1161-50ef-061b-d92218224348
