### PR TITLE
Fix "EMPTY" label in profile

### LINKED ISSUE #6630: Relationship status and gender fields show on profile when empty
### Expected behavior
When relationship status and gender are not filled in, it should show nothing on your profile page.

### Actual behavior
On the profile page the relationship and gender icons are showed, followed by the word EMPTY

### Steps to reproduce the problem
Go to Settings > Profiles
Enable "Show more profile fields"
Click Submit
Expand Relation section
Click Submit in Relation section, without filling any field.
(Gender icon appears on profile followed by the word EMPTY)
Click Submit in Relation section again, without filling any field.
(Relationship icon appears on profile followed by the word EMPTY)

### Friendica version you encountered the problem
Friendica version 2019.03-dev
Database version 1302
Post update version 1297.

### PHP version
PHP 7.2.10

### SQL version
MariaDB 10.1.38

[Edit 1] : See this profile as an example: https://libranet.de/profile/testnerd/?tab=profile
It seems that Sexual Preference field is also affected (in the Advanced tab)
[Edit 2]: Typo: Expend -> Expand
[Edit 3]: Updated with PHP/SQL versions used on libranet.de

### PR DESCRIPTION
**Pull request by MrPetovan**
Follow-up to #5751
Fixes #6630

Additionally, this PR hides the "never" string for marital status age.

### CODE REVIEW

File: mod/profiles.php [hunk 1]
```diff
@@ -535,18 +535,18 @@ function profiles_content(App $a) {
 		$personal_account = !(in_array($a->user["page-flags"],
 					[User::PAGE_FLAGS_COMMUNITY, User::PAGE_FLAGS_PRVGROUP]));
 
-		$detailled_profile = (PConfig::get(local_user(), 'system', 'detailled_profile') AND $personal_account);
+		$detailed_profile = (PConfig::get(local_user(), 'system', 'detailled_profile') AND $personal_account);
```
Comment (AlfredSK) [inline mod/profiles.php]: There is another detai**ll**ed_profile.

Comment (MrPetovan) [reply mod/profiles.php]: Yes but it would reset all existing user settings to the default value, and I didn't want to write a post update script.

Comment (AlfredSK) [reply mod/profiles.php]: Ah! I understand.
