### PR TITLE
Fix wrong default value in Module\Api\Friendica\Photo\Create::post

### LINKED ISSUE #11163: api/friendica/photo/create fails to upload images
- [ x ] I have searched open and closed issues for duplicates

### Bug Description
After very recent updates (two weeks ago max) this API endpoint no longer works throwing code 500.

### Steps to Reproduce

1.  use `api/friendica/photo/create` to upload an image.

E.g. the following Python code used to work:

```
myfile = {"media": ("filename", open('/tmp/tmpimg', "rb"))}
r = requests.post('https://friends.deko.cloud/api/friendica/photo/create', files=myfile, data={'album':'Temp'}, auth=HTTPBasicAuth(usr, pss))
```

Actual Result:

The API returns code 500 and the following response:

`b''`

Expected Result:

JSON with the details of newly uploaded image.

### Platform Info

Friendica Version:

Current RC (2022.01.17, git)

### PR DESCRIPTION
**Pull request by MrPetovan**
Fix #11163 

- The underlying Model\Photo::upload doesn't accept a null value for description

### CODE REVIEW

File: src/Module/Api/Friendica/Photo/Create.php [hunk 1]
```diff
@@ -55,7 +55,7 @@ protected function post(array $request = [])
 		$type = $this->getRequestValue($this->parameters, 'extension', 'json');
 
 		// input params
-		$desc      = $this->getRequestValue($request, 'desc');
+		$desc      = $this->getRequestValue($request, 'desc') ?? '';
```
Comment (annando) [inline src/Module/Api/Friendica/Photo/Create.php:58]: The function does handle default values, so it should look this way:
 `$desc = $this->getRequestValue($request, 'desc','');`

Comment (MrPetovan) [reply src/Module/Api/Friendica/Photo/Create.php:58]: Ah, right, I forgot about that.
