### PR TITLE
Config Set Bugfix

### LINKED ISSUE #6711: Matomo / Piwik add-on doesn't allow setting change
### Expected behavior

In the Matomo / Piwik adminitrative settings, the "Show opt-out cookie link? " should allow you to turn it on or off.

### Actual behavior

The setting resets to checked/On after unchecking it and saving the setting.

### Steps to reproduce the problem

Go to /admin/addons/piwik.  Uncheck the "Show opt-out cookie link?" setting and click "Save Settings"

### Friendica version you encountered the problem

2019.03-rc - 1302

### Friendica source (git, zip)

git

### PHP version

7.3.1

### SQL version

mariadb 10.3.12

### LINKED ISSUE #6716: 2019-3-RC Settings in the admin are not taken over, text disappears.
It has just struck me that in the admin area under page -> registration the welcome text has disappeared and changed settings are no longer adopted.

### Friendica source (git, zip)
git
### PHP version
7.2
### SQL version
5.5.5 Meria

### PR DESCRIPTION
**Pull request by nupplaphil**
FollowUp #6641 

- Reverted manual `$basepath` loading into the cache
- Added `$basePath` again at `App` initialization
-> A cleaner solution would be as suggested at #6720 

- Refactored `!<unset>!` usage to real null-returns (now we can use `isset()` again ..)

- Fixed #6716 - register text doesn't disappear anymore
- Fixed #6711 - boolean flags are now working again

Tested each bug with config_adapter preload and jit on my node
Tested some other (personal) settings f.e. other themes

### CODE REVIEW

File: src/App.php [hunk 1]
```diff
@@ -205,21 +205,23 @@ public function registerFooterScript($path)
...
+	public function __construct($basePath, Configuration $config, LoggerInterface $logger, Profiler $profiler, $isBackend = true)
 	{
 		BaseObject::setApp($this);
 
 		$this->logger   = $logger;
 		$this->config   = $config;
 		$this->profiler = $profiler;
-		$this->basePath = $this->config->get('system', 'basepath');
+		$cfgBasePath = $this->config->get('system', 'basepath');
+		$this->basePath = (isset($cfgBasePath) && $cfgBasePath !== '') ? $cfgBasePath : $basePath;
```
Comment (MrPetovan) [inline src/App.php]: You can simplify the condition here:
```suggestion
		$this->basePath = !empty($cfgBasePath) ? $cfgBasePath : $basePath;
```

File: src/Core/Config.php [hunk 2]
```diff
@@ -48,6 +48,8 @@ public static function load($cat = "config")
 	 * @brief Get a particular user's config variable given the category name
 	 * ($family) and a key.
 	 *
+	 * Note: Please do not store booleans - convert to 0/1 integer values!
```
Comment (MrPetovan) [inline src/Core/Config.php]: Why did you move this comment from set to get ?

File: src/Core/Config/Adapter/IConfigAdapter.php [hunk 3]
```diff
@@ -21,10 +21,12 @@ public function load($cat = "config");
 	 * Get a particular system-wide config variable given the category name
 	 * ($family) and a key.
 	 *
+	 * Note: Boolean variables are defined as 0/1 in the database
+	 *
 	 * @param string  $cat The category of the configuration value
 	 * @param string  $key The configuration key to query
 	 *
-	 * @return mixed Stored value or "!<unset>!" if it does not exist
+	 * @return null|mixed Stored value or null if it does not exist
```
Comment (MrPetovan) [inline src/Core/Config/Adapter/IConfigAdapter.php]: I'm curious: Isn't `null` included in `mixed`?

Comment (nupplaphil) [reply src/Core/Config/Adapter/IConfigAdapter.php]: I thought it would be helpful to explicit mention that the return could be nullable.

Comment (MrPetovan) [reply src/Core/Config/Adapter/IConfigAdapter.php]: Fair enough.

**Comment by nupplaphil** [comment]
Possibly fixes #6712 too .. It really sounds like..

**Comment by annando** [comment]
I'm now getting this:
```
$ Fatal error: Uncaught TypeError: Argument 2 passed to Friendica\Database\DBA::connect() must implement interface Friendica\Core\Config\Cache\IConfigCache, instance of Friendica\Util\Profiler given, called in /path/to/friendica/src/Database/DBA.php on line 172 and defined in /path/to/friendica/src/Database/DBA.php:62
Stack trace:
#0 /path/to/friendica/src/Database/DBA.php(172): Friendica\Database\DBA::connect(Object(Friendica\Core\Config\Cache\ConfigCache), Object(Friendica\Util\Profiler), '...', '...', '...', '...', '...')
#1 /path/to/friendica/bin/daemon.php(174): Friendica\Database\DBA::reconnect()
#2 {main}
  thrown in /path/to/friendica/src/Database/DBA.php on line 62
```
