### PR TITLE
Issue 12367: Calculate relative date on "date" level instead of "datetime"

### LINKED ISSUE #12367: Wrong time for last login
### Bug Description

Not important:
I created some test user and logged in after I created it, then I logged out, used the reset password function. 

Then now in /moderation I see in the list of users this:
image

This is wrong, it was within the last hour I logged in, maybe it is minutes instead of hours, but not sure. 

User list: /moderation/users/active?o=-register_date

### Platform Info

Friendica Version:

Friendica Source: git

PHP version: 8.1.13

SQL version: mariadb  Ver 15.1 Distrib 10.9.4-MariaDB

### PR DESCRIPTION
**Pull request by annando**
Fixes #12367

### CODE REVIEW

File: src/Util/Temporal.php [hunk 1]
```diff
@@ -305,13 +305,14 @@ public static function getDateTimeField(
...
-	 * @param string $format (optional) Parsed with sprintf()
+	 * @param string $posted_date       MySQL-formatted date string (YYYY-MM-DD HH:MM:SS)
+	 * @param string $format            (optional) Parsed with sprintf()
+	 * @param bool   $compare_date_time Compare date (false) or datetime (true). "true" is default.
 	 *    <tt>%1$d %2$s ago</tt>, e.g. 22 hours ago, 1 minute ago
 	 *
 	 * @return string with relative date
 	 */
-	public static function getRelativeDate(string $posted_date = null, string $format = null): string
+	public static function getRelativeDate(string $posted_date = null, string $format = null, bool $compare_date_time = true): string
```
Comment (MrPetovan) [inline src/Util/Temporal.php]: Please simplify the parameter name.
```suggestion
	public static function getRelativeDate(string $posted_date = null, string $format = null, bool $compare_time = true): string
```

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Util/Temporal.php (hunk 1 above)
Comment (annando) [reply src/Util/Temporal.php]: done

**Review by MrPetovan — APPROVED** [review]
