### PR TITLE
(Hopefully) query performance improvements

### LINKED ISSUE #11828: RemoveUnusedAvatars query fix
- [x] I have searched open and closed issues for duplicates

### Bug Description

The RemoveUnusedAvatars performance has been shown to be thrashing databases. I've been experimenting with the query and think that removing the nulls from the `cause-id` inner-select dramatically improves performance

### Steps to Reproduce

I ran the query manually in mysql CLI with incremental elements of the query to see where the delay was being created. It was only when the `causer-id` inner select clause existed. I noticed the only difference between it and the other types was that it was nullable. I therefore tweaked the query to be:

```sql
SELECT COUNT(*) AS `total` FROM `contact` 
INNER JOIN `photo` ON `contact`.`id` = `contact-id` 
WHERE `contact`.`uid` = 0 AND NOT `self`
 AND (`photo` != '' OR `thumb` != '' OR `micro` != '') AND NOT `nurl` IN (
 SELECT `nurl` FROM `contact` WHERE `uid` != 0) 
 AND NOT `contact`.`id` IN (SELECT `author-id` FROM `post-user`)
 AND NOT `contact`.`id` IN (SELECT `owner-id` FROM `post-user`) 
 AND NOT `contact`.`id` IN (SELECT `causer-id` FROM `post-user` WHERE `causer-id` IS NOT NULL)
 AND NOT `contact`.`id` IN (SELECT `cid` FROM `post-tag`)
 AND NOT `contact`.`id` IN (SELECT `contact-id` FROM `post-user`);
```

...adding the WHERE IS NOT NULL element. The query on my machine with a stalled original query still going 800 seconds and not completed this completed in about 1 second.

I suggest changing the sub-select query on this line to have the NON NULL where clause in https://github.com/friendica/friendica/blob/05a76a3dc2fd313e660752a7eb139ec2fb3a6667/src/Worker/RemoveUnusedAvatars.php#L37-L44

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2022.06 - 1469

PHP version: PHP 7.4.29

SQL version: mariadb  Ver 15.1 Distrib 10.3.34-MariaDB

### PR DESCRIPTION
**Pull request by annando**
Fixes #11828 

It seems as if these "NOT id IN (SELECT id FROM table)" queries can drain the performance. This is now hopefully improved.

### CODE REVIEW

File: src/Protocol/Diaspora.php [hunk 1]
```diff
@@ -54,7 +54,8 @@
 use SimpleXMLElement;
 
 /**
- * This class contain functions to create and send Diaspora XML files
+ * This class contain functions to communicate via the Diaspora protocol
```
Comment (MrPetovan) [inline src/Protocol/Diaspora.php]: Typo
```suggestion
 * This class contains functions to communicate via the Diaspora protocol
```

**Review by MrPetovan — CHANGES_REQUESTED** [review]

**Review by MrPetovan — APPROVED** [review]
