### PR TITLE
Issue 14692: Prevent loops with remote servers

### LINKED ISSUE #14692: ActivityPub server being slammed by friendica instances
- [x] I have searched open and closed issues for duplicates

### Bug Description

Starting with a couple of weeks ago random identica servers have started slamming my instance that runs a custom ActivityPub service.

### Steps to Reproduce

I have no idea what is triggering this.

#### Actual Result:

A lot of requests coming from the friendica instance (in this case it's pirati.ca) and some of them signed with invalid HTTP Signatures.

See the [pirati-ca.log](https://github.com/user-attachments/files/18399832/pirati-ca.log) for one second worth of requests.
 
Based on the logs it looks like there's a feedback loop taking place where my instance tries to fetch the public key for each request received and it fails.

If it's not obvious from the logs the instance that's being accessed is: `https://releases.bruta.link` (and it's collections)

I'll open a separate ticket for the software that runs on my server to add a back-off on the key loading, because I feel like that compounds the problem for everybody.

#### Expected Result:

Not as many requests. 

### Platform Info

Friendica Version:

The User-Agent has these version identifiers: **Friendica/2024.12** **DatabaseVersion/1576** **Request/ServerInfo/1**

### PR DESCRIPTION
**Pull request by annando**
Preparation to fix #14692

### CODE REVIEW

**Comment by annando** [comment]
Pipeline fails because PR https://git.friendi.ca/friendica/friendica-addons/pulls/1590 is not merged yet.

File: src/Util/HTTPSignature.php [hunk 1]
```diff
@@ -604,13 +604,14 @@ public static function getKeyIdContact(array $http_headers): array
 	/**
 	 * Gets a signer from a given HTTP request
 	 *
-	 * @param string $content
-	 * @param array $http_headers
+	 * @param string   $content
+	 * @param array    $http_headers
```
Comment (Art4) [inline src/Util/HTTPSignature.php]: We should remove phpdocs that add no value.

File: src/Util/HTTPSignature.php [hunk 2]
```diff
@@ -604,13 +604,14 @@ public static function getKeyIdContact(array $http_headers): array
...
+	 * @param ?boolean $update true = always update, false = never update, null = update when not found or outdated
 	 *
 	 * @return string|null|false Signer
 	 * @throws \Friendica\Network\HTTPException\InternalServerErrorException
 	 */
-	public static function getSigner(string $content, array $http_headers)
+	public static function getSigner(string $content, array $http_headers, bool $update = null)
```
Comment (Art4) [inline src/Util/HTTPSignature.php]: Nullable types without `?` will start throwing deprecation warnings in PHP 8.4.

```suggestion
	public static function getSigner(string $content, array $http_headers, ?bool $update = null)
```

File: src/Util/HTTPSignature.php [hunk 3]
```diff
@@ -802,17 +803,18 @@ public static function getSigner(string $content, array $http_headers)
...
-	 * @param string $actor
+	 * @param string   $id
+	 * @param string   $actor
+	 * @param ?boolean $update true = always update, false = never update, null = update when not found or outdated
 	 *
 	 * @return array with actor url and public key
 	 * @throws \Exception
 	 */
-	private static function fetchKey(string $id, string $actor): array
+	private static function fetchKey(string $id, string $actor, bool $update = null): array
```
Comment (Art4) [inline src/Util/HTTPSignature.php]:
```suggestion
	private static function fetchKey(string $id, string $actor, ?bool $update = null): array
```

File: src/Util/HTTPSignature.php [hunk 4]
```diff
@@ -802,17 +803,18 @@ public static function getSigner(string $content, array $http_headers)
 	/**
 	 * fetches a key for a given id and actor
 	 *
-	 * @param string $id
-	 * @param string $actor
+	 * @param string   $id
+	 * @param string   $actor
```
Comment (Art4) [inline src/Util/HTTPSignature.php]: This two phpdocs can be removed.

**Review by Art4 — CHANGES_REQUESTED** [review]

File: src/Util/HTTPSignature.php (hunk 1 above)
Comment (annando) [reply src/Util/HTTPSignature.php]: Documentation added

File: src/Util/HTTPSignature.php (hunk 2 above)
Comment (annando) [reply src/Util/HTTPSignature.php]: Changed

File: src/Util/HTTPSignature.php (hunk 3 above)
Comment (annando) [reply src/Util/HTTPSignature.php]: Changed

File: src/Util/HTTPSignature.php (hunk 4 above)
Comment (annando) [reply src/Util/HTTPSignature.php]: Documentation added

**Review by MrPetovan — APPROVED** [review]

**Comment by melroy89** [comment]
Thank you 🙏
