### PR TITLE
Fix notices in OEmbed et al.

### LINKED ISSUE #5443: PHP errors caused by the worker
### Expected behavior
no errors
### Actual behavior
PHP Notice:  getimagesizefromstring(): Read error! in /home/users/zsemberi/www/friendica/src/Object/Image.php on line 789
PHP Notice:  Undefined property: stdClass::$html in /home/users/zsemberi/www/friendica/src/Content/OEmbed.php on line 170
PHP Notice:  Undefined property: stdClass::$type in /home/users/zsemberi/www/friendica/src/Content/OEmbed.php on line 171
PHP Notice:  Undefined property: stdClass::$type in /home/users/zsemberi/www/friendica/src/Content/OEmbed.php on line 173
PHP Notice:  Undefined property: stdClass::$type in /home/users/zsemberi/www/friendica/src/Content/OEmbed.php on line 207
PHP Notice:  Undefined index: body in /home/users/zsemberi/www/friendica/src/Model/Item.php on line 2231
PHP Notice:  Only variables should be passed by reference in /home/users/zsemberi/www/friendica/src/Protocol/PortableContact.php on line 1685
### Steps to reproduce the problem
Log of Cronjob
### Friendica version you encountered the problem
Friendica 'The Tazmans Flax-lily' 2018.08-dev - 1279
### Friendica source (git, zip)
git
### PHP version
7.2
### SQL version
Maria

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #5443

### CODE REVIEW

File: src/Content/OEmbed.php [hunk 1]
```diff
@@ -49,132 +48,128 @@ public static function replaceCallback($matches)
...
 
-		Addon::callHooks('oembed_fetch_url', $embedurl, $j);
+		Addon::callHooks('oembed_fetch_url', $embedurl, $oembed);
 
-		return $j;
+		return $oembed;
 	}
 
-	private static function formatObject(stdClass $j)
+	private static function formatObject(\Friendica\Object\OEmbed $oembed)
```
Comment (Quix0r) [inline src/Content/OEmbed.php]: Please put a `use Friendica\Object\OEmbed` in head of this file.

File: src/Model/Item.php [hunk 2]
```diff
@@ -2228,6 +2228,9 @@ public static function addShadowPost($itemid)
 	 */
 	private static function addLanguageToItemArray(&$item)
 	{
+		// @TODO Find out why body can be empty here
```
Comment (Quix0r) [inline src/Model/Item.php]: To find this out, an exception can be thrown when `$item['body']` is empty.

File: src/Content/OEmbed.php (hunk 1 above)
Comment (MrPetovan) [reply src/Content/OEmbed.php]: It conflicts with the class name it's used in.

Best I can do is either 
```php
use Friendica\Object;

function formatObject(Object\OEmbed $oembed) {
...
}
```
or
```php
use Friendica\Object\OEmbed as OEmbedObject;

function formatObject(OEmbedObject $oembed) {
...
}
```

File: src/Model/Item.php (hunk 2 above)
Comment (MrPetovan) [reply src/Model/Item.php]: Good idea, however I won't add an Exception in the develop branch. It should be used for debugging only.

Comment (Quix0r) [reply src/Model/Item.php]: For debugging only, exceptions are never the choice. They are like hard errors, like a missing file but it was expected. Then `assert(isset($item['body']));` is here maybe the right choice. Still, if `body` is absent, an `E_NOTICE` is later triggered. Or use `array_key_exists()`.

Can you please add `array` as type-hint here? Also can you please add `@param` documentation?

File: src/Content/OEmbed.php (hunk 1 above)
Comment (Quix0r) [reply src/Content/OEmbed.php]: Then `OEmbed` is maybe not the right choice after all due to class name (without namespace) conflict. Maybe rename the name class to `OEmbedObject` then?

**Comment by Quix0r** [comment]
Conflicts found. :-)

**Comment by MrPetovan** [comment]
Fixed conflicts.

File: src/Content/OEmbed.php [hunk 3]
```diff
@@ -48,132 +47,128 @@ public static function replaceCallback($matches)
...
-
-		$noexts = ["mp3", "mp4", "ogg", "ogv", "oga", "ogm", "webm"];
+		$noexts = ['mp3', 'mp4', 'ogg', 'ogv', 'oga', 'ogm', 'webm'];
 		$ext = pathinfo(strtolower($embedurl), PATHINFO_EXTENSION);
 
+		$oembed = new \Friendica\Object\OEmbed($embedurl);
 
-		if (is_null($txt)) {
-			$txt = "";
+		if ($json_string) {
```
Comment (annando) [inline src/Content/OEmbed.php]: Will this work even when ```$json_string``` is ```null```?

File: src/Content/OEmbed.php [hunk 4]
```diff
@@ -48,132 +47,128 @@ public static function replaceCallback($matches)
...
-		if (!is_object($j)) {
-			return false;
+			Cache::set($cache_key, $json_string, CACHE_DAY);
 		}
 
-		// Always embed the SSL version
-		if (isset($j->html)) {
-			$j->html = str_replace(["http://www.youtube.com/", "http://player.vimeo.com/"], ["https://www.youtube.com/", "https://player.vimeo.com/"], $j->html);
+		if ($oembed->type == 'error') {
+			return $oembed;
```
Comment (annando) [inline src/Content/OEmbed.php]: Why do we return now the variable ```$oembed``` instead of a ```false```?

File: src/Content/OEmbed.php [hunk 5]
```diff
@@ -48,132 +47,128 @@ public static function replaceCallback($matches)
...
+					'url' => normalise_link($embedurl),
+					'maxwidth' => $a->videowidth,
+					'content' => $json_string,
+					'created' => DateTimeFormat::utcNow()
+				], true);
+			}
 
-		if (!is_object($j)) {
-			return false;
+			Cache::set($cache_key, $json_string, CACHE_DAY);
```
Comment (annando) [inline src/Content/OEmbed.php]: This here means that we even will save an error into the cache. Is this intended?

File: src/Model/Item.php (hunk 2 above)
Comment (annando) [reply src/Model/Item.php]: We should possibly just move ```self::addLanguageToItemArray($item);``` some lines to the bottom where the bad had already been checked for content.

P.S.: I suggest just logging the callstack. Then we can check for the origin. I strongly oppose to using an exception here that would prevent the item from being stored. This would mean data loss.

File: src/Protocol/PortableContact.php [hunk 6]
```diff
@@ -1647,27 +1647,33 @@ public static function discover($complete = false)
...
-		$r = q("SELECT `id`, `url`, `nurl`, `network` FROM `gserver` WHERE `last_contact` >= `last_failure` AND `poco` != '' AND `last_poco_query` < '%s' ORDER BY RAND()", DBA::escape($last_update));
-		if (DBA::isResult($r)) {
-			foreach ($r as $server) {
-				if (!self::checkServer($server["url"], $server["network"])) {
+		$gservers = q("SELECT `id`, `url`, `nurl`, `network`
+			FROM `gserver`
+			WHERE `last_contact` >= `last_failure`
+			AND `poco` != ''
+			AND `last_poco_query` < '%s'
+			ORDER BY RAND()", DBA::escape($last_update)
```
Comment (annando) [inline src/Protocol/PortableContact.php]: I guess we don't need the ```RAND()``` here. This means that in some future step we can replace this with some ```dba::select```.

File: src/Content/OEmbed.php (hunk 4 above)
Comment (MrPetovan) [reply src/Content/OEmbed.php]: Because the functions calling this expect an OEmbed object, not a boolean.

File: src/Content/OEmbed.php (hunk 3 above)
Comment (MrPetovan) [reply src/Content/OEmbed.php]: Yes, as long as it's been declared previously.

File: src/Content/OEmbed.php (hunk 5 above)
Comment (MrPetovan) [reply src/Content/OEmbed.php]: Yes, just for a day though.

File: src/Protocol/PortableContact.php (hunk 6 above)
Comment (MrPetovan) [reply src/Protocol/PortableContact.php]: What about the `>=` and `<` operators?

File: src/Content/OEmbed.php (hunk 1 above)
Comment (MrPetovan) [reply src/Content/OEmbed.php]: That's the point of namespaces, you can have meaningful short class names organized in meaningful folders and still be able to use them together.

File: src/Model/Item.php (hunk 2 above)
Comment (MrPetovan) [reply src/Model/Item.php]: Good idea to move the call.

File: src/Content/OEmbed.php (hunk 5 above)
Comment (annando) [reply src/Content/OEmbed.php]: Just imagine the page only has got some short hiccup? I mostly prefer not to store this - or possibly not a day but some minutes only.

File: src/Protocol/PortableContact.php (hunk 6 above)
Comment (annando) [reply src/Protocol/PortableContact.php]: The condition can be something like this: 
```$condition = "[`last_contact` >= `last_failure` AND `poco` != '' AND `last_poco_query` < ?", $last_update]```

File: src/Content/OEmbed.php (hunk 5 above)
Comment (annando) [reply src/Content/OEmbed.php]: Would you like to reduce the cache time on an error? This is the only thing that I currently would like to have changed.

Comment (MrPetovan) [reply src/Content/OEmbed.php]: Sure, but I'm at work at the moment, give me a minute.

Comment (annando) [reply src/Content/OEmbed.php]: No problem. I just wanted to prevent that we wait on each other for ever ;-)

Comment (MrPetovan) [reply src/Content/OEmbed.php]: I changed it according to your wishes.
