### PR TITLE
Issue 11919: Avoid possible memory problems

### LINKED ISSUE #11919: Possible memory problems: Items aren't displayed when there too much
I'm running the latest 2022.09rc on my machine. On only one of my servers I have a strange problem. When I visit the community page, everything looks okay. Then I increase the number of items per page and after some point the community page doesn't display the content anymore:
image
I checked that the database query went well and that the conversation  function returned content. It seems that afterwards the content is lost. There are no entries in the log that could be a hint. Also it seems to depend on the content, since it doesn't fail all the time.

### PR DESCRIPTION
**Pull request by annando**
This possibly fixes #11919 

Previously we passed the whole conversation content through the template.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

File: src/Module/Conversation/Community.php [hunk 1]
```diff
@@ -53,11 +53,17 @@ protected function content(array $request = []): string
 	{
 		$this->parseRequest();
 
+		$t = Renderer::getMarkupTemplate("community.tpl");
```
Comment (Quix0r) [inline src/Module/Conversation/Community.php:56]: A bit to late for a review but here I know we use single quotes.
