### PR TITLE
E-Mail Message-ID & Newline fix

### LINKED ISSUE #9142: [phpmailer] Double Message-ID header in some notification mails - RFC violation
### Expected behavior
A mail must contain one Message-ID header. Two Message-ID headers are a RFC violation.
Setting the message ID is a task for the used mailer but not for the application, I think.

### Actual behavior
Some (!) - not all - notification messages have two Message-ID headers. I got bounce mails because of this RFC violation.

I think the problem is here:
https://github.com/friendica/friendica/blob/40a93223ee0fcc77d541f2ef9c3c02a2722a41fe/include/enotify.php#L523

Example:
```
Date: Fri, 4 Sep 2020 00:42:35 +0000
To: libranet@someremotedomain.com
From: "LIBRANET.de" <admin@libranet.de>
Reply-To: "LIBRANET.de" <admin@libranet.de>
Subject: [Friendica:Notify] Example User tagged you (exampleuser@libranet.de)
Message-ID: <Blx5qbY0czTL40q3ZNGWzGjgvszFW9ECBcRJWwGU@librabox2.libranet.de>
X-Mailer: PHPMailer 6.1.4 (https://github.com/PHPMailer/PHPMailer)
Precedence: list
X-Friendica-Host: libranet.de
X-Friendica-Platform: Friendica
X-Friendica-Version: 2020.09-dev
List-ID: <notification.libranet.de>
List-Archive: <https://libranet.de/notifications/system>
X-Friendica-Account: <exampleuser@libranet.de>
Message-ID: <83810059@libranet.de>
MIME-Version: 1.0
Content-Type: multipart/alternative;
....
```

### Steps to reproduce the problem
I do use the phpmailer add-on. That add-on creates a message ID with the local hostname as domain part. That's okay.

But enotify adds another message ID under some circumstances. Most other notification mails have a `References: <83200641@libranet.de>` and `In-Reply-To: <83200641@libranet.de>` instead. That works. But the two message IDs are bad.

### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

### PR DESCRIPTION
**Pull request by nupplaphil**
At least should now fix #9142  
With https://github.com/friendica/friendica-addons/pull/1021

### CODE REVIEW

**Comment by AlfredSK** [comment]
Tests are failing.

File: src/Util/Emailer.php [hunk 1]
```diff
@@ -134,6 +134,18 @@ public function send(IEmail $email)
...
+		// @see https://github.com/friendica/friendica/issues/9142
+		$countMessageId = 0;
+		foreach ($email->getAdditionalMailHeader() as $name => $value) {
+			if (strtolower($name) == 'message-id') {
+				$countMessageId += count($value);
+			}
+		}
+		if ($countMessageId > 0) {
+			$this->logger->warning('More than one Message-ID found - RFC violation', ['email' => $email]);
+			return false;
```
Comment (MrPetovan) [inline src/Util/Emailer.php]: No no no no no, we can't just discard the email because we failed to build it properly. This isn't related to any user error so it should not prevent an email send.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Util/Emailer.php (hunk 1 above)
Comment (nupplaphil) [reply src/Util/Emailer.php]: hmkay .. I thought as a RFC violation, it isn't trustable anymore .. and in the worst case, Mailservers suspects just mails and deny them (afaik mailservers are really restrictive in such cases because of spam ..)

Comment (MrPetovan) [reply src/Util/Emailer.php]: Yes but the solution isn't to silently discard the emails even before they can be denied by remote mail servers. It is a code issue we will fix that doesn't warrant this stopgap.

Comment (nupplaphil) [reply src/Util/Emailer.php]: OK, I changed it back for now. At a later stage, we should think about a proper solution .. Like cleanup such cases and log them ...

Comment (MrPetovan) [reply src/Util/Emailer.php]: You already added logging which is great, now we can move on to the proper solution.

**Review by MrPetovan — APPROVED** [review]
