### PR TITLE
Issue 11846: Fix client behaviour when following hash tags

### LINKED ISSUE #11846: [Mastodon/API] Links to hashtags or profiles
See https://github.com/tuskyapp/Tusky/issues/2657 : In some Mastodon clients, hashtag and profile links emitted via Friendica Mastodon API do not trigger in-app interactions but rather lead to the app opening a web link in the browser. This _seems_ to be caused by the way Friendica is building these links. This could be fixed in the frontend apps but maybe fixing it in the API implementation would be generally better. Is that possible...?

EDIT: Unsure why this has been labeled "Bug", but seems I'm unable to change that.

### PR DESCRIPTION
**Pull request by annando**
Fixes #11846

### CODE REVIEW

File: src/Object/Api/Mastodon/Status.php [hunk 1]
```diff
@@ -109,7 +109,7 @@ public function __construct(array $item, Account $account, Counts $counts, UserA
 		}
 
 		$this->sensitive    = $sensitive;
-		$this->spoiler_text = $item['title'] ?: $item['content-warning'];
+		$this->spoiler_text = ($item['title'] ?: $item['content-warning']) ?: '';
```
Comment (MrPetovan) [inline src/Object/Api/Mastodon/Status.php]: Coalescing operators aren't ambiguous the way ternary operators are. Here, variables are evaluated from left to right.
```suggestion
		$this->spoiler_text = $item['title'] ?: $item['content-warning'] ?: '';
```

**Review by MrPetovan — CHANGES_REQUESTED** [review]

**Review by MrPetovan — APPROVED** [review]
