### PR TITLE
Transform BaseURL to URIInterface conform class with less business logic

### LINKED ISSUE #12793: White pages since update to last dev version
- [X] I have searched open and closed issues for duplicates

### Bug Description
After updating to the latest dev version (commit d3acdd3) I'm getting a white page everywhere.
Interestingly no logs through PHP or Apache are created even when I try to force it with
ini_set('display_errors', true);
error_reporting(E_ALL);
in index.php.
In addition the requests are answered with HTTP 200 instead of e.g. 500.

Edit: Even the installer won't start after a fresh checkout.

### Steps to Reproduce

1.  checkout latest dev version
2.  get white pages everywhere

Actual Result:

Friendica shows white pages everywhere

Expected Result:

Working website

### Platform Info

Friendica Version: latest dev

Friendica Source: git

PHP version: 8.1.15

SQL version:

### PR DESCRIPTION
**Pull request by nupplaphil**
Fixes #12793 

This PR removes the usage of the following settings:
- `config.hostname`
- `system.urlpath`
- `system.ssl_policy`

The whole `BaseURL` is now based on `system.url` only. If this config isn't set, it will determine a URL once and logs a critical line that the config isn't set right.

Additionally, `BaseURL` now implements the `UriInterface`, so it's now full PSR compatible :-)

And I fixed the manual installation workflow.

I tested it locally with Vagrant and selfsigned certificate (including the `system.force_ssl` setting) and already migrated my `https://friendica.philipp.info` to this branch

**Beware** Needs https://git.friendi.ca/friendica/friendica-addons/pulls/1356 as well

### CODE REVIEW

File: src/Content/Conversation.php [hunk 1]
```diff
@@ -784,7 +784,7 @@ public function create(array $items, string $mode, $update, bool $preview = fals
 		}
 
 		$o = Renderer::replaceMacros($page_template, [
-			'$baseurl'     => $this->baseURL->get($ssl_state),
```
Comment (MrPetovan) [inline src/Content/Conversation.php:787]: Do we still need the `$ssl_state` variable?

File: src/Content/Nav.php [hunk 2]
```diff
@@ -194,7 +194,7 @@ private function getInfo(): array
 
 		$myident = !empty($this->session->getLocalUserNickname()) ? $this->session->getLocalUserNickname() . '@' : '';
 
-		$sitelocation = $myident . substr($this->baseUrl->get($ssl_state), strpos($this->baseUrl->get($ssl_state), '//') + 2);
```
Comment (MrPetovan) [inline src/Content/Nav.php:197]: Do we still need the `$ssl_state` variable?

File: src/App/BaseURL.php [hunk 3]
```diff
@@ -23,284 +23,66 @@
...
-		if ($this->url !== $currUrl) {
-			$configTransaction->set('system', 'url', $this->url);
+		$url = $config->get('system', 'url');
+		if (empty($url)) {
+			$logger->critical('Invalid config - Missing system.url');
+			$url = ServerRequest::getUriFromGlobals()
+								->withQuery('')
+								->withPath($this->determineURLPath($server));
+
+			parent::__construct((string)$url);
```
Comment (MrPetovan) [inline src/App/BaseURL.php]: I believe explicit casting is unnecessary here as it should be done automatically thanks to type-hinting.

File: src/Module/Home.php [hunk 4]
```diff
@@ -69,7 +69,7 @@ protected function content(array $request = []): string
 			$customHome = $homeFilePath;
 
 			if (file_exists($cssFilePath)) {
-				DI::page()['htmlhead'] .= '<link rel="stylesheet" type="text/css" href="' . DI::baseUrl()->get() . '/home.css' . '" media="all" />';
+				DI::page()['htmlhead'] .= '<link rel="stylesheet" type="text/css" href="' . DI::baseUrl() . '/home.css' . '" media="all" />';
```
Comment (MrPetovan) [inline src/Module/Home.php]: Please use `Page->registerStylesheet` instead.
```suggestion
				DI::page()->registerStylesheet('home.css', 'all');
```

File: src/Module/Install.php [hunk 5]
```diff
@@ -218,43 +212,31 @@ protected function content(array $request = []): string
...
 						$this->t('Required')],
-					'$urlpath'    => ['system-urlpath',
-						$this->t('Sub path of the URL'),
-						$configCache->get('system', 'urlpath'),
-						$this->t('Overwrite this field in case the sub path determination isn\'t right, otherwise leave it as is. Leaving this field blank means the installation is at the base URL without sub path.'),
-						''],
+					'$system_url'    => ['system-url',
+						$this->t('The Friendica system URL'),
+						(string)$baseUrl,
+						$this->t('Overwrite this field in case the system URL determination isn\'t right, otherwise leave it as is.'),
```
Comment (MrPetovan) [inline src/Module/Install.php]: It's ok to use double-quotes to prevent escaping single quotes in text which makes its searching more difficult.
```suggestion
						$this->t("Overwrite this field in case the system URL determination isn't right, otherwise leave it as is."),
```

File: mod/message.php [hunk 6]
```diff
@@ -58,7 +58,7 @@ function message_init(App $a)
 
 	$head_tpl = Renderer::getMarkupTemplate('message-head.tpl');
 	DI::page()['htmlhead'] .= Renderer::replaceMacros($head_tpl, [
-		'$baseurl' => DI::baseUrl()->get(true),
+		'$baseurl' => DI::baseUrl(),
```
Comment (MrPetovan) [inline mod/message.php]: You can remove those, `$baseurl` is always set for all templates. These were needed because the scheme was potentially different.
```suggestion
```

File: mod/message.php [hunk 7]
```diff
@@ -178,7 +178,7 @@ function message_content(App $a)
 
 		$tpl = Renderer::getMarkupTemplate('msg-header.tpl');
 		DI::page()['htmlhead'] .= Renderer::replaceMacros($tpl, [
-			'$baseurl' => DI::baseUrl()->get(true),
+			'$baseurl' => DI::baseUrl(),
```
Comment (MrPetovan) [inline mod/message.php]:
```suggestion
```

File: mod/message.php [hunk 8]
```diff
@@ -284,7 +284,7 @@ function message_content(App $a)
...
```
Comment (MrPetovan) [inline mod/message.php]:
```suggestion
```

File: src/Module/Admin/Addons/Details.php [hunk 9]
```diff
@@ -112,7 +112,7 @@ protected function content(array $request = []): string
 			'$page' => DI::l10n()->t('Addons'),
 			'$toggle' => DI::l10n()->t('Toggle'),
 			'$settings' => DI::l10n()->t('Settings'),
-			'$baseurl' => DI::baseUrl()->get(true),
+			'$baseurl' => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Admin/Addons/Details.php]:
```suggestion
```

File: src/Module/Admin/Addons/Index.php [hunk 10]
```diff
@@ -68,7 +68,7 @@ protected function content(array $request = []): string
 			'$page' => DI::l10n()->t('Addons'),
 			'$submit' => DI::l10n()->t('Save Settings'),
 			'$reload' => DI::l10n()->t('Reload active addons'),
-			'$baseurl' => DI::baseUrl()->get(true),
+			'$baseurl' => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Admin/Addons/Index.php]:
```suggestion
```

File: src/Module/Admin/DBSync.php [hunk 11]
```diff
@@ -102,13 +102,13 @@ protected function content(array $request = []): string
 
 				if (!count($failed)) {
 					$o = Renderer::replaceMacros(Renderer::getMarkupTemplate('admin/dbsync/structure_check.tpl'), [
-						'$base' => DI::baseUrl()->get(true),
+						'$base' => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Admin/DBSync.php]: Same remark as for the `'$baseurl'` template variable, except it should be renamed in `admin/dbsync/structure_check.tpl`
```suggestion
```

File: src/Module/Admin/DBSync.php [hunk 12]
```diff
@@ -102,13 +102,13 @@ protected function content(array $request = []): string
...
 						'$banner' => DI::l10n()->t('No failed updates.'),
 						'$check' => DI::l10n()->t('Check database structure'),
 					]);
 				} else {
 					$o = Renderer::replaceMacros(Renderer::getMarkupTemplate('admin/dbsync/failed_updates.tpl'), [
-						'$base' => DI::baseUrl()->get(true),
+						'$base' => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Admin/DBSync.php]: Same remark as for the `'$baseurl'` template variable, except it should be renamed in `admin/dbsync/failed_updates.tpl`
```suggestion
```

File: src/Module/Admin/Features.php [hunk 13]
```diff
@@ -81,7 +81,7 @@ protected function content(array $request = []): string
 		$tpl = Renderer::getMarkupTemplate('admin/features.tpl');
 		$o = Renderer::replaceMacros($tpl, [
 			'$form_security_token' => self::getFormSecurityToken("admin_manage_features"),
-			'$baseurl'             => DI::baseUrl()->get(true),
+			'$baseurl'             => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Admin/Features.php]:
```suggestion
```

File: src/Module/Admin/Logs/Settings.php [hunk 14]
```diff
@@ -80,7 +80,7 @@ protected function content(array $request = []): string
 			'$page' => DI::l10n()->t('Logs'),
 			'$submit' => DI::l10n()->t('Save Settings'),
 			'$clear' => DI::l10n()->t('Clear'),
-			'$baseurl' => DI::baseUrl()->get(true),
+			'$baseurl' => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Admin/Logs/Settings.php]:
```suggestion
```

File: src/Module/Admin/Logs/View.php [hunk 15]
```diff
@@ -80,7 +80,7 @@ protected function content(array $request = []): string
 			}
 		}
 		return Renderer::replaceMacros($t, [
-			'$baseurl'       => DI::baseUrl()->get(true),
+			'$baseurl'       => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Admin/Logs/View.php]:
```suggestion
```

File: src/Module/Admin/Site.php [hunk 16]
```diff
@@ -452,7 +406,7 @@ protected function content(array $request = []): string
 			'$relocate'          => DI::l10n()->t('Relocate Node'),
 			'$relocate_msg'      => DI::l10n()->t('Relocating your node enables you to change the DNS domain of this node and keep all the existing users and posts. This process takes a while and can only be started from the relocate console command like this:'),
 			'$relocate_cmd'      => DI::l10n()->t('(Friendica directory)# bin/console relocate https://newdomain.com'),
-			'$baseurl'           => DI::baseUrl()->get(true),
+			'$baseurl'           => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Admin/Site.php]:
```suggestion
```

File: src/Module/Admin/Storage.php [hunk 17]
```diff
@@ -144,7 +144,7 @@ protected function content(array $request = []): string
 			'$use'                   => DI::l10n()->t('Use storage backend'),
 			'$save_reload'           => DI::l10n()->t('Save & Reload'),
 			'$noconfig'              => DI::l10n()->t('This backend doesn\'t have custom settings'),
-			'$baseurl'               => DI::baseUrl()->get(true),
+			'$baseurl'               => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Admin/Storage.php]:
```suggestion
```

File: src/Module/Admin/Themes/Details.php [hunk 18]
```diff
@@ -91,7 +91,7 @@ protected function content(array $request = []): string
 			'$page' => DI::l10n()->t('Themes'),
 			'$toggle' => DI::l10n()->t('Toggle'),
 			'$settings' => DI::l10n()->t('Settings'),
-			'$baseurl' => DI::baseUrl()->get(true),
+			'$baseurl' => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Admin/Themes/Details.php]:
```suggestion
```

File: src/Module/Admin/Themes/Embed.php [hunk 19]
```diff
@@ -95,7 +95,7 @@ protected function content(array $request = []): string
 
 		$t = Renderer::getMarkupTemplate('admin/addons/embed.tpl');
 		return Renderer::replaceMacros($t, [
-			'$action' => DI::baseUrl()->get(true) . '/admin/themes/' . $theme . '/embed?mode=minimal',
+			'$action' => DI::baseUrl() . '/admin/themes/' . $theme . '/embed?mode=minimal',
```
Comment (MrPetovan) [inline src/Module/Admin/Themes/Embed.php]: Since there can be no scheme difference, we can rely on `<base>` in all cases now.
```suggestion
			'$action' => 'admin/themes/' . $theme . '/embed?mode=minimal',
```

File: src/Module/Admin/Themes/Index.php [hunk 20]
```diff
@@ -112,7 +112,7 @@ protected function content(array $request = []): string
 			'$page'                => DI::l10n()->t('Themes'),
 			'$submit'              => DI::l10n()->t('Save Settings'),
 			'$reload'              => DI::l10n()->t('Reload active themes'),
-			'$baseurl'             => DI::baseUrl()->get(true),
+			'$baseurl'             => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Admin/Themes/Index.php]:
```suggestion
```

File: src/Module/Contact.php [hunk 21]
```diff
@@ -220,7 +220,7 @@ protected function content(array $request = []): string
 
 		$tpl = Renderer::getMarkupTemplate('contacts-head.tpl');
 		DI::page()['htmlhead'] .= Renderer::replaceMacros($tpl, [
-			'$baseurl' => DI::baseUrl()->get(true),
+			'$baseurl' => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Contact.php]:
```suggestion
```

File: src/Module/Contact/Profile.php [hunk 22]
```diff
@@ -236,7 +236,7 @@ protected function content(array $request = []): string
 		$_SESSION['return_path'] = $this->args->getQueryString();
 
 		$this->page['htmlhead'] .= Renderer::replaceMacros(Renderer::getMarkupTemplate('contact_head.tpl'), [
-			'$baseurl' => $this->baseUrl->get(true),
+			'$baseurl' => $this->baseUrl,
```
Comment (MrPetovan) [inline src/Module/Contact/Profile.php]:
```suggestion
```

File: src/Module/Debug/Localtime.php [hunk 23]
```diff
@@ -58,7 +58,7 @@ protected function content(array $request = []): string
 			$output .= '<p>' . DI::l10n()->t('Converted localtime: %s', self::$mod_localtime) . '</p>';
 		}
 
-		$output .= '<form action ="' . DI::baseUrl()->get() . '/localtime?time=' . $time . '" method="post" >';
+		$output .= '<form action ="' . DI::baseUrl() . '/localtime?time=' . $time . '" method="post" >';
```
Comment (MrPetovan) [inline src/Module/Debug/Localtime.php]:
```suggestion
		$output .= '<form action ="localtime?time=' . $time . '" method="post">';
```

File: src/Module/Help.php [hunk 24]
```diff
@@ -102,7 +102,7 @@ protected function content(array $request = []): string
 
 					$idNum[$level] ++;
 
-					$href = DI::baseUrl()->get() . "/help/{$filename}#{$anchor}";
+					$href = DI::baseUrl() . "/help/{$filename}#{$anchor}";
```
Comment (MrPetovan) [inline src/Module/Help.php]:
```suggestion
					$href = "help/{$filename}#{$anchor}";
```

File: src/Module/Moderation/Users/Blocked.php [hunk 25]
```diff
@@ -149,7 +149,7 @@ protected function content(array $request = []): string
 			'$form_security_token' => self::getFormSecurityToken('moderation_users_blocked'),
 
 			// values //
-			'$baseurl'      => $this->baseUrl->get(true),
+			'$baseurl'      => $this->baseUrl,
```
Comment (MrPetovan) [inline src/Module/Moderation/Users/Blocked.php]:
```suggestion
```

File: src/Module/Moderation/Users/Create.php [hunk 26]
```diff
@@ -65,7 +65,7 @@ protected function content(array $request = []): string
 			'$form_security_token' => self::getFormSecurityToken('admin_users_create'),
 
 			// values //
-			'$baseurl'      => $this->baseUrl->get(true),
+			'$baseurl'      => $this->baseUrl,
```
Comment (MrPetovan) [inline src/Module/Moderation/Users/Create.php]:
```suggestion
```

File: src/Module/Moderation/Users/Deleted.php [hunk 27]
```diff
@@ -85,7 +85,7 @@ protected function content(array $request = []): string
 			'$form_security_token' => self::getFormSecurityToken('moderation_users_deleted'),
 
 			// values //
-			'$baseurl'      => $this->baseUrl->get(true),
+			'$baseurl'      => $this->baseUrl,
```
Comment (MrPetovan) [inline src/Module/Moderation/Users/Deleted.php]:
```suggestion
```

File: src/Module/Moderation/Users/Index.php [hunk 28]
```diff
@@ -168,7 +168,7 @@ protected function content(array $request = []): string
 			'$form_security_token' => self::getFormSecurityToken('moderation_users'),
 
 			// values //
-			'$baseurl'      => $this->baseUrl->get(true),
+			'$baseurl'      => $this->baseUrl,
```
Comment (MrPetovan) [inline src/Module/Moderation/Users/Index.php]:
```suggestion
```

File: src/Module/Moderation/Users/Pending.php [hunk 29]
```diff
@@ -105,7 +105,7 @@ protected function content(array $request = []): string
 			'$form_security_token' => self::getFormSecurityToken('admin_users_pending'),
 
 			// values //
-			'$baseurl' => $this->baseUrl->get(true),
+			'$baseurl' => $this->baseUrl,
```
Comment (MrPetovan) [inline src/Module/Moderation/Users/Pending.php]:
```suggestion
```

File: src/Module/NodeInfo210.php [hunk 30]
```diff
@@ -52,7 +52,7 @@ protected function rawContent(array $request = [])
 		$nodeinfo = [
 			'version' => '1.0',
 			'server'  => [
-				'baseUrl'  => $this->baseUrl->get(),
+				'baseUrl'  => $this->baseUrl,
```
Comment (MrPetovan) [inline src/Module/NodeInfo210.php]:
```suggestion
```

File: src/Module/Profile/Schedule.php [hunk 31]
```diff
@@ -78,7 +78,7 @@ protected function content(array $request = []): string
 		$tpl = Renderer::getMarkupTemplate('profile/schedule.tpl');
 		$o .= Renderer::replaceMacros($tpl, [
 			'$form_security_token' => BaseModule::getFormSecurityToken("profile_schedule"),
-			'$baseurl'             => DI::baseUrl()->get(true),
+			'$baseurl'             => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Profile/Schedule.php]:
```suggestion
```

File: src/Module/Profile/UnkMail.php [hunk 32]
```diff
@@ -141,7 +141,7 @@ protected function content(array $request = []): string
 
 		$tpl = Renderer::getMarkupTemplate('profile/unkmail-header.tpl');
 		$this->page['htmlhead'] .= Renderer::replaceMacros($tpl, [
-			'$baseurl'  => $this->baseUrl->get(true),
+			'$baseurl'  => $this->baseUrl,
```
Comment (MrPetovan) [inline src/Module/Profile/UnkMail.php]:
```suggestion
```

File: src/Module/Security/Login.php [hunk 33]
```diff
@@ -132,7 +132,7 @@ public static function form(string $return_path = null, bool $register = false):
 			DI::page()['htmlhead'] .= Renderer::replaceMacros(
 				Renderer::getMarkupTemplate('login_head.tpl'),
 				[
-					'$baseurl' => DI::baseUrl()->get(true)
+					'$baseurl' => DI::baseUrl()
```
Comment (MrPetovan) [inline src/Module/Security/Login.php]:
```suggestion
```

File: src/Module/Security/PasswordTooLong.php [hunk 34]
```diff
@@ -93,7 +93,7 @@ protected function content(array $request = []): string
 				'submit' => $this->l10n->t('Update Password'),
 			],
 
-			'$baseurl'             => $this->baseUrl->get(true),
+			'$baseurl'             => $this->baseUrl,
```
Comment (MrPetovan) [inline src/Module/Security/PasswordTooLong.php]:
```suggestion
```

File: src/Module/Settings/Account.php [hunk 35]
```diff
@@ -555,10 +555,10 @@ protected function content(array $request = []): string
 		$tpl = Renderer::getMarkupTemplate('settings/account.tpl');
 		$o   = Renderer::replaceMacros($tpl, [
 			'$ptitle' => DI::l10n()->t('Account Settings'),
-			'$desc'   => DI::l10n()->t("Your Identity Address is <strong>'%s'</strong> or '%s'.", $nickname . '@' . DI::baseUrl()->getHostname() . DI::baseUrl()->getUrlPath(), DI::baseUrl() . '/profile/' . $nickname),
+			'$desc'   => DI::l10n()->t("Your Identity Address is <strong>'%s'</strong> or '%s'.", $nickname . '@' . DI::baseUrl()->getHost() . DI::baseUrl()->getPath(), DI::baseUrl() . '/profile/' . $nickname),
 
 			'$submit'              => DI::l10n()->t('Save Settings'),
-			'$baseurl'             => DI::baseUrl()->get(true),
+			'$baseurl'             => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Settings/Account.php]:
```suggestion
```

File: src/Module/Settings/Display.php [hunk 36]
```diff
@@ -252,7 +252,7 @@ protected function content(array $request = []): string
 			'$calendar_title' => $this->t('Calendar'),
 
 			'$form_security_token' => self::getFormSecurityToken('settings_display'),
-			'$baseurl'             => $this->baseUrl->get(true),
+			'$baseurl'             => $this->baseUrl,
```
Comment (MrPetovan) [inline src/Module/Settings/Display.php]:
```suggestion
```

File: src/Module/Settings/OAuth.php [hunk 37]
```diff
@@ -68,7 +68,7 @@ protected function content(array $request = []): string
 		$tpl = Renderer::getMarkupTemplate('settings/oauth.tpl');
 		return Renderer::replaceMacros($tpl, [
 			'$form_security_token' => BaseSettings::getFormSecurityToken('settings_oauth'),
-			'$baseurl'             => $this->baseUrl->get(true),
+			'$baseurl'             => $this->baseUrl,
```
Comment (MrPetovan) [inline src/Module/Settings/OAuth.php]:
```suggestion
```

File: src/Module/Settings/Profile/Index.php [hunk 38]
```diff
@@ -208,7 +208,7 @@ protected function content(array $request = []): string
 		];
 
 		DI::page()['htmlhead'] .= Renderer::replaceMacros(Renderer::getMarkupTemplate('settings/profile/index_head.tpl'), [
-			'$baseurl' => DI::baseUrl()->get(true),
+			'$baseurl' => DI::baseUrl(),
```
Comment (MrPetovan) [inline src/Module/Settings/Profile/Index.php]:
```suggestion
```

File: update.php [hunk 39]
```diff
@@ -1287,3 +1287,15 @@ function update_1514()
...
 	return Update::SUCCESS;
 }
+
+function update_1515()
+{
+	DI::config()
+	  ->beginTransaction()
+	  ->delete('config', 'hostname')
+	  ->delete('system', 'urlpath')
+	  ->delete('system', 'ssl_policy')
```
Comment (MrPetovan) [inline update.php]: Once again, I'm with @annando , we don't need to delete them if we don't use them anymore.

File: view/templates/install/01_checks.tpl [hunk 40]
```diff
@@ -1,7 +1,7 @@
 
 <h1><img width="32" height="32" src="{{$baseurl}}/images/friendica.svg"> {{$title}}</h1>
 <h2>{{$pass}}</h2>
-<form  action="{{$baseurl}}/index.php?pagename=install" method="post">
+<form  action="{{$baseurl}}/install" method="post">
```
Comment (MrPetovan) [inline view/templates/install/01_checks.tpl]: Isn't this going to stunt servers with no mod_rewrite activated yet?

File: view/theme/smoothly/theme.php [hunk 41]
```diff
@@ -1,4 +1,30 @@
...
+ * You should have received a copy of the GNU Affero General Public License
+ * along with this program.  If not, see <https://www.gnu.org/licenses/>.
+ *
+ * Name: Vier
+ * Version: 1.2
+ * Author: Fabio <http://kirgroup.com/profile/fabrixxm>
+ * Author: Ike <http://pirati.ca/profile/heluecht>
+ * Author: Beanow <https://fc.oscp.info/profile/beanow>
+ * Maintainer: Ike <http://pirati.ca/profile/heluecht>
+ * Description: "Vier" is a very compact and modern theme. It uses the font awesome font library: http://fortawesome.github.com/Font-Awesome/
```
Comment (MrPetovan) [inline view/theme/smoothly/theme.php]: This is all inaccurate as it's been copied from Vier. Also it needs to mention it's unsupported.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Content/Conversation.php (hunk 1 above)
Comment (nupplaphil) [reply src/Content/Conversation.php:787]: No, this was necessary in case we use SSL, but don't force it. With this flag we could enforce SSL for some links in these circumstances. But now the baseurl is either with or without SSL at all.

File: src/Module/Admin/DBSync.php (hunk 11 above)
Comment (nupplaphil) [reply src/Module/Admin/DBSync.php]: funny enough .. it isn't used in this template, it's already `$baseurl` everywhere, so we can remove this setting :)

File: src/Content/Nav.php (hunk 2 above)
Comment (nupplaphil) [reply src/Content/Nav.php:197]: same as above

File: src/Content/Conversation.php (hunk 1 above)
Comment (MrPetovan) [reply src/Content/Conversation.php:787]: Yes, and what about the variable you removed a reference to, is it still used elsewhere?

**Review by MrPetovan — APPROVED** [review]

**Comment by nupplaphil** [comment]
@MrPetovan I cannot solve all license checks. Or shall I really add the license title to the config files :)

**Comment by MrPetovan** [comment]
> @MrPetovan I cannot solve all license checks. Or shall I really add the license title to the config files :)

I know, I just am on mobile today and it makes it hard for me to be sure of myself enough to pull the merge trigger.

**Comment by AlfredSK** [comment]
> Beware Needs https://git.friendi.ca/friendica/friendica-addons/pulls/1356 as well

When this PR for the add-ons is needed why is it on git.friendi.ca only?

**Comment by MrPetovan** [comment]
Because I believe the Friendica addon repository was successfully moved to ForgeJo, leaving the GitHub repository as a mirror.

**Comment by AlfredSK** [comment]
> Because I believe the Friendica addon repository was successfully moved to ForgeJo, leaving the GitHub repository as a mirror.

Shouldn't we announce that? I found no hint about the move.

**Comment by nupplaphil** [comment]
Currently we're stuck in the migration process because this repo is too big to migrate. There's a possible solution in the backlog of Forgejo/Gitea. Meanwhile the add-on repo is already migrated but because we mirror the whole repository, it doesn't matter for anyone except for developers :-)

**Comment by MrPetovan** [comment]
I'm with @nupplaphil , I think we should announce the change when the move is complete. At the moment as an admin you can clone from either remote repository interchangeably and it will work the same way you've been used to.

**Comment by AlfredSK** [comment]
Ah! Ok. I was afraid that pulling from GitHub (or my own mirror of the GitHub repo) would break a node running on develop.

Thank you.
