### PR TITLE
Contact requests blocked

### LINKED ISSUE #6981: Contact requests from server blocked profiles
### Expected behavior
If a user (profile) is on the server's remote contact blocklist (.../admin/contactblock) users shouldn't get contact/friend requests from these remote users.

### Actual behavior
The users are getting contact/friend requests from server blocked users/profiles and also get notifications about it.
Also, it doesn't help to ignore the contact requests. The user gets new contact requests again and again although the former requests had been ignored and are listed on the ignored contact request list (.../notifications/intros/all).

So, actually there are two issues with these contact requests. But I think they're related to the same underlying problem.

I see this behavior with ActivityPub (Mastodon) users/profiles. Maybe other protocols are affected too. But I only see the issue with AP users/profiles.

### Steps to reproduce the problem
Add an AP user/profile to your server's remote contact blocklist and then send a contact request from that AP user (click on Mastodon's 'follow' button) to your Friendica profile.

### Friendica version you encountered the problem
2019.03

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #6981 

The big change in this PR is `Model\Contact::addRelationship` returning a value, either `true` for relationship establishment success, `null` for relationship establishment pending, and `false` for relationship establishment failure.

This allowed me to move AP-specific code out of this method and properly add a contact block provision to it.

Side fixes/improvements:
- SQL error in admin summary
- JsonLD exception handling
- API call not implemented logging

### CODE REVIEW

**Comment by annando** [comment]
I guess you have to return "null" on error to not accidentally trigger a rejection. But I don't really like moving the AP code out of this function. Compare it with functions like "createFromProbe" or "terminateFriendship". These are the "black boxes" that do the whole protocol specific contact management for us. They can also be called - for example - via the API or possibly some other places. I think that this relocating of code makes debugging more complicated.

File: src/Module/Admin/Summary.php [hunk 1]
```diff
@@ -26,7 +26,7 @@ public static function content()
 
 		// are there MyISAM tables in the DB? If so, trigger a warning message
 		$warningtext = [];
-		if (DBA::count('`information_schema`.`tables`', ['engine' => 'myisam', 'table_schema' => DBA::databaseName()])) {
+		if (DBA::count('information_schema`.`tables', ['engine' => 'myisam', 'table_schema' => DBA::databaseName()])) {
```
Comment (nupplaphil) [inline src/Module/Admin/Summary.php]: This one doesn't seem right. Or is this a hack to count on system tables? If so, maybe there is a better solution directly in `DBA` possible?

Comment (nupplaphil) [reply src/Module/Admin/Summary.php]: Like a optional flag in `count(..., $schema = null)` and if not null, use it

Comment (annando) [reply src/Module/Admin/Summary.php]: In fact I just had a look at the code - it works that way but is ugly.

Comment (annando) [reply src/Module/Admin/Summary.php]: I suggest that I apply some changes to the database class for this.

Comment (annando) [reply src/Module/Admin/Summary.php]: I suggest doing it that way:
```
DBA::count(['information_schema' => 'tables'], ['engine' => 'myisam', 'table_schema' => DBA::databaseName()])
```

Comment (nupplaphil) [reply src/Module/Admin/Summary.php]: much better of course! :-)

**Comment by MrPetovan** [comment]
> I guess you have to return "null" on error to not accidentally trigger a rejection.

Why? What can justify acknowledging a contact request when the contact ID is missing? If the public contact doesn't exist?

> I think that this relocating of code makes debugging more complicated.

Why so? On the contrary, having protocol-specific stuff in the model makes methods bigger with multiples code paths, increasing complexity. Don't take my word for it, I removed 10 protocol-specific lines from `Contact::addRelationship`, including 2 conditions and multiple DB requests to retrieve the contact protocol, and I replaced it with 3 lines with 1 condition and no extra DB requests. The original version wasn't even handling the `ActivityPub\Transmitter::sendContactReject` case.

Yes, I understand the convenience of seeing what every protocol is doing on contact actions in a single method, but it isn't sustainable and is harder to maintain since there isn't a clear separation of concern.

I'll take care of `Contact::terminateFriendship` as well as it is in the same situation. `Contact::createFromProbe` has other issues (like the `$interactive` parameter flag) that are outside of the scope of this issue.

**Comment by annando** [comment]
BTW: The not sending of ```sendContactReject``` was intentionally. Sending a contact reject is optional in the protocol description, since possibly a user don't want the requesting person to know that this user rejected the contact request instead of ignoring it.

The problem with splitting these functions into several parts has got the problem that you never know if there possibly will come some new protocol that needs some very different treatment that we cannot handle that way.

I don't have that much paradigm when coding, but I really prefer the concept to have functions that are doing the whole stuff. This especially is much better when it comes to tasks that are possibly be called from different places like in the future by the API.

**Comment by MrPetovan** [comment]
There are two ways of handling this:
- Either you have a massive function that handles every possible case. Each new case inflates the function length until it is too long/complex to be easily parseable by humans.
- Or you identify atomic behaviors, export them in separate functions, and only call them when you need. I believe that no matter what protocol comes along, the underlying Friendica way of adding a relationship between a user and a contact won’t change. This is an atomic, protocol-independent behavior that deserves to have its own function. Now each protocol can call it (or not) depending on the protocol-specific behavior.

File: src/Model/Contact.php [hunk 2]
```diff
@@ -2120,17 +2120,33 @@ public static function updateSslPolicy(array $contact, $new_policy)
...
+		$fields = ['url', 'name', 'nick', 'photo', 'network', 'blocked'];
 		$pub_contact = DBA::selectFirst('contact', $fields, ['id' => $datarray['author-id']]);
 		if (!DBA::isResult($pub_contact)) {
 			// Should never happen
-			return;
+			return false;
+		}
+
+		// Contact is blocked on node-level or user-level
+		if (!empty($pub_contact['blocked']) || !empty($contact['blocked'])) {
```
Comment (annando) [inline src/Model/Contact.php]: BTW: We do have ```isBlocked``` and ```isBlockedByUser``` - we should use that instead.

File: src/Protocol/ActivityPub/Processor.php [hunk 3]
```diff
@@ -541,7 +541,14 @@ public static function followUser($activity)
 		// Ensure that the contact has got the right network type
 		self::switchContact($item['author-id']);
 
-		Contact::addRelationship($owner, $contact, $item, '', false, $note);
+		$result = Contact::addRelationship($owner, $contact, $item, false, $note);
+		if ($result === false) {
+			ActivityPub\Transmitter::sendContactReject($item['author-link'], $item['author-id'], $owner['uid']);
```
Comment (annando) [inline src/Protocol/ActivityPub/Processor.php]: I don't like sending a contact reject in case of a blocked account. The other person doesn't need to know if we just ignore the person or have blocked the person.

Comment (MrPetovan) [reply src/Protocol/ActivityPub/Processor.php]: I think they do, because there is a difference between ignore and block. Do we have a way to ignore a contact without following them/them following us?

File: src/Model/Contact.php (hunk 2 above)
Comment (MrPetovan) [reply src/Model/Contact.php]: Fair enough.

File: src/Module/Admin/Summary.php (hunk 1 above)
Comment (MrPetovan) [reply src/Module/Admin/Summary.php]: Moved to #7174

File: src/Protocol/ActivityPub/Processor.php (hunk 3 above)
Comment (MrPetovan) [reply src/Protocol/ActivityPub/Processor.php]: I removed the follow reject response until we sort this out.

File: src/Model/Contact.php (hunk 2 above)
Comment (MrPetovan) [reply src/Model/Contact.php]: Done. You were 100% right, I forgot about the server block and the `user-contact` table. Thanks for the pointer.

File: src/Protocol/ActivityPub/Processor.php (hunk 3 above)
Comment (tobiasd) [reply src/Protocol/ActivityPub/Processor.php]: We can just hit the "ignore" button on the introduction they send us and they will never get a response (as long as you don't dive into the list of ignored introductions)

Comment (MrPetovan) [reply src/Protocol/ActivityPub/Processor.php]: In this case (blocked contact or blocked node) the contact request won't be saved as an introduction at all. The question is if the remote contact should receive a follow rejection response or not in this case.

**Comment by tobiasd** [comment]
> The question is if the remote contact should receive a follow
> rejection response or not in this case.

With diaspora* it is the case that an discarded introduction is send over and over again, hence there is only the ignore button.

What will happen if the blocke users request is just dropped? Will the other end send requests again and again?

Will it stop if the rejection was send?

Does the other account know it was blocked?

If not, I'd say just drop the request into /dev/null who I block or ignore should not be share I think.

**Comment by MrPetovan** [comment]
Ok then this PR is ready in this case. I already removed the contentious follow rejection response.
