### PR TITLE
Fix last batch of implicit mentions issues

### LINKED ISSUE #6676: Implicit mentions: Master issue list
Follow-up to #6541
Follow-up to #6552

Second round of fixes. On the menu:
- [x] Fix incoming AP implicit mentions by recording implicit mentions (they were just discarded before, preventing the removal of further conversant mentions beyond the replied-to author) (#6726)
- [x] Add global config killswitch for implicit mentions (the existing config key only changed the behavior of incoming AP implicit mention removal) (#6726)
- [x] Fix Friendica-submitted items implicit mentions (Currently there aren't any implicit mentions) (#6726)
- [x] Fix potential issue with outgoing Diaspora implicit mentions (the top-level author may be mentioned instead of the replied-to author). (#6726)
- [x] Fix explicit mention default comment box text (Explicit mentions are sometimes missing from the comment box) (#6726)
- [x] Fix outgoing AP implicit mentions (we shouldn't add implicit self-mentions) (#6717)
- [x] Test new comment boxes collapse with explicit mentions (#6726)

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #6676 

This is the last implicit mentions fix for this release, although the general "Improve all the mentions" project isn't complete yet.

Known caveats that won't be addressed in this version:
- OStatus messages are currently ignored by the implicit mention behavior, both incoming and outgoing.
- DFRN messages are currently ignored by the implicit mention behavior, both incoming and outgoing.
- Twitter/connectors messages are currently ignored by the implicit mention behavior, both incoming and outgoing.
- Incoming Pleroma (AP) message bodies are left as-is.
- Incoming Hubzilla (AP) message bodies are left as-is.
- Mentions (in general) in outgoing Pleroma messages aren't converted in the target format like we do for Mastodon.

### CODE REVIEW

File: mod/item.php [hunk 1]
```diff
@@ -1099,3 +1097,34 @@ function handle_tag(&$body, &$inform, &$str_tags, $profile_uid, $tag, $network =
...
+
+		foreach ($implicit_mentions as $url => $label) {
+			if ($url != \Friendica\Model\Profile::getMyURL() && !stripos(implode($tags), '[url=' . $url . ']')) {
+				$tags[] = Term::TAG_CHARACTER[Term::IMPLICIT_MENTION] . '[url=' . $url . ']' . $label . '[/url]';
+			}
+		}
+	}
+
+	return $tags;
+}
```
Comment (nupplaphil) [inline mod/item.php]: EOL missing

File: src/Database/DBA.php [hunk 2]
```diff
@@ -420,7 +420,7 @@ public static function p($sql) {
 
 		if ((substr_count($sql, '?') != count($args)) && (count($args) > 0)) {
 			// Question: Should we continue or stop the query here?
-			Logger::log('Parameter mismatch. Query "'.$sql.'" - Parameters '.print_r($args, true), Logger::DEBUG);
+			Logger::error('Parameter mismatch. Query "'.$sql.'" - Parameters '.print_r($args, true));
```
Comment (nupplaphil) [inline src/Database/DBA.php]: is this really an error? Debug is mapped to notice normally. Maybe you can fill the context array with the parameters and the query.

File: src/Model/Item.php [hunk 3]
```diff
@@ -1336,7 +1336,7 @@ public static function insert($item, $force_parent = false, $notify = false, $do
 			$expire_date = time() - ($expire_interval * 86400);
 			$created_date = strtotime($item['created']);
 			if ($created_date < $expire_date) {
-				Logger::log('item-store: item created ('.date('c', $created_date).') before expiration time ('.date('c', $expire_date).'). ignored. ' . print_r($item,true), Logger::DEBUG);
+				Logger::notice('item-store: item created ('.date('c', $created_date).') before expiration time ('.date('c', $expire_date).'). ignored. ' . print_r($item,true));
```
Comment (nupplaphil) [inline src/Model/Item.php]: If possible, please fill the context array.

File: src/Model/Item.php [hunk 4]
```diff
@@ -1354,7 +1354,7 @@ public static function insert($item, $force_parent = false, $notify = false, $do
 			if (DBA::isResult($existing)) {
 				// We only log the entries with a different user id than 0. Otherwise we would have too many false positives
 				if ($uid != 0) {
-					Logger::log("Item with uri ".$item['uri']." already existed for user ".$uid." with id ".$existing["id"]." target network ".$existing["network"]." - new network: ".$item['network']);
+					Logger::notice("Item with uri ".$item['uri']." already existed for user ".$uid." with id ".$existing["id"]." target network ".$existing["network"]." - new network: ".$item['network']);
```
Comment (nupplaphil) [inline src/Model/Item.php]: If possible, please fill the context array.

File: src/Model/Item.php [hunk 5]
```diff
@@ -1442,22 +1442,21 @@ public static function insert($item, $force_parent = false, $notify = false, $do
...
 
 		if (Contact::isBlocked($item["owner-id"])) {
-			Logger::log('Contact '.$item["owner-id"].' is blocked, item '.$item["uri"].' will not be stored');
+			Logger::notice('Contact '.$item["owner-id"].' is blocked, item '.$item["uri"].' will not be stored');
 			return 0;
 		}
 
 		if ($item['network'] == Protocol::PHANTOM) {
-			Logger::log('Missing network. Called by: '.System::callstack(), Logger::DEBUG);
+			Logger::notice('Missing network. Called by: '.System::callstack(), Logger::DEBUG);
```
Comment (nupplaphil) [inline src/Model/Item.php]: remove `Logger::DEBUG`

File: src/Model/Item.php [hunk 6]
```diff
@@ -1442,22 +1442,21 @@ public static function insert($item, $force_parent = false, $notify = false, $do
...
 
 			$item['network'] = Protocol::DFRN;
-			Logger::log("Set network to " . $item["network"] . " for " . $item["uri"], Logger::DEBUG);
+			Logger::notice("Set network to " . $item["network"] . " for " . $item["uri"], Logger::DEBUG);
```
Comment (nupplaphil) [inline src/Model/Item.php]: Remove `Logger::DEBUG`

File: src/Model/Item.php [hunk 7]
```diff
@@ -1432,7 +1432,7 @@ public static function insert($item, $force_parent = false, $notify = false, $do
 		$item['author-id'] = defaults($item, 'author-id', Contact::getIdForURL($item["author-link"], 0, false, $default));
 
 		if (Contact::isBlocked($item["author-id"])) {
-			Logger::log('Contact '.$item["author-id"].' is blocked, item '.$item["uri"].' will not be stored');
+			Logger::notice('Contact '.$item["author-id"].' is blocked, item '.$item["uri"].' will not be stored');
```
Comment (nupplaphil) [inline src/Model/Item.php]: If possible, please fill the context array.

File: src/Model/Item.php [hunk 8]
```diff
@@ -1442,22 +1442,21 @@ public static function insert($item, $force_parent = false, $notify = false, $do
 		$item['owner-id'] = defaults($item, 'owner-id', Contact::getIdForURL($item["owner-link"], 0, false, $default));
 
 		if (Contact::isBlocked($item["owner-id"])) {
-			Logger::log('Contact '.$item["owner-id"].' is blocked, item '.$item["uri"].' will not be stored');
+			Logger::notice('Contact '.$item["owner-id"].' is blocked, item '.$item["uri"].' will not be stored');
```
Comment (nupplaphil) [inline src/Model/Item.php]: If possible, please fill the context array.

File: src/Model/Item.php [hunk 9]
```diff
@@ -1442,22 +1442,21 @@ public static function insert($item, $force_parent = false, $notify = false, $do
...
-			Logger::log("Set network to " . $item["network"] . " for " . $item["uri"], Logger::DEBUG);
+			Logger::notice("Set network to " . $item["network"] . " for " . $item["uri"], Logger::DEBUG);
 		}
 
 		// Checking if there is already an item with the same guid
-		Logger::log('Checking for an item for user '.$item['uid'].' on network '.$item['network'].' with the guid '.$item['guid'], Logger::DEBUG);
 		$condition = ['guid' => $item['guid'], 'network' => $item['network'], 'uid' => $item['uid']];
 		if (self::exists($condition)) {
-			Logger::log('found item with guid '.$item['guid'].' for user '.$item['uid'].' on network '.$item['network'], Logger::DEBUG);
+			Logger::notice('Found already existing item with guid '.$item['guid'].' for user '.$item['uid'].' on network '.$item['network']);
```
Comment (nupplaphil) [inline src/Model/Item.php]: If possible, please fill the context array.

File: src/Model/Term.php [hunk 10]
```diff
@@ -6,32 +6,61 @@
 
 use Friendica\Core\System;
 use Friendica\Database\DBA;
+use Friendica\Util\Strings;
 
 class Term
```
Comment (nupplaphil) [inline src/Model/Term.php]: Missing phpdoc of the class itself and the meaning of the constants

File: src/Model/Term.php [hunk 11]
```diff
@@ -147,64 +201,73 @@ public static function insertFromTagFieldByItemId($itemid, $tags)
 					$term = substr($tag, 1);
 				}
 			} else { // This shouldn't happen
```
Comment (nupplaphil) [inline src/Model/Term.php]: If this shouldn't happen, maybe a additional `Logger::notice()` would be helpful?

File: src/Model/Term.php [hunk 12]
```diff
@@ -252,64 +315,82 @@ public static function populateTagsFromItem(&$item)
...
-			$author = ['uid' => 0, 'id' => $item['author-id'],
-				'network' => $item['author-network'], 'url' => $item['author-link']];
-
-			$prefix = '';
-			if ($tag['type'] == TERM_HASHTAG) {
-				$tag['url'] = Contact::magicLinkByContact($author, $tag['url']);
-				if ($orig_tag != $tag['url']) {
-					$item['body'] = str_replace($orig_tag, $tag['url'], $item['body']);
-				}
+			$prefix = self::TAG_CHARACTER[$tag['type']];
```
Comment (nupplaphil) [inline src/Model/Term.php]: Are you sure that there aren't any missmatchings `$tag['type']` and `self::TAG_CHARACTER[]`? Because this seems to possibly create PHP errors/notices.

File: src/Protocol/ActivityPub/Processor.php [hunk 13]
```diff
@@ -275,8 +275,8 @@ private static function postItem($activity, $item)
 	{
 		/// @todo What to do with $activity['context']?
 
-		if (($item['gravity'] != GRAVITY_PARENT) && !Item::exists(['uri' => $item['parent-uri']])) {
-			Logger::log('Parent ' . $item['parent-uri'] . ' not found, message will be discarded.', Logger::DEBUG);
+		if (($item['gravity'] != GRAVITY_PARENT) && !Item::exists(['uri' => $item['thr-parent']])) {
+			Logger::log('Parent ' . $item['thr-parent'] . ' not found, message will be discarded.', Logger::DEBUG);
```
Comment (nupplaphil) [inline src/Protocol/ActivityPub/Processor.php]: please change to `Logger::info()`

File: src/Database/DBA.php (hunk 2 above)
Comment (MrPetovan) [reply src/Database/DBA.php]: Maybe more of a warning.

File: src/Model/Term.php (hunk 12 above)
Comment (MrPetovan) [reply src/Model/Term.php]: The queried term types are narrowly defined in the `$taglist` DBA call, so I'm not worried about this.

File: src/Model/Term.php [hunk 14]
```diff
@@ -118,12 +183,12 @@ public static function insertFromTagFieldByItemId($itemid, $tags)
...
 				}
 
-				$tags[$match[1] . trim($match[3], ',.:;[]/\"?!')] = $match[2];
+				$tags[$match[2]] = $match[1] . trim($match[3], ',.:;[]/\"?!');
 			}
 		}
 
-		foreach ($tags as $tag => $link) {
-			if (substr(trim($tag), 0, 1) == '#') {
+		foreach ($tags as $link => $tag) {
```
Comment (annando) [inline src/Model/Term.php]: Was the change from ```$tags as $tag => $link``` to ```$tags as $link => $tag``` some kind of bugfix?

Comment (MrPetovan) [reply src/Model/Term.php]: Yep. If you had two tags with the same label, one of them would be overwritten. The correct unique key of this array is the tag link. You aren't supposed to have multiple tags pointing to the same URL, but you can have similar tag labels pointing to different URLs (like two accounts with the same display name on different servers).

**Comment by annando** [comment]
I don't understand this here:
> * Mentions (in general) in outgoing Pleroma messages aren't converted in the target format like we do for Mastodon.
How can Pleroma and Mastodon be different?

**Comment by MrPetovan** [comment]
As usual with those long-running tasks, I started before the RC, and separating the code refurbishment from the fixes would be even more expensive for me.

That said, I apologize in advance for #6732
