### PR TITLE
Use user-specific id to fetch the list of group appartenance in Module\Contact\Profile

### LINKED ISSUE #11029: Contacts cannot be added to groups
### Bug Description

As mentioned in #11021 currently I cannot add a contact to a contact group from the `/contact/ID` page. Instead a notification bubble pops up, that the contact was not found.

Adding them in the group management `/group` works.

### Platform Info

Friendica Version: 2021.12-dev dbcaf5192315d00f73c88d54e413c827fd31759b

Friendica Source: git

PHP version: 7.4

SQL version: mysql  Ver 15.1 Distrib 10.5.12-MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #11029 again

### CODE REVIEW

File: src/Module/Contact/Profile.php [hunk 1]
```diff
@@ -208,7 +208,7 @@ protected function content(array $request = []): string
 		$groups_widget = '';
 
 		if (!in_array($localRelationship->rel, [Contact::NOTHING, Contact::SELF])) {
-			$groups_widget = Group::sidebarWidget('contact', 'group', 'full', 'everyone', $contact['id']);
+			$groups_widget = Group::sidebarWidget('contact', 'group', 'full', 'everyone', $data['user']);
```
Comment (annando) [inline src/Module/Contact/Profile.php:211]: Wouldn't it be better to check for the existance of `$data['user']`?

Comment (MrPetovan) [reply src/Module/Contact/Profile.php:211]: The condition on line 210 implicitly ensures there's one.
