### PR TITLE
Replace remaining references to default banner image by `api.mastodon_banner` configuration value

### LINKED ISSUE #13355: Header Image
- [x] I have searched open and closed issues for duplicates

### Bug Description

With this entry in the `local.config.php` it should actually be possible to define an instance wide banner, which is then displayed e.g. at Mastodon.

```
        'api' => [
                // mastodon_banner (String)
                // Banner for Mastodon API
                'mastodon_banner' => '/images/banner.jpg',
        ]
```

In a profile where I have defined a banner via the API (Fedilab), this is also displayed. Only in the profiles where no banner was defined via the API, no banner is displayed, not even the default banner.

### Steps to Reproduce

1.  Define a banner in `local.config.php`
2.  Wait a little
3.  Log in to a Mastodon server and call up a profile of your Friendica instance.

#### Actual Result:

No banner will be displayed.

#### Expected Result:

The defined banner should be displayed.

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2023.09-dev - 1524

Friendica Source: git

PHP version: 8.2.9

### PR DESCRIPTION
**Pull request by MrPetovan**
- Ensure leading slash is present at every place the configuration value is used

Fix #13355

### CODE REVIEW

File: src/Model/Contact.php [hunk 1]
```diff
@@ -1899,13 +1899,7 @@ public static function getDefaultHeader(array $contact): string
...
 			case 'friendica':
 			case 'friendika':
-				/**
-				 * Picture credits
-				 * @author  Lostinlight <https://mastodon.xyz/@lightone>
-				 * @license CC0 https://creativecommons.org/share-your-work/public-domain/cc0/
-				 * @link    https://gitlab.com/lostinlight/per_aspera_ad_astra/-/blob/master/friendica-404/friendica-promo-bubbles.jpg
-				 */
-				$header = DI::baseUrl() . '/images/friendica-banner.jpg';
+				$header = DI::baseUrl() . '/' . ltrim(DI::config()->get('api', 'mastodon_banner'), '/');
```
Comment (annando) [inline src/Model/Contact.php]: Wouldn't be an idea to have a central function for fetching the value? I don't really like that the value is fetched and then the ltrim is executed each time at several places.

Comment (MrPetovan) [reply src/Model/Contact.php]: Sure, but I'm not sure where to put it yet.
