### PR TITLE
Replace reference to post plink by author base URL

### LINKED ISSUE #13367: Local community not accessible (WSOD)
- [x] I have searched open and closed issues for duplicates

### Steps to Reproduce

WSOD when calling the local community (/community/local) after today's pull. 

```
2023-08-21T15:44:52Z app [ERROR]: Uncaught Exception TypeError: "Friendica\Util\Network::isLocalLink(): Argument #1 ($url) must be of type string, null given, called in /var/www/html/friend/src/Object/Post.php on line 287" at /var/www/html/friend/src/Util/Network.php line 645
{"exception":"TypeError: Friendica\\Util\\Network::isLocalLink(): Argument #1 ($url) must be of type string, null given, called in /var/www/html/friend/src/Object/Post.php on line 287 and defined in /var/www/html/friend/src/Util/Network.php:645
Stack trace:
#0 /var/www/html/friend/src/Object/Post.php(287): Friendica\\Util\\Network::isLocalLink()
#1 /var/www/html/friend/src/Object/Thread.php(208): Friendica\\Object\\Post->getTemplateData()
#2 /var/www/html/friend/src/Content/Conversation.php(670): Friendica\\Object\\Thread->getTemplateData()
#3 /var/www/html/friend/src/Content/Conversation.php(568): Friendica\\Content\\Conversation->getThreadList()
#4 /var/www/html/friend/src/Module/Conversation/Community.php(160): Friendica\\Content\\Conversation->render()
#5 /var/www/html/friend/src/BaseModule.php(244): Friendica\\Module\\Conversation\\Community->content()
#6 /var/www/html/friend/src/App.php(707): Friendica\\BaseModule->run()
#7 /var/www/html/friend/index.php(55): Friendica\\App->runFrontend()
#8 {main}"} - {"file":null,"line":null,"function":null,"request-id":"64e386734dd2b","uid":"a9d8cb","process_id":1526}
```

grafik

### Platform Info

Friendica Version: dev

Friendica Source: git

PHP version: 8.0

SQL version: 10.3

### LINKED ISSUE #13378: click certain diaspora contact name --> white screen of death
### Bug Description

When I try to open the conversations page of a certain diaspora contact, I get a WSOD. 
Other contact links seem to work fine.

Actual Result:

`ERROR: app`

    Uncaught Exception TypeError: "Friendica\Util\Network::isLocalLink(): Argument #1 ($url) must be of type string, null given, called in /var/www/localhost/friendica/src/Object/Post.php on line 287" at /var/www/localhost/friendica/src/Util/Network.php line 645
        
more info:

    TypeError: Friendica\Util\Network::isLocalLink(): Argument #1 ($url) must be of type string, null given, called in /var/www/localhost/friendica/src/Object/Post.php on line 287 and defined in /var/www/localhost/friendica/src/Util/Network.php:645
    Stack trace:
    #0 /var/www/localhost/friendica/src/Object/Post.php(287): Friendica\Util\Network::isLocalLink()
    #1 /var/www/localhost/friendica/src/Object/Thread.php(208): Friendica\Object\Post->getTemplateData()
    #2 /var/www/localhost/friendica/src/Content/Conversation.php(670): Friendica\Object\Thread->getTemplateData()
    #3 /var/www/localhost/friendica/src/Content/Conversation.php(568): Friendica\Content\Conversation->getThreadList()
    #4 /var/www/localhost/friendica/src/Model/Contact.php(1634): Friendica\Content\Conversation->render()
    #5 /var/www/localhost/friendica/src/Module/Contact/Conversations.php(116): Friendica\Model\Contact::getPostsFromId()
    #6 /var/www/localhost/friendica/src/BaseModule.php(244): Friendica\Module\Contact\Conversations->content()
    #7 /var/www/localhost/friendica/src/App.php(707): Friendica\BaseModule->run()
    #8 /var/www/localhost/friendica/index.php(55): Friendica\App->runFrontend()
    #9 {main}

### Platform Info

Friendica Version:

Diese Friendica-Instanz verwendet die Version 2023.09-dev, sie ist unter der folgenden Adresse im Web zu finden https://boerdica.de. Die Datenbankversion ist 1528/1528 und die Post-Update-Version 1507/1507.

PHP 8.1.22 (cli) (built: Aug  3 2023 19:18:42) (NTS)

mysql  Ver 15.1 Distrib 10.11.4-MariaDB, for Linux (x86_64) using readline 5.1

### PR DESCRIPTION
**Pull request by MrPetovan**
Fix #13367

### CODE REVIEW

File: src/Object/Post.php [hunk 1]
```diff
@@ -284,7 +284,7 @@ public function getTemplateData(array $conv_responses, string $formSecurityToken
 				'label' => DI::l10n()->t('Report post'),
 				'href'  => 'moderation/report/create?' . http_build_query(['cid' => $item['author-id'], 'uri-ids' => [$item['uri-id']]]),
 			];
-			if (!Network::isLocalLink($item['plink'])) {
+			if (!empty($item['uri']) && !Network::isLocalLink($item['uri'])) {
```
Comment (annando) [inline src/Object/Post.php]: The URI does not always contain an HTTP address. I guess best would be to include the `baseurl` field from the contact in the view for the posts and to check that. We could then even use that field for the label.

Comment (MrPetovan) [reply src/Object/Post.php]: What is the "contact in the view for the posts" ?

Comment (annando) [reply src/Object/Post.php]: I suggest adding the `baseurl` here: https://github.com/friendica/friendica/blob/develop/static/dbview.config.php#L187

This can then also be used for the menu label.

Comment (MrPetovan) [reply src/Object/Post.php]: On both my nodes the `contact.baseurl` isn't consistently filled, same for `contact.gsid`. This also means it can't reliably be used for the Ignore Server menu label either.

Comment (annando) [reply src/Object/Post.php]: We can only block a server when we know the server. Also on my system only 4544 out of 3028402 contacts (ActivityPub as a network and not failed) don't have this field filled. My expectation is that the relationship will be similar on most systems.

**Comment by MrPetovan** [comment]
This is now ready.

**Comment by annando** [comment]
@MrPetovan I'm preparing some PR to improve the consistency with the `baseurl` and the `gsid`.

**Comment by MrPetovan** [comment]
Can you please merge this in the meantime? It's generating WSOD errors.

**Comment by annando** [comment]
Sorry, I'm away this weekend, so I'm only sometimes available.
