### PR TITLE
Harden /parseurl

### LINKED ISSUE #9929: External service interaction (HTTP & DNS)
**Hello Friendica Team.**

### Issue detail
I found a vulnerability issue while testing frendica locally.
It is possible to induce the application to perform server-side DNS lookups of arbitrary domain names and HTTP request.

### Bug Description
The ability to send requests to other systems can allow the vulnerable server to be used as an attack proxy. By submitting suitable payloads, an attacker can cause the application server to attack other systems that it can interact with. This may include public third-party systems, internal systems within the same organization, or services available on the local loopback adapter of the application server itself. Depending on the network architecture, this may expose highly vulnerable internal services that are not otherwise accessible to external attackers.

### Steps to Reproduce
**The request:**
```
GET /parse_url?binurl=73767274703267776f7375713063623539706668336f69366a78706e64632e62757270636f6c6c61626f7261746f722e6e6574&_=1613263595343 HTTP/1.1
Host: 192.168.0.3
Pragma: no-cache
Cache-Control: no-cache, no-transform
Connection: close
```
**The response:**
```
HTTP/1.1 200 OK
Date: Sun, 14 Feb 2021 03:02:34 GMT
Server: Apache/2.4.38 (Debian)
X-Powered-By: PHP/7.3.27
Set-Cookie: PHPSESSID=9f79e6ff0575a2775860501f03d5095b; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-Account-Management-Status: none
Vary: Accept-Encoding
Content-Length: 103
Connection: close
Content-Type: text/html; charset=UTF-8

[attachment type='link' url='http://svrtp2gwosuq0cb59pfh3oi6jxpndc.burpcollaborator.net'][/attachment]
```
**The DNS and HTTP request received:**
image

### More details
To make this request doesn't need to be authenticated, the friendica application accepts any request as an attachment and next do the DNS lookup and the HTTP request.

### Issue remediation
You should review the purpose and intended use of the relevant application functionality, and determine whether the ability to trigger arbitrary external service interactions is intended behavior. If so, you should be aware of the types of attacks that can be performed via this behavior and take appropriate measures. 
These measures might include blocking network access from the application server to other internal systems, and hardening the application server itself to remove any services available on the local loopback adapter. If the ability to trigger arbitrary external service interactions is not intended behavior, then you should implement a whitelist of permitted services and hosts, and block any interactions that do not appear on this whitelist.

### References

- [External service interaction (DNS)](https://portswigger.net/kb/issues/00300200_external-service-interaction-dns)
- [CWE-918: Server-Side Request Forgery (SSRF)](https://cwe.mitre.org/data/definitions/918.html)
- [CWE-406: Insufficient Control of Network Message Volume (Network Amplification)](https://cwe.mitre.org/data/definitions/406.html)

### Platform Info
This is Friendica, version 2021.01 that is running at the web location localhost
The database version is 1384/1384, the post update version is 1383/.

- Apache/2.4.38 (Debian)
-  PHP/7.3.27
- mysql  Ver 15.1 Distrib 10.5.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #9929 
Part of #4090

This PR drastically reduces the opportunity to use `/parseurl` for malicious purposes:
1. The module is now restricted to authenticated users.
2. The underlying site info is now cached from an hour to 3 months depending whether the call was a failure and if the response contains a specific `Cache-Control` value.

Relatedly, the `parsed_url` table now features an `expires` field for finer cache control and can now store native media URLs like images, video and audio files. Additionally, we don't truncate URLs to 255 characters anymore in this table, we hash them instead.

@annando The change of primary key on this table make it mandatory to truncate the table before the database update, can you please verify that I created the `pre_update` function correctly?

### CODE REVIEW

File: update.php [hunk 1]
```diff
@@ -817,3 +817,13 @@ function update_1400()
 
 	return Update::SUCCESS;
 }
+
+function pre_update_1402()
+{
+	// Necessary before a primary key change
+	if (!DBA::e("TRUNCATE TABLE `parsed_url`")) {
```
Comment (annando) [inline update.php]: I guess it would be better to use  `DROP TABLE`here.

File: database.sql [hunk 2]
```diff
@@ -959,13 +959,16 @@ CREATE TABLE IF NOT EXISTS `openwebauth-token` (
 -- TABLE parsed_url
 --
 CREATE TABLE IF NOT EXISTS `parsed_url` (
-	`url` varbinary(255) NOT NULL COMMENT 'page url',
+    `url-hash` char(64) NOT NULL COMMENT 'page url hash',
```
Comment (annando) [inline database.sql]: The `database.sql` doesn't fit to the `dbstructure.config.php`. It would be better to create it via the command line command `bin/console dbstructure dumpsql > database.sql`

File: static/dbstructure.config.php [hunk 3]
```diff
@@ -1019,15 +1019,18 @@
 	"parsed_url" => [
 		"comment" => "cache for 'parse_url' queries",
 		"fields" => [
-			"url" => ["type" => "varbinary(255)", "not null" => "1", "primary" => "1", "comment" => "page url"],
+			"url_hash" => ["type" => "char(64)", "not null" => "1", "primary" => "1", "comment" => "page url hash"],
```
Comment (annando) [inline static/dbstructure.config.php]: I would suggest using `BINARY` instead of `CHAR`. We don't need collation here. This would also reduce the key size and increase the fetch speed.

File: update.php (hunk 1 above)
Comment (MrPetovan) [reply update.php]: I tested the update successfully so I limited this query but it's fine with me as well.

File: database.sql (hunk 2 above)
Comment (MrPetovan) [reply database.sql]: I will never do that correctly because I'm not committing from my node machine, so I can't use this specific command in my PR and as such I need to edit the `database.sql` file by hand every time.

File: static/dbstructure.config.php (hunk 3 above)
Comment (MrPetovan) [reply static/dbstructure.config.php]: It is indeed a hexadecimal value, but does the comparison with strings still stands with a binary column?

Comment (annando) [reply static/dbstructure.config.php]: The `item-uri` table uses a `varbinary` for the `uri` and we can fetch and store it like a string.

The difference of the `binary` types vs. the `char` types is that a `binary(64)` stores 64 bytes, while a `char(64)` stores 64 characters - but since it has to support multi byte characters, it stores 4 bytes per character, so a `char(64)` stores 256 bytes.

In `char` the string `ABCD` is equal to `abcd` and a `ä` can be equal to an `a`, depending on your collation.

With a hash you don't need 4 byte unicode storage, you don't need support for umlauts, ...

File: src/Content/Text/BBCode.php [hunk 4]
```diff
@@ -2210,4 +2211,75 @@ public static function getShareOpeningTag(string $author, string $profile, strin
...
+		if (in_array($siteinfo['type'], ['image', 'video', 'audio'])) {
+			switch ($siteinfo['type']) {
+				case 'video':
+					$bbcode = "\n" . '[video]' . $url . '[/video]' . "\n";
+					break;
+				case 'audio':
+					$bbcode = "\n" . '[audio]' . $url . '[/audio]' . "\n";
+					break;
+				default:
+					$bbcode = "\n" . '[img]' . $url . '[/img]' . "\n";
```
Comment (annando) [inline src/Content/Text/BBCode.php:2268]: What about alternative text descriptions?

File: src/Util/ParseUrl.php [hunk 5]
```diff
@@ -65,18 +69,20 @@ class ParseUrl
...
 	 * @see   ParseUrl::getSiteinfo() for more information about scraping
 	 * embeddable content
 	 */
-	public static function getSiteinfoCached($url, $no_guessing = false, $do_oembed = true)
+	public static function getSiteinfoCached($url, $no_guessing = false, $do_oembed = true): array
 	{
-		if ($url == "") {
-			return false;
+		if (empty($url)) {
+			throw new HTTPException\InternalServerErrorException('URL parameter can\'t be empty');
```
Comment (annando) [inline src/Util/ParseUrl.php]: I'm not a huge fan of throwing an exception when the situation is recoverable. This function is also used for fetching additional information for feed items. So when a feed provided some empty value here, the fetching of the feed would fail - and since the worker job failed it would be repeated over and over again. Also the user wouldn't receive any new feed items from this source.

File: static/dbstructure.config.php (hunk 3 above)
Comment (MrPetovan) [reply static/dbstructure.config.php]: Ok, I just needed an assurance that I don't need to change my conditions.

File: src/Util/ParseUrl.php (hunk 5 above)
Comment (MrPetovan) [reply src/Util/ParseUrl.php]: It's about return type expectations. In the current state the method always returns an array, or throw an exception if the provided parameter is invalid. I can make sure the calling code doesn't provide an empty URL.

Comment (MrPetovan) [reply src/Util/ParseUrl.php]: Well, you won, now we return a dummy array when URL is empty.

**Comment by annando** [comment]
Concerning my last question: Can we scrape alternative text descriptions as well? And if so, we should provide this as well. Accessibility is something that I really take seriously.

**Comment by MrPetovan** [comment]
Sorry, I missed it earlier. At the spot where we create this image tag, there's no description available. Either it was provided along with a title and the `BBCode::embedURL` method returned earlier, or the siteinfo data determined the URL is an image file and there's no description to be gathered from it.

**Comment by annando** [comment]
Have you tried it on your machine?

**Comment by MrPetovan** [comment]
Yes, on my dev node.
