### PR TITLE
Fix Issue #2816 - Unable to save config items present in .htconfig.php but not in DB

### LINKED ISSUE #2816: [Admin] Unable to save config items present in .htconfig.php but not in DB
I was trying to set the default system theme in the Admin when I noticed that my selection was not remembered, while I could see other config changes being correctly saved.

It turns out the admin save action checks for the existence of a config value before trying to insert or update a row in the database. However, if a default value is defined in the `.htconfig.php` file, the config value will be considered to exist in the database, but the resulting `UPDATE` query will be unsuccessful because the record doesn't exist.

This issue can be averted by using the `REPLACE` query statement which create a record if it doesn't already exist in the table, or update the row if it exists. However, it relies on a `PRIMARY` or `UNIQUE` key, which would be on the couple of fields `config.cat` and `config.k`. There already is an index on those fields, but it's not set as `UNIQUE`.

I don't know how complicated it is to push a database migration change, and depending on the difficulty, I can propose an alternative fix which wouldn't rely on such a key by adding a simple existence check query before the `INSERT` or `UPDATE` query. Please note this wouldn't be ideal because it would significantly slow down the admin settings save action.

As a side note, the `.htconfig` header stating:

    /* *********************************************************************
     *  The configuration below will be overruled by the admin panel.
     *  Changes made below will only have an effect if the database does
     *  not contain any configuration for the friendica system.
     * *********************************************************************/

Is not exactly true at the moment, since any value present in the file but not in the DB cannot in fact be updated through the Admin Panel.

### PR DESCRIPTION
**Pull request by Hypolite**
- Change (P)Config::set to use INSERT >>> ON DUPLICATE KEY UPDATE
- Add DB update

Fixes #2816

### CODE REVIEW

**Comment by zotlabs** [comment]
If I'm not mistaken you will need to update the base schema so that new installs get the right schema. update.php is only run for changes made after installation. 

I'm also unclear this method (update.php) is used any more. If I recall, there's now a schema definition file and the database is modified to match the definition. Last time I tried this in Friendica a year or two ago, any updates I made in install/updates.php were reverted when the schema upgrade task ran; and were only retained if they went into the php schema definition array.  This is why I suggested asking @annando.

**Comment by Hypolite** [comment]
I also added a new command line option of dbstructure.php to show the queries that will be run during an update without executing them:

`$>php include/dbstructure.php dryrun`

**Comment by annando** [comment]
Have you checked which duplicates are removed? Hopefully it keeps the first entry and removes the later ones?

BTW: I really appreciate having the possibility for unique keys (and a hopefully safe way to create them on old data). There are some places in the database where this really makes sense.

**Comment by annando** [comment]
BTW: I just read this: http://dev.mysql.com/doc/refman/5.7/en/alter-table.html

> As of MySQL 5.7.4, the IGNORE clause for ALTER TABLE is removed and its use produces an error.

I'm not sure how Percona and MariaDB are handling this.

On this page the author showed some alternative ways: http://www.tocker.ca/2013/11/06/the-future-of-alter-ignore-table-syntax.html

File: boot.php [hunk 1]
```diff
@@ -38,7 +38,7 @@
 define ( 'FRIENDICA_CODENAME',     'Asparagus');
 define ( 'FRIENDICA_VERSION',      '3.5.1-dev' );
 define ( 'DFRN_PROTOCOL_VERSION',  '2.23'    );
-define ( 'DB_UPDATE_VERSION',      1203      );
```
Comment (annando) [inline boot.php]: Why have you used the version number 1210 and not 1204?

File: include/dbstructure.php [hunk 2]
```diff
@@ -176,7 +186,7 @@ function update_structure($verbose, $action, $tables=null, $definition=null) {
 				if ($current_index_definition != $new_index_definition && substr($indexname, 0, 6) != 'local_') {
 					$sql2=db_drop_index($indexname);
 					if ($sql3 == "")
-						$sql3 = "ALTER TABLE `".$name."` ".$sql2;
+						$sql3 = "ALTER IGNORE TABLE `".$name."` ".$sql2;
```
Comment (annando) [inline include/dbstructure.php]: See my comment concerning MySQL 5.7 which doesn't support this statement anymore. Either we check the version number here or we do it differently.

File: boot.php (hunk 1 above)
Comment (Hypolite) [inline boot.php]: I figured it was a big enough change to warrant a bigger bump.

**Comment by Hypolite** [comment]
> Have you checked which duplicates are removed? Hopefully it keeps the first entry and removes the later ones?

Yes I did and yes it does. 😄

> BTW: I really appreciate having the possibility for unique keys (and a hopefully safe way to create them on old data). There are some places in the database where this really makes sense.

Thanks, I appreciate it. I was pretty surprised when I saw that there was absolutely no UNIQUE index on the tables aside the PRIMARY keys.

>BTW: I just read this: http://dev.mysql.com/doc/refman/5.7/en/alter-table.html
>>As of MySQL 5.7.4, the IGNORE clause for ALTER TABLE is removed and its use produces an error.

This is bad ☹️

I used the `ALTER IGNORE TABLE` method because the Friendica DB structure update happens before the content updates. There's no way of running a content-altering SQL query before the DB structure update in the current system, so no technique based on running arbitrary queries before the UNIQUE index creation would work.

I have no easy solution to suggest, the ALTER IGNORE was the best worst solution to de-duplicate a database without running arbitrary queries before adding the index. 😕

**Comment by annando** [comment]
Concerning your surprise about the missing unique keys: Yeah, I was surprised as well. But I hadn't known that "alter table ignore" existed.

I could live with a solution that simply excludes more modern versions of mysql. (Could you check how MariaDB and Percona are behaving?)

**Comment by Hypolite** [comment]
MariaDB:
> When adding a UNIQUE index on a column (or a set of columns) which have duplicated values, an error will be produced and the statement will be stopped. To suppress the error and force the creation of UNIQUE indexes, discarding duplicates, the IGNORE option can be specified.

Percona:
> ALTER IGNORE does not normally work in Percona because of their InnoDB fast index creation feature but if you “set session old_alter_table=1″ beforehand, Percona will use the old alter table behavior.

Please note that we are already setting `old_alter_table=1` before upgrading the DB structure.

**Comment by annando** [comment]
Could you add the check for MySQL 5.7.4?

**Comment by Hypolite** [comment]
I can add the check, but what should it do? Prevent Friendica from installing at all? Removing the IGNORE keyword, disabling the duplicates removal on UNIQUE index creation?

**Comment by annando** [comment]
The check could just disable the "ignore" keyword. Then the user could hope that there isn't an entry that breaks it. Additionally we should place a note in the upgrade documentation that users with this SQL version had to manually check for duplicates before applying the update. (or after the database update failed)

In this documentation we could link to the hints from above so that the user could check the data. For example: On my system I haven't got a duplicate in config and pconfig. So hopefully this doesn't affect too much installations.

**Comment by annando** [comment]
I hove some development on my system that I want to make a pull request for. But it changes the database version number. So the question is if you could add the detection for the special mysql version soon or should I do my pull request now? In that case you had to increase your version number by one and you possibly are having some merge conflict.

**Comment by Hypolite** [comment]
Please, go forward with your merge, I can change the number again, no problem.

**Comment by Hypolite** [comment]
Aside note: where's the upgrade documentation located at?

**Comment by annando** [comment]
I guess @tobiasd knows the best location. I'm not so good in documentation.

File: include/dbstructure.php [hunk 3]
```diff
@@ -154,6 +158,19 @@ function update_structure($verbose, $action, $tables=null, $definition=null) {
...
 
+	// Ensure index conversion to unique removes duplicates
+	$sql_config = "SET session old_alter_table=1;";
+	if ($verbose)
+		echo $sql_config."\n";
+	if ($action)
+		@$db->q($sql_config);
+
+	// MySQL >= 5.7.4 doesn't support the IGNORE keyword in ALTER TABLE statements
+	if (version_compare($db->getdb()->server_info, '5.7.4') >= 0) {
```
Comment (annando) [inline include/dbstructure.php]: Theoretically we support the old mysql functionality as well (and not only mysqli). This would fail when mysqli wasn't used. Could you add a check for it? You could use the class variable $mysqli (boolean) for it.

**Comment by tobiasd** [comment]
> I guess @tobiasd knows the best location. I'm not so good in
> documentation.

Documentation should be done in `/doc` with translations in `/doc/$lng`, except for the README and the INSTALL which is actually done in two places, and the documentation for alternative server settings and the tools in `/util`.

**Comment by annando** [comment]
@tobiasd Question is where to write the special recommendations for upgrading to another version when using this version of MySQL. Where would you place that?

**Comment by tobiasd** [comment]
> @tobiasd Question is where to write the special recommendations for
> upgrading to another version when using this version of MySQL. Where
> would you place that?

Why not `/doc/upgrade.md` which then can be linked from the release notes and the doc home, and referenced from the INSTALL file(s).

**Comment by Hypolite** [comment]
I added the backward compatibility for the deprecated MySQL API, I still have the doc to write.

File: include/dba.php [hunk 4]
```diff
@@ -91,6 +91,22 @@ public function getdb() {
 		return $this->db;
 	}
 
+	/** Returns the MySQL server version string
```
Comment (rabuzarus) [inline include/dba.php]: the description needs to be a line below and with `@brief`

Comment (Hypolite) [inline include/dba.php]: According to the Doxygen docs, the @brief description can be set on the opening tag line without the "@brief" mention. Is it another implicit convention for documentation?

Comment (rabuzarus) [inline include/dba.php]: yes this is possible but just for consistency (with the other doxygen headers in friendica) it would be nice if you could change it to
```
/**
 * @brief Returns the MySQL server version string
```

Comment (Hypolite) [inline include/dba.php]: I definitely can and I will.

File: boot.php [hunk 5]
```diff
@@ -38,7 +38,7 @@
...
+define ( 'DB_UPDATE_VERSION',      1204      );
```
Comment (annando) [inline boot.php]: I was faster with my pull request. You now have to use the 1205.

File: include/dba.php (hunk 4 above)
Comment (annando) [inline include/dba.php]: I think that once you added this small change, we finally can merge it. Hooray :-)

**Comment by Hypolite** [comment]
You're killing me >.<

File: include/dba.php (hunk 4 above)
Comment (annando) [inline include/dba.php]: Greetings from Mr Nitpicker: Could you add this little "brief" parameter? ;-)

Comment (Hypolite) [inline include/dba.php]: Ha ha, usually it's @rabuzarus with the notice. It's done 😉
