### PR TITLE
Avoid lock problems, fix foreign key problems with contact-relation

### LINKED ISSUE #9881: DB Error 1452 – Cannot add or update a child row: a foreign key constraint fails
- [X] I have searched open and closed issues for duplicates

### Bug Description
Had a look at possible DB errors after the latest structure changes and found pretty much of these...

```
2021-01-29T23:59:57Z worker [ERROR]: DB Error {"code":1452,"error":"Cannot add or update a child row: a foreign key constraint fails (`friendica`.`contact-relation`, CONSTRAINT `contact-relation_ibfk_2` FOREIGN KEY (`relation-cid`) REFERENCES `contact` (`id`) ON DELETE CASCADE)","callstack":"DBA::insert, Relation::discoverByUrl, ContactDiscovery::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"INSERT INTO `contact-relation` (`cid`, `relation-cid`, `follows`, `follow-updated`) VALUES (425934, 1803115, 1, '2021-01-29 23:59:57') ON DUPLICATE KEY UPDATE `cid` = 425934, `relation-cid` = 1803115, `follows` = 1, `follow-updated` = '2021-01-29 23:59:57'"} - {"file":"Database.php","line":765,"function":"e","uid":"a5fb1d","process_id":819210}
2021-01-29T23:59:57Z worker [ERROR]: DB Error {"code":1452,"error":"Cannot add or update a child row: a foreign key constraint fails (`friendica`.`contact-relation`, CONSTRAINT `contact-relation_ibfk_1` FOREIGN KEY (`cid`) REFERENCES `contact` (`id`) ON DELETE CASCADE)","callstack":"DBA::insert, Relation::discoverByUrl, ContactDiscovery::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"INSERT INTO `contact-relation` (`cid`, `relation-cid`, `follows`, `follow-updated`) VALUES (1803115, 425934, 1, '2021-01-29 23:59:57') ON DUPLICATE KEY UPDATE `cid` = 1803115, `relation-cid` = 425934, `follows` = 1, `follow-updated` = '2021-01-29 23:59:57'"} - {"file":"Database.php","line":765,"function":"e","uid":"a5fb1d","process_id":819210}
```

### Platform Info

Friendica Version:
2021.03-dev - 1395

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

### PR DESCRIPTION
**Pull request by annando**
This should finally fix #9881. Also this hopefully should reduce lock conflicts while expiring posts.

### CODE REVIEW

File: src/Worker/ExpirePosts.php [hunk 1]
```diff
@@ -46,54 +45,54 @@ public static function execute()
...
-							WHERE `uri-id` = `post-thread`.`uri-id`)
-						AND NOT `uri-id` IN (SELECT `uri-id` FROM `post-media`
-							WHERE `uri-id` = `post-thread`.`uri-id`)
-						AND NOT `uri-id` IN (SELECT `parent-uri-id` FROM `post-user` INNER JOIN `contact` ON `contact`.`id` = `contact-id` AND `notify_new_posts`
-							WHERE `parent-uri-id` = `post-thread`.`uri-id`)
-						AND NOT `uri-id` IN (SELECT `parent-uri-id` FROM `post-user`
-							WHERE (`origin` OR `event-id` != 0 OR `post-type` = ?) AND `parent-uri-id` = `post-thread`.`uri-id`)
-						AND NOT `uri-id` IN (SELECT `uri-id` FROM `post-content`
-							WHERE `resource-id` != 0 AND `uri-id` = `post-thread`.`uri-id`))
-					ORDER BY `id` LIMIT ?", $expire_days, Item::PT_PERSONAL_NOTE, $limit);
```
Comment (MrPetovan) [inline src/Worker/ExpirePosts.php:65]: Is `$limit` still used in this method?

Comment (annando) [reply src/Worker/ExpirePosts.php:65]: Only in a way to control whether an expiry should be done at all.

**Review by MrPetovan — APPROVED** [review]

**Comment by tobiasd** [comment]
I've changed the target of this PR to be 2021.03-rc. Just in case this is unwanted, please redirect it do develop ;-)
