### PR TITLE
Curl result tests

### LINKED ISSUE #5886: CurlResult current header regex
https://github.com/friendica/friendica/blob/71a60c5f66bd1f3f71e908241db711f5e4e1088d/src/Network/CurlResult.php#L122
I get errors in my test at the line showed above.

The error is gone when changing
```php
/^HTTP\/[1-2].+? [1-5][0-9][0-9]/
```
to
```php
/^HTTP\/[1-2].+?[1-5][0-9][0-9]/
``` 

I searched in the commits and found that exactly this regex is used for years. So before making any (maybe wrong) conclusions, I want to ask if somebody can see, if the whitespace does or doesn't matter (normaly in regex everything matters ;-) ).

I also made a online test:
works: https://www.phpliveregex.com/p/pxt
doesn't work: https://www.phpliveregex.com/p/pxu

What do you say?

### PR DESCRIPTION
**Pull request by nupplaphil**
Fixes #5886 

FollowUp #5878

### CODE REVIEW

File: tests/src/Network/CurlResultTest.php [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+		]);
+
+		$this->assertTrue($curlResult->isSuccess());
+		$this->assertFalse($curlResult->isTimeout());
+		$this->assertTrue($curlResult->isRedirectUrl());
+		$this->assertSame($header, $curlResult->getHeader());
+		$this->assertSame($body, $curlResult->getBody());
+		$this->assertSame('text/html; charset=utf-8', $curlResult->getContentType());
+		$this->assertSame('https://test.local/test/it', $curlResult->getUrl());
+		$this->assertSame('https://test.other/test/it', $curlResult->getRedirectUrl());
```
Comment (MrPetovan) [inline tests/src/Network/CurlResultTest.php]: How is the final redirect URL different from the one you fed it? Why is the old URL path arbitrarily slapped on top of it?

Comment (nupplaphil) [reply tests/src/Network/CurlResultTest.php]: it redirects from `https://test.**local**` to `https://test.**other**`

the path is because of 
https://github.com/friendica/friendica/blob/fc19373ec4d167933255d48fa58771127f8b4c9a/src/Network/CurlResult.php#L162-L164

Comment (MrPetovan) [reply tests/src/Network/CurlResultTest.php]: But wouldn't the redirect URL be a fully-qualified one including path? Why do you assume that if there's no path it should be the previous URL path?

Comment (nupplaphil) [reply tests/src/Network/CurlResultTest.php]: To be honest, it was in the original code which I moved to the check.

I thought it's a fallback for a miss-configured server. It doesn't work for Redirects in the header too, so it's just half the way ;-)

Comment (MrPetovan) [reply tests/src/Network/CurlResultTest.php]: Fair enough.
