### PR TITLE
Issue 14879: Fix activity trust check

### LINKED ISSUE #14879: Friend requests no longer come through
- [X] I have searched open and closed issues for duplicates

### Bug Description

I am not sure when it started happening but my server (current develop) doesn't process incoming contact requests anymore. Someone from another server tries to add someone from my server and nothing happens. The target user on my server gets no notification or request. The rest seems to work - comments can be exchanged, outgoing friend requests work as intended but incoming friend requests silently fail.

### Steps to Reproduce

1.  I made a test account at social.vivaldi.net
2.  I add myself from that account
3.  Nothing happens

No errors but here is the log capture (grepped by remote server and I kept entire log too):

```
2025-04-09T16:45:46Z app [DEBUG]: Request received {"address":"46.22.99.207","request":"POST /inbox/shuro HTTP/1.1","referer":"","user-agent":"Mastodon/4.3.7+vivaldimod (http.rb/5.2.0; +https://social.vivaldi.net/)"} - {"file":"App.php","line":438,"function":"runFrontend","request-id":"67f6a43ae722a","stack":"App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:46Z app [INFO]: Set inbox status to success {"inbox":"https://social.vivaldi.net/users/shuromuro/inbox"} - {"file":"APContact.php","line":569,"function":"unmarkForArchival","request-id":"67f6a43ae722a","stack":"APContact::unmarkForArchival (102), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:46Z app [INFO]: Set shared inbox status to success {"sharedinbox":"https://social.vivaldi.net/inbox"} - {"file":"APContact.php","line":573,"function":"unmarkForArchival","request-id":"67f6a43ae722a","stack":"APContact::unmarkForArchival (102), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:46Z app [INFO]: Taking key from id {"id":"https://social.vivaldi.net/users/shuromuro#main-key"} - {"file":"HTTPSignature.php","line":825,"function":"fetchKey","request-id":"67f6a43ae722a","stack":"HTTPSignature::fetchKey (710), HTTPSignature::getSigner (112), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:46Z app [INFO]: Valid HTTP signature {"signer":"https://social.vivaldi.net/users/shuromuro"} - {"file":"Receiver.php","line":120,"function":"processInbox","request-id":"67f6a43ae722a","stack":"Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:46Z app [INFO]: Message for user 7 is from actor https://social.vivaldi.net/users/shuromuro [] - {"file":"Receiver.php","line":124,"function":"processInbox","request-id":"67f6a43ae722a","stack":"Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:46Z app [DEBUG]: Request start. {"url":"https://social.vivaldi.net/9464e5dd-374a-46c4-abf7-d857b77aa26e","method":"get"} - {"file":"HttpClient.php","line":60,"function":"request","request-id":"67f6a43ae722a","stack":"HttpClient::request (203), HttpClient::get (573), HTTPSignature::fetchRaw (479), HTTPSignature::fetch (1603), Processor::fetchCachedActivity (327), Receiver::prepareObjectData (680), Receiver::processActivity (156), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:47Z app [DEBUG]: http request config. {"url":"https://social.vivaldi.net/9464e5dd-374a-46c4-abf7-d857b77aa26e","method":"get","options":{"headers":{"User-Agent":"Friendica/2025.02-dev DatabaseVersion/1580 Request/ActivityPub/1 +https://friends.deko.cloud","Date":"Wed, 09 Apr 2025 16:45:46 GMT","Host":"social.vivaldi.net","Signature":"keyId=\"https://friends.deko.cloud/profile/shuro#main-key\",algorithm=\"rsa-sha256\",headers=\"(request-target) date host\",signature=\"uJgaAdOAuBpPEqAWDilKhjoHEfGmCetl3KU7P6be7sGaP86Dp7af9VuI68VSh+h3aYiuTYDRuvp+o32mkf4C5D4iM74UpZCekYrSinDdZYZu7XSMCMMF6dCkoOjkYHizqwvhRazbBqPA1neWKKcNPaWS0QlWTxOkusxvWbK22VXgOkqbRpjmvtFF3mmFAVzRoxZcVw/JEQ9QCvTployY3ZiTTfQSApxxQjubD3pwBTg50gBxiq00hPZXpWgVglZpiK4u8rt74lIc8Tk4e+p4hb0QusbHg4yEyeb8GuJVe5RucTvzI9kD28WPzXmegXtiGqUXWCl8TLEIkJ48VMiVFukFggB97xOkJqCL7ZG6qwu8fLThqhErA14rp1cm06S7fGXNXA7VpRcoLFnNUNPbeMkjUGGk60egmFUBrJtTG+7/a1tiZq2YW8N1t++UbH+Csw5XJFL05dod2R7ajKfYGwCpRVfTqU2B2XzgL3L80LRubSiCGSLXVtM7j6NW7qErgEVqKX3Cy8AM9UY+1qjG24AH4Wj+cVlQQZtOtEQR+TM5A5cGK/F6jqGIlc9DWQd7cHwawKKb27/0NbmGPxjTV0DCHWcDBQy1d8a8VcK6X3HlhLx8SlF0N6EOH1MIK/NReUR2vsy79USrwQBfOjvBLYKjX0hZhX0FkQmiW6au6wc=\"","Accept":["application/activity+json, application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\""]},"on_headers":{},"sink":"/tmp/friends.deko.cloud/http-eTYEmj"}} - {"file":"HttpClient.php","line":165,"function":"request","request-id":"67f6a43ae722a","stack":"HttpClient::request (203), HttpClient::get (573), HTTPSignature::fetchRaw (479), HTTPSignature::fetch (1603), Processor::fetchCachedActivity (327), Receiver::prepareObjectData (680), Receiver::processActivity (156), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:47Z app [DEBUG]: debug {"info":{"Date":["Wed, 09 Apr 2025 16:45:47 GMT"],"Content-Type":["application/json; charset=utf-8"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"vary":["Accept-Encoding","Accept"],"x-frame-options":["DENY"],"x-content-type-options":["nosniff"],"x-xss-protection":["0"],"referrer-policy":["same-origin"],"Cache-Control":["private, no-store"],"content-security-policy":["base-uri 'none'; default-src 'none'; frame-ancestors 'none'; font-src 'self' https://social-cdn.vivaldi.net; img-src 'self' data: blob: https://social-cdn.vivaldi.net; style-src 'self' https://social-cdn.vivaldi.net 'nonce-/s8Qa3oEWU1kHsiUcAIyPQ=='; media-src 'self' data: https://social-cdn.vivaldi.net; manifest-src 'self' https://social-cdn.vivaldi.net; form-action 'self' https://login.vivaldi.net/oauth2/authorize; child-src 'self' blob: https://social-cdn.vivaldi.net; worker-src 'self' blob: https://social-cdn.vivaldi.net; connect-src 'self' data: blob: https://social-cdn.vivaldi.net wss://social.vivaldi.net; script-src 'self' https://social-cdn.vivaldi.net 'wasm-unsafe-eval'; frame-src 'self' https:"],"x-request-id":["6a89d9ad-f7bd-45dd-af33-57462656b012"],"x-runtime":["0.011151"],"strict-transport-security":["max-age=63072000; includeSubDomains"],"cf-cache-status":["DYNAMIC"],"Server":["cloudflare"],"CF-RAY":["92db7a116edf1e5a-FRA"]}} - {"file":"GuzzleResponse.php","line":68,"function":"checkSuccess","request-id":"67f6a43ae722a","stack":"GuzzleResponse::checkSuccess (53), GuzzleResponse::__construct (168), HttpClient::request (203), HttpClient::get (573), HTTPSignature::fetchRaw (479), HTTPSignature::fetch (1603), Processor::fetchCachedActivity (327), Receiver::prepareObjectData (680), Receiver::processActivity (156), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:47Z app [DEBUG]: Request stop. {"url":"https://social.vivaldi.net/9464e5dd-374a-46c4-abf7-d857b77aa26e","method":"get"} - {"file":"HttpClient.php","line":183,"function":"request","request-id":"67f6a43ae722a","stack":"HttpClient::request (203), HttpClient::get (573), HTTPSignature::fetchRaw (479), HTTPSignature::fetch (1603), Processor::fetchCachedActivity (327), Receiver::prepareObjectData (680), Receiver::processActivity (156), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:47Z app [INFO]: Fetched for user 7 from https://social.vivaldi.net/9464e5dd-374a-46c4-abf7-d857b77aa26e returned 404 [] - {"file":"HTTPSignature.php","line":577,"function":"fetchRaw","request-id":"67f6a43ae722a","stack":"HTTPSignature::fetchRaw (479), HTTPSignature::fetch (1603), Processor::fetchCachedActivity (327), Receiver::prepareObjectData (680), Receiver::processActivity (156), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:47Z app [DEBUG]: Fetching was unsuccessful {"url":"https://social.vivaldi.net/9464e5dd-374a-46c4-abf7-d857b77aa26e","return-code":"404","error-number":0,"error":""} - {"file":"HTTPSignature.php","line":486,"function":"fetch","request-id":"67f6a43ae722a","stack":"HTTPSignature::fetch (1603), Processor::fetchCachedActivity (327), Receiver::prepareObjectData (680), Receiver::processActivity (156), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:47Z app [NOTICE]: Activity was not fetchable, aborting. {"url":"https://social.vivaldi.net/9464e5dd-374a-46c4-abf7-d857b77aa26e","uid":7} - {"file":"Processor.php","line":1610,"function":"fetchCachedActivity","request-id":"67f6a43ae722a","stack":"Processor::fetchCachedActivity (327), Receiver::prepareObjectData (680), Receiver::processActivity (156), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:47Z app [INFO]: Activity could not been fetched {"id":"https://social.vivaldi.net/9464e5dd-374a-46c4-abf7-d857b77aa26e"} - {"file":"Receiver.php","line":348,"function":"prepareObjectData","request-id":"67f6a43ae722a","stack":"Receiver::prepareObjectData (680), Receiver::processActivity (156), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:47Z app [INFO]: Got actor and followers {"actor":"https://social.vivaldi.net/users/shuromuro","followers":"https://social.vivaldi.net/users/shuromuro/followers"} - {"file":"Receiver.php","line":1188,"function":"getReceivers","request-id":"67f6a43ae722a","stack":"Receiver::getReceivers (361), Receiver::prepareObjectData (680), Receiver::processActivity (156), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:47Z app [NOTICE]: Post has got no receivers {"fetch_unlisted":false,"actor":"https://social.vivaldi.net/users/shuromuro","id":"https://social.vivaldi.net/9464e5dd-374a-46c4-abf7-d857b77aa26e","type":"as:Follow"} - {"file":"Receiver.php","line":1313,"function":"getReceivers","request-id":"67f6a43ae722a","stack":"Receiver::getReceivers (361), Receiver::prepareObjectData (680), Receiver::processActivity (156), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:47Z app [INFO]: Processing {"type":"as:Follow","object_type":"as:Person","id":"https://social.vivaldi.net/9464e5dd-374a-46c4-abf7-d857b77aa26e","actor":"https://social.vivaldi.net/users/shuromuro","platform":"mastodon"} - {"file":"Receiver.php","line":500,"function":"prepareObjectData","request-id":"67f6a43ae722a","stack":"Receiver::prepareObjectData (680), Receiver::processActivity (156), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:47Z app [INFO]: Activity trust could not be achieved. {"id":"https://friends.deko.cloud/profile/shuro","type":"as:Follow","signer":["https://social.vivaldi.net/users/shuromuro"],"actor":"https://social.vivaldi.net/users/shuromuro","attributedTo":null} - {"file":"Receiver.php","line":737,"function":"processActivity","request-id":"67f6a43ae722a","stack":"Receiver::processActivity (156), Receiver::processInbox (94), Inbox::post (231), BaseModule::run (96), BaseApi::run (30), Inbox::run (588), App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
2025-04-09T16:45:47Z app [DEBUG]: Request processed with exception {"response":202,"address":"46.22.99.207","request":"POST /inbox/shuro HTTP/1.1","referer":"","user-agent":"Mastodon/4.3.7+vivaldimod (http.rb/5.2.0; +https://social.vivaldi.net/)","duration":"0.271"} - {"file":"App.php","line":600,"function":"runFrontend","request-id":"67f6a43ae722a","stack":"App::runFrontend (191), App::processRequest (22)","uid":"7d079e","process_id":1376497}
```

### PR DESCRIPTION
**Pull request by annando**
Fixes #14879

### CODE REVIEW

File: src/Protocol/ActivityPub/Receiver.php [hunk 1]
```diff
@@ -644,16 +644,19 @@ public static function processActivity(array $activity, string $body = '', int $
 				return true;
 			}
 		} else {
-			$attributed_to = '';
+			$attributed_to = null;
 		}
 
 		// Test the provided signatures against the actor and "attributedTo"
 		if ($trust_source) {
-			if ($attributed_to !== false && $attributed_to !== '') {
```
Comment (nupplaphil) [inline src/Protocol/ActivityPub/Receiver.php:652]: can we learn something about my recent discussion with @art4 about "loose checks" and "more robust and precise checks" found here https://github.com/friendica/friendica/pull/14913#discussion_r2095000214 ?

why do we need to explicitly set a string variable to null, just to check it later with a loose check? Wouldn't it be better to have a meaningful flag instead?

**Review by nupplaphil — CHANGES_REQUESTED** [review]

File: src/Protocol/ActivityPub/Receiver.php (hunk 1 above)
Comment (annando) [reply src/Protocol/ActivityPub/Receiver.php:652]: The variable `$attributed_to` is fetched from the ActivityPub message. And when the message doesn't contain the variable `attributedTo`, then the variable `$attributed_to` is set to `null` - which is totally correct, I think.

File: src/Protocol/ActivityPub/Receiver.php [hunk 2]
```diff
@@ -644,16 +644,19 @@ public static function processActivity(array $activity, string $body = '', int $
...
+			if (!is_null($attributed_to)) {
```
Comment (Art4) [inline src/Protocol/ActivityPub/Receiver.php:652]: Because of `JsonLD::fetchElement(): string|null` the `$attributed_to` variable could only contain `string|null`. The previous check for this variable was changed in commit 5772c7021689c018d7d3fd1b77a32ef7ebb3aefe:

```diff
-			if (!empty($attributed_to) && $actor !== null) {
+			if ($attributed_to !== false && $attributed_to !== '') {
```

The comparison with `!== false` is obviously wrong, but an empty string would also be `empty`. So my suggestion would be:

```suggestion
			if ($attributed_to !== null && $attributed_to !== '') {
```

Comment (annando) [reply src/Protocol/ActivityPub/Receiver.php:652]: We have to cover two scenarios: One is a message type that contains `attributedTo` and one that doesn't. Should a message contain `attributedTo` but had it set to '', then this was intentional. Also we would then try to refetch the item - and possibly fetch a valid item.

Comment (Art4) [reply src/Protocol/ActivityPub/Receiver.php:652]: Very important point. 👍 We should add a comment about this, maybe in `JsonLD::fetchElement()`. There we should also make sure that the method only returns `string|null`.

Comment (annando) [reply src/Protocol/ActivityPub/Receiver.php:652]: The function `fetchElement` can return multiple types, it can be integer as well or any other type that JSON supports.

Comment (Art4) [reply src/Protocol/ActivityPub/Receiver.php:652]: Then we should fix the `@return` in the phpdoc for `JsonLD::fetchElement()` as well.

Comment (annando) [reply src/Protocol/ActivityPub/Receiver.php:652]: What should be the appropriate value for "any type and null"?

Comment (Art4) [reply src/Protocol/ActivityPub/Receiver.php:652]: `@return mixed|null The value or null if not set`

Comment (annando) [reply src/Protocol/ActivityPub/Receiver.php:652]: Is changed
