### PR TITLE
proxy_url: Fix extension extraction for URLs containing a . after a ? redux

### LINKED ISSUE #3017: Diaspora: Proxyfied images don't play well with Camo
[Camo](https://github.com/atmos/camo) is the image proxy Diaspora chose to circumvent mixed-content warning on HTTPS pods with remote HTTP images. However, it requires that the original URL to be proxyfied correctly set the Content-Type header.

Friendica's `proxy` mod is basically doing the same, except it doesn't keep the Content-Type after the original URL is proxyfied, which leads Camo to refuse to serve it.

Friendica's `proxy` should keep the original Content-Type when serving the requested URL.

Reference thread: https://friendica.mrpetovan.com/display/748ab390a558013435ef52540061b601

### PR DESCRIPTION
**Pull request by Hypolite**
Follow-up to #3030.

Fixes #3017

And also definitively converts `mod/proxy.php` to standards compliance.

### CODE REVIEW

File: mod/proxy.php [hunk 1]
```diff
@@ -24,160 +22,170 @@ function proxy_init() {
...
 	$size = 1024;
-	$sizetype = "";
+	$sizetype = '';
 	$basepath = $a->get_basepath();
 
 	// If the cache path isn't there, try to create it
-	if (!is_dir($basepath."/proxy"))
-		if (is_writable($basepath))
-			mkdir($basepath."/proxy");
+	if (!is_dir($basepath . '/proxy') AND is_writable($basepath)) {
```
Comment (Quix0r) [inline mod/proxy.php]: Nice you found these.
