### PR TITLE
issue 9996: "bd" cannot be ""

### LINKED ISSUE #9996: DB Error 1525
- [X] I have searched open and closed issues for duplicates

### Bug Description

I was asked to submit my database errors [here by Michael Vogel](https://pirati.ca/display/ec054ce7-7760-224c-d426-08d369931464?owt=2d4546f4deb077df2ad1afb9455448f6). I can't really explain them, or what goes wrong, but was told the errors themselves contain all the needed information, so here it goes:

```2021-03-07T01:02:52Z worker [ERROR]: DB Error {"code":1525,"error":"Incorrect DATE value: ''","callstack":"DBA::select, Contact::updateBirthdays, UpdateContactBirthdays::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"SELECT `id`, `uid`, `name`, `url`, `bd` FROM `contact` WHERE (`bd` != \"\" AND `bd` > \"0001-01-01\" AND SUBSTRING(`bd`, 1, 4) != `bdyear` AND (`contact`.`rel` = 2 OR `contact`.`rel` = 3) AND NOT `contact`.`pending` AND NOT `contact`.`hidden` AND NOT `contact`.`blocked` AND NOT `contact`.`archive` AND NOT `contact`.`deleted`)"} - {"file":"Database.php","line":662,"function":"p","uid":"ff32b0","process_id":3711}```

### Platform Info

Friendica Version:

Friendica Source: Friendica 'Red Hot Poker' 2021.03-dev - 1406

PHP version: 7.4.3

SQL version: 8.0.23

### PR DESCRIPTION
**Pull request by annando**
Fixes #9996

The field "bd" is a date field. MySQL is right about complaining that "" is no valid value.

### CODE REVIEW

File: src/Model/Contact.php [hunk 1]
```diff
@@ -2579,9 +2579,7 @@ public static function removeSharer($importer, $contact, array $datarray = [], $
 	public static function updateBirthdays()
 	{
 		$condition = [
-			'`bd` != ""
-			AND `bd` > "0001-01-01"
-			AND SUBSTRING(`bd`, 1, 4) != `bdyear`
+			'`bd` > "0001-01-01"
```
Comment (MrPetovan) [inline src/Model/Contact.php]: Should we use one of our nifty constants?

Comment (annando) [reply src/Model/Contact.php]: Done

**Review by MrPetovan — APPROVED** [review]
