### PR TITLE
Fix item.private value in Model\Event::getItemArrayForId

### LINKED ISSUE #13240: Calendar events are visible to people they are not shared with
- [X] I have searched open and closed issues for duplicates

### Bug Description

Calendar event shared with limited number of people appears in other people's fediverse feed.

### Steps to Reproduce

1.  Create a calendar event
2.  On permissions tab, set to show to one person
3.  View timeline of someone who is following the user that created the calendar event

Actual Result:

Calendar event appears in fediverse feed of person that is following user

Expected Result:

Calendar event should only appear in feed of person that it is to be shown to

### Screenshots

Sharing with one person - event details
Creating event

Sharing with one person - permissions
Setting permissions - only visible to one person

Sharing with one person - event visible on Mastodon
Event is visible on another person's Mastodon feed

### Platform Info

Friendica Version: 
This is Friendica, version 2023.05 that is running at the web location https://social.justec.co.uk. The database version is 1518/1518, the post update version is 1507/1507.

Friendica Source: 

PHP version: PHP 7.4.33

SQL version: 10.5.19-MariaDB-0+deb11u2 - Debian 11

### PR DESCRIPTION
**Pull request by MrPetovan**
Fix #13240 

- The `$event` array doesn't have a `private` key because the event table doesn't have a `private` field.

### CODE REVIEW

File: src/Model/Event.php [hunk 1]
```diff
@@ -344,7 +344,6 @@ public static function getItemArrayForId(int $event_id, array $item = []): array
 		$event['id'] = $event_id;
 
 		$item['uid']           = $event['uid'];
-		$item['contact-id']    = $event['cid'];
```
Comment (annando) [inline src/Model/Event.php:347]: Why is it removed?

File: src/Model/Event.php [hunk 2]
```diff
@@ -363,11 +362,10 @@ public static function getItemArrayForId(int $event_id, array $item = []): array
 		$item['allow_gid']     = $event['allow_gid'];
 		$item['deny_cid']      = $event['deny_cid'];
 		$item['deny_gid']      = $event['deny_gid'];
-		$item['private']       = intval($event['private'] ?? 0);
+		$item['private']       = $event['allow_cid'] && $event['allow_gid'] && $event['deny_cid'] && $event['deny_gid'] ? 0 : 1;
 		$item['visible']       = 1;
 		$item['verb']          = Activity::POST;
 		$item['object-type']   = Activity\ObjectType::EVENT;
-		$item['post-type']     = Item::PT_EVENT;
```
Comment (annando) [inline src/Model/Event.php:370]: Why is this removed?

**Review by annando — COMMENTED** [review]
Just some questions.

File: src/Model/Event.php (hunk 1 above)
Comment (MrPetovan) [reply src/Model/Event.php:347]: Array key is duplicated in the same block.

File: src/Model/Event.php (hunk 2 above)
Comment (MrPetovan) [reply src/Model/Event.php:370]: Array key is duplicated in the same block.
