### PR TITLE
Fix  processing of incoming Diaspora messages

### LINKED ISSUE #11751: Diaspora and RSS seems to be broken
- [X ] I have searched open and closed issues for duplicates

### Bug Description
I don't receive any posts from Diaspora since 2 days. 
Also, I just noticed that I don't get any RSS posts anymore. The RSS contacts are gone.

Just a quick emergency report w/o details. I can provide them if needed.
 
### Platform Info

Friendica Version:
2022.09-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

### PR DESCRIPTION
**Pull request by annando**
This PR restores the original functionality.

### CODE REVIEW

File: src/Util/XML.php [hunk 1]
```diff
@@ -141,9 +141,9 @@ public static function fromArray(array $array, &$xml, bool $remove_header = fals
 	 * @param string        $elementname Name of the XML element of the target
 	 * @return void
 	 */
-	public static function copy(&$source, &$target, string $elementname)
```
Comment (nupplaphil) [inline src/Util/XML.php:144]: What kind of types are possible for elementname? What's the source for it? Why not mapping/checking it before calling a copy function?

For me, moving such checks near to the source makes the reason more transparent for others.. and maybe leads to refactorings :D

**Review by nupplaphil — CHANGES_REQUESTED** [review]

File: src/Util/XML.php (hunk 1 above)
Comment (annando) [reply src/Util/XML.php:144]: This PR just restores the original function before the type hints had been added. Currently it is effectively blocking the processing of incoming messages.

I'm sure that we can rewrite that whole part in a better way. But for now this PR fixes a critical issue.

**Review by MrPetovan — APPROVED** [review]
