### PR TITLE
Issue 7892: Improve "plink" generation for Diaspora posts

### LINKED ISSUE #7892: "Link to source" for hubzilla & Friendica is broken
### Expected behavior
Clicking on the frio menu on the right side of a post "Link to source" should lead you to the post on the original server

### Actual behavior
The post can' be found.

Post on friendica https://horche.demkontinuum.de/display/64da3b94-1b34-4f95-ac21-4a7faf5c53e4

1. Url that friendica has for "Link to source" https://hubzilla.eu/channel/cb7f604332cf39/?mid=64da3b94-1b34-4f95-ac21-4a7faf5c53e4
2. Hubzilla URL https://hubzilla.eu/channel/cb7f604332cf39/?f=&mid=b64.aHR0cHM6Ly9odWJ6aWxsYS5ldS9pdGVtLzY0ZGEzYjk0LTFiMzQtNGY5NS1hYzIxLTRhN2ZhZjVjNTNlNA

### Steps to reproduce the problem
Do the share ping pong (friendica -> hubzilla -> friendica)

### Friendica version you encountered the problem
git / develop / PHP7.3 / MariaDB

### PR DESCRIPTION
**Pull request by annando**
Fixes #7892 - The "plink" should now mostly point to the correct post on the remote system.

### CODE REVIEW

File: src/Protocol/Diaspora.php [hunk 1]
```diff
@@ -1600,28 +1600,55 @@ public static function isRedmatrix($url)
...
+
+		if ($platform == 'hubzilla') {
+			return $contact['baseurl'] . '/item/' . $guid;
 		}
 
-		if (self::isRedmatrix($contact["url"])) {
-			return $contact["url"] . "/?mid=" . $guid;
+		if ($platform == 'socialhome') {
+			// This doesn't really seem to work on Socialhome
+			return $contact['baseurl'] . '/content/' . $guid;
```
Comment (tobiasd) [inline src/Protocol/Diaspora.php]: Is there something that would work better?

Comment (annando) [reply src/Protocol/Diaspora.php]: False alarm. This had been a bug in my browser.
