### PR TITLE
Issue 15043: Improved performance for unseen posts

### LINKED ISSUE #15043: Slow query when loading network page
- [X ] I have searched open and closed issues for duplicates

### Bug Description

I'm using the latest stable version of **MariaDB - 11.4.7**. The first query to load the content of the network page is very, very slow - especially for very active users with a lot of content in the database. The query is running for 30-60 seconds at best and up to several minutes (!) in worst case. On subsequent page loads (reloading the page or when infinite scroll is kicking in) the same query is much faster (less than 2 seconds).

I think this is a typical case for indexes not being used correctly.

I'm pretty sure that the same query was much faster with older MariaDB versions. But with the last 3 or 4 stable releases of MariaDB it is painfully slow.

I have tried a lot of configuration changes (buffers, caches, optimizer settings) but I can't speed that query up significantly. 

Maybe it is possible to optimize the query or the use of indexes in Friendica's code itself. :-)

**Path:**

```https://example.com/network```

**Query:**

```SELECT `uri-id` FROM `post-user-view` WHERE (`unseen` = ? AND `uid` = ?) LIMIT 100``` 

**Explain with unseen = 1 and uid = 2:**

``` 
MariaDB [friendica]> explain SELECT `uri-id` FROM `post-user-view` WHERE (`unseen` = 1 AND `uid` = 2) LIMIT 100;
+------+--------------------+------------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------+----------------------------------------------------+------+-------------------------------------------+
| id   | select_type        | table            | type        | possible_keys                                                                                                                                                                                               | key               | key_len | ref                                                | rows | Extra                                     |
+------+--------------------+------------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------+----------------------------------------------------+------+-------------------------------------------+
|    1 | PRIMARY            | post-thread-user | index_merge | PRIMARY,uri-id,uid_commented,uid,uid_mention,uid_received,uid_starred,uid_wall_received,uid_created                                                                                                         | uid,PRIMARY       | 3,3     | NULL                                               | 620  | Using intersect(uid,PRIMARY); Using where |
|    1 | PRIMARY            | post-user        | ref         | uid_uri-id,contact-id,parent-uri-id_uid,owner-id,author-id_uid,uid_unseen_contactid,parent-uri-id,author-id,uid_contactid,uid_unseen,uid_hidden_uri-id,uid_wall_received,author-id_created,owner-id_created | parent-uri-id_uid | 8       | friendica.post-thread-user.uri-id,const            | 4    | Using where                               |
|    1 | PRIMARY            | contact          | eq_ref      | PRIMARY                                                                                                                                                                                                     | PRIMARY           | 4       | friendica.post-user.contact-id                     | 1    |                                           |
|    1 | PRIMARY            | author           | eq_ref      | PRIMARY                                                                                                                                                                                                     | PRIMARY           | 4       | friendica.post-user.author-id                      | 1    |                                           |
|    1 | PRIMARY            | owner            | eq_ref      | PRIMARY                                                                                                                                                                                                     | PRIMARY           | 4       | friendica.post-user.owner-id                       | 1    |                                           |
|    1 | PRIMARY            | post-content     | eq_ref      | PRIMARY                                                                                                                                                                                                     | PRIMARY           | 4       | friendica.post-user.uri-id                         | 1    |                                           |
|    5 | DEPENDENT SUBQUERY | post-media       | ref         | uri-id-url,uri-id-id                                                                                                                                                                                        | uri-id-url        | 4       | friendica.post-user.uri-id                         | 1    | Using index                               |
|    4 | DEPENDENT SUBQUERY | post-category    | ref         | PRIMARY,uid_uri-id                                                                                                                                                                                          | PRIMARY           | 7       | friendica.post-user.uri-id,friendica.post-user.uid | 1    |                                           |
|    3 | DEPENDENT SUBQUERY | post-collection  | eq_ref      | PRIMARY,type                                                                                                                                                                                                | type              | 5       | const,friendica.post-user.uri-id                   | 1    | Using index                               |
+------+--------------------+------------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------+----------------------------------------------------+------+-------------------------------------------+
```

**Actual Result:**

Query is running for several minutes in worst case, network page takes ages to load or is running into a timeout error.

**Expected Result:**

Query should be processed in less than 2 seconds and network should load in a reasonable time.

### Platform Info

Friendica Version:
2025.07-rc / db 1580

Friendica Source: 
git

PHP version:
8.3

SQL version:
**MariaDB 11.4.7**

### PR DESCRIPTION
**Pull request by annando**
Fixes #15043

### CODE REVIEW

File: src/Model/Post.php [hunk 1]
```diff
@@ -607,6 +607,17 @@ public static function selectOriginalForUser(int $uid, array $selected = [], arr
 		return self::selectFirstForUser($uid, $original_selected, ['uri-id' => $result['thr-parent-id'], 'uid' => [0, $uid]], $params);
 	}
 
+	/**
+	 * Retrieves a list of up to 100 unseen posts for a user
+	 * @param int $uid User ID
+	 * @return array Array containing the URI IDs of unseen posts
+	 */
+	public static function getUnseenPosts(int $uid): array
```
Comment (nupplaphil) [inline src/Model/Post.php:615]: Will it be statically 100? Maybe you can therefore name it

```suggestion
	public static function getFirstHundredUnseenPosts(int $uid): array
```

Just an idea, it's not a must have

Comment (annando) [reply src/Model/Post.php:615]: I would like to keep the `100` just in the description. Who knows? Possibly it does make sense in the future to change that value.
