### PR TITLE
Road to Router Part 5: Move pager out of App

### LINKED ISSUE #2893: Failed redirection after action
It's been twice today that after an action (last one being removing a contact), I'm redirected to this URL:

    https://friendica.mrpetovan.com/network?mode=raw&pagename=network?f=&order=post&page=9&_=1478405237509`

Notice the double question mark. The `pagename` parameter become `network?f=` and Friendica expectedly throws a 404 error. I didn't try to look at the code for redirection yet.

### PR DESCRIPTION
**Pull request by MrPetovan**
Follow-up to #5979
Follow-up to #5987
Follow-up to #5988
Follow-up to #5990

Ok, I'll admit this part isn't strictly necessary to add a Router to Friendica, but this was bugging me for a while. An implicit pager built in `App` but with global functions in `include/text.php` referencing `App` properties?

Worse, a lone `App ->date_offset` property that was only set in the `/network` module and used in the pager?

Now we have a proper self-contanied Pager that doesn't depend on `App` at all and vice-versa. Modules instantiates a `Pager` only if they need one.

`App->data_offset` was harder to remove, it required that I enable hooks for legacy modules (it was easy) and somehow pass a `Pager` object between the global functions of the `/network` module (it wasn't easy).

In the end, the infinite scroll data only shows up in the `<head>` tag for the `/network` module and only if it is enabled.

Overall pretty happy with the result, even if I had to touch pretty much all the files in the project. `boot.php` get a cut again, as well as `include/text.php`!

It may even address #2893 !

Don't forget about https://github.com/friendica/friendica-addons/pull/762

### CODE REVIEW

**Comment by annando** [comment]
I had no time to look at it. But since you touched the pager, I really would like to have only the infinite scroll and the pager without page numbers. There are several places in the code where we need to perform very expensive ```count``` commands to let the pager have all needed data. I really would like to remove all these counts.

**Comment by MrPetovan** [comment]
I think numbered pages are warranted in most non-stream cases. I'd rather optimize the count queries than remove the full pager rendering altogether.

**Comment by annando** [comment]
Due to the way that MySQL is working, a ```count``` always means really counting the rows. This means that in every situation with more than some pages, we cannot really use the pager with page numbers at all. So We will have to replace the pager at most places anyway - with only a few places where we do have only a few entries. This isn't really relevant for single user systems, but systems like squeet.me are really aching. So possibly you could add some small coding, so that in the admin interface one could switch between the two modes?

**Comment by MrPetovan** [comment]
How severe is the performance hit? And yes, we can add a config, even if it can't be checked in a single location because of the difference of `ItemCount` parameter meaning between the `renderMinimal` and `renderFull` methods.

**Comment by annando** [comment]
On photos it can lead to a count with a duration of several minutes - which leads to a timeout.

**Comment by MrPetovan** [comment]
Oof, got it. I'd still rather add the config in a separate PR.

**Comment by MrPetovan** [comment]
Running this branch on my server, I had trouble on my phone because it was using a cached version of `main.js`.

File: src/Content/Pager.php [hunk 1]
```diff
@@ -0,0 +1,282 @@
...
+	}
+
+	/**
+	 * Sets the base query string from a full query string.
+	 *
+	 * Strips the 'page' parameter, and remove the 'q=' string for some reason.
+	 *
+	 * @param string $queryString
+	 */
+	public function setQueryString($queryString)
```
Comment (nupplaphil) [inline src/Content/Pager.php]: Just a suggestion :-)

```php
function testQueryString() 
{
       $pager = new Paget(..);
       $queryString = 'a/query/string?key=value&q=value';
       $stripped = 'a/query/string?key=value';
       $pager->setQueryString($queryString);
       $this->assertSame($stripped, $this->getBaseQueryString());
}
```

File: src/Content/Pager.php [hunk 2]
```diff
@@ -0,0 +1,282 @@
...
+	 * Guesses the page number from the GET parameter 'page'.
+	 *
+	 * @param string  $queryString  The query string of the current page
+	 * @param integer $itemsPerPage An optional number of items per page to override the default value
+	 */
+	public function __construct($queryString, $itemsPerPage = 50)
+	{
+		$this->setQueryString($queryString);
+		$this->setItemsPerPage($itemsPerPage);
+		$this->setPage(defaults($_GET, 'page', 1));
```
Comment (nupplaphil) [inline src/Content/Pager.php]: just a suggestion (avoiding $_GET dependency inside class)

```php
function __construct($queryString, $page = 1, $itemsPerPage = 50)
{
....
$this->setPage($page);
}
```
And $page will be set during object initialization:
```php
$pager = new Pager($queryString, defaults($_GET, 'page'));
```

Comment (MrPetovan) [reply src/Content/Pager.php]: I thought about it, and then I realized that it's actually self-contained since the Pager set the GET `page`  parameter in the query strings it produces. I actually like the current way better because the modules don't even have to know how the page parameter is called at all or how it is transmitted.

File: src/Content/Pager.php (hunk 1 above)
Comment (MrPetovan) [reply src/Content/Pager.php]: I'll add this test in a subsequent PR. Thank you for the suggestion!
