### PR TITLE
Issue 11938: Fix weird date formats

### LINKED ISSUE #11938: DateTimeFormat - Failed to parse time string
- [ ] I have searched open and closed issues for duplicates

### Bug Description

Looks like some items have a German time zone string that cannot be parsed.

```
2022-09-26T16:21:34Z worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Mo, 19 Sep 2022 14:51:00 +0200) at position 0 (M): The timezone could not be found in the database {"worker_id":"5b6ff7f","worker_cmd":"OnePoll"} - {"file":"DateTimeFormat.php","line":161,"function":"convert","uid":"307ae3","process_id":680430}
2022-09-26T16:21:34Z worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Di, 20 Sep 2022 11:12:00 +0200) at position 0 (D): The timezone could not be found in the database {"worker_id":"5b6ff7f","worker_cmd":"OnePoll"} - {"file":"DateTimeFormat.php","line":161,"function":"convert","uid":"307ae3","process_id":680430}
2022-09-26T16:21:34Z worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Mi, 21 Sep 2022 07:37:00 +0200) at position 0 (M): The timezone could not be found in the database {"worker_id":"5b6ff7f","worker_cmd":"OnePoll"} - {"file":"DateTimeFormat.php","line":161,"function":"convert","uid":"307ae3","process_id":680430}
2022-09-26T16:21:35Z worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Mi, 21 Sep 2022 10:39:00 +0200) at position 0 (M): The timezone could not be found in the database {"worker_id":"5b6ff7f","worker_cmd":"OnePoll"} - {"file":"DateTimeFormat.php","line":161,"function":"convert","uid":"307ae3","process_id":680430}
2022-09-26T16:21:35Z worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Mi, 21 Sep 2022 12:24:00 +0200) at position 0 (M): The timezone could not be found in the database {"worker_id":"5b6ff7f","worker_cmd":"OnePoll"} - {"file":"DateTimeFormat.php","line":161,"function":"convert","uid":"307ae3","process_id":680430}
2022-09-26T16:21:35Z worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Mi, 21 Sep 2022 12:43:00 +0200) at position 0 (M): The timezone could not be found in the database {"worker_id":"5b6ff7f","worker_cmd":"OnePoll"} - {"file":"DateTimeFormat.php","line":161,"function":"convert","uid":"307ae3","process_id":680430}
2022-09-26T16:21:35Z worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Mi, 21 Sep 2022 15:15:00 +0200) at position 0 (M): The timezone could not be found in the database {"worker_id":"5b6ff7f","worker_cmd":"OnePoll"} - {"file":"DateTimeFormat.php","line":161,"function":"convert","uid":"307ae3","process_id":680430}
2022-09-26T16:21:35Z worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Sa, 24 Sep 2022 08:37:00 +0200) at position 0 (S): The timezone could not be found in the database {"worker_id":"5b6ff7f","worker_cmd":"OnePoll"} - {"file":"DateTimeFormat.php","line":161,"function":"convert","uid":"307ae3","process_id":680430}
```

Not sure if this is an issue with the source format or with our datetime parser.

### Platform Info

Friendica Version:
2022.09-rc

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB

### PR DESCRIPTION
**Pull request by annando**
Fixes #11938
There are some weird date formats that PHP doesn't understand. This function fixes this.

### CODE REVIEW

File: src/Util/DateTimeFormat.php [hunk 1]
```diff
@@ -173,6 +175,29 @@ public static function convert($s = 'now', $tz_to = 'UTC', $tz_from = 'UTC', $fo
...
+				['#(\d+-\d+-\d+)T(\d+:\d+:\d+)ZZ#', '$1T$2Z'],
+				['#(\d+-\d+-\d+)T(\d+:\d+:\d+\.\d+)ZZ#', '$1T$2Z'],
+				['#(\w+), (\d+ \w+ \d+) (\d+:\d+:\d+) (.+)#', '$2 $3 $4'],
+				['#(\d+:\d+) (\w+), (\w+) (\d+), (\d+)#', '$1 $2 $3 $4 $5'],
+			];
+
+		foreach ($pattern as $search_replace) {
+			$dateString = preg_replace($search_replace[0], $search_replace[1], $dateString);
+		}
+		return $dateString;
```
Comment (MrPetovan) [inline src/Util/DateTimeFormat.php]: No need for 2 indentation levels + various minor improvements.
```suggestion
		$patterns = [
			['#(\w+), (\d+/\d+/\d+) - (\d+:\d+)#', '$1, $2 $3'],
			['#(\d+-\d+-\d+)T(\d+:\d+:\d+)ZZ#', '$1T$2Z'],
			['#(\d+-\d+-\d+)T(\d+:\d+:\d+\.\d+)ZZ#', '$1T$2Z'],
			['#(\w+), (\d+ \w+ \d+) (\d+:\d+:\d+) (.+)#', '$2 $3 $4'],
			['#(\d+:\d+) (\w+), (\w+) (\d+), (\d+)#', '$1 $2 $3 $4 $5'],
		];

		foreach ($patterns as $pattern) {
			$dateString = preg_replace($pattern[0], $pattern[1], $dateString);
		}
		
		return $dateString;
```

**Review by MrPetovan — CHANGES_REQUESTED** [review]

**Review by MrPetovan — APPROVED** [review]
