### PR TITLE
Fix URI structure condition in Probe::detect

### LINKED ISSUE #11055: Unable to follow a Diaspora account from sysad.org
_Originally posted by @haheute in https://github.com/friendica/friendica/issues/11047#issuecomment-984415200_
> Thanks. I tried following another user/pod, and got the same message as above. + another one:
> 
> ```
> msgid "The network type couldn't be detected. Contact can't be added."
> msgstr "Der Netzwerktyp wurde nicht erkannt. Der Kontakt kann nicht hinzugefügt werden."
> ```
> 
> here the link: https://libranet.de/follow?url=https%3A%2F%2Fsysad.org%2Fu%2Ftomgrzyb

### PR DESCRIPTION
**Pull request by MrPetovan**
Fix #11055 

Additionally, this PR deprecates `Network::unparseURL` since we now can do it with `Guzzle\Psr7\Uri`.

### CODE REVIEW

File: src/Network/Probe.php [hunk 1]
```diff
@@ -688,22 +686,21 @@ private static function detect(string $uri, string $network, int $uid, array $ap
...
-			if (strpos($uri, 'mailto:') !== false) {
-				$uri = str_replace('mailto:', '', $uri);
-				return self::mail($uri, $uid);
-			}
-
-			if ($network == Protocol::MAIL) {
-				return self::mail($uri, $uid);
-			}
-		} else {
+		if (empty($parts['scheme']) && empty($parts['host']) && !strstr($parts['path'], '@')) {
```
Comment (annando) [inline src/Network/Probe.php:689]: Wouldn't this be invoked with an URL in the format `mailto:user@domain.tld`?

File: src/Network/Probe.php [hunk 2]
```diff
@@ -58,26 +59,23 @@ class Probe
...
 	{
 		// At first remove leading and trailing junk
-		$URI = trim($URI, "@#?:/ \t\n\r\0\x0B");
-
-		$parts = parse_url($URI);
+		$uri = trim($uri, "@#?:/ \t\n\r\0\x0B");
 
-		if (empty($parts['scheme'])) {
-			return $URI;
+		$uri = new Uri($uri);
```
Comment (annando) [inline src/Network/Probe.php]: What is the advantage of not using `parse_url` here?

File: src/Network/Probe.php (hunk 1 above)
Comment (MrPetovan) [reply src/Network/Probe.php:689]:
```php
$parsed = parse_url('mailto:user@domain.tld');
// array(2) {
//   ["scheme"]=>
//   string(6) "mailto"
//   ["path"]=>
//   string(15) "user@domain.tld"
// }
```
It would fail the first and the third part of the condition.

File: src/Network/Probe.php (hunk 2 above)
Comment (MrPetovan) [reply src/Network/Probe.php]: Anytime we need to actually change individual parts of a URI, it's better to use this object than `Network::unparseURL` thanks to compliance checks we do not currently perform.

For read-only access it's functionally equivalent, which is why I don't particularly recommend to change the places we already use `parse_url`.

File: src/Network/Probe.php [hunk 3]
```diff
@@ -58,26 +59,23 @@ class Probe
...
+		if (!$uri->getScheme()) {
+			return $uri->__toString();
```
Comment (annando) [inline src/Network/Probe.php:72]: Shouldn't we return `$uri` here?

File: src/Network/Probe.php (hunk 2 above)
Comment (annando) [reply src/Network/Probe.php]: BTW: It's slightly confusing when the `$uri` string is converted to a `$uri` object.

File: tests/src/Network/ProbeTest.php [hunk 4]
```diff
@@ -117,12 +117,45 @@ public function testGetFeedLinkBase()
...
-				'assertUri'   => 'Artists4Future_Muenchen@climatejustice.global',
+				'expected' => 'Artists4Future_Muenchen@climatejustice.global',
+				'uri'      => '@Artists4Future_Muenchen@climatejustice.global',
+			],
+			'no-scheme-no-fragment' => [
+				'expected' => 'example.com/path?arg=value',
+				'uri'      => 'example.com/path?arg=value',
+			],
+			'no-scheme-fragment' => [
+				'expected' => 'example.com/path?arg=value#fragment',
```
Comment (annando) [inline tests/src/Network/ProbeTest.php:135]: Are we really expecting this fragment there?

Comment (MrPetovan) [reply tests/src/Network/ProbeTest.php:135]: I don't know, but this is how the original function was implemented and I just wanted to ensure we weren't changing its behavior with the switch to the `Uri` object.

File: src/Network/Probe.php (hunk 3 above)
Comment (MrPetovan) [reply src/Network/Probe.php:72]: At this point `$uri` is an object and the original function was returning a string so we need to cast it back to string.

File: src/Network/Probe.php (hunk 2 above)
Comment (MrPetovan) [reply src/Network/Probe.php]: I'm not happy with it either but I couldn't come with a good way to separate URI strings and URI objects.

Comment (annando) [reply src/Network/Probe.php]: Couldn't you use some prefix for the parameter text? I find it really confusing.

File: src/Network/Probe.php (hunk 3 above)
Comment (annando) [reply src/Network/Probe.php:72]: Yeah, I guess at that moment I realized this - which is another reason for using a different name for the two variables :grin:

File: tests/src/Network/ProbeTest.php (hunk 4 above)
Comment (annando) [reply tests/src/Network/ProbeTest.php:135]: Understandable. Possibly you could add a comment there, that this is the current return result but it is to discuss if this behaviour is correct?

File: src/Network/Probe.php (hunk 2 above)
Comment (MrPetovan) [reply src/Network/Probe.php]: I don't like prefixes and I use suffixes sparingly. Since we do not have any further use for the URI string after it's converted to an object, I don't think it is a problem in this short method.

Comment (MrPetovan) [reply src/Network/Probe.php:70]: A good alternative is for the method to take a `Uri` object as parameter, it would require changing only 6 mentions, what do you say?

Comment (annando) [reply src/Network/Probe.php]: Wouldn't `$rawuri` be a good name?

Comment (MrPetovan) [reply src/Network/Probe.php]: I guess so, let's go with that.

File: tests/src/Network/ProbeTest.php (hunk 4 above)
Comment (MrPetovan) [reply tests/src/Network/ProbeTest.php:135]: Done.
