### PR TITLE
Avoid double updates

### LINKED ISSUE #6788: Multiple admin notification mails
### Expected behavior
When a notification mail is sent to the mail address of the admin it should be one mail.

### Actual behavior
When a notification mail is sent that mail is sent two, four, six, eight or 244 times.

### Steps to reproduce the problem
I have two admin accounts with two different mail addresses. So, I understand that each mail is sent twice. But when a user deletes his/her account I often get 4 ,6 or 8 mails about it.
Today the database structure was updated to version 1304 and I got **244** admin notification mails about the update.

This behavior has been confirmed by another node admin in our XMPP chat room. He got 50+ mails about the DB update.

### Friendica version you encountered the problem
2019.03-rc

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

### PR DESCRIPTION
**Pull request by nupplaphil**
Should fix #6788 ... again ...
Redux of #6842 

This time just the bugfix without any improvement..
And this time I reseted the "build" number one version down a few times with exactly one update run..

I'm really looking forward this time to NOT create a catastrophic PR .. (who knows -.-** ...)

### CODE REVIEW

File: src/Core/Update.php [hunk 1]
```diff
@@ -92,6 +92,7 @@ public static function run($basePath, $force = false, $override = false, $verbos
 					// Checks if the build changed during Lock acquiring (so no double update occurs)
 					$retryBuild = Config::get('system', 'build', null, true);
 					if ($retryBuild !== $build) {
+						Logger::debug('Update from \'' . $stored . '\' to \''. $current . '\' - already done');
```
Comment (MrPetovan) [inline src/Core/Update.php]: No love for  `context`?

**Comment by nupplaphil** [comment]
Worked even with Logger output now:
```console
2019-03-11 20:46:16 worker [INFO]: Update starting. {"from":1303,"to":1304} {"file":"Update.php","line":86,"function":"run","uid":"56e9465","process_id":7577}                                
2019-03-11 20:46:16 worker [INFO]: Update function start. {"function":"pre_update_1304"} {"file":"Update.php","line":160,"function":"runUpdateFunction","uid":"56e9465","process_id":7577}    
2019-03-11 20:46:16 worker [INFO]: Update function skipped. {"function":"pre_update_1304"} {"file":"Update.php","line":198,"function":"runUpdateFunction","uid":"56e9465","process_id":7577}  
2019-03-11 20:46:17 worker [INFO]: updating structure [] {"file":"DBStructure.php","line":268,"function":"update","uid":"56e9465","process_id":7577}                                          
2019-03-11 20:46:17 worker [INFO]: updating structure for table workerqueue ... [] {"file":"DBStructure.php","line":281,"function":"update","uid":"56e9465","process_id":7577}
2019-03-11 20:46:17 worker [INFO]: Update finished. {"from":1303,"to":1304} {"file":"Update.php","line":123,"function":"run","uid":"56e9465","process_id":7577}
2019-03-11 20:46:17 worker [INFO]: Update function start. {"function":"update_1304"} {"file":"Update.php","line":160,"function":"runUpdateFunction","uid":"56e9465","process_id":7577}
2019-03-11 20:46:17 worker [INFO]: Update function skipped. {"function":"update_1304"} {"file":"Update.php","line":198,"function":"runUpdateFunction","uid":"56e9465","process_id":7577}
2019-03-11 20:46:18 worker [NOTICE]: Update success. {"from":1303,"to":1304} {"file":"Update.php","line":134,"function":"run","uid":"56e9465","process_id":7577}
2019-03-11 20:46:18 worker [INFO]: sending notification email [] {"file":"enotify.php","line":572,"function":"notification","uid":"56e9465","process_id":7577}
2019-03-11 20:46:18 worker [INFO]: header To: admin@philipp.info Precedence: list X-Friendica-Host: friendica.philipp.info X-Friendica-Account: <@friendica.philipp.info> X-Friendica-Platform: Friendica X-Friendi
ca-Version: 2019.03-rc List-ID: <notification.friendica.philipp.info> List-Archive: <http://friendica.philipp.info/notifications/system> From: Philipp's Friendica <no-reply@friendica.philipp.info> Reply-To: Phil
ipp's Friendica <no-reply@friendica.philipp.info> MIME-Version: 1.0 Content-Type: multipart/alternative; boundary="4-989545552-951655163=:74188" [] {"file":"Emailer.php","line":102,"function":"send","uid":"56e94
65","process_id":7577}

```
