### PR TITLE
Issue-9358 (now for real) commenting and updating on contact now work

### LINKED ISSUE #9358: like toggle on /contact/{id}/conversations page not (visually) completing
The like function on the contact conversations page seems to load forever / does not seem to visually complete.

- [x] I have searched open and closed issues for duplicates

### Bug Description
On the contact conversations page, when I like or 'unlike' a post, the spinning graphic seems to spin forever and does not seem to complete, until I reload the page. I have only tried with diaspora contacts.

On the `/network?order=post` page, this function works. After very short time the spinner image disappears and the likes get refreshed (new like is counted/displayed).

### Steps to Reproduce

1. go to a (diaspora) contact's conversations page (for example hovercard -> click cloud icon)
2. like a post
3. wait or reload page if it does not seem to complete visually

Actual Result:

only after reloading the page, the spinning graphic disappears and the new like is displayed

Expected Result:

show the spinning image and hide it again and refresh the likes below the post 

### Screenshots

friendica-like-endless

### Platform Info

Friendica Version: 2020.09-1
database version: 1369/1369 
Post-Update-Version: 1350
Theme: Frio V.0.8.5

### PR DESCRIPTION
**Pull request by annando**
Fixes #9358 - now for real :grinning:

### CODE REVIEW

File: mod/update_contact.php [hunk 1]
```diff
@@ -28,11 +28,10 @@
 
 function update_contact_content(App $a)
 {
-	if (!empty($_GET['force']) || !DI::pConfig()->get(local_user(), 'system', 'no_auto_update')) {
-		$text = Contact::content([], true);
+	if (!empty($a->argv[1]) && (!empty($_GET['force']) || !DI::pConfig()->get(local_user(), 'system', 'no_auto_update'))) {
+		$text = Contact::getConversationsHMTL($a, $a->argv[1], true, ($_GET['item'] ?? 0));
```
Comment (MrPetovan) [inline mod/update_contact.php:32]: Please make sure `$a->argv[1]` is set with a `??` for example.

File: mod/update_contact.php [hunk 2]
```diff
@@ -28,11 +28,10 @@
...
 	} else {
 		$text = '';
 	}
-
```
Comment (MrPetovan) [inline mod/update_contact.php:36]: Why did you remove this new line?

File: src/Model/Contact.php [hunk 3]
```diff
@@ -1248,12 +1248,13 @@ public static function isHidden($cid)
 	 * @param string $contact_url Contact URL
 	 * @param bool   $thread_mode
 	 * @param int    $update
+	 * @param int    $parent
```
Comment (MrPetovan) [inline src/Model/Contact.php]: What is it supposed to be aside from an integer?

File: src/Model/Contact.php [hunk 4]
```diff
@@ -1262,10 +1263,11 @@ public static function getPostsFromUrl($contact_url, $thread_mode = false, $upda
 	 * @param integer $cid
 	 * @param bool    $thread_mode
 	 * @param integer $update
+	 * @param int     $parent
```
Comment (MrPetovan) [inline src/Model/Contact.php]: What is it supposed to be aside from an integer?

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: mod/update_contact.php (hunk 1 above)
Comment (annando) [reply mod/update_contact.php:32]: There is the `empty($a->argv[1])` for.

File: mod/update_contact.php (hunk 2 above)
Comment (annando) [reply mod/update_contact.php:36]: Why not?

File: mod/update_contact.php (hunk 1 above)
Comment (MrPetovan) [reply mod/update_contact.php:32]: Never mind.

File: src/Model/Contact.php [hunk 5]
```diff
@@ -1245,10 +1245,10 @@ public static function isHidden($cid)
...
 	 * Returns posts from a given contact url
 	 *
-	 * @param string $contact_url Contact URL
-	 * @param bool   $thread_mode
-	 * @param int    $update
-	 * @param int    $parent
+	 * @param string  $contact_url Contact URL
+	 * @param bool    $thread_mode
+	 * @param integer $update      Update mode 
+	 * @param int     $parent      Parent ID for the update mode
```
Comment (MrPetovan) [inline src/Model/Contact.php]: What table is it an ID from? Can there be an update mode without a parent id?

File: src/Model/Contact.php [hunk 6]
```diff
@@ -1245,10 +1245,10 @@ public static function isHidden($cid)
 	/**
 	 * Returns posts from a given contact url
 	 *
-	 * @param string $contact_url Contact URL
-	 * @param bool   $thread_mode
-	 * @param int    $update
-	 * @param int    $parent
+	 * @param string  $contact_url Contact URL
+	 * @param bool    $thread_mode
+	 * @param integer $update      Update mode
```
Comment (MrPetovan) [inline src/Model/Contact.php]: Please use the more ubiquitous `int`, or at least the same type string in the same doc block.

File: src/Model/Contact.php [hunk 7]
```diff
@@ -1260,10 +1260,10 @@ public static function getPostsFromUrl($contact_url, $thread_mode = false, $upda
 	/**
 	 * Returns posts from a given contact id
 	 *
-	 * @param integer $cid
+	 * @param integer $cid         Contact ID
 	 * @param bool    $thread_mode
-	 * @param integer $update
-	 * @param int     $parent
+	 * @param integer $update      Update mode
```
Comment (MrPetovan) [inline src/Model/Contact.php]: Please use the more ubiquitous `int`, or at least the same type string in the same doc block.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Model/Contact.php (hunk 5 above)
Comment (annando) [reply src/Model/Contact.php]: Yes. This is the case for the regular background update. The `$parent` is only set when you comment on something.

File: mod/update_contact.php (hunk 2 above)
Comment (MrPetovan) [reply mod/update_contact.php:36]: Because not doing a thing is easier than doing it? I've been consistently adding a new line after closing curly braces so I wanted to know why you removed it in this specific instance.

**Review by MrPetovan — APPROVED** [review]
