### PR TITLE
Fix addon reload

### LINKED ISSUE #4314: renamed hooks cause addon config not to work
With #4288 the hook names `plugin_*` got renamed to `addons_*` but in the database still the old name is anchored so that the new hooks are not executed.

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #4314

Just a missing `dba::inArray`.

### CODE REVIEW

File: update.php [hunk 1]
```diff
@@ -173,3 +175,12 @@ function update_1245() {
 
 	return UPDATE_SUCCESS;
 }
+
+function update_1247() {
+	// Removing hooks with the old name
+	dba::e("DELETE FROM `hook`
+WHERE `hook` LIKE 'plugin_%'");
```
Comment (tobiasd) [inline update.php]: the indentation looks wrong in the github diff.

Comment (MrPetovan) [reply update.php]: It's a habit I formed after having debugged countless SQL query strings (before statements). I wouldn't indent the queries at their current level because the output would be affected by where they would be in the code. Instead, I resolved to deindent them manually, which made them stand out in my code and look nicer when debugging.

Comment (annando) [reply update.php]: They are "deindented" automatically by the dba class. So this doesn't affect the query.

Comment (MrPetovan) [reply update.php]: I know, like I said it's a personal habit, I'll try to be more mindful of it.
