### PR TITLE
Avoid storing plaintext password in register table

### LINKED ISSUE #4804: Pending registrations different information on different admin pages
### Expected behavior
Same info from 
  * /admin page 
  * /admin/users/ page 
about the number of registrations. In my case this number should be 0 (zero).

### Actual behavior
On the /admin page I have the info
>     Pending registrations  **6** 

On the /admin/users/ page it says
>    User registrations awaiting confirmation
>    **No registrations.**

### Steps to reproduce the problem
I don't know. I have just to click on those pages ;)

### Friendica version you encountered the problem
Friendica 'The Tazmans Flax-lily' 2018-05-dev - 1259
### Friendica source (git, zip)
git
### PHP version
PHP Version 7.0.29-1~dotdeb+8.1
### SQL version
MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Redux of #5918
Fixes #4804

It started with a simple refactoring into a model class. The goal was to prevent modules from making direct DB calls about the register table.

Then I found out that we were storing the plaintext password in the register table until a pending registration is either approved or denied.

It isn't necessarily a problem with auto-generated password, but it would become a huge liability with user-provided passwords, which I would like Friendica to move to eventually.

### CODE REVIEW

File: boot.php [hunk 1]
```diff
@@ -647,7 +647,7 @@ function killme()
 /**
  * @brief Redirect to another URL and terminate this process.
  */
-function goaway($path)
+function goaway($path = '')
```
Comment (nupplaphil) [inline boot.php]: Interesting for #5907 
So I will rename it from `System::redirectTo($url)` to `System::redirect($to = '');` :-)

File: include/enotify.php [hunk 2]
```diff
@@ -84,7 +84,7 @@ function notification($params)
 	// with $params['show_in_notification_page'] == false, the notification isn't inserted into
 	// the database, and an email is sent if applicable.
 	// default, if not specified: true
-	$show_in_notification_page = ((x($params, 'show_in_notification_page'))	? $params['show_in_notification_page']:true);
+	$show_in_notification_page = isset($params['show_in_notification_page']) ? $params['show_in_notification_page'] : true;
```
Comment (nupplaphil) [inline include/enotify.php]: wouldn't `defaults($params, ''show_in_notification_page', true)` be better?

File: src/Model/Register.php [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+	}
+
+	/**
+	 * Creates a register record for approval and returns the success of the database insert
+	 * Checks for the existence of the provided user id
+	 *
+	 * @param  integer $uid      The ID of the user needing approval
+	 * @param  string  $language The registration language
+	 * @param  string  $note     An additional message from the user
+	 * @return boolean
```
Comment (nupplaphil) [inline src/Model/Register.php]: true is when an approval is successfully stored, isn't it? I would add it to the doc

File: include/enotify.php (hunk 2 above)
Comment (MrPetovan) [reply include/enotify.php]: Not in this case, `defaults()` only work when we are expecting a truthy value, otherwise the falsy default value is used. However, if we are expecting a falsy value, `defaults()` would use the default value instead.

This is because `defaults()` is based on `x()`.

Comment (nupplaphil) [reply include/enotify.php]: Noticed for some `boot.php` refactor action ;-)

File: src/Model/Register.php (hunk 3 above)
Comment (MrPetovan) [reply src/Model/Register.php]: I feel like it is a generic enough return type that it doesn't need to be explained. You guessed it right, didn't you?

**Comment by MrPetovan** [comment]
I didn't include a database schema change because I want the transition to be as transparent as possible.

Which reminds me that the email sent on approval doesn't contain the password even if the legacy register row has it.

**Comment by MrPetovan** [comment]
Alright, now it will still send the plaintext password on approval if it was in the register table.
