### PR TITLE
Fix Diaspora LF in code blocks/Move php-markdown to composer

### LINKED ISSUE #3639: Line feeds in code blocks are broken on Diaspora
I just posted something with a lot of code blocks. The post was delivered to Diaspora as well.
All the line feeds inside the code blocks are broken on Diaspora's side. Instead of line feeds HTML br tags are shown.
Can we do something about this?

See:
https://libranet.de/display/0b6b25a85959981abf47efb116424689
https://despora.de/posts/0b6b25a85959981abf47efb116424689

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #3639
Part of #4116

Moves michelf/php-markdown to Composer

Fixes an issue with code blocks where multi-line code blocks without a new line after the `[code]` tag wouldn't be recognized as such and subjected to the `\n` => `<br/>`  treatment.

### CODE REVIEW

File: library/markdown.php [hunk 1]
```diff
@@ -6,14 +6,13 @@
  * @brief Parser for Markdown files
  */
 
-require_once "library/php-markdown/Michelf/MarkdownExtra.inc.php";
 use \Michelf\MarkdownExtra;
 
 /**
```
Comment (annando) [inline library/markdown.php]: Please remove/relocate this function as well. This was some wrapper from a time where no one seemed to understand autoloader and such stuff.

This file doesn't belong under /library since it is one of our functions.

Comment (MrPetovan) [reply library/markdown.php]: Not sure where to move it for now, I don't think we have agreed on anything, `Friendica\Content`?

Comment (annando) [reply library/markdown.php]: I think it belongs to the same place the bbcode parser and all other parsers belong to. I would like to have them all in a separate folder.

**Comment by MrPetovan** [comment]
I chose `src/Content/Text` for the parsers directory.
