### PR TITLE
Issue 9276: Cache the trending hashtags in the background

### LINKED ISSUE #9276: Trending tags feature - performance
### Actual behavior
Can someone maybe possibly please have a look at the performance impact of the trending tags feature? The first loading of the community pages takes a long time when that feature is enabled.

cc @annando 

### Steps to reproduce the problem
Enable trending tags.
Go to community pages.

### Friendica version you encountered the problem
All of them.

Short issue because I'm on vacation and mobile only.

### PR DESCRIPTION
**Pull request by annando**
This fixes https://github.com/friendica/friendica/issues/9276

We now create the cache for the trending tags in the background.

### CODE REVIEW

File: src/Model/Tag.php [hunk 1]
```diff
@@ -488,54 +488,86 @@ public static function getURIIdListByTag(string $search, int $uid = 0, int $star
 	 * Returns a list of the most frequent global hashtags over the given period
 	 *
 	 * @param int $period Period in hours to consider posts
+	 * @param int $limit  Number of returned tags
 	 * @return array
 	 * @throws \Exception
 	 */
 	public static function getGlobalTrendingHashtags(int $period, $limit = 10)
 	{
 		$tags = DI::cache()->get('global_trending_tags');
```
Comment (MrPetovan) [inline src/Model/Tag.php]: The cache key name should take the period and limit parameter into account, otherwise the results shown would always be the same regardless of the variable parameters.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

**Review by MrPetovan — APPROVED** [review]
