### PR TITLE
Add current section highlighting to Frio's navbar, fix related logic

### LINKED ISSUE #13397: [frio] Highlight the top menu icon which is selected
**Currently**

There is no highlighting of the top menu icon which is actively selected, which results in slightly confusing UI, making it hard for users  to find orientation.

**Expected**

Highlighting the selected section icon will help convey to users which area of friendica they are currently viewing.

**Potential Solutions**

Either the icon itself could be colored in highlight color.
Alternatively the icon could be underlined in highlight color.

The second navigation bar does have highlighting of the selected option. Not sure if that is great UX, maybe sticking to white text (on dark background) and vice versa and only underlining the selected option in highlight color would make for a better look.

GitHub uses white text and underlines the selected option:

### PR DESCRIPTION
**Pull request by marcusxss**
Closes #13397

There is logic in PHP and the frio templates for "current section highlighting" which Bookface uses but Frio does not.
It seems to be broken in some places, though - specifically calendar and contacts.

This adds current section to Frio, using the same effect used on hover.
This is to improve UX, especially for new users.
The calendar is only highlighted if you're on your own calendar, as that's where clicking that link takes you...?

Also Vier's reference to the calendar didn't work because it referred to it by the name "events". That's been fixed, and also the top nav current section highlighting has been added to the calendar in Vier as well.

Edit: This is no longer the case:

~The styling change breaks the UI of Bookface a little, but adding e.g. `background: none` to this section should fix it again:~
```css
#topbar-first .nav > li > a.selected,
#nav-notification.dropdown.open
```
~Will create an issue in the bookface repo if this is merged.~

# Before

image

# After

## Current

image

image

image

Bookface is no longer visually broken by it, but it does get an extra underline
image

## Original

image

### CODE REVIEW

**Comment by foss-** [comment]
Related: https://github.com/friendica/friendica/issues/13397
Is it better to also use some sort of underline instead of highlighting the entire icon background? Highlighting entire background is also identical to current mouse over implementation which could be slightly confusing. Underline would be in line with the secondary navigation bar. Using the highlight color which is used on mouse over could work. Wdyt?

**Comment by marcusxss** [comment]
I don't really like how it looks visually currently so I'm not set on that. It was just the fastest to reuse the hover effect.

I was initially thinking about perhaps colouring the icon with the accent colour, but when the navbar itself is that color it won't work. It could be that underlining could work. I think Vier does that.
I seem to recall Bookface both changes its color AND underlines it, which it can do because its navbar is white/black, not the accent colour.

**Comment by marcusxss** [comment]
The underline is also the hover effect for the submenu, so in a sense its already consistent with that, ie. the same styling is used for the current section and hovering.

**Comment by marcusxss** [comment]
A few quick mockups of alternative ways to indicate it:

Underline:
image

Overline and underline:
image

Using a secondary accent colour - the yellow from the Friendica logo:
image
...not sure if this last one would work with all accent colours, but alternatively some of them could perhaps use the friedica logo's blue colour instead.

If we were to instead use the accent colour for highlighting the current section we'd have to change the background colour of the main navigation in light mode as you mentioned previously, fx. to white like Bookface. Maybe that's too big of a change this close to a release?

**Comment by foss-** [comment]
From the mock-ups underline feels most in line with the rest of the current UI and concept of 2nd nav-bar.
On the long run adjusting background color for nav bar could work. But I think that should be a post-release change. The release is overdue and anything potentially holding it back should be avoided.

**Comment by annando** [comment]
This here is some change that doesn't seem to be a bugfix or something that is really critical, isn't it? I really would like to freeze the current state with the PRs, so that only bugs and crucial improvements are added.

**Comment by marcusxss** [comment]
I agree with foss- saying:
> The release is overdue and anything potentially holding it back should be avoided.

...so I don't think this should hold back the release. I think the highlighting would help usability a good amount, but "really critical" it's certainly not. And I think Vier is already quite broken in several ways, so those changes don't make much of a difference there.

**Comment by marcusxss** [comment]
Btw. I updated the PR to use underline instead as suggested. The description and screenshots have been updated.

**Comment by foss-** [comment]
Looks good imo - will you file an issue with bookface to inform them about the double underline introduced by this change?

**Comment by marcusxss** [comment]
I will when it's merged but I assume that will be after the release.

**Comment by annando** [comment]
Please fix the conflict.

File: src/Module/Calendar/Show.php [hunk 1]
```diff
@@ -90,7 +90,10 @@ protected function content(array $request = []): string
 			'$i18n'         => $i18n,
 		]);
 
-		Nav::setSelected($is_owner ? 'home' : 'calendar');
+		// Only highlight the calendar link if you're on your own calendar
+		if ($is_owner) {
```
Comment (annando) [inline src/Module/Calendar/Show.php]: What happens now, when the page isn't visited by an owner?

Comment (marcusxss) [reply src/Module/Calendar/Show.php]: Before the PR, if you're on your own calendar "Home" is selected (though there's no visual indication), and if you're on someone else's calendar, nothing is selected (in Frio).

After the PR, but **without** this particular change, "Home" would be selected when you're on your own calendar, and "Calendar" would be selected if you're on someone else's.

After the PR **with** this change, "calendar" is selected if you're on your own, and nothing is selected if you're on someone else's. This is based on that if you actually click the link, you always get to your own calendar, and I don't believe you generally navigate to the calendars of other people from there. Other people's profiles, where their calendars are, are not directly accessible from the main navigation.

**Comment by tobiasd** [comment]
There is a merge conflict with the translations.

**Comment by marcusxss** [comment]
Fixed!
