### PR TITLE
Suppress Type error exception in ActivityPub\Processor

### LINKED ISSUE #11091: Argument 1 passed to Friendica\Util\DateTimeFormat::utc() must be of the type string, null given
- [X ] I have searched open and closed issues for duplicates

### Bug Description

With current release candidate I see a lot of errors with an exception related to `ActivityPub/Processor.php` and `Util/DateTimeFormat.php`.

**Forum thread**
https://forum.friendi.ca/display/0b6b25a8-1061-b45f-9669-233077937349

**Logged errors:**

```
index [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Util\DateTimeFormat::utc() must be of the type string, null given, called in .../src/Protocol/ActivityPub/Processor.php on line 290" at .../src/Util/DateTimeFormat.php line 55 

{"exception":"TypeError: Argument 1 passed to Friendica\\Util\\DateTimeFormat::utc() must be of the type string, null given, called in .../src/Protocol/ActivityPub/Processor.php on line 290 and defined in .../src/Util/DateTimeFormat.php:55
Stack trace:
#0 .../src/Protocol/ActivityPub/Processor.php(290): Friendica\\Util\\DateTimeFormat::utc()
#1 .../src/Protocol/ActivityPub/Processor.php(382): Friendica\\Protocol\\ActivityPub\\Processor::createItem()
#2 .../src/Protocol/ActivityPub/Receiver.php(538): Friendica\\Protocol\\ActivityPub\\Processor::createActivity()
#3 .../src/Protocol/ActivityPub/Receiver.php(145): Friendica\\Protocol\\ActivityPub\\Receiver::processActivity()
#4 .../src/Module/ActivityPub/Inbox.php(67): Friendica\\Protocol\\ActivityPub\\Receiver::processInbox()
#5 .../src/BaseModule.php(233): Friendica\\Module\\ActivityPub\\Inbox->rawContent()
#6 .../src/App.php(711): Friendica\\BaseModule->run()
#7 .../index.php(44): Friendica\\App->runFrontend()
#8 {main}"} - 
{"file":null,"line":null,"function":null,"uid":"06a73a","process_id":1382087}
```

### Platform Info

Friendica Version:

2021.12-rc

Friendica Source: 
git

PHP version:
PHP 7.4

SQL version:
MariaDB 10.3

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #11091 

- Add logging for unexpected empty published key in activity

### CODE REVIEW

File: src/Protocol/ActivityPub/Processor.php [hunk 1]
```diff
@@ -287,7 +287,11 @@ public static function createItem($activity)
 
 		$item['uri'] = $activity['id'];
 
-		$item['created'] = DateTimeFormat::utc($activity['published']);
+		if (empty($activity['published'])) {
+			DI::logger()->notice('published key is empty for activity', ['activity' => $activity]);
```
Comment (annando) [inline src/Protocol/ActivityPub/Processor.php]: Possibly you could add a callstack?

Comment (MrPetovan) [reply src/Protocol/ActivityPub/Processor.php]: I don't see the point, this is the AP processor so the call stack will be straightforward from the AP inbox endpoints, for reference you can use [the one @AlfredSK provided in the corresponding issue](https://github.com/friendica/friendica/issues/11091#issue-1077552088).

Comment (annando) [reply src/Protocol/ActivityPub/Processor.php]: The processor can be called when fetching posts (thread autocomplete, relay) or when receiving posts.

**Comment by AlfredSK** [comment]
I have added some logging examples to the issue using the extended logging of this PR.

File: src/Protocol/ActivityPub/Processor.php (hunk 1 above)
Comment (MrPetovan) [reply src/Protocol/ActivityPub/Processor.php]: And the exception this PR addresses shows that this error happens when receiving, do you need to know if it would happen when fetching posts as well?

**Comment by MrPetovan** [comment]
This PR now covers `edited` as well, and a call stack has been added to the logging.
