### PR TITLE
Normalize BBCode hashtags links

### LINKED ISSUE #6124: "... is not a fully qualified URL, please use App->internalRedirect() instead"
Related to https://github.com/friendica/friendica/issues/6019

```
[13-Nov-2018 08:45:32 Europe/Berlin] PHP Fatal error:  Uncaught Friendica\Network\HTTPException\InternalServerErrorException: 'https://squeet.me/https://squeet.me/search?tag=Mobilität' is not a fully qualified URL, please use App->internalRedirect() instead in /src/Core/System.php:252
Stack trace:
#0 /src/App.php(1850): Friendica\Core\System::externalRedirect('https://squeet....')
#1 /src/App.php(1865): Friendica\App->internalRedirect('https://squeet....')
#2 /mod/redir.php(41): Friendica\App->redirect('https://squeet....')
#3 /src/LegacyModule.php(68): redir_init(Object(Friendica\App))
#4 /src/LegacyModule.php(39): Friendica\LegacyModule::runModuleFunction('init')
#5 [internal function]: Friendica\LegacyModule::init()
```

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #6124
Addresses https://github.com/friendica/friendica/issues/5913#issuecomment-440942527
Related to #5996

So far the policy around BBCOde hashtag links was pretty inconsistent. Most links properly encoded the search term included in the tag link, but ultimately the BBCode converter disregarded the link entirely in favor of the term that it wasn't encoding in the final URL.

This PR reverses the process, by not encoding the term when it's used to build a BBCode tag, but encoding it when the BBCode tag is converted to HTML.

Additionally, storing hashtags in the `term` table will stop adding the link URL that we can easily reconstruct ourselves.

Addon counterpart: https://github.com/friendica/friendica-addons/pull/776

### CODE REVIEW

File: include/items.php [hunk 1]
```diff
@@ -97,7 +97,7 @@ function add_page_info_data(array $data, $no_photos = false)
 			/// @TODO make a positive list of allowed characters
 			$hashtag = str_replace([" ", "+", "/", ".", "#", "'", "’", "`", "(", ")", "„", "“"],
 						["", "", "", "", "", "", "", "", "", "", "", ""], $keyword);
-			$hashtags .= "#[url=" . System::baseUrl() . "/search?tag=" . rawurlencode($hashtag) . "]" . $hashtag . "[/url] ";
+			$hashtags .= "#[url=" . System::baseUrl() . "/search?tag=" . $hashtag . "]" . $hashtag . "[/url] ";
```
Comment (annando) [inline include/items.php]: Why have you removed the "rawurlencode" here? And possibly you could instead work with a positive list, like suggested in the ```@todo```?

Comment (MrPetovan) [reply include/items.php]: Because this URL isn't meant to be displayed in a HTML context, we're building a BBCode tag that doesn't require any specific encoding.

On top of that, we are completely discarding the URL in favor of a rebuilt URL based on the hashtag term when we eventually convert to HTML, and at that point we are URL encoding.

And it wasn't in the scope of this PR but no, we can't work with a positive list of characters because there are accents and different alphabets (Japanese, Chinese, Arabic, Cyrillic,...) to take into account.
