### PR TITLE
categories of postings linked

### LINKED ISSUE #6865: Category labels in posts are not clickable
### Expected behavior
The green category labels in posts should be clickable and lead to the corresponding url. For example a
click on a green category label called "My Photos" should take me and anyone who clicks it to:
https://servername/profile/username?f=&category=My%20Photos

### Actual behavior
Right now the green category labels are not clickable. They are just sitting at the bottom of a post being only descriptive

### Steps to reproduce the problem
Go to any post that uses category labels and try clicking on the label. Nothing will happen.

### Friendica version you encountered the problem

2019.03-rc-1304

### PR DESCRIPTION
**Pull request by tobiasd**
With this PR we make categories of postings linked to the category overview in the profile of the author.

Should fix #6865

### CODE REVIEW

File: src/Content/Item.php [hunk 1]
```diff
@@ -42,10 +42,16 @@ public function determineCategoriesTerms(array $item)
 		$folders = [];
 		$first = true;
 
+		if (!empty($item['author-link'])) {
+			$url = $item['author-link'] . "?category=" . rawurlencode($savedFolderName);
```
Comment (AlfredSK) [inline src/Content/Item.php]: Undefined variable $savedFolderName produces a lot of notices.

Comment (AlfredSK) [reply src/Content/Item.php]: Fixed
