### PR TITLE
Fix mastodon v2 active month naming error

### LINKED ISSUE #12847: /api/v2/instance, API response not compatible with Mastodon
- [x] I have searched open and closed issues for duplicates

### Bug Description

In response to the api/v1/instance api call, the incorrect key is provided.  The key in the JSON response is "active_montly"
'usage': {'users': {'active_monthly': 7}}

The correct key is 'active_month', as documented: https://docs.joinmastodon.org/methods/instance/#v2
This was seen on servers reporting the version: '2.8.0 (compatible; Friendica 2023.03-dev)' in the api response.

### Steps to Reproduce

1.  make the api call 
2.  review result

Actual Result:

The response to the api call includes:
usage': {'users': {'active_monthly': 7}}

Expected Result:

usage': {'users': {'active_month': 7}}

### Platform Info

Friendica Version:  '2.8.0 (compatible; Friendica 2023.03-dev)'

### PR DESCRIPTION
**Pull request by HankG**
Corrects naming error of the active monthly users stat from `active_monthly` to correct `active_month`. 

Fixes #12847

### CODE REVIEW

File: src/Object/Api/Mastodon/InstanceV2/UserStats.php [hunk 1]
```diff
@@ -31,13 +31,13 @@
...
 	/** @var int */
-	protected $active_monthly = 0;
+	protected $active_month = 0;
 
 	/**
-	 * @param $active_monthly
+	 * @param $active_month
 	 */
-	public function __construct($active_monthly)
+	public function __construct($active_month)
```
Comment (MrPetovan) [inline src/Object/Api/Mastodon/InstanceV2/UserStats.php]: Please add a type hint `int` for this parameter.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Object/Api/Mastodon/InstanceV2/UserStats.php [hunk 2]
```diff
@@ -33,10 +33,10 @@ class UserStats extends BaseDataTransferObject
...
 	protected $active_month = 0;
 
-	/**
-	 * @param $active_month
-	 */
-	public function __construct($active_month)
+    /**
+     * @param int $active_month
+     */
+    public function __construct(int $active_month)
```
Comment (nupplaphil) [inline src/Object/Api/Mastodon/InstanceV2/UserStats.php]:
```suggestion
	/**
	 * @param int $active_month
	 */
	public function __construct(int $active_month)
```

**Review by nupplaphil — CHANGES_REQUESTED** [review]

File: src/Object/Api/Mastodon/InstanceV2/UserStats.php (hunk 2 above)
Comment (MrPetovan) [reply src/Object/Api/Mastodon/InstanceV2/UserStats.php]: So now PHPStorm doesn't add tabs anywhere 😅

Comment (nupplaphil) [reply src/Object/Api/Mastodon/InstanceV2/UserStats.php]: I'm using PHPStorm as well and normally - except for JSON files (like `composer.json`)  - the indentation check works fine

Comment (HankG) [reply src/Object/Api/Mastodon/InstanceV2/UserStats.php]: Sigh... @nupplaphil is there a config file you can throw me because I'm at wits end with these PHP IDEs and this tabs/spaces BS at this point :(.
