### PR TITLE
Fix registration

### LINKED ISSUE #4041: [Urgent] Unable to register new users
See this discussion:
[https://forum.friendi.ca/display/0b6b25a8125a297737e6a4e212566317](https://forum.friendi.ca/display/0b6b25a8125a297737e6a4e212566317)

At the moment it is not possible to register new users.

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #4041

The problem was a misconception on my part of the condition array in `dba::select()`, I thought I could just mention a field to check its boolean value, but the resulting condition associative array missed a field name key and a field value. Consequently, `Contact::createSelfForUserId()` always returned true when checking for existing rows, even if they haven't been created beforehand.

Since I looked at it so much, I also replaced all the `q()` calls with shiny new `dba` calls in `User::create` and enabled Exceptions for error handling.

PR for addons coming up.

### CODE REVIEW

File: mod/admin.php [hunk 1]
```diff
@@ -1587,8 +1594,8 @@ function admin_page_users(App $a)
 	/* get pending */
 	$pending = q("SELECT `register`.*, `contact`.`name`, `user`.`email`
 				 FROM `register`
-				 LEFT JOIN `contact` ON `register`.`uid` = `contact`.`uid`
-				 LEFT JOIN `user` ON `register`.`uid` = `user`.`uid`;");
+				 JOIN `contact` ON `register`.`uid` = `contact`.`uid`
```
Comment (annando) [inline mod/admin.php]: Why have you replaced the ```LEFT JOIN``` with ```JOIN```?

File: src/Model/Contact.php [hunk 2]
```diff
@@ -96,11 +96,11 @@ public static function getOStatusCountByGroupId($gid)
 	public static function createSelfFromUserId($uid)
 	{
 		// Only create the entry if it doesn't exist yet
-		if (dba::exists('contact', ['uid' => intval($uid), 'self'])) {
+		if (dba::exists('contact', ['uid' => $uid, 'self' => true])) {
```
Comment (annando) [inline src/Model/Contact.php]: Oh, yeah. Indeed, that code was not working. Do you think that we should change dba.php to make this work? Should be an easy task.

File: src/Model/User.php [hunk 3]
```diff
@@ -304,100 +280,83 @@ public static function create(array $data)
...
-				intval($netpublish)
-			);
-			if ($r === false) {
-				$result['message'] .= t('An error occurred creating your default profile. Please try again.') . EOL;
-				// Start fresh next time.
-				dba::delete('user', array('uid' => $newuid));
-				return $result;
-			}
+		// if somebody clicked submit twice very quickly, they could end up with two accounts
+		// due to race condition. Remove this one.
```
Comment (annando) [inline src/Model/User.php]: What about just creating an unique index on the nickname in the user table? This would be easier.

File: src/Model/User.php [hunk 4]
```diff
@@ -304,100 +280,83 @@ public static function create(array $data)
...
-				q("UPDATE `user` SET `allow_gid` = '%s' WHERE `uid` = %d",
-					dbesc("<" . $def_gid . ">"),
-					intval($newuid)
-				);
-			}
+		// Create a group with no members. This allows somebody to use it
+		// right away as a default group for new contacts.
+		$def_gid = Group::create($uid, t('Friends'));
+		if (!$def_gid) {
+			dba::delete('user', ['uid' => $uid]);
```
Comment (annando) [inline src/Model/User.php]: Packing this into a transaction and using "commit" if everything was okay - or "rollback" if not - would be the cleanest way. (But of course this here is better than what had been done before)

File: mod/admin.php (hunk 1 above)
Comment (MrPetovan) [reply mod/admin.php]: Because in some case, the pending list can end up being populated with the entire `contact` table.

File: src/Model/Contact.php (hunk 2 above)
Comment (MrPetovan) [reply src/Model/Contact.php]: No, it's more explicit this way.

File: src/Model/User.php (hunk 3 above)
Comment (MrPetovan) [reply src/Model/User.php]: Absolutely, it's in my DB suggested changes document.

File: src/Model/User.php (hunk 4 above)
Comment (MrPetovan) [reply src/Model/User.php]: You're again absolutely right.

File: mod/admin.php (hunk 1 above)
Comment (annando) [reply mod/admin.php]: In which cases could that be? ```LEFT JOIN``` in comparison to ```INNER JOIN``` allows for joins where the right side needn't to exist.

BTW: I would always prefer ```INNER JOIN``` instead of ```JOIN```.

Comment (MrPetovan) [reply mod/admin.php]: It happened to me yesterday while I was conducting registration tests, I refreshed the admin users page to approve the 5th or 6th account I created and the screen blew in my face with thousands of contact names in the pending list.

I don't think it is the normal case but if the contact and user related to a registration row don't exist, nothing *else* should turn up in the results of the pending users query.

Comment (annando) [reply mod/admin.php]: When the right side doesn't exist, the selected rows will be ```NULL``` - but there never will be more than one row. It can only be something different. I have to check this - especially if it does make sense here to use something different than an "inner join".

Comment (MrPetovan) [reply mod/admin.php]: Basically, we expect corresponding rows in `contact` and `user`, so the `LEFT JOIN` is unwarranted here even if it will work most of the time.

Comment (annando) [reply mod/admin.php]: I guess I know why the query had had problems in your case. I guess that it is expected to display the "self" contact - but "self" isn't queried.

I had a look at the git history. There wasn't any hint why it was realized as a "left join", so an "inner join" indeed was correct.

Only thing is: Please don't replace other "left join" - most of them are expected that way, I think :-)

Comment (MrPetovan) [reply mod/admin.php]: Ha ha, this isn't a crusade about `LEFT JOIN`, I changed this specific one because it gave me trouble. I wish I didn't have to spend time figuring out why my admin page was suddenly broken. Initially I thought that a bot registered thousands of accounts through the registration form temporary open for my tests, including harmful HTML that wouldn't have been properly escaped.

File: src/Model/User.php (hunk 3 above)
Comment (annando) [reply src/Model/User.php]: if you are not sure how to apply the changes to dbstructure.php, just ask.

Comment (MrPetovan) [reply src/Model/User.php]: I probably won't add anything myself until I submit my document to you.

Comment (annando) [reply src/Model/User.php]: Okay.
