### PR TITLE
Overhauling proxy_url/Fix encoded ampersand

### LINKED ISSUE #2925: Image URLs from Diaspora containing & are failing
Over the past couple of months, I experienced empty Diaspora posts. It was image posts whose image I couldn't see on my Friendica instance. A few of them were because the Diaspora instance hosting the image was unavailable, but not all of them were self-hosted.

And then tonight I found the issue. If the embedded image URL contains a `&` (like most Facebook image URLs), then this character is escaped as `&amp;` in the body field of the item. And once it gets processed by the bbcode parser, it ends up being the wrong URL because we don't directly show the provided URLs, instead we escape it one more time.

I'm not familiar with debugging the Diaspora protocol, so I've got a few questions:
- Does anyone else have this issue?
- Is there any way to log the raw requests from Diaspora servers?
- Are we performing any escape on our end when we receive the item from Diaspora? If yes, where? If now, it seems like we should unescape what we receive from Diaspora but I'm not comfortable with the idea.

Please tell me what you think.

### PR DESCRIPTION
**Pull request by Hypolite**
Fixes #2925

- Decode possible HTML entities in the input URL
- Add the safe extension for the shortpath as well

### CODE REVIEW

File: mod/proxy.php [hunk 1]
```diff
@@ -233,66 +233,87 @@ function proxy_init() {
...
-	if ((strlen($proxypath) > 250) AND $writemode)
-		return (hash("md5", $url));
-	elseif (strlen($proxypath) > 250)
-		return ($a->get_baseurl()."/proxy/".hash("md5", $url)."?url=".urlencode($url));
-	elseif ($writemode)
-		return ($path);
-	else
-		return ($proxypath.$size);
+	if ((strlen($proxypath) > 250) AND $writemode) {
+		return hash('md5', $url);
```
Comment (annando) [inline mod/proxy.php]: Shouldn't that be "shortpath"?

Comment (Hypolite) [inline mod/proxy.php]: Yes, definitely.

Comment (Hypolite) [inline mod/proxy.php]: Done.

The whole proxy algorithm looks sketchy, I'm going to do some more testing because it could be that local proxy cache folder is completely bypassed when the target URL produces a base64 encoded string longer than ~250 characters minus the string length of Friendica base URL + "/proxy/".
