### PR TITLE
Issue 9281: User export now exports data

### LINKED ISSUE #9281: Exported account data broken
### Expected behavior

If you export the account data from the settings, the exported files should contain the correct information.

### Actual behavior

Except of the "user" data block, the information is `null`. E.g.:

```
"contact":[{"id":null,"uid":null,"created":"0001-01-01 00:00:00","updated":"0001-01-01 00:00:00","self":null,"remote_self":null,"rel":null,"duplex":null,"network":null,"protocol":null,"name":null,"nick":null,"location":null,"about":null,"keywords":null,"gender":null,"xmpp":null,"attag":null,"avatar":null,"photo":null,"thumb":null,"micro":null,"site-pubkey":null,"issued-id":null,"dfrn-id":null,"url":null,"nurl":null,"addr":null,"alias":null,"pubkey":null,"prvkey":null,"batch":null,"request":null,"notify":null,"poll":null,"confirm":null,"subscribe":null,"poco":null,"aes_allow":null,"ret-aes":null,"usehub":null,"subhub":null,"hub-verify":null,"last-update":"0001-01-01 00:00:00","success_update":"0001-01-01 00:00:00","failure_update":"0001-01-01 00:00:00","failed":null,"name-date":"0001-01-01 00:00:00","uri-date":"0001-01-01 00:00:00","avatar-date":"0001-01-01 00:00:00","term-date":"0001-01-01 00:00:00","last-item":"0001-01-01 00:00:00","last-discovery":"0001-01-01 00:00:00",
```

and so on.

### Steps to reproduce the problem

* Go to the user settings
* export the account data to JSON file

### Friendica version you encountered the problem

2020.12-dev 04f993b6112361e9129ee4d25a1ff122a92fa92d

### PR DESCRIPTION
**Pull request by annando**
Fixes https://github.com/friendica/friendica/issues/9281

### CODE REVIEW

File: src/Module/Settings/UserExport.php [hunk 1]
```diff
@@ -162,9 +169,9 @@ private static function exportContactsAsCSV()
 		// write the table header (like Mastodon)
 		echo "Account address, Show boosts\n";
 		// get all the contacts
-		$contacts = DBA::select('contact', ['addr'], ['uid' => $_SESSION['uid'], 'self' => false, 'rel' => [1,3], 'deleted' => false]);
+		$contacts = DBA::select('contact', ['addr', 'url'], ['uid' => $_SESSION['uid'], 'self' => false, 'rel' => [1,3], 'deleted' => false]);
 		while ($contact = DBA::fetch($contacts)) {
-			echo $contact['addr'] . ", true\n";
+			echo ($contact['addr'] ? $contact['addr'] : $contact['url']) . ", true\n";
```
Comment (MrPetovan) [inline src/Module/Settings/UserExport.php:174]: Small readability improvement
```suggestion
			echo ($contact['addr'] ?: $contact['url']) . ", true\n"
```
