### PR TITLE
Hash the URL before using it as cache key in Util\Images::getInfoFromURLCached

### LINKED ISSUE #11248: Data too long for column 'k' at row 1
From @fabrixxm in https://github.com/friendica/friendica/issues/10353#issuecomment-957646427

> I've got a similar error:
> 
> File | Line | Function 
> -- | -- | -- 
> Database.php | 766 | e 
> 
> 
> **Data too long for column 'k' at row 1**
> ```
> callstack:
> Media::insert, Processor::storeAttachmentAsMedia, Processor::storeAttachments, Processor::createItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent, call_user_func
> 
> params:
> REPLACE `cache` (`k`, `v`, `expires`, `updated`) VALUES ('https://botusercontent.telegra.ph/ifttt/file/eyJmIjoiQWdBQ0FnUUFBeDBDVWJRMmRBQUNYRUpoZ1VHdllBdVJZQVVYeXU0d190N1lrMlBDM2dBQ1JhMHhHX0x4REZBWTBaX2NrQnhIV3dFQUF3SUFBM2tBQXlFRSIsIm0iOiJpbWFnZVwvanBlZyIsIm4iOiJwaG90by5qcGciLCJkIjoxNjM1ODYwOTEyfQ/8c78e7d4cc5abedf22/photo.jpg', 'a:8:{i:0;i:768;i:1;i:1024;i:2;i:2;i:3;s:25:\"width=\"768\" height=\"1024\"\";s:4:\"bits\";i:8;s:8:\"channels\";i:3;s:4:\"mime\";s:10:\"image/jpeg\";s:4:\"size\";i:133072;}', '2021-11-02 13:55:12', '2021-11-02 13:50:12')
> ```

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #11248 
- This prevents oversized URL from stunting the database cache

### CODE REVIEW

File: src/Util/Images.php [hunk 1]
```diff
@@ -184,12 +184,12 @@ public static function getInfoFromURLCached($url)
 			return $data;
 		}
 
-		$data = DI::cache()->get($url);
+		$data = DI::cache()->get('getInfoFromURL:' . sha1($url));
```
Comment (annando) [inline src/Util/Images.php]: For these situations I prefer a `$cachekey` variable that is used both when fetching and writing the cache. This ensures that the same cache key is used.

Comment (MrPetovan) [reply src/Util/Images.php]: Good point.

Comment (MrPetovan) [reply src/Util/Images.php]: Done.
