### PR TITLE
Like behavior fix/improvements

### LINKED ISSUE #2792: Highlight the "Like" link for liked posts/comments
When one clicks on the "Like" link on any publication, it should turn to "Unlike" immediately to acknowledge the action. If the action isn't successful, it should of course revert back to "Like".

When a post have been already liked, the "Like" link should already be changed to "Unlike". In that case, clicking on the "Unlike" link should immediately turn it to "Like" to acknowledge the action.

I'll look into the code hopefully this week-end to see if I can make the change myself. Not sure if it is a theme-specific change?

screen shot 2016-09-23 at 2 18 28 pm
Since I've already liked this post, the "like" link should read "unlinke" instead.

### PR DESCRIPTION
**Pull request by Hypolite**
Re-Fixes #2792

This PR is two-pronged:
- It makes sure that the like display is accurate by using `author-id` instead of the unreliable `contact-id`.
- It prevents `do_like()` from deleting other people's likes due to `contact-id` unreliability.

As an extra, it's no longer required to click twice on the event attendance buttons to switch state.

### CODE REVIEW

File: include/like.php [hunk 1]
```diff
@@ -18,155 +18,169 @@
...
 		$like_item_id = $like_item['id'];
 		proc_run(PRIORITY_HIGH, "include/notifier.php", "like", $like_item_id);
 
-		return true;
+		if (!$event_verb_flag || $like_item['verb'] == $activity) {
+			return true;
+		}
 	}
 
-	$uri = item_new_uri($a->get_hostname(),$owner_uid);
```
Comment (annando) [inline include/like.php]: Is this not needed?

Comment (Hypolite) [inline include/like.php]: I moved it in the item data array assignment.

Comment (annando) [inline include/like.php]: Ah, okay.

**Comment by Hypolite** [comment]
Thanks, I even set up a separate instance to test the remote login!

Please note this PR doesn't fix the wrongly set `contact-id` by some OStatus likes.
