### PR TITLE
Prevent post mirroring by blocked users

### LINKED ISSUE #13217: Blocked users can still distribute RSS feeds and mirror accounts
- [ x ] I have searched open and closed issues for duplicates

### Bug Description

Accounts that distribute RSS feeds or mirror other accounts have been blocked. 
The block does not prevent content from continuing to be shared. It only ensures that the user can no longer access the account.

Expected behaviour: Blocking not only prevents access to the account, but also prevents the distribution of content from other sources.

In order to intervene in a moderating capacity, the admin only has the option of deleting the account completely. This would be a very strong and, in this specific case, inappropriate intervention.

That it is a mistake is, of course, an assertion. It may also be a new feature.

### Platform Info

Friendica Version: stable

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

### PR DESCRIPTION
**Pull request by MrPetovan**
Fix #13217 

Additionally, prevent polling contact of blocked users.

### CODE REVIEW

File: src/Model/Item.php [hunk 1]
```diff
@@ -2333,16 +2334,15 @@ private static function autoReshare(array $item)
 			return;
 		}
 
-		$cdata = Contact::getPublicAndUserContactID($item['author-id'], $item['uid']);
```
Comment (annando) [inline src/Model/Item.php:2336]: Have you removed that line intentionally? Directly below you use the `$cdata` variable.

Comment (MrPetovan) [reply src/Model/Item.php:2336]: Look at the original code, the $cdata variable is initialized twice the same way. I removed the duplicate and added a new check, which the diff then superposes.

Comment (annando) [reply src/Model/Item.php:2336]: Oookay, that looks weird. For whatever reason some lines are duplicated.
