### PR TITLE
Remove RINO2

### LINKED ISSUE #4272: [Urgent] Upgrade defuse/php-encryption to version 2 to ditch mcrypt requirement
#4259 reintroduced an regression dependency to `mcrypt` : https://github.com/friendica/friendica/pull/4259#issuecomment-358521690

This is because we manually edited the `defuse/php-encryption:1.21` library files before moving them to Composer.

Version 2 fixes this dependency: https://github.com/defuse/php-encryption/blob/master/docs/UpgradingFromV1.2.md

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #4272 

Self-excludes with #4280

### CODE REVIEW

File: include/network.php [hunk 1]
```diff
@@ -488,7 +488,7 @@ function validate_url($url)
 	/// @TODO Really suppress function outcomes? Why not find them + debug them?
 	$h = @parse_url($url);
 
-	if ((is_array($h)) && (dns_get_record($h['host'], DNS_A + DNS_CNAME + DNS_PTR) || filter_var($h['host'], FILTER_VALIDATE_IP) )) {
+	if ((is_array($h)) && (@dns_get_record($h['host'], DNS_A + DNS_CNAME + DNS_PTR) || filter_var($h['host'], FILTER_VALIDATE_IP) )) {
```
Comment (zeroadam) [inline include/network.php]: Finally, freedom from these "accepted" errors :smile:

File: src/Protocol/DFRN.php [hunk 2]
```diff
@@ -465,7 +471,7 @@ public static function relocate($owner, $uid)
 		/* get site pubkey. this could be a new installation with no site keys*/
 		$pubkey = Config::get('system', 'site_pubkey');
 		if (! $pubkey) {
-			$res = Crypto::newKeypair(1024);
+			$res = FriendicaCrypto::newKeypair(1024);
```
Comment (zeroadam) [inline src/Protocol/DFRN.php]: I'm no expert here, is 1024 good enough?

Comment (MrPetovan) [reply src/Protocol/DFRN.php]: In general, no, [RSA-1024 can be broken](https://www.techworld.com/news/security/rsa-1024-bit-private-key-encryption-cracked-3214360/), but for our use where, after being almost securely transmitted, we store plaintext data on cheap hosting boxes for years, it should be enough.

File: mod/admin.php [hunk 3]
```diff
@@ -1336,7 +1336,7 @@ function admin_page_site(App $a)
 
 		'$relocate_url'		=> ['relocate_url', t("New base url"), System::baseUrl(), t("Change base url for this server. Sends relocate message to all Friendica and Diaspora* contacts of all users.")],
 
-		'$rino' 		=> ['rino', t("RINO Encryption"), intval(Config::get('system','rino_encrypt')), t("Encryption layer between nodes."), ["Disabled", "RINO1 (deprecated)", "RINO2"]],
+		'$rino' 		=> ['rino', t("RINO Encryption"), intval(Config::get('system','rino_encrypt')), t("Encryption layer between nodes."), ["Disabled", "RINO3"]],
```
[the remark this answers is not in the document]
Comment (MrPetovan) [reply mod/admin.php]: Yeah, I actually realized that while I was drifting into sleep!

**Comment by MrPetovan** [comment]
> Additionally I would prefer that in the admin settings a value of "2" would automatically be set to "1" and that RINO3 was marked as "experimental".
> 
> This should ensure that communication would still work and that we could test RINO3 without endangering the communication.

Unfortunately, like I explained in the PR, after we update the defuse/php-encryption in version 2, we can't keep encrypting the way it used to do in version 1 in RINO2. We can still decrypt existing RINO2 messages but we can't encrypt new ones.

So RINO3 really isn't a brand-new version but RINO2.1 with backward compatibility only for decrypting.

File: mod/admin.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (annando) [reply mod/admin.php]: Yeah, I know this as well. When you are reviewing my stuff and I'm so asleep that I can't really think anymore.

**Comment by annando** [comment]
Concerning this RINO stuff: it is some additional transport encryption. It is on top of the HTTPS connection encryption.

It does make sense - but surely can be solved in a better way.

**Comment by MrPetovan** [comment]
It makes sense communicating with/between HTTP-only servers, With HTTPS, signing is enough.

**Comment by annando** [comment]
Without trashing too much of your work: But I guess @fabrixxm once created RINO2, because mcrypt wasn't part of PHP anymore. When now RINO1 does work without installed mcrypt, we could simply default to version 1 again.

Diaspora does it better: Transmitting public data is unencrypted (only HTTPS) but signed by the sender, private stuff is encrypted by the sender.

Sometimes I really would like to trash our whole communication stack and use some Diaspora stuff to transport our own payload. This would help in many ways.

File: htconfig.php [hunk 4]
```diff
@@ -62,9 +62,9 @@
 
 // Server-to-server private message encryption (RINO) is allowed by default.
 // Encryption will only be provided if this setting is set to a non zero value
-// set to 0 to disable, 2 to enable, 1 is deprecated
+// set to 0 to disable, 3 to enable
```
Comment (annando) [inline htconfig.php]: Could you describe the other options as well?

Comment (MrPetovan) [reply htconfig.php]: I started a whole documentation page for RINO 😄

**Comment by annando** [comment]
Have you activated RINO3 on your system and are you running with this code? The communication between our two system seem to work, so that 2 to 3 will work (in some fallback mode).

Then I think we should accept the PR.

**Comment by MrPetovan** [comment]
> When now RINO1 does work without installed mcrypt, we could simply default to version 1 again.

I’m all for it, it would remove our current dependency to php-encryption.

**Comment by MrPetovan** [comment]
> Have you activated RINO3 on your system and are you running with this code?

Not yet, I was waiting for a review and for someone™️ to test two-ways RINO3 with my node. I’ll enable this code tonight if we don’t just scrap RINO2 entirely.

**Comment by tobiasd** [comment]
See #1683 for the RINO2 implementation

**Comment by annando** [comment]
If you don't mind trashing your work, then removing 2 and 3 completely would be fine for me.

**Comment by MrPetovan** [comment]
Of course not, I love removing stuff, remember? 😄

File: src/Protocol/DFRN.php (hunk 2 above)
Comment (MrPetovan) [reply src/Protocol/DFRN.php]: Turns out the users' RSA keys already are initialized with 4096 bits! This is only for the server, I'll leave it be.

File: src/Protocol/DFRN.php [hunk 5]
```diff
@@ -1291,31 +1294,13 @@ public static function deliver($owner, $contact, $atom, $dissolve = false)
 
 			switch ($rino_remote_version) {
 				case 1:
+				case 2:
```
[the remark this answers is not in the document]
Comment (MrPetovan) [reply src/Protocol/DFRN.php]: It's for the transition between new nodes with no RINO2 and legacy/stable nodes that still are advertising a RINO version 2. This code ensures that the following communication will be using the version 1 no matter what instead of nothing at all.

File: src/Protocol/DFRN.php [hunk 6]
```diff
@@ -1291,31 +1294,14 @@ public static function deliver($owner, $contact, $atom, $dissolve = false)
 
 			switch ($rino_remote_version) {
 				case 1:
-					// Deprecated rino version!
+				case 2:
```
Comment (annando) [inline src/Protocol/DFRN.php]: I guess you mustn't handle "2" here.

Comment (MrPetovan) [reply src/Protocol/DFRN.php]: After review, it appears you are right. The handshake with `dfrn_notify` apparently already takes care of agreeing on a specific RINO version.

**Comment by fabrixxm** [comment]
Yet I'm for drop RINO completely.

**Comment by MrPetovan** [comment]
YES, more deletion!

**Comment by fabrixxm** [comment]
:)
but I'm not joking. Imho, RINO was useful in a pre-let's encrypt era, when not everyone had the technical skill, time or money to get a verified certificate. Now most if not all of the main webservers are supported by LE tools, and many started to supports LE certificates natively.
With LE, shared hosting can (and started to) offer https out-of-the box.
So why we should support RINO infrastructure when webservers and curl can do it better than us using https, and can fix bug faster than us?
I'm not an expert, and maybe my point has some fails, but I don't see the need of server-to-server encryption when the message is transferred over https, and saved decrypted in db anyway...

**Comment by MrPetovan** [comment]
Yes, that was my point exactly when I was looking into encryption libraries yesterday!

**Comment by tobiasd** [comment]
Well, https is broken behond repair ;-)

**Comment by MrPetovan** [comment]
What do you mean?

**Comment by AlfredSK** [comment]
Possibly @tobiasd is speaking of the concept of trust in CAs.

**Comment by MrPetovan** [comment]
Gotcha. That is the purpose of the two featured PRs, we don't have to remove RINO altogether but if we opt to, it's ready!

**Comment by annando** [comment]
I will accept this PR. But the other one I will leave untouched yet, until we discussed it completely.

**Comment by MrPetovan** [comment]
It feels weird not having a pending pull request anymore, maybe I’ll spend some time with my family tonight 🤔

**Comment by annando** [comment]
And I guess I can finally work on my own issues :)

**Comment by zeroadam** [comment]
Horray! I just tested composer install and no more mcrypt dependency errors!!!! Now, to update my node!

**Comment by AlfredSK** [comment]
## Famous last words...
> _maybe I’ll spend some time with my family tonight_ 🤔

😂 sorry.

**Comment by MrPetovan** [comment]
I’m at the restaurant where my daughter keeps telling me she’s not talking to me when she is talking to my girlfriend. 🙄

I could have fixed the contact search instead!

**Comment by zeroadam** [comment]
😒

**Comment by MrPetovan** [comment]
Closes #1917
