### PR TITLE
Dropzone placeholder

### LINKED ISSUE #14680: Dropzone not working on "Mention" Button
- [x] I have searched open and closed issues for duplicates

### Bug Description

When i view a profile, right above is a "Mention"-Link. It opens a modal to create a new posting, mentioning this user.
The dropzone does not get initialized on this modal. All the classes are set, the script-link (from head.tpl) is there.
But dropzone does not initialize.

### Steps to Reproduce

1.  open a profile
2.  click on the "Mention" button right above
3.  try to add an image by drag&drop or click into the grey bar below the textarea

Actual Result:

no initialized dropzone

Expected Result:

dropzone just working as in comments and for new postings

### Platform Info

Friendica Version: develop commit 275b383be7

Friendica Source: git

PHP version: 8.3

SQL version:

Theme: frio

### PR DESCRIPTION
**Pull request by xundeenergie**
This PR adds a small textual placeholder for image-uploades, which get replaced by the bb-code from the upload to show the image.

The placeholder works better than the upload right now.

### CODE REVIEW

**Comment by xundeenergie** [comment]
the last commit enabled already the dropzone in dialog "mention-link"
fixes #14680

**Comment by xundeenergie** [comment]
How can i fix the failed check?

File: view/js/dropzone-factory.js [hunk 1]
```diff
@@ -23,14 +23,19 @@ var DzFactory = function (max_imagesize) {
 			dictRemoveFile: dzStrings.dictRemoveFile,
 			dictMaxFilesExceeded: dzStrings.dictMaxFilesExceeded,
 			accept: function(file, done) {
+					const targetTextarea = document.getElementById(textareaElementId);
+					if (targetTextarea.setRangeText) {
+						targetTextarea.setRangeText("\n[upload-"+file.name+"]\n",targetTextarea.selectionStart,targetTextarea.selectionEnd,"end");
```
Comment (MrPetovan) [inline view/js/dropzone-factory.js]:
```suggestion
						targetTextarea.setRangeText("\n[upload-" + file.name + "]\n", targetTextarea.selectionStart, targetTextarea.selectionEnd, "end");
```

File: view/js/dropzone-factory.js [hunk 2]
```diff
@@ -23,14 +23,19 @@ var DzFactory = function (max_imagesize) {
...
+					}
 				done();
 			},
 			init: function() {
 				this.on('success', function(file, serverResponse) {
 					const targetTextarea = document.getElementById(textareaElementId);
 					if (targetTextarea.setRangeText) {
 						//if setRangeText function is supported by current browser
-						targetTextarea.setRangeText(serverResponse);
+						let u = "[upload-"+file.name+"]";
```
Comment (MrPetovan) [inline view/js/dropzone-factory.js]:
```suggestion
						let u = "[upload-" + file.name + "]";
```

File: view/js/dropzone-factory.js [hunk 3]
```diff
@@ -23,14 +23,19 @@ var DzFactory = function (max_imagesize) {
...
+						targetTextarea.setRangeText(serverResponse, targetTextarea.value.indexOf(u), targetTextarea.value.indexOf(u)+u.length, "end");
```
Comment (MrPetovan) [inline view/js/dropzone-factory.js]:
```suggestion
						targetTextarea.setRangeText(serverResponse, targetTextarea.value.indexOf(u), targetTextarea.value.indexOf(u) + u.length, "end");
```

**Review by MrPetovan — CHANGES_REQUESTED** [review]
Please address the few code standards changes.

**Review by xundeenergie — COMMENTED** [review]
Codestyle ok

**Comment by xundeenergie** [comment]
Should i push the code to git.friendi.ca too, to get the failed check as ok?

**Comment by MrPetovan** [comment]
No, it's fine, the error has nothing to do with your code.

**Review by MrPetovan — APPROVED** [review]
