### PR TITLE
Show only the user's categories on their profile

### LINKED ISSUE #11234: How to clean up erroneous  categories?
Related to this issue https://github.com/friendica/friendica/issues/10552 (it never got any attention and would be great if it would be put on some waiting list): I just noticed that I have a lot of wrong categories displayed on my public profile page if logged off.

When I am logged in I see only the categories I use. If someone else looks at my profile page (or I log off) I see all categories on the server displayed there, some of which are used by someone else and some are categories I created erroneously (i.e. misspelled the name) and then stopped using them so they don't contain any posts anymore. If I click them they show nothing but they are still displayed.

Can I clean them out somehow? AFAIK there is no frontend for category editing/removal but maybe I can do it via API or directly in the database?

Logged in (correct categories):
image

Logged off (includes some junk):
image

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #11234 

Long story short, we were using `local_user()` to filter the category list, which would only correctly show the user's categories on its own profile page. It would also show their own categories on every other profile, but only if the visited profile user activated the additional feature themselves.

To retrieve the categories, we perform a query on the `category-view` view and the condition on the integer `uid` field used the value `false` that `local_user()` returns for non-logged users. While I haven't been able to reproduce @SpcCw 's specific issue, I'm not surprised it failed spectacularly for them by showing only node-wide categories in which there were no posts at all (otherwise `uid` would be set).

### CODE REVIEW

File: src/Module/Profile/Status.php [hunk 1]
```diff
@@ -118,7 +118,7 @@ protected function content(array $request = []): string
 		$commvisitor = $commpage && $remote_contact;
 
 		DI::page()['aside'] .= Widget::postedByYear(DI::baseUrl() . '/profile/' . $profile['nickname'] . '/status', $profile['profile_uid'] ?? 0, true);
-		DI::page()['aside'] .= Widget::categories(DI::baseUrl() . '/profile/' . $profile['nickname'] . '/status', XML::escape($category));
+		DI::page()['aside'] .= Widget::categories($profile['uid'], DI::baseUrl() . '/profile/' . $profile['nickname'] . '/status', $category);
```
Comment (tobiasd) [inline src/Module/Profile/Status.php:121]: The XML::escape is not needed any more at this place?

Comment (MrPetovan) [reply src/Module/Profile/Status.php:121]: Nope, we never actually output this user-provided value, and even if we did, the template engine is escaping special characters by default. It's a remnant of the legacy misled input-escaping strategy that leads to a lot of unpleasantness, like storing HTML-escaped values in the database where it absolutely doesn't matter.

Comment (annando) [reply src/Module/Profile/Status.php:121]: We pass this value all through the widget when it finally is used in `widget/filter.tpl` as `{{$base}}`. The escaping functionally would perform some `htmlentity` call. But I think we have to perform some `urlencode()` here.
