### PR TITLE
Suppress a couple MemcachedException

### LINKED ISSUE #11343: Memcached key format errors
Memcache keys are limited to 250 characters, so we can't really put a URL in them, but we definitely can't put _these_ URLs.
```
2022-03-15T11:25:04Z worker [ERROR]: Uncaught Exception Friendica\Core\Cache\Exception\CachePersistenceException: "Cannot get cache entry with key apcontact:getByURL:https://horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi" at /home/friendica/friendica/friendica/src/Core/Cache/Type/MemcachedCache.php line 122 {"exception":"MemcachedException: A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE in /home/friendica/friendica/friendica/src/Core/Cache/Type/MemcachedCache.php:122
Stack trace:
#0 /home/friendica/friendica/friendica/src/Model/APContact.php(172): Friendica\\Core\\Cache\\Type\\MemcachedCache->get()
#1 /home/friendica/friendica/friendica/src/Protocol/ActivityPub.php(147): Friendica\\Model\\APContact::getByURL()
#2 /home/friendica/friendica/friendica/src/Network/Probe.php(353): Friendica\\Protocol\\ActivityPub::probeProfile()
#3 /home/friendica/friendica/friendica/src/Model/Contact.php(2147): Friendica\\Network\\Probe::uri()
#4 /home/friendica/friendica/friendica/src/Worker/UpdateContact.php(35): Friendica\\Model\\Contact::updateFromProbe()
#5 [internal function]: Friendica\\Worker\\UpdateContact::execute()
#6 /home/friendica/friendica/friendica/src/Core/Worker.php(497): call_user_func_array()
#7 /home/friendica/friendica/friendica/src/Core/Worker.php(387): Friendica\\Core\\Worker::execFunction()
#8 /home/friendica/friendica/friendica/src/Core/Worker.php(112): Friendica\\Core\\Worker::execute()
#9 /home/friendica/friendica/friendica/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()
#10 {main}

Next Friendica\\Core\\Cache\\Exception\\CachePersistenceException: Cannot get cache entry with key apcontact:getByURL:https://horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi in /home/friendica/friendica/friendica/src/Core/Cache/Type/MemcachedCache.php:122
Stack trace:
#0 /home/friendica/friendica/friendica/src/Model/APContact.php(172): Friendica\\Core\\Cache\\Type\\MemcachedCache->get()
#1 /home/friendica/friendica/friendica/src/Protocol/ActivityPub.php(147): Friendica\\Model\\APContact::getByURL()
#2 /home/friendica/friendica/friendica/src/Network/Probe.php(353): Friendica\\Protocol\\ActivityPub::probeProfile()
#3 /home/friendica/friendica/friendica/src/Model/Contact.php(2147): Friendica\\Network\\Probe::uri()
#4 /home/friendica/friendica/friendica/src/Worker/UpdateContact.php(35): Friendica\\Model\\Contact::updateFromProbe()
#5 [internal function]: Friendica\\Worker\\UpdateContact::execute()
#6 /home/friendica/friendica/friendica/src/Core/Worker.php(497): call_user_func_array()
#7 /home/friendica/friendica/friendica/src/Core/Worker.php(387): Friendica\\Core\\Worker::execFunction()
#8 /home/friendica/friendica/friendica/src/Core/Worker.php(112): Friendica\\Core\\Worker::execute()
#9 /home/friendica/friendica/friendica/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()
#10 {main}"} - {"file":null,"line":null,"function":null,"uid":"dc28dd","process_id":9046}
```

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #11343 

- Replace URL by uri-id in apcontact
- Replace date with a space and nurl by nick and Zulu time in mod/poco

### CODE REVIEW

File: mod/poco.php [hunk 1]
```diff
@@ -121,10 +122,12 @@ function poco_init(App $a) {
 			if (isset($contact['account-type'])) {
 				$contact['contact-type'] = $contact['account-type'];
 			}
-			$about = DI::cache()->get("about:" . $contact['updated'] . ":" . $contact['nurl']);
+
+			$cacheKey = 'about:' . $contact['nick'] . ':' . DateTimeFormat::utc($contact['updated'], DateTimeFormat::ATOM);
```
Comment (annando) [inline mod/poco.php:126]: The `nick` field is not unique. Of course it is unlikely that the `updated` date is the same for two contacts with the same `nick`, but nonetheless it is better to take some different value.

Comment (MrPetovan) [reply mod/poco.php:126]: The nick is unique among the local users which this cache key is about. About, get it? 😜

Comment (annando) [reply mod/poco.php:126]: Looking at that code fragment, I guess we can fully omit the caching here.

Comment (MrPetovan) [reply mod/poco.php:126]: It's because of the `BBCode::convert` that's potentially expensive. Why remove caching from a public endpoint that can possibly be abused?
