### PR TITLE
Issue 7223: Don't strip links

### LINKED ISSUE #7223: Don't strip hyperlinks over ActivityPub
This is an enhancement request, not a bug.

### Expected behavior

If you enter a url in a post in Friendica, the post will contain a hyperlink to that url. The link text may be different from the url. When this post is published to e.g. Twitter, the hyperlink is deconstructed and a plain text version with the link text and the url is sent. That's ok, because Twitter doesn't support hyperlinks.

When publishing this post over ActivityPub, to e.g. Mastodon or Pleroma, I do expect the hyperlink to remain as-is in the content, since both support hyperlinks.

### Actual behavior

When the post is sent to Mastodon or Pleroma over ActivityPub, the hyperlink is deconstructed into the link text and url and sent as plain text anyway. At least, that is how it appears to the receiving user.

### Steps to reproduce the problem

Create a post on Friendica with a url and a link text that differs from the url. Target a user on Mastodon or Pleroma. As the receiving user, see that the link text is placed before the url.

Optionally create a similar post on Pleroma with a hyperlink. Target a user on Mastodon. See as the receiving user that you have received a post where the link text is clickable and takes you to the url.

### Friendica version you encountered the problem

2019.06-rc or earlier on social.isurf.ca

_thanks for your attention_

### PR DESCRIPTION
**Pull request by annando**
Fixes #7223

### CODE REVIEW

File: src/Content/Text/BBCode.php [hunk 1]
```diff
@@ -985,16 +985,9 @@ private static function convertShareCallback(array $attributes, array $author_co
 				$text = ($is_quote_share? '<br />' : '') . '<p>' . html_entity_decode('&#x2672; ', ENT_QUOTES, 'UTF-8') . ' ' . $author_contact['addr'] . ': </p>' . "\n" . $content;
 				break;
 			case 7: // statusnet/GNU Social
+			case 9:
```
Comment (MrPetovan) [inline src/Content/Text/BBCode.php]: Please add the network name in a comment.
