### PR TITLE
fix missing space in DE translation

### LINKED ISSUE #15464: Mail notification missing space in subject
- [x] I have searched open and closed issues for duplicates

### Bug Description

Email notifications, at least in the German translation, are missing a space in the subject line of the mail.

Image

The missing space is between `Meldung]` and the actual subject `Du hast`.

### Steps to Reproduce

Get a mail about a new contact.

Actual Result -> Space is missing

Expected Result -> Space added

### Platform Info

Friendica Version: 2026.01

### PR DESCRIPTION
**Pull request by tobiasd**
closes #15464

### CODE REVIEW

File: view/lang/de/strings.php [hunk 1]
```diff
@@ -3012,9 +3012,9 @@ function string_plural_select_de($n){
 $a->strings['You\'ve received [url=%1$s]an introduction[/url] from %2$s.'] = 'Du hast eine [url=%1$s]Kontaktanfrage[/url] von %2$s erhalten.';
 $a->strings['You may visit their profile at %s'] = 'Hier kannst du das Profil betrachten: %s';
 $a->strings['Please visit %s to approve or reject the introduction.'] = 'Bitte besuche %s, um die Kontaktanfrage anzunehmen oder abzulehnen.';
-$a->strings['%s You have a new friend'] = '%sDu hast einen neuen Kontakt';
+$a->strings['%s You have a new friend'] = '%s Du hast einen neuen Kontakt';
 $a->strings['%1$s is your friend at %2$s'] = '%1$s ist dein Freund bei %2$s';
-$a->strings['%s You have a new follower'] = '%sDu hast einen neuen Kontakt';
+$a->strings['%s You have a new follower'] = '%s Du hast einen neuen Kontakt';
 $a->strings['You have a new follower at %2$s : %1$s'] = 'Du hast einen neuen Kontakt auf %2$s: %1$s';
 $a->strings['%s Friend suggestion received'] = '%sKontaktvorschlag erhalten';
```
Comment (annando) [inline view/lang/de/strings.php]: Here is some space missing as well.

**Review by annando — CHANGES_REQUESTED** [review]
There is an additional line with a missing space.

**Comment by tobiasd** [comment]
Fixed the missing space and added the DE translations for the new strings.
