### PR TITLE
Issue 11553: Reliably return the user's contacts

### LINKED ISSUE #11553: Show which user I'm displaying follows/ followers for in Tusky
- [x] I have searched open and closed issues for duplicates

### Bug Description

See https://github.com/tuskyapp/Tusky/issues/2538. The list of followers and followed in Tusky is empty. It does work with a Mastodon server though (so I believe it's a friendica issue).

### Steps to Reproduce

See https://github.com/tuskyapp/Tusky/issues/2538. 

Friendica Version: 2022.03, docker image

### PR DESCRIPTION
**Pull request by annando**
Fixes #11553

### CODE REVIEW

File: src/Module/Api/Mastodon/Accounts/Followers.php [hunk 1]
```diff
@@ -55,32 +56,59 @@ protected function rawContent(array $request = [])
...
-			$params['order'] = ['cid'];
-		}
-
-		$accounts = [];
-
-		$followers = DBA::select('contact-relation', ['relation-cid'], $condition, $params);
-		while ($follower = DBA::fetch($followers)) {
-			self::setBoundaries($follower['relation-cid']);
-			$accounts[] = DI::mstdnAccount()->createFromContactId($follower['relation-cid'], $uid);
+		if (false && $id == Contact::getPublicIdByUserId($uid)) {
```
Comment (MrPetovan) [inline src/Module/Api/Mastodon/Accounts/Followers.php]: Please remove debug code, this condition is always false and as a result the first statement of the `if` will never be executed.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Module/Api/Mastodon/Accounts/Followers.php (hunk 1 above)
Comment (annando) [reply src/Module/Api/Mastodon/Accounts/Followers.php]: Ooops ...

**Review by MrPetovan — APPROVED** [review]
