### PR TITLE
Issue 14275: Avoid "Data too long" error

### LINKED ISSUE #14275: DB Error: Data too long for column 'filename' at row 1
- [ x] I have searched open and closed issues for duplicates

### Bug Description

I have e few entries with description as in the subject. The error says:

`Data too long for column 'filename' at row 1
`
`INSERT INTO `photo` (`uid`, `contact-id`, `guid`, `resource-id`, `hash`, `created`, `edited`, `filename`, `type`, `album`, `height`, `width`, `datasize`, `blurhash`, `data`, `scale`, `photo-type`, `profile`, `allow_cid`, `allow_gid`, `deny_cid`, `deny_gid`, `desc`, `backend-class`, `backend-ref`) VALUES (0, 212481, 'e6e6686439eb35b7', '19861422006686439e673f4056884348', 'aacc09b62b5378614aed1ff1b630e278', '2024-07-04 06:39:26', '2024-07-04 06:39:26', '449331361_490825080129006_7838707475878528745_n.jpg?stp=dst-jpg_s400x400&_nc_cat=1&ccb=1-7&_nc_sid=3fd06f&_nc_ohc=msK5TnCdnPEQ7kNvgF1NGT_&_nc_ht=scontent-zrh1-1.cdninstagram.com&gid=AqTkzK4ekF9RGD4qG22-3a7&oh=00_AYBz6C2RULXfOjGmng7eHrq-aWR-FLLBmX5VCJMTYxWkUA&oe=668C1A03', 'image/jpeg', 'Contact Photos', 48, 48, 3023, '|5AJi}-?0056~C?HkERjIT-co|.9xuMxM_WTt7tS2{kr^0-9XAWZSPNGV?-%tQxvWXM_V@xZogS5%Mog%2t69uE2xEslofXoogr=enR%S2bca~V?WSRjkDf8nhn$jrofW?^+WE9ZM_xaxuogWBRi-7niIqNHadjYj[kCWX', '', 6, 20, 0, '', '', '', '', '', 'Filesystem', '2073867758178a4b971da045916ea54be2630bdc913dfdb364f9ba96acdd118c')`

### Platform Info

Friendica Version: 2024.06-fpm-rc - 1565
Friendica Source:  Docker image
PHP version: 8.1.29
SQL version: MariaDB 11.4.2-MariaDB-ubu2404

### PR DESCRIPTION
**Pull request by annando**
Fixes #14275

### CODE REVIEW

File: src/Model/Photo.php [hunk 1]
```diff
@@ -476,6 +476,8 @@ public static function store(Image $image, int $uid, int $cid, string $rid, stri
 			'backend-ref' => $backend_ref
 		];
 
+		$fields = DI::dbaDefinition()->truncateFieldsForTable('photo', $fields);
```
Comment (MrPetovan) [inline src/Model/Photo.php:480]: Shouldn't this be automatically called in `Database->update` and `Database->insert`?

Comment (annando) [reply src/Model/Photo.php:480]: Since this will have a (small) impact on the performance, I would like to do this only at some dedicated places.
