### PR TITLE
Better curl error during install.

### LINKED ISSUE #3629: nginx: URL rewrite test failed while browsing test URL is successful
Hi,

I'm trying to revive a Docker container for friendica: https://github.com/mkaag/docker-friendica. This container is based on Nginx. Currently, I have a functioning Friendica. But... I need to comment out some check in the install.php.

In the context of the `install.php`, the test for URL rewriting (`/install/testrewrite`) failed, while pointing directly my browser to this page return the expected "ok".

Looking at the logs, I found that error.log contains such errors:
```
2017/08/12 23:22:03 [error] 23#0: *17 open() "/usr/share/nginx/html/install/testrewrite" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /install/testrewrite HTTP/1.1", host: "localhost"
```

I suspect some rewriting rule is false because there is no reason to look under `/usr/share/nginx/html` while friendica is installed under `/opt/friendica`. Do you have any idea how to solve this?
The config is: https://github.com/mkaag/docker-friendica/blob/master/build/nginx.conf

PS: I'm not familiar with Nginx.

### PR DESCRIPTION
**Pull request by astifter**
Fixes #3629 by providing proper errors to the user.

### CODE REVIEW

File: src/Util/Network.php [hunk 1]
```diff
@@ -36,7 +36,13 @@ class Network
 	 */
 	public static function fetchUrl($url, $binary = false, &$redirects = 0, $timeout = 0, $accept_content = null, $cookiejar = 0)
 	{
-		$ret = self::curl(
+		$ret = fetchUrlFull($url, $binary, $redirects, $timeout, $accept_content, $cookiejar);
+
+		return($ret['body']);
```
Comment (MrPetovan) [inline src/Util/Network.php]: Code Standards: Remove parentheses from language constructs (include, return). I know you didn't write it, but I'd like to bring the whole code base to code standards.

File: src/Util/Network.php [hunk 2]
```diff
@@ -36,7 +36,13 @@ class Network
...
+	}
+	public static function fetchUrlFull($url, $binary = false, &$redirects = 0, $timeout = 0, $accept_content = null, $cookiejar = 0)
```
Comment (MrPetovan) [inline src/Util/Network.php]: Please add a space before the function declaration, as well as a Doxygen doc block similar to the one above the function declaration you're taking from.

**Comment by AlfredSK** [comment]
We introduced a bug with this PR. I referenced the issue I created.
