### PR TITLE
Use correct request parameter type for poke privacy

### LINKED ISSUE #9306: Poking ACL selection for private pokes is wrong
### Bug Description

When poking some contact privately, the poke should be delivered only to that account. Instead it is delivered to the ACL _default_ group of contacts. Also the poked person is not mentioned it seems.

Here is the source of the poke.

```
[url=https://social.diekershoff.de/profile/tobias]Tobias[/url] stupste [url=]Michael Vogel[/url]
```

### Steps to Reproduce

0. Define a default contact group for your postings in the settings, maybe... I have one
1. Start to poke somebody
2. Limit the audience to private
3. Do the poking

Actual Result:

The poke is posted to the default ACL group.

Expected Result:

Having the poke only distributed to the poked contact.

### Screenshots

friendica-poke

### Platform Info

Friendica 2020.12-devf

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #9306 
Blocked by #9694 for test fix

### CODE REVIEW

File: src/Module/Contact/Poke.php [hunk 1]
```diff
@@ -44,14 +44,14 @@ public static function post(array $parameters = [])
...
-		$contact = DBA::selectFirst('contact', ['id', 'name'], ['id' => $parameters['id'], 'uid' => local_user()]);
+		$contact = DBA::selectFirst('contact', ['id', 'name', 'url'], ['id' => $parameters['id'], 'uid' => local_user()]);
 		if (!DBA::isResult($contact)) {
 			return self::postReturn(false);
 		}
 
 		$a = DI::app();
 
-		$private = (!empty($_GET['private']) ? intval($_GET['private']) : Model\Item::PUBLIC);
+		$private = !empty($_POST['private']) ? Model\Item::PRIVATE : Model\Item::PUBLIC;
```
Comment (annando) [inline src/Module/Contact/Poke.php:54]: Why not `_REQUEST` to handle both `_POST` and `_GET`?

Comment (annando) [reply src/Module/Contact/Poke.php:54]: I just saw, it is in the `post` section, so `_POST` is fin.

Comment (MrPetovan) [reply src/Module/Contact/Poke.php:54]: Because the rest of the function uses `$_POST` and I didn’t want to spend too much time on a feature I believe should be removed.
