### PR TITLE
Bug/fix diaspora attachment links

### LINKED ISSUE #3163: Attached URL OEmbed: HTTP Code 302 should be followed
Currently, Friendica is displaying a nice version of the first URL it finds in any post, the same way Facebook or Twitter do. However, the OEmbed retrieval process stops at the first response, which ends up showing 302 redirections:

screen shot 2017-02-14 at 4 55 00 pm

https://friendica.mrpetovan.com/display/d4e2bbc0d51e01342b53782bcb452bd5

I believe it's just a matter of setting curl `FOLLOW_LOCATION` setting to `true` in the OEmbed probe.

### PR DESCRIPTION
**Pull request by Hypolite**
In certain cases (like medium.com links), `ParseUrl::getSiteInfo` teamed up with `original_url` to send large numbers of duplicate requests that ended up breaking the request limit and return a "302 Found" result that would be added to posts in the footer.

Deduping `ParseUrl::getSiteInfo` and `original_url` behaviors as well as getting rid of the unnecessary `ParseUrl::getSiteInfo` HEAD requests seem to fix this particular issue.

Fixes #3163

### CODE REVIEW

**Comment by Hypolite** [comment]
Reviewers: [This is the only interesting bit in this PR](https://github.com/friendica/friendica/pull/3171/commits/432587464ce16dff513ed2de340fa3437dbe45aa).

File: include/network.php [hunk 1]
```diff
@@ -670,42 +670,69 @@ function fix_contact_ssl_policy(&$contact,$new_policy) {
...
+ * through HTTP code or meta refresh tags. Stops after 10 redirections.
+ *
+ * @see ParseUrl::getSiteinfo
+ *
+ * @param string $url
+ * @param int $depth
+ * @param bool $fetchbody
+ * @return string
+ */
+function original_url($url, $depth = 1, $fetchbody = false) {
```
Comment (rabuzarus) [inline include/network.php]: A suggestion:

I think it would be better to have the `depth` parameter at the end because it is a counter for internal use. (`function original_url($url, $fetchbody = false, $depth = 1) {`

I looked through the code (and addons) and it seems that it needs only a change in the function itself

Comment (annando) [inline include/network.php]: I second that.

Comment (Hypolite) [inline include/network.php]: Both parameters are internal, exchanging their place wouldn't change anything, and you were able to verify it.

If anything, the `$fetchbody` parameter should be removed and the function reworked to limit the amount of extraneous `curl` calls, but this isn't in the scope of this PR.

File: include/network.php [hunk 2]
```diff
@@ -670,42 +670,69 @@ function fix_contact_ssl_policy(&$contact,$new_policy) {
...
+
+/**
+ * @brief Returns the original URL of the provided URL
+ *
+ * This function strips tracking query params and follows redirections, either
+ * through HTTP code or meta refresh tags. Stops after 10 redirections.
+ *
+ * @see ParseUrl::getSiteinfo
+ *
+ * @param string $url
```
Comment (Hypolite) [inline include/network.php]: Of course.

File: include/network.php (hunk 1 above)
Comment (annando) [inline include/network.php]: Okay. I had thought at first that you introduced this parameter.

**Comment by annando** [comment]
I just realized that this check for tracking parameters has to be done after expanding the url with "original_url" as well. If someone puts a link with tracking parameters through a shortlink service, these parameters won't be replaced by now.

**Comment by Hypolite** [comment]
Both ˋoriginal_url()` and `ParseUrl::getSiteInfo()` call to `strip_tracking_params()` for each redirection, so this is already taken care of 🙂
