### PR TITLE
Fix photo-upload and croping #5411

### LINKED ISSUE #5411: Profile Photo Upload/Crop Broken
When uploading a picture a broken croping dialog is shown:
screenshot_2018-07-19 friendica social network profile_photo 1
I think this happens because in https://github.com/friendica/friendica/blob/develop/mod/profile_photo.php#L237 _$imagecrop_ is tested in the wrong direction. 

When I try to use a already uploaded image as profile image the link to /profile_photo/use/<image-hash> displays a notice "Image uploaded..." and the photo upload dialog is shown:
screenshot_2018-07-19 friendica social network profile_photo
This happens because the user is not forwared to /profile_picture/use/<image-hash>.

I have a PR request prepared, please verify.

### PR DESCRIPTION
**Pull request by astifter**
This fixes #5411, please verify.

### CODE REVIEW

File: mod/profile_photo.php [hunk 1]
```diff
@@ -221,7 +218,7 @@ function profile_photo_content(App $a)
 				Worker::add(PRIORITY_LOW, "Directory", $url);
 			}
 
-			goaway(System::baseUrl() . '/profiles');
+			goaway($url);
```
Comment (MrPetovan) [inline mod/profile_photo.php]: Where is `$_SESSION[ 'my_url']` set and couldn't it be reconstructed instead of being stored in session?

File: mod/profile_photo.php [hunk 2]
```diff
@@ -234,7 +231,7 @@ function profile_photo_content(App $a)
 	);
 
 
-	if (!empty($imagecrop)) {
+	if (empty($imagecrop)) {
```
Comment (MrPetovan) [inline mod/profile_photo.php]: Good catch! 👍

File: mod/profile_photo.php (hunk 1 above)
Comment (astifter) [reply mod/profile_photo.php]: Maybe, I was just using whats there. Have no idea how its set...

Comment (MrPetovan) [reply mod/profile_photo.php]: Few things are called “my_url” in the project. If you don’t know how to search the whole project on your computer, you can do it in GitHub in the search bar at the top of the desktop website.

Comment (astifter) [reply mod/profile_photo.php]: _I'm a 40 year old Linux-C-Developer. Just for further reference and as a soft of introduction. :)_

I have searched (grep'ed!) for where the session parameter is set but I'm unclear where that might be. I have changed that to the same construct that is used everywhere else.
