### PR TITLE
Issue 11034: Use the profile photo for local users

### LINKED ISSUE #11034: Profile image cannot be changed
### Bug Description

Changing the profile picture is not possible. The info bubble about the STRG+R reload to bypass the cache is shown, but the picture is not updated.

### Steps to Reproduce

You can either upload a pic directly or use one from your gallery. Both ways lead to the shown notification bubble, none updates your profile picture.

Actual Result:

The profile picture is not updated.

Expected Result:

The new profile picture should be used.

### Platform Info

Friendica Version: 2021.12-dev b03b1fe3671e06fde5e85081ed4186f3dd8fa2d6

### PR DESCRIPTION
**Pull request by annando**
Fixes #11034 by simply using the photo record that is marked as "profile" for local users.

### CODE REVIEW

File: src/Model/Contact.php [hunk 1]
```diff
@@ -1913,7 +1913,14 @@ public static function updateAvatar(int $cid, string $avatar, bool $force = fals
 			$avatar = self::getDefaultAvatar($contact, Proxy::SIZE_SMALL);
 		}
 
-		if (in_array($contact['network'], [Protocol::FEED, Protocol::MAIL]) || DI::config()->get('system', 'cache_contact_avatar')) {
+		$cache_avatar = DI::config()->get('system', 'cache_contact_avatar');
+
+		// Local contact avatars don't need to be cached
+		if ($cache_avatar && Network::isLocalLink($contact['url'])) {
+			$cache_avatar = !DBA::exists('contact', ['nurl' => $contact['nurl'], 'self' => true]);
+		}
```
Comment (MrPetovan) [inline src/Model/Contact.php:1921]: This can be rewritten as a one-liner:
```suggestion
		// Local contact avatars don't need to be cached
		$cache_avatar = 
			DI::config()->get('system', 'cache_contact_avatar')
			&& Network::isLocalLink($contact['url'])
			&& !DBA::exists('contact', ['nurl' => $contact['nurl'], 'self' => true]);
```

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Model/Contact.php (hunk 1 above)
Comment (annando) [reply src/Model/Contact.php:1921]: I know. But this doesn't really increase readability.

Comment (MrPetovan) [reply src/Model/Contact.php:1921]: I disagree, in my version the `$cache_avatar` flag is only set once, and never accessed before it's actually useful.

Comment (annando) [reply src/Model/Contact.php:1921]: I'm not so much in multi-line "one-liners" because I always lose the focus when I'm trying to read them. Yes, the variable is only written once in your version, but I think my server is more readable.

Comment (MrPetovan) [reply src/Model/Contact.php:1921]: I guess we need a third pair of eyes then. @nupplaphil @tobiasd @fabrixxm ?

Comment (tobiasd) [reply src/Model/Contact.php:1921]: For me annandos version is more readable. The compacted version has lost ease of reading by connecting all the boolean statements into one.

Comment (fabrixxm) [reply src/Model/Contact.php:1921]: While at first I would prefer @MrPetovan version, on a secon read @annando is more clear on the intent to me.

Comment (MrPetovan) [reply src/Model/Contact.php:1921]: Thanks, folks!

**Review by MrPetovan — APPROVED** [review]
