### PR TITLE
Fix OAuth Redirect Url Scrubbing

### LINKED ISSUE #13556: OAuth login: "Entity could not be processed"
Seen with both Kaiteki (https://github.com/Kaiteki-Fedi/Kaiteki/issues/448) and Relatica (https://gitlab.com/mysocialportal/relatica/-/issues/48): Login to 2023.09RC instances seems not possible anymore. Error message:

tempFileForShare_20231018-093120

This seems related to https://github.com/andstatus/andstatus/issues/569 and maybe (?) https://github.com/friendica/friendica/pull/12719 ; I've seen this problem before but the error message itself is rather brief.

### PR DESCRIPTION
**Pull request by HankG**
Fixes #13556  by changing how the redirect URIs are scrubbed. The original fixes for these problems to account for query parameters on buffer URIs broke it into constituents and then reassembled the scheme, host, and path. This method produces several problems that caused failures in the OAuth initial authorization process. First, it strips off port numbers in reconstruction. Therefore an app that uses port numbers will never have a matching URI. Second, it converted hosts to all lower case. Therefore an app that used mixed case in their "host" path would never have a matching URI. For custom app paths that only specified a scheme and not a path it would create a triple forward slash string which never matched the URI. Lastly on apps that used a single slash separator rather than double it would fail to properly parse. Converting this to using `strtok` to find the beginning of the query parameters string and then stripping all that off preserves the original scheme, hostname/port, and path as passed from the app.  I don't have buffers to test this against to confirm that there was not something else that needed to be captured. 

This was tested against all the clients listed as well as desktop Relatica

### CODE REVIEW

File: src/Security/OAuth.php [hunk 1]
```diff
@@ -143,6 +142,7 @@ public static function getApplication(string $client_id, string $client_secret,
 		}
 
 		// The redirect_uri could contain several URI that are separated by spaces.
+		$exploded = explode(' ', $application['redirect_uri']);
```
Comment (MrPetovan) [inline src/Security/OAuth.php]: This variable isn't used anywhere. It also mirrors what is done on line 146 in the condition

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: src/Security/OAuth.php (hunk 1 above)
Comment (HankG) [reply src/Security/OAuth.php]: crap I forgot to remove that. I just did that when I was trying to figure out what that array looked like.

**Comment by HankG** [comment]
Does someone have a way of testing this change against Buffers before merging if it isn't patently obvious that this doesn't break it to them?

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
Testing in prod, baby!
