### PR TITLE
Only output ActivityPub contacts in /followers and /following AP endpoints

### LINKED ISSUE #8588: ActivityPub followers/following collections contain non-ActivityPub actors
### Expected behavior
ActivityPub actors in `followers` and `following` collections would contain valid ActivityPub actors.

### Actual behavior
Actors from Diaspora et al appear alongside ActivityPub actors. Attempts to `GET` the URLs of e.g., Diaspora actors result in a 406, 404, or timeout. 

### Steps to reproduce the problem
View the `followers` or `following` collection of a Friendica user with both ActivityPub and non-ActivityPub actors, e.g., https://friendica.mrpetovan.com/profile/hypolite

### Friendica version you encountered the problem
Current

see `example.com/friendica` on your Friendica node for the version information.

### PHP version
N/a
### SQL version
N/a

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #8588

### CODE REVIEW

File: src/Protocol/ActivityPub/Transmitter.php [hunk 1]
```diff
@@ -62,72 +62,26 @@
...
 	 *
 	 * @return array of owners
-	 * @throws \Friendica\Network\HTTPException\InternalServerErrorException
+	 * @throws \Exception
 	 */
-	public static function getFollowers($owner, $page = null)
+	public static function getContacts($owner, $rel, $module, $page = null)
 	{
-		$condition = ['rel' => [Contact::FOLLOWER, Contact::FRIEND], 'network' => Protocol::FEDERATED, 'uid' => $owner['uid'],
+		$condition = ['rel' => $rel, 'network' => Protocol::ACTIVITYPUB, 'uid' => $owner['uid'],
```
Comment (annando) [inline src/Protocol/ActivityPub/Transmitter.php:77]: We mustn't query the contacts this way, since this would filter out most Friendica systems and (partially) systems like Hubzilla or Socialhome. If we want to publish only AP enabled contacts, we have to check against the `apcontact` table.

Comment (MrPetovan) [reply src/Protocol/ActivityPub/Transmitter.php:77]: I was hoping you would chime in, I knew my solution would be too restrictive but I wasn't sure what was the right way. Thanks for the pointer.

**Comment by MrPetovan** [comment]
Great, there's no efficient way of joining `contact` and `apcontact`. `apcontact` has an index on `url` but `contact` doesn't. It has an index on `nurl` but `apcontact` doesn't have such a column.

@annando We can either add an index on `contact`.`url` or add the `apcontact`.`nurl` column with an index on it, what do you prefer?

**Comment by annando** [comment]
For linking the `contact` with the `apcontact` you don't need an index on the contact `url`. You can join them with no performance issues.

**Comment by MrPetovan** [comment]
I don't understand why, but I'll comply with the Database Master. So this would be fine:
```sql
SELECT COUNT(*)
FROM `contact` c
JOIN `apcontact` ap_c ON ap_c.`url` = c.`url`
WHERE c.`uid` = ?
AND c.`rel` IN (?, ?)
```
?

**Comment by annando** [comment]
This "`contact` c" is ugly. But the rest is okay. I'm currently thinking about a contact join that includes the "contact" table, the "fcontact" (Diaspora) and "apcontact" (ActivityPub).

**Comment by MrPetovan** [comment]
Why is it ugly? Do you have a general problem with aliases?

**Comment by MrPetovan** [comment]
I can definitely do away with them in this case.

**Comment by MrPetovan** [comment]
Here's the revised version.

File: src/Protocol/ActivityPub/Transmitter.php [hunk 2]
```diff
@@ -138,22 +106,31 @@ public static function getFollowing($owner, $page = null)
...
 
 		if (empty($page)) {
-			$data['first'] = DI::baseUrl() . '/following/' . $owner['nickname'] . '?page=1';
+			$data['first'] = DI::baseUrl() . $modulePath . $owner['nickname'] . '?page=1';
 		} else {
 			$data['type'] = 'OrderedCollectionPage';
 			$list = [];
 
-			$contacts = DBA::select('contact', ['url'], $condition, ['limit' => [($page - 1) * 100, 100]]);
+			$sql = "SELECT `contact`.`url`
```
Comment (annando) [inline src/Protocol/ActivityPub/Transmitter.php:114]: Shouldn't the condition be indented one more tab?

Comment (MrPetovan) [reply src/Protocol/ActivityPub/Transmitter.php:114]: It can, would you like the rest of the SQL query multi-line string to be indented?

Comment (annando) [reply src/Protocol/ActivityPub/Transmitter.php:114]: Since the query string is part of the instruction above, I think that every line of the instruction should be intended, shouldn't it?

Comment (MrPetovan) [reply src/Protocol/ActivityPub/Transmitter.php:114]: Here you go.
