### PR TITLE
Issue 9135: Display only reshared posts at the top

### LINKED ISSUE #9135: Don't show '... reshared this' at top of post in all cases
### Expected behavior
The new place for '...reshared this' is a good thing for items I got in my stream because of the reshare. It doesn't make sense for all other cases:
- someone reshared a post of me
- I had that item in my network stream anyway (not because of the reshare)
- it shows '7 people reshared this' (then the display at the top it completely weird)

From my point of view the intention was right. But as it is now it's not ready for the next release. We should rethink and refine that thing.

It should only show the one sharer who is responsible for making me see the post in my stream. The number of reshares should return to the bottom of the item (where the likes count is, too). And maybe only show the number of reshares there.

### Actual behavior
Reshares, resharer, number of reshares are always displayed at the top of a post that has reshares. That's confusing and as it is now (see above examples) it seems out of place in most cases.

### Steps to reproduce the problem
Look at various reshares. :-)

### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

### PR DESCRIPTION
**Pull request by annando**
Handles https://github.com/friendica/friendica/issues/9135

It is currently incomplete. Only frio is changed.

### CODE REVIEW

File: src/Object/Post.php [hunk 1]
```diff
@@ -497,6 +503,7 @@ public function getTemplateData(array $conv_responses, $thread_level = 1)
 			'uriid'           => $item['uri-id'],
 			'return'          => (DI::args()->getCommand()) ? bin2hex(DI::args()->getCommand()) : '',
 			'direction'       => $direction,
+			'reshared'        => $reshared,
```
Comment (MrPetovan) [inline src/Object/Post.php]: The following code makes the 6 new lines above obsolete.
```suggestion
			'reshared'        => $item['reshared'] ?? '',
```

File: view/theme/frio/templates/wall_thread.tpl [hunk 2]
```diff
@@ -81,7 +81,7 @@ as the value of $top_child_total (this is done at the end of this file)
 <span class="uriid" style="display: none;">{{$item.uriid}}</span>
 {{/if}}
 	<div class="media {{$item.shiny}}">
-	{{if $item.responses.announce && $mode != 'display'}}
+	{{if $item.reshared}}
```
Comment (MrPetovan) [inline view/theme/frio/templates/wall_thread.tpl:84]: This would still show "X people reshared this" as it is still using the output of the announce item.

File: include/conversation.php [hunk 3]
```diff
@@ -758,6 +758,7 @@ function conversation_fetch_comments($thread_items, $pinned) {
 	if (!empty($direction)) {
 		foreach ($parentlines as $line) {
 			$comments[$line]['direction'] = $direction;
+			$comments[$line]['reshared'] = DI::l10n()->t('%s reshared this.', $actor['name']);
```
Comment (MrPetovan) [inline include/conversation.php]: Please add an HTML link to the resharer's profile.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: view/theme/frio/templates/wall_thread.tpl [hunk 4]
```diff
@@ -81,7 +81,7 @@ as the value of $top_child_total (this is done at the end of this file)
...
 		<div class="wall-item-ammounce wall-item-responses" id="wall-item-ammounce-{{$item.id}}">{{$item.responses.announce.output nofilter}}</div>
 	{{/if}}
```
Comment (MrPetovan) [inline view/theme/frio/templates/wall_thread.tpl]: This would still show "X people reshared this" as it is still using the announce item output.

Additionally, please add a prefixing reshare icon.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

**Comment by annando** [comment]
I did some changes. But: for "vier" and "quattro" this is not working at the moment. i had some HTML formatting problems. Question is how to continue. I would prefer working at some of the open bugs.

File: include/conversation.php [hunk 5]
```diff
@@ -727,7 +727,12 @@ function conversation_fetch_comments($thread_items, $pinned) {
 			&& ($row['thr-parent'] == $row['parent-uri']) && ($row['received'] > $received)
 			&& Contact::isSharing($row['author-id'], $row['uid'])) {
 			$direction = ['direction' => 3, 'title' => DI::l10n()->t('%s reshared this.', $row['author-name'])];
-			$actor = ['link' => $row['author-link'], 'avatar' => $row['author-avatar'], 'name' => $row['author-name']];
+
+			$author = ['uid' => 0, 'id' => $row['author-id'],
+				'network' => $row['author-network'], 'url' => $row['author-link']];
+			$url = '<a href="'. Contact::magicLinkByContact($author) .'">' . htmlentities($row['author-name']) . '</a>';
```
Comment (MrPetovan) [inline include/conversation.php]: The href value must be HTML encoded as well.

File: view/theme/frio/templates/wall_thread.tpl [hunk 6]
```diff
@@ -82,7 +82,7 @@ as the value of $top_child_total (this is done at the end of this file)
 {{/if}}
 	<div class="media {{$item.shiny}}">
 	{{if $item.reshared}}
-		<div class="wall-item-ammounce wall-item-responses" id="wall-item-ammounce-{{$item.id}}">{{$item.responses.announce.output nofilter}}</div>
+		<div class="wall-item-ammounce wall-item-responses" id="wall-item-ammounce-{{$item.id}}">{{$item.reshared nofilter}}</div>
```
Comment (MrPetovan) [inline view/theme/frio/templates/wall_thread.tpl]: Please add a leading reshare icon.

**Review by MrPetovan — CHANGES_REQUESTED** [review]

File: include/conversation.php (hunk 5 above)
Comment (annando) [reply include/conversation.php]: Are you sure with this?

File: view/theme/frio/templates/wall_thread.tpl (hunk 6 above)
Comment (annando) [reply view/theme/frio/templates/wall_thread.tpl]: Done

File: include/conversation.php (hunk 5 above)
Comment (MrPetovan) [reply include/conversation.php]: Yes, since we will add this HTML snippet as is to the template without relying on Smarty encoding.

Comment (annando) [reply include/conversation.php]: But when we encode the URL then the URL will be invalid?

Comment (MrPetovan) [reply include/conversation.php]: HTML encode, not URL encode.

Comment (annando) [reply include/conversation.php]: Okay, changed.

**Review by MrPetovan — APPROVED** [review]
