### PR TITLE
Issue 10947: Send correct accept-header for AP

### LINKED ISSUE #10947: Can't follow Zap account, ActivityPub not detected
- [X ] I have searched open and closed issues for duplicates

### Bug Description

Can't follow Zap contact,

### Steps to Reproduce

1.  follow a zap account, eg. https://z.fedipen.xyz/channel/asherpen

Actual Result:

Failed. "The network type couldn't be detected. Contact can't be added."

Expected Result:

Succeeded in following a Zap account

### Screenshots

9xd4MI43rS

### Platform Info

Friendica Version: 2021.09

Friendica Source: I think it's from git

PHP version: 7.2.24-0ubuntu0.18.04.9

SQL version: I'm not quite sure

Probe Diagnostic:

> Array
(
    [name] => https://z.fedipen.xyz/channel/asherpen
    [nick] => https://z.fedipen.xyz/channel/asherpen
    [guid] => 
    [url] => https://z.fedipen.xyz/channel/asherpen
    [addr] => 
    [alias] => 
    [photo] => https://letus.inspiredlife.fun/images/person-300.jpg
    [header] => 
    [account-type] => 
    [community] => 
    [keywords] => 
    [location] => 
    [about] => 
    [xmpp] => 
    [matrix] => 
    [hide] => 
    [batch] => 
    [notify] => 
    [poll] => 
    [request] => 
    [confirm] => 
    [subscribe] => https://z.fedipen.xyz/follow?url={uri}
    [poco] => 
    [following] => 
    [followers] => 
    [inbox] => 
    [outbox] => 
    [sharedinbox] => 
    [priority] => 0
    [network] => unkn
    [pubkey] => 
    [manually-approve] => 
    [baseurl] => https://z.fedipen.xyz
    [gsid] => 150186
)

### PR DESCRIPTION
**Pull request by annando**
Fixes #10947

We now send the correct `accept` header. Also we send it as a single string. It seems as if we sent this as two headers - which could create problems under certain cicrumstances.

### CODE REVIEW

File: src/Util/HTTPSignature.php [hunk 1]
```diff
@@ -417,7 +417,7 @@ public static function fetch($request, $uid)
 	 * @return \Friendica\Network\HTTPClient\Capability\ICanHandleHttpResponses CurlResult
 	 * @throws \Friendica\Network\HTTPException\InternalServerErrorException
 	 */
-	public static function fetchRaw($request, $uid = 0, $opts = ['accept_content' => ['application/activity+json', 'application/ld+json']])
+	public static function fetchRaw($request, $uid = 0, $opts = ['accept_content' => ['application/activity+json, application/ld+json; profile="https://www.w3.org/ns/activitystreams"']])
```
Comment (MrPetovan) [inline src/Util/HTTPSignature.php:420]: This is the correct way of having several values for the same header instead of having a single value by repeated header.

**Review by MrPetovan — APPROVED** [review]

File: src/Util/HTTPSignature.php (hunk 1 above)
Comment (nupplaphil) [reply src/Util/HTTPSignature.php:420]: I think for a long-term fix, we should allow arrays as an input and format them inside Guzzle as a string.
Because so we could make checks against an array rather than an string

Comment (annando) [reply src/Util/HTTPSignature.php:420]: There could be arrays that shouldn't be folded but should be added as separate entries.

Comment (nupplaphil) [reply src/Util/HTTPSignature.php:420]: Hm, I think I don't fully understand.

This issue happened because Guzzle sent 2 `Accept` headers:
```
Accept: application/activity+json
Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"
```
instead of one comma-separated

**But** this is only an issue for this specific case, because normally we should send separate entries? Or do you mean we are not allowed to send different `Accept` headers, but for other headers we're allowed to?

Comment (MrPetovan) [reply src/Util/HTTPSignature.php:420]: Some headers accept several values by repeating the header, but to my knowledge `Accept:` uses a comma-delimited list for multiple values.

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept
