### PR TITLE
Fix "remember me" cookie for OpenID logins

### LINKED ISSUE #2432: 'remember me' keeps forgetting about me
On my own node, the "Remember me" option on login doesn't behave as expected.
The cookie is set with 1 year expiration date, but somehow the node occasionally forgets about me nonetheless. I suspect there's a cleanup running at the database side but didn't run any deep debugging on the cause.

I think others confirmed the problem in a forum thread but i hadn't found a ticket, so here it is.

@annando maybe this is one of those things you could look at next :)

### PR DESCRIPTION
**Pull request by strk**
Closes #2432

NOTE: I didn't really test this :)

### CODE REVIEW

File: include/security.php [hunk 1]
```diff
@@ -94,6 +94,20 @@ function authenticate_success($user_record, $login_initial = false, $interactive
...
+
+	// If the user specified to remember the authentication, then set a cookie
+	// that expires after one week (the default is when the browser is closed).
+	// The cookie will be renewed automatically.
+	// The week ensures that sessions will expire after some inactivity.
+	if ($_SESSION['remember']) {
+		new_cookie(604800, $r[0]);
+		unset $_SESSION['remember'];
+	}
+	else
```
Comment (Hypolite) [inline include/security.php]: Standards: Can you please add braces to the `else` statement?

**Comment by Hypolite** [comment]
Can you at least confirm the regular login remember me still works? 😅

**Comment by strk** [comment]
@Hypolite I cannot confirm w/out testing and I'm not setup locally to test.
But I can confirm that *reading* the code I'm confident that you would :)

Hey, this is Friendica after all, are you really expecting things to be tested ?! :')

**Comment by strk** [comment]
@Hypolite with  		ca83f55 it should actually even work with OpenID (which was the main focus of this PR).

I belive things could be cleared up more (like for example by setting the 'remember' session variable earlier in the function, and once. And rename it to be more self-explaining. And even only set by the POST handler rather than in the auth.php file as a global thing (which slows down things) -- but this is just an attempt at fixing a bug, not a refactoring PR.

It would be great if there was a try.friendi.ca kind of website continuously deploying the "develop" branch, wouldn't it ? :)

File: include/security.php [hunk 2]
```diff
@@ -94,6 +94,20 @@ function authenticate_success($user_record, $login_initial = false, $interactive
 
 
 	}
+
+	// If the user specified to remember the authentication, then set a cookie
+	// that expires after one week (the default is when the browser is closed).
+	// The cookie will be renewed automatically.
+	// The week ensures that sessions will expire after some inactivity.
+	if ($_SESSION['remember']) {
```
Comment (Hypolite) [inline include/security.php]: Can you please use `isset` to check the existence of the array key, it would avoid unnecessary Notice messages when it's not set.

**Comment by Hypolite** [comment]
> It would be great if there was a try.friendi.ca kind of website continuously deploying the "develop" branch, wouldn't it ? :)

I can volunteer a Friendica instance for that, with a script that updates the codebase every 5mn or so. It just needs the domain to point on my machine.

**Comment by strk** [comment]
Give me an IP, I'll point you a friendica-dev.xxx.xx name (to be disclosed after it's done, to avoid spreading the wrong resolution)

**Comment by Hypolite** [comment]
I can do that as well, I was thinking about `try.friendi.ca` specifically.

**Comment by strk** [comment]
That'd be great ! While you sort out the details, I realized I have my node, so can just pull my branch there for testing. Will do now.

**Comment by strk** [comment]
So: DO NOT MERGE THIS ! 

Glad I tested :)

needs more love (if anyone want to help, please, as I'm not sure when I'll be ready for that)

**Comment by Hypolite** [comment]
You can close this PR without losing your changes on your branch to avoid an accidental merge. You can always reopen it if you add changes later.

**Comment by strk** [comment]
Nah, I'll trust Friendica developers to at least read the comments before merging :)
I'm looking at it anyway: `Call to undefined function new_cookie()`
That function name is horribe, btw, do you mind if I rename to something else ?

**Comment by Hypolite** [comment]
I don't, but it's easy to start renaming/reformatting things and it's a pretty deep rabbit hole at the moment. Don't get sucked in too far!

If you do that, please add some documentation to the function using `/** */` Doxygen-like comments.

**Comment by strk** [comment]
I'm closer now: Hash for user doesn't fit. I need a way to transport the user hash to the session too

**Comment by strk** [comment]
Partially fixed but still I have a problem with "Hash for user 1 doesn't fit." message when checking the "Remember me" while logging via OpenID...

**Comment by strk** [comment]
Alright this is finally working and in production on my node. Feel free to break in to prove it wrong :)

**Comment by strk** [comment]
(I'm pretty sure it isn't hard either, beside my PR)

**Comment by annando** [comment]
The function "authenticate_success" is used when switching between delegated accounts as well:
https://github.com/friendica/friendica/blob/develop/mod/manage.php#L81

Have you checked whether this causes some disturbance?

**Comment by strk** [comment]
I've no idea what "delegated accounts" is, and how to test.
The branch is live on my node, if it is something you can
test (in case it's about my node delegating auth to your node...)

**Comment by annando** [comment]
Create an additional account on your system with the same mail address and the same password. Then you have a menu link named "manage" with which you can switch between these accounts. This function (see the link above) is calling the function that you changed. It has to be tested if it still works and if the cookies are set correctly in that case.

**Comment by strk** [comment]
Since which version it is allowed to have more than a single user with
the same email address ? I tried but failed in weird ways (from the
admin panel I created the user, which was then listed there, but then
wasn't available anymore upon logging out and in again).

**Comment by strk** [comment]
NOTE: I'm trying to do the delegation (succeeded creating an account with same email but Oops also same OID: #3229)

**Comment by strk** [comment]
Ok I finally tested:
 - Created a new user with same email and same password
 - Logged in and out as the new and old user with and w/out Remember me
 - The "Friendica" cookie was injected when using Remember me and NOT when not using it

Now, for the Manage thing, which I'm new to. What should I check in the cookies, exactly ?

**Comment by annando** [comment]
Just switch between these two users with the "manage" functionality under the url ```/manage```. Then have a look at the cookies.

**Comment by strk** [comment]
@annando this is what I observed when using manage:
 - The "Friendica" cookie (handler of "remembering") is *removed* from browser as soon as you pick a profile, even if it's the same profile you had before

Is the above what you would expect ?
I'm not sure this was introduced by my patch though, will try develop and let you know

**Comment by annando** [comment]
I expected this, because during the switch the function is called that you changed. This hadn't happen before since then the cookie was set at a different place. I guess you have to move out your change to a separate function or you hide it under a parameter that is called at login but not at the switching between the users.

**Comment by strk** [comment]
Ok what's the semantic of `login_initial` parameter for, then ?
Is it correct that mod/manage.php passes in `true` for that ? It's not an "initial login" if  you still want the user to be remembered. Documenting that function could help. Should I try to pass in false for that parameter instead ?

**Comment by strk** [comment]
Or I could set the REMEMBER session variable if the Friendica cookie is set, what do you think ?

**Comment by strk** [comment]
(in mod/manage, that is)

**Comment by annando** [comment]
I have to analyze the code as well to answer that.

BTW: One can edit comments as well, there is no need to write multiple ones ;-)

**Comment by strk** [comment]
Nope, my proposal doesn't work because then we have:
```
 [NORMAL]:auth.php:16:require    Hash for user 28 doesn't fit.
```

Given the fragility of that cookie ("doesn't fit" message unless we pass an exact $user_record, even in aliases) -- are you really sure that cookie is working right now, when you switch accounts ?

**Comment by strk** [comment]
See how you like the just-committed solution ( https://github.com/friendica/friendica/pull/3221/commits/cbaf196f509cc5b21f04574cbf80ddd3ecf9f8db )

Basically as the problem is the *removal* of the cookie, I put that part back where it was (in the auth.php file). That way you only get the cookie removed IFF you are submitting the "login" form and you did not check the "remember me" button. In all other cases the cookie is sticky (I noticed it also sticks on logout, but even before this PR)

**Comment by annando** [comment]
It now looks okay. But I guess that @Hypolite will have some remarks concerning the PSR-2 standards (e.g. braces for every "if" construction) .

File: include/security.php [hunk 3]
```diff
@@ -1,5 +1,41 @@
...
+
+/**
+ * @brief Set the "Friendica" cookie
+ *
+ * @param int $time
+ * @param array $user Record from "user" table
+ */
+function new_cookie($time, $user = array()) {
+
+	if ($time != 0)
```
Comment (Hypolite) [inline include/security.php]: Standards: Please add braces.

File: include/security.php [hunk 4]
```diff
@@ -1,5 +1,41 @@
...
+		$time = $time + time();
+
+	if ($user)
```
Comment (Hypolite) [inline include/security.php]: Standards: Please add braces.

File: include/security.php [hunk 5]
```diff
@@ -1,5 +1,41 @@
...
+		$value = json_encode(array("uid" => $user["uid"],
+					"hash" => cookie_hash($user),
+					"ip" => $_SERVER['REMOTE_ADDR']));
+	else
```
Comment (Hypolite) [inline include/security.php]: Standards: Please add braces.

File: include/auth.php [hunk 6]
```diff
@@ -178,17 +179,12 @@
...
 		}
 
-		// If the user specified to remember the authentication, then set a cookie
-		// that expires after one week (the default is when the browser is closed).
-		// The cookie will be renewed automatically.
-		// The week ensures that sessions will expire after some inactivity.
-		if ($_POST['remember'])
-			new_cookie(604800, $r[0]);
-		else
+		if ( ! $_POST['remember']) {
```
Comment (Hypolite) [inline include/auth.php]: Standards: Please remove the extra space after the opening parentheses.

**Comment by strk** [comment]
Please don't do this to me.
You're referencing all places that my change did NOT TOUCH !

How about you merge this PR and then shoult STYLE ! in another PR ? :)

**Comment by Hypolite** [comment]
Well, I can't make you change your code, can I? 😉

I'm not a project contributor, which means I'm just advising here.

**Comment by annando** [comment]
@strk he's doing it with all of us. ;-) At first it might feel annoying - but in fact it helps to unify the codebase. And additionally it helps to memorize the PSR-2 rules :-)

**Comment by strk** [comment]
Micheal my point is: does it make sense to be called into changing
parts that have nothing to do with the change in the topic ?

The topic here is a bugfix, and I don't like mixing style and
functional changes (harder to spot a breaking change with
bisect) - I guess I could solve this with a new commit, but then
why not just approach a single file and do a style-only change
in a dedicated PR ?

Another thing is enforcing the correct style to newly added code,
which I've done when asked the previous time.

Please help those who are not as patient as me with their "free"
node forgetting about them :)

**Comment by strk** [comment]
@Hypolite btw you DO CAN make me change my code, just send a PR for me to pull :)

Will now look at my parts of the code to be changed, those one I'll change

**Comment by strk** [comment]
Well I also did the other parts, as requested. Please check which other portions of the pre-existing code are exposed with the new diff, I'm sure you'll find more things to change .... (or please merge this and let's stop hijacking PRs :)
