### PR TITLE
Fix connection request and suggestion removal

### LINKED ISSUE #15362: Introduction/Connection request removal not working
Clicking remove on an intro/connection request does not work.

...as reported [here](https://forum.friendi.ca/display/adf174d5-1569-53ae-fca5-48e790011701).

They also mention ignoring not working initially, but from the follow-up I'm unsure that's the case?
I can reproduce removal not working, but not ignoring. I can't undo the ignore but I don't know if that was possible before?

I tried reverting !15336 and then it worked, so evidently I broke something in that PR.
Specifically with the changes to intros.tpl.

A quick fix could be to revert the intros.tpl changes and frio style.css changes, so the notifications changes remain.
I can look more into finding the issue and making a fix tomorrow evening.

### PR DESCRIPTION
**Pull request by marcusxss**
Closes #15362 

A draft as I need to do a bit more testing, specifically of suggestions.
I'm wondering a little if instead of setting the "value" and identifying which submit button was pressed through that, if we should instead distinguish by "name".

Also did the following:
- Change the submit button hover text of suggestions to "Remove" so its consistent with the new text used for connection requests/introductions.
- Change input -> button

# Edit

I wanted to test suggestions but even though the page loads for me now after annando fixed it (thanks!), when I select a user and suggest a friend, it fails at that point with "Contact not found". Specifically this check on line 56 in FriendSuggest.php:
```php
// We do query the "uid" as well to ensure that it is our contact
if (!$this->dba->exists('contact', ['id' => $cid, 'uid' => DI::userSession()->getLocalUserId()])) {
	throw new NotFoundException($this->t('Contact not found.'));
}
```

...it could be a local test instance issue, though.

Here are all the `contact` entries in the database with the nicknames for either user:
```
+-----+-----+-------+
| id  | uid | nick  |
+-----+-----+-------+
|   3 |   0 | admin |
|   2 |   2 | admin |
|  53 |   5 | admin |
| 109 |   6 | admin |
|  60 |  10 | admin |
| 104 |  11 | admin |
| 100 |  64 | admin |
|  24 |   0 | werw  |
|  23 |   9 | werw  |
+-----+-----+-------+
```

...and it's a friend suggestion for "admin" from "werv", and so PHP is checking for:
ID = 3
UID = 6
...finding no matches.

Maybe I should create an issue for that if someone else can reproduce friend suggestions not working?

### CODE REVIEW

File: src/Module/Notifications/Notification.php [hunk 1]
```diff
@@ -68,11 +68,11 @@ protected function post(array $request = [])
 			$intro = $this->introductionRepo->selectOneById($request_id, DI::userSession()->getLocalUserId());
 
 			switch ($_POST['submit']) {
-				case $this->l10n->t('Discard'):
+				case "discard":
```
Comment (marcusxss) [inline src/Module/Notifications/Notification.php:71]: Alternatively we could create a new variable (in both Introductions.php and Notification.php) only used for the programmatic value (and not a translation) and pass it to the template, and then refer to that variable here as well...?

**Comment by annando** [comment]
Please fix the conflict.

**Comment by marcusxss** [comment]
Done.
