### PR TITLE
Ensure FactorySession->create returns an object no matter what

### LINKED ISSUE #12792: Console can't create session for several commands
- [X] I have searched open and closed issues for duplicates

### Bug Description
When using the console e.g. for user management I'm getting the following error:

```
bin/console user
[Error] Friendica\Core\Session\Factory\Session::createSession(): Return value must be of type Friendica\Core\Session\Capability\IHandleSessions, null returned
```

This does not occur with every command e.g. cache works while addon doesn't work, too.

### Steps to Reproduce

1.  try to list e.g. users through the console: bin/console user
2.  get the error

Actual Result: console throws error [Error] Friendica\Core\Session\Factory\Session::createSession(): Return value must be of type Friendica\Core\Session\Capability\IHandleSessions, null returned

Expected Result: Console command works

### Platform Info

Friendica Version:

Friendica Source: latest dev

PHP version:

SQL version:

### PR DESCRIPTION
**Pull request by MrPetovan**
- Rename redundant method name createSession
- Add exception logging

Fixes #12792 

I'm curious about the kind of exception we are getting at this point, but we might have to suppress the most common ones.

### CODE REVIEW

**Comment by nupplaphil** [comment]
This seems weird to me .. there is already a default value in case it doesn't exist

Shouldn't we add a lookup table when setting a session type to ensure a valid config and add a `update()` routine to cleanup invalid settings, should we?

Because currently it seems like avoiding the impact, but not fixing the root cause...

File: src/Core/Session/Factory/Session.php [hunk 1]
```diff
@@ -82,10 +80,15 @@ public function createSession(App\Mode $mode, App\BaseURL $baseURL, IManageConfi
 							$handler = new Handler\Cache($cache, $logger);
 						}
 						break;
+					default:
+						$handler = null;
```
Comment (nupplaphil) [inline src/Core/Session/Factory/Session.php:84]: This should log an exception and set the sessionhandler to default

```suggestion
						$handler = self::HANDLER_DEFAULT;
						$this->logger->alert(...);
```

File: src/Core/Session/Factory/Session.php [hunk 2]
```diff
@@ -82,10 +80,15 @@ public function createSession(App\Mode $mode, App\BaseURL $baseURL, IManageConfi
...
 				}
 
 				$session = new Type\Native($baseURL, $handler);
 			}
+		} catch (\Throwable $e) {
+			$logger->notice('Unable to create session', ['mode' => $mode, 'session_handler' => $session_handler, 'exception' => $e]);
```
Comment (nupplaphil) [inline src/Core/Session/Factory/Session.php:90]:
```suggestion
			$logger->alert('Unable to create session', ['mode' => $mode, 'session_handler' => $session_handler, 'exception' => $e]);
```

File: src/Core/Session/Factory/Session.php [hunk 3]
```diff
@@ -82,10 +80,15 @@ public function createSession(App\Mode $mode, App\BaseURL $baseURL, IManageConfi
...
+			$session = new Type\Memory();
```
Comment (nupplaphil) [inline src/Core/Session/Factory/Session.php:91]:
```suggestion
			$session = new self::HANDLER_DEFAULT();
```

**Review by nupplaphil — CHANGES_REQUESTED** [review]

File: src/Core/Session/Factory/Session.php (hunk 1 above)
Comment (MrPetovan) [reply src/Core/Session/Factory/Session.php:84]: `$handler` is supposed to be an object extending `AbstractSessionHandler` while `self::HANDLER_DEFAULT` is a string, I'm not sure how you reconcile this.

File: src/Core/Session/Factory/Session.php (hunk 3 above)
Comment (MrPetovan) [reply src/Core/Session/Factory/Session.php:91]: This will try to instantiate an object of the class `Friendica\Core\Session\Factory\database`, not sure it's going to work.

File: src/Core/Session/Factory/Session.php (hunk 2 above)
Comment (MrPetovan) [reply src/Core/Session/Factory/Session.php:90]: I'm not using a high log level because there might be common reasons why a session can't be instantiated, like in backend mode or in CLI mode. In these mode we still offer a degraded script-only session so the log shouldn't fill with high-priority messages for an expected behavior.

File: tests/src/Core/KeyValueStorage/DBKeyValueStorageTest.php [hunk 4]
```diff
@@ -80,6 +80,6 @@ public function testUpdatedAt($k, $v)
 
 		$updateAtAfter = $entry['updated_at'];
 
-		self::assertLessThanOrEqual($updateAt, $updateAtAfter);
+		self::assertGreaterThanOrEqual($updateAt, $updateAtAfter);
```
Comment (MrPetovan) [inline tests/src/Core/KeyValueStorage/DBKeyValueStorageTest.php:83]: @annando @nupplaphil Found the source of the intermittent PHPUnit failure: the wrong order of parameters in this assertion. For `assertLessThanOrEqual`, the target high bound needs to be the first parameter. Instead of flipping the parameters which could still lead to confusion, I changed the assertion so that the order of parameters feels more natural.

We used the wrong assertion, but thanks to the "Equal" part it didn't systematically fail. In particular, the faster the test runner was, the harder it was to detect the logic error.
