### PR TITLE
Issue 11876: Fix local message distribution

### LINKED ISSUE #11876: Can't see posts of local forums and some local contacts
- [X] I have searched open and closed issues for duplicates

### Bug Description

Im following several Forums and accounts on my local server. It started that I (with my personal user) can't see the posts of my forum accounts I am following. Now it starts, that i can't see the posts of my other local accounts that I am following. -> It is getting worse.

### Steps to Reproduce

1.  Loggin in with my ONE Account
2.  Switching to my FORUM Account - writing a message
3.  Switching back to my ONE Account
4. Can't see it in my timeline and the Forum is empty

### 2. Steps to reproduce 

1.  Loggin in with my ONE Account
2. Switching to my SECOND Account
3. writing a post with my SECOND Account
4. Switching back to ONE Account
5. Can't see it in my timeline
6. Searching for SECOND Account -> getting older posts
7. Clicking on "Network Posts" (hover Card) -> Seeing that post

### Platform Info

Friendica Version: dev ( pull 30.08.22.15:30)
Friendica Source:  git
PHP version: 7.4
SQL version: mariadb 10.3.34

### PR DESCRIPTION
**Pull request by annando**
Hopefully fixes #11876

The calculation of the post-reason was wrong. So posts hadn't always been distributed.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

File: src/Model/Item.php [hunk 1]
```diff
@@ -1552,14 +1552,16 @@ public static function storeForUserByUriId(int $uri_id, int $uid, array $fields
 
 		$item = array_merge($item, $fields);
 
-		$item['post-reason'] = self::getPostReason($item);
+		if (($uid != 0) && Contact::isSharing(($item['gravity'] == GRAVITY_PARENT) ? $item['owner-id'] : $item['author-id'], $uid)) {
```
Comment (Quix0r) [inline src/Model/Item.php:1555]: Note to self: Needs to be fixed to `Item::GRAVITY_*`.
